'use strict';

const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {chromium}=require('playwright');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const firestore=require('firebase/firestore');
const LtdSync=require('../../src/core/ltd-sync');
const {make}=require('../test-fixture');

const root=path.resolve(__dirname,'../..');
const artifact=path.join(root,'.hosting-build','account-isolation-browser');
const evidence=path.resolve(process.env.TAXMATE_ACCOUNT_ISOLATION_EVIDENCE||path.join(root,'.hosting-build','account-isolation-evidence'));
const resultPath=path.join(evidence,'account-isolation-browser-result.json');
const runId=Date.now().toString(36),origin='http://127.0.0.1:4193',password='Account-Isolation-Only-20260901!';
const profileRoot=path.join(os.tmpdir(),`tm-isolate-${runId}`),sharedProfile=path.join(profileRoot,'shared');
const assertions=[],externalRequests=[],consoleErrors=[],contexts=new Set(),resourceFailures=[];
const currentCache=require('../../src/core/versions').VERSIONS.PWA_CACHE_VERSION;
const oldCache='taxmate-v2-first-sync-safety-production-2';
const swDiagnostics={served:[],missing:[]};
let assertionCount=0,testEnv,server,serveLegacyWorker=false,legacyServiceWorker=null;

function check(value,message){assert.ok(value,message);assertionCount++;assertions.push(message);}
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);assertionCount++;assertions.push(message);}
function sha(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function waitFor(fn,message,timeout=60000){const started=Date.now();let last;while(Date.now()-started<timeout){try{last=await fn();if(last)return last;}catch(error){last=error.message;}await sleep(150);}throw new Error(`${message}; last=${String(last)}`);}
function chromePath(){for(const candidate of [process.env.TAXMATE_CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'])if(candidate&&fs.existsSync(candidate))return candidate;throw new Error('Installed Chrome not found');}
function entitlement(tier){return{subscriptionStatus:tier==='pro'?'active':'inactive',paidTier:tier,currentPeriodEnd:tier==='pro'?Date.now()+86400000:0,serverVerifiedAt:Date.now()};}
function gitBlob(spec){const result=spawnSync('git',['show',spec],{cwd:root,encoding:null});if(result.status!==0)throw new Error(`Unable to read ${spec}`);return result.stdout;}

function prepareArtifact(){
  const build=spawnSync(process.execPath,['scripts/build-hosting.js','production','account-isolation-browser'],{cwd:root,stdio:'inherit'});if(build.status!==0)throw new Error('Account-isolation Hosting artifact build failed');
  const firebaseFiles=['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js','firebase-storage-compat.js','firebase-app-check-compat.js'],vendor=path.join(artifact,'vendor','firebase');fs.mkdirSync(vendor,{recursive:true});
  for(const file of firebaseFiles)fs.copyFileSync(path.join(root,'node_modules','firebase',file),path.join(vendor,file));
  const htmlPath=path.join(artifact,'index.html');let html=fs.readFileSync(htmlPath,'utf8');
  for(const file of firebaseFiles)html=html.replace(new RegExp(`https://www\\.gstatic\\.com/firebasejs/[^"']+/${file}`,'g'),`vendor/firebase/${file}`);
  html=html.replace(/<script[^>]+https:\/\/(?:cdnjs\.cloudflare\.com|js-de\.sentry-cdn\.com)[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'').replace(/<noscript><link[^>]+https:\/\/fonts\.googleapis\.com[^>]*><\/noscript>\s*/gi,'');
  fs.writeFileSync(htmlPath,html);fs.writeFileSync(path.join(artifact,'src','app','sentry-bootstrap.js'),"'use strict';\nwindow.__TAXMATE_SENTRY_STATE__=Object.freeze({enabled:false,reason:'account_isolation_emulator',sdkRequested:false});\n");
  legacyServiceWorker=gitBlob('origin/main:sw.js');const legacyBoundaryPath=path.join(artifact,'src','core','account-boundary.js');fs.mkdirSync(path.dirname(legacyBoundaryPath),{recursive:true});fs.writeFileSync(legacyBoundaryPath,gitBlob('origin/main:src/core/account-boundary.js'));
  fs.writeFileSync(path.join(artifact,'firebase-environment.js'),`'use strict';
window.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:Object.freeze({apiKey:'demo-api-key',authDomain:'demo-taxmate.firebaseapp.com',projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com',messagingSenderId:'100000000000',appId:'1:100000000000:web:account-isolation'}),hosts:Object.freeze(['127.0.0.1','localhost']),appCheckKey:'demo-only',functionsOrigin:'http://127.0.0.1:5001'});
(function(){const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(config,name){const app=init(config,name),auth=firebase.auth(app);auth.useEmulator('http://127.0.0.1:9099',{disableWarnings:true});firebase.firestore(app).useEmulator('127.0.0.1',8080);firebase.storage(app).useEmulator('127.0.0.1',9199);auth.signInWithPopup=async function(){const email=localStorage.getItem('__tm_account_isolation_email');if(!email)throw new Error('No synthetic account selected');const credential=await auth.signInWithEmailAndPassword(email,${JSON.stringify(password)});return{user:credential.user,credential:null,additionalUserInfo:null,operationType:'signIn'};};return app;};firebase.appCheck=function(){return{activate:function(){},getToken:async function(){return{token:'emulator-app-check'};}};};})();
`);
}

function startServer(){const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.ico':'image/x-icon','.svg':'image/svg+xml','.xml':'application/xml','.txt':'text/plain; charset=utf-8'};server=http.createServer((request,response)=>{const pathname=new URL(request.url,origin).pathname,relative=decodeURIComponent(pathname==='/'?'/index.html':pathname).replace(/^\/+/,''),target=path.resolve(artifact,relative);if(!target.startsWith(path.resolve(artifact)+path.sep)||!fs.existsSync(target)){swDiagnostics.missing.push(relative);response.writeHead(404);response.end('Not found');return;}if(relative==='sw.js'){const version=serveLegacyWorker?'2.1.14':'2.1.15';swDiagnostics.served.push({version});response.writeHead(200,{'content-type':mime['.js'],'cache-control':'no-cache, no-store, must-revalidate'});response.end(serveLegacyWorker?legacyServiceWorker:fs.readFileSync(target));return;}response.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','cache-control':'no-store'});fs.createReadStream(target).pipe(response);});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(4193,'127.0.0.1',resolve);});}
async function createUser(label){const email=`${label}-${runId}@taxmate.local`,response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-api-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});if(!response.ok)throw new Error('Auth emulator user creation failed');return{...(await response.json()),email};}
async function adminSet(pathName,value){await testEnv.withSecurityRulesDisabled(async context=>firestore.setDoc(firestore.doc(context.firestore(),...pathName.split('/')),value));}
async function adminGet(pathName){let value=null;await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDoc(firestore.doc(context.firestore(),...pathName.split('/')));value=snap.exists()?snap.data():null;});return value;}
async function adminRows(pathName){let rows=[];await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDocs(firestore.collection(context.firestore(),...pathName.split('/')));rows=snap.docs.map(doc=>doc.data());});return rows;}
async function accountCloudSummary(uid){const ltd={};for(const collection of LtdSync.COLLECTIONS)ltd[collection]=(await adminRows(`users/${uid}/ltd/v1/${collection}`)).length;return{meta:!!(await adminGet(`users/${uid}/app/meta`)),entries:(await adminRows(`users/${uid}/entries`)).length,ltd:Object.values(ltd).reduce((sum,count)=>sum+count,0)};}
function founderFixture(uid){const state=JSON.parse(JSON.stringify(make('existing').driver.state));state.settings={...state.settings,lang:'en',theme:'light'};for(const row of state.entries||[]){row.receiptPath=null;row.receiptUrl=null;}state.entries[0].receiptPath=`receipts/${uid}/linked.jpg`;return state;}
async function seedFounder(user,state){const now=Date.now(),meta={businesses:state.businesses,businessTombstones:state.businessTombstones||[],folders:state.folders||[],folderTombstones:state.folderTombstones||[],customCats:state.customCats||{},activeCats:state.activeCats||{},yearData:state.yearData||{},settings:state.settings,metaVersions:state.metaVersions||{},updatedAt:Number(state.metaUpdatedAt)||now,deviceId:'2.1.14-local-upgrade'};await adminSet(`users/${user.localId}/entitlements/current`,entitlement('pro'));await adminSet(`users/${user.localId}/app/meta`,meta);for(const row of state.entries)await adminSet(`users/${user.localId}/entries/${row.id}`,row);const profile=state.domain.companyProfiles.find(row=>row.deletedAt==null),companyIds=new Set([profile.entityId]),records=LtdSync.recordsForSync(state);await adminSet(`users/${user.localId}/ltdControl/activeCompany`,{schemaVersion:1,status:'active_slot_claimed',activeCompanyId:profile.entityId,accountOwnerUid:user.localId,releasePolicy:'founder_approval_required',claimedAt:now,updatedAt:now});for(const collection of LtdSync.COLLECTIONS)for(const row of records[collection]){const envelope=LtdSync.envelope(collection,row,LtdSync.companyIdForRecord(collection,row,companyIds));await adminSet(LtdSync.documentPath(user.localId,collection,row.id),envelope);}}
async function installGuard(context){await context.route('**/*',async route=>{const url=route.request().url(),external=/^https?:\/\//i.test(url)&&!/^http:\/\/(?:127\.0\.0\.1|localhost)(?::\d+)?\//i.test(url);if(external){externalRequests.push(url);await route.abort('blockedbyclient');return;}await route.continue();});}
async function launch(options={}){const profile=options.profileName||'shared',selected=options.profileName?path.join(profileRoot,options.profileName):sharedProfile,context=await chromium.launchPersistentContext(selected,{headless:true,executablePath:chromePath(),viewport:{width:390,height:844},serviceWorkers:'allow',userAgent:options.userAgent||undefined});contexts.add(context);context.on('close',()=>contexts.delete(context));context.on('response',response=>{if(response.url().startsWith(origin)&&response.status()>=400)resourceFailures.push({path:new URL(response.url()).pathname,status:response.status()});});await installGuard(context);await context.addInitScript(({standalone,staleInstalled})=>{localStorage.setItem('taxmateuk_analytics_consent','denied');if(staleInstalled)localStorage.setItem('taxmateuk_pwa_installed','1');if(standalone){const native=window.matchMedia.bind(window);window.matchMedia=query=>query==='(display-mode: standalone)'?{matches:true,media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true;}}:native(query);}},{standalone:options.standalone===true,staleInstalled:options.staleInstalled===true});const page=context.pages()[0]||await context.newPage();page.on('pageerror',error=>consoleErrors.push(`${profile}: ${error.message}`));page.on('console',message=>{if(message.type()==='error'&&!/(?:ERR_FAILED|ERR_BLOCKED_BY_CLIENT|Failed to load resource)/.test(message.text()))consoleErrors.push(`${profile}: ${message.text()}`);});await page.goto(origin+'/',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>typeof ensureFB==='function'&&window.TaxMateAccountStorage&&window.TaxMateCore,null,{timeout:30000});return{context,page};}
async function signInDirect(page,user){await page.evaluate(async({email,password})=>{await ensureFB();await firebase.auth().signInWithEmailAndPassword(email,password);},{email:user.email,password});await page.waitForFunction(()=>firebase.auth().currentUser&&!firebase.auth().currentUser.isAnonymous,null,{timeout:30000});}
async function waitConverged(page,message){try{await waitFor(()=>page.evaluate(()=>{const user=cloudUser();return!!user&&ACTIVE_ACCOUNT_SCOPE&&ACTIVE_ACCOUNT_SCOPE.kind==='firebase'&&ACTIVE_ACCOUNT_SCOPE.uid===user.uid&&CLOUD.hydrationState==='converged'&&CLOUD.partnershipHydrationState==='converged';}),message);}catch(error){const state=await page.evaluate(()=>({scope:ACTIVE_ACCOUNT_SCOPE&&ACTIVE_ACCOUNT_SCOPE.kind,transition:ACCOUNT_TRANSITION_PENDING,hydration:CLOUD.hydrationState,partnership:CLOUD.partnershipHydrationState,error:CLOUD.hydrationError,businesses:S.businesses.length,entries:S.entries.length,onboarding:!!OB}));throw new Error(`${message}; ${JSON.stringify(state)}; ${error.message}`);}check(true,message);}
async function openPreferences(page){await waitFor(()=>page.evaluate(()=>FB.ready&&!ACCOUNT_TRANSITION_PENDING&&ACTIVE_ACCOUNT_SCOPE&&ACTIVE_ACCOUNT_SCOPE.kind==='local'),'local account scope did not settle before opening Preferences');await page.evaluate(()=>{TaxMateAccountStorage.write(localStorage,TaxMateAccountStorage.localScope(),'onboarding-done','browser-test');if(OB)obClose();S.settings.lang='en';S.tab='more';save();render();});await waitFor(()=>page.evaluate(()=>{const summary=[...document.querySelectorAll('summary')].find(node=>(node.textContent||'').trim()==='Preferences'),details=summary&&summary.closest('details');if(!summary||!details||!summary.isConnected)return false;if(!details.open)summary.click();return details.isConnected&&details.open;}),'Preferences did not remain open');}
async function waitForDownload(page,message){try{await waitFor(()=>page.getByRole('button',{name:'Download',exact:true}).isVisible(),message,15000);}catch(error){const state=await page.evaluate(()=>({tab:S.tab,lang:S.settings.lang,standalone:isStandalone(),installOptions:pwaInstallOptions(),onboarding:!!OB,preferences:[...document.querySelectorAll('details')].filter(node=>(node.querySelector('summary')&&node.querySelector('summary').textContent||'').trim()==='Preferences').map(node=>({open:node.open,visible:node.getClientRects().length>0})),buttons:[...document.querySelectorAll('button')].map(node=>({text:(node.textContent||'').trim(),visible:node.getClientRects().length>0})).filter(row=>/download/i.test(row.text))}));throw new Error(`${error.message}; pwaState=${JSON.stringify(state)}`);}}
async function exerciseServiceWorkerUpgrade(){
  serveLegacyWorker=true;const browser=await launch({profileName:'sw-upgrade'}),page=browser.page;
  try{
    await waitFor(()=>page.evaluate(async old=>{const registration=await navigator.serviceWorker.ready,keys=await caches.keys();return registration.active&&registration.active.state==='activated'&&keys.includes(old);},oldCache),'2.1.14 Service Worker did not activate');
    const before=await page.evaluate(async()=>{const registration=await navigator.serviceWorker.ready;return{active:registration.active&&registration.active.state,waiting:registration.waiting&&registration.waiting.state,installing:registration.installing&&registration.installing.state,caches:await caches.keys()};});
    serveLegacyWorker=false;
    let result;
    try{result=await page.evaluate(async({oldCache,currentCache})=>{const registration=await navigator.serviceWorker.ready,timeline=[],started=Date.now(),seen=new WeakSet(),record=(label,worker)=>{if(!worker)return;if(!seen.has(worker)){seen.add(worker);timeline.push({label,state:worker.state});worker.addEventListener('statechange',()=>timeline.push({label,state:worker.state}));}},snapshot=async()=>({active:registration.active&&registration.active.state,waiting:registration.waiting&&registration.waiting.state,installing:registration.installing&&registration.installing.state,caches:await caches.keys()});record('old-active',registration.active);registration.addEventListener('updatefound',()=>record('new-installing',registration.installing));await registration.update();record('post-update-installing',registration.installing);while(Date.now()-started<30000){const value=await snapshot();if(value.active==='activated'&&value.caches.includes(currentCache)&&!value.caches.includes(oldCache))return{timeline,beforeUpdate:'activated',...value};await new Promise(resolve=>setTimeout(resolve,100));}throw new Error(`service worker upgrade timeout ${JSON.stringify({timeline,state:await snapshot()})}`);},{oldCache,currentCache});}catch(error){const state=await page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();return{active:registration&&registration.active&&registration.active.state,waiting:registration&&registration.waiting&&registration.waiting.state,installing:registration&&registration.installing&&registration.installing.state,caches:await caches.keys()};});throw new Error(`${error.message}; diagnostic=${JSON.stringify({state,served:swDiagnostics.served,missing:swDiagnostics.missing,resourceFailures})}`);}
    const diagnostic={before,after:result,timeline:result.timeline,served:swDiagnostics.served.slice(),missing:swDiagnostics.missing.slice(),resourceFailures:resourceFailures.slice()};equal(before.caches.includes(oldCache),true,'real 2.1.14 worker and cache are active before update');equal(result.caches.includes(currentCache),true,'2.1.15 worker installs its complete current cache');equal(result.caches.includes(oldCache),false,'2.1.15 activation removes the 2.1.14 cache');equal(swDiagnostics.missing,[],'Service Worker upgrade has no missing required asset');equal(resourceFailures,[],'Service Worker upgrade has no failed same-origin response');return diagnostic;
  }finally{serveLegacyWorker=false;await browser.context.close();}
}

(async()=>{
  fs.mkdirSync(evidence,{recursive:true});prepareArtifact();await startServer();testEnv=await initializeTestEnvironment({projectId:'demo-taxmate',firestore:{rules:fs.readFileSync(path.join(root,'firestore.rules'),'utf8')},storage:{rules:fs.readFileSync(path.join(root,'storage.rules'),'utf8')}});
  const founder=await createUser('founder'),clean=await createUser('clean'),localA=await createUser('local-a'),localB=await createUser('local-b');const founderState=founderFixture(founder.localId);await seedFounder(founder,founderState);
  let browser=await launch(),page=browser.page;
  await page.evaluate(({founderUid,state})=>{const founder=TaxMateAccountStorage.firebaseScope(founderUid);TaxMateAccountStorage.write(localStorage,founder,'canonical',JSON.stringify(state));TaxMateAccountStorage.write(localStorage,founder,'onboarding-done','2.1.14');},{founderUid:founder.localId,state:founderState});
  await signInDirect(page,founder);await waitConverged(page,'2.1.14 Founder local profile and cloud data converge');
  const founderHome=await page.evaluate(()=>({businesses:S.businesses.map(row=>row.name),entries:S.entries.length,ltd:S.domain.companyProfiles.filter(row=>row.deletedAt==null).length,onboarding:!!OB,warning:(document.body.innerText||'').includes('Cloud sync paused after an account-data safety check')}));
  equal(founderHome.businesses,['das','Evri','Newset','Taxmate app'],'Founder Home shows all four businesses once');equal(founderHome.entries,79,'Founder restores all 79 local/cloud entries');equal(founderHome.ltd,1,'Founder restores the persistent Ltd');equal(founderHome.onboarding,false,'existing Founder account closes stale onboarding');equal(founderHome.warning,false,'removed account-boundary warning is absent');
  await page.evaluate(async()=>{const record=S.entries.find(row=>row.receiptPath),bytes=new Uint8Array([255,216,255,224,0,16,74,70,73,70,255,217]);await firebase.storage().ref(record.receiptPath).put(bytes,{contentType:'image/jpeg'});await firebase.storage().ref(`receipts/${cloudUser().uid}/orphan.jpg`).put(bytes,{contentType:'image/jpeg'});});
  const founderBackup=await page.evaluate(async()=>{const before=JSON.stringify(S),output=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(await output.archive.arrayBuffer());return{preview:inspected.preview,unchanged:before===JSON.stringify(S),businesses:inspected.state.businesses.map(row=>row.name)};});equal(founderBackup.preview.receipts,1,'Founder Full Backup includes the owned linked receipt');equal(founderBackup.preview.orphans,1,'Founder Full Backup includes the owned orphan');equal(founderBackup.unchanged,true,'Founder Full Backup does not mutate app state');equal(founderBackup.businesses,['das','Evri','Newset','Taxmate app'],'Founder Full Backup contains only the active Founder scope');
  await page.evaluate(()=>doSignOut());await signInDirect(page,clean);await waitConverged(page,'clean account opens its own scope');const cleanView=await page.evaluate(()=>{const founderNames=['das','Evri','Newset','Taxmate app','ToodaLoop Ltd'],businessRows=[...document.querySelectorAll('[data-home-business-row] .t')].map(node=>(node.textContent||'').trim()),textLines=(document.body.innerText||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);return{businesses:S.businesses.length,entries:S.entries.length,ltd:S.domain.companyProfiles.length,businessRows,founderTextLines:textLines.filter(line=>founderNames.includes(line))};});equal(cleanView,{businesses:0,entries:0,ltd:0,businessRows:[],founderTextLines:[]},'Founder to clean account transfers and renders no Founder data');const cleanBackup=await page.evaluate(async()=>{const before=JSON.stringify(S),output=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(await output.archive.arrayBuffer());return{preview:inspected.preview,unchanged:before===JSON.stringify(S)};});equal({businesses:cleanBackup.preview.businesses,entries:cleanBackup.preview.entries,receipts:cleanBackup.preview.receipts,orphans:cleanBackup.preview.orphans},{businesses:0,entries:0,receipts:0,orphans:0},'zero-receipt Full Backup succeeds');equal(cleanBackup.unchanged,true,'zero-receipt Full Backup leaves state unchanged');
  await page.evaluate(()=>doSignOut());await signInDirect(page,founder);await waitConverged(page,'Founder reopens after clean account');equal(await page.evaluate(()=>({businesses:S.businesses.map(row=>row.name),entries:S.entries.length,ltd:S.domain.companyProfiles.length})),{businesses:['das','Evri','Newset','Taxmate app'],entries:79,ltd:1},'Founder to clean to Founder restores the exact Founder scope');
  await page.evaluate(async()=>{await doSignOut();S=freshState();const now=Date.now();S.businesses=[{id:'local-business',name:'Unsigned Local Trade',structure:'sole',share:100,recordType:'business',schemaVersion:5,createdAt:now,updatedAt:now,deletedAt:null,deviceId:DEVICE_ID}];S.entries=[{id:'local-entry',bizId:'local-business',businessId:'local-business',kind:'income',amount:321,date:'2026-09-01',cat:'sales',pct:100,recordType:'entry',schemaVersion:5,createdAt:now,updatedAt:now,deletedAt:null,deviceId:DEVICE_ID}];save();});await page.evaluate(email=>localStorage.setItem('__tm_account_isolation_email',email),localA.email);await page.evaluate(()=>signIn());await page.getByRole('heading',{name:'Use this Google account?',exact:true}).waitFor({timeout:30000});equal(await page.locator('[data-first-sync-email]').innerText(),localA.email,'first-sync screen shows the complete selected email');equal(await accountCloudSummary(localA.localId),{meta:false,entries:0,ltd:0},'selected Account A receives zero writes before confirmation');
  await page.evaluate(email=>localStorage.setItem('__tm_account_isolation_email',email),localB.email);await page.getByRole('button',{name:'Choose another account',exact:true}).click();await page.getByRole('heading',{name:'Use this Google account?',exact:true}).waitFor({timeout:30000});equal(await page.locator('[data-first-sync-email]').innerText(),localB.email,'Choose another account returns to account selection and displays Account B');equal(await accountCloudSummary(localA.localId),{meta:false,entries:0,ltd:0},'choosing another account leaves Account A untouched');equal(await accountCloudSummary(localB.localId),{meta:false,entries:0,ltd:0},'Account B also receives zero writes before confirmation');equal(await page.evaluate(()=>{const raw=TaxMateAccountStorage.read(localStorage,TaxMateAccountStorage.localScope(),'canonical'),local=raw?JSON.parse(raw):null;return{businesses:(local&&local.businesses||[]).map(row=>row.id),entries:(local&&local.entries||[]).map(row=>row.id),pending:TaxMateAccountStorage.localAssociationPending(localStorage)};}),{businesses:['local-business'],entries:['local-entry'],pending:true},'unsigned local data remains unchanged while choosing accounts');
  await page.getByRole('button',{name:'Yes, use this account',exact:true}).click();await waitConverged(page,'confirmed Account B receives local data once');await waitFor(async()=>{const summary=await accountCloudSummary(localB.localId);return summary.meta&&summary.entries===1&&summary.ltd===0;},'confirmed Account B upload did not settle');equal(await accountCloudSummary(localB.localId),{meta:true,entries:1,ltd:0},'confirmed local data uploads once only to Account B');equal(await accountCloudSummary(localA.localId),{meta:false,entries:0,ltd:0},'unconfirmed Account A remains untouched');await page.evaluate(()=>flushSyncForConvergence(cloudUser().uid));equal((await adminRows(`users/${localB.localId}/entries`)).filter(row=>row.id==='local-entry').length,1,'double flush cannot duplicate the confirmed local entry');
  await browser.context.close();const upgrade=await exerciseServiceWorkerUpgrade();
  const chromeUa='Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36';browser=await launch({profileName:'android-chrome',userAgent:chromeUa,staleInstalled:true});page=browser.page;await openPreferences(page);await waitForDownload(page,'ordinary Android Chrome did not keep Download visible');check(true,'ordinary Android Chrome shows Download despite a stale installed marker');await page.evaluate(()=>{deferredInstall=null;});await page.getByRole('button',{name:'Download',exact:true}).click();await page.locator('#sb-andinstall.open').waitFor();check((await page.locator('#sb-andinstall').innerText()).includes('Chrome'),'Chrome receives browser-specific install instructions when no native prompt is available');await browser.context.close();
  const samsungUa='Mozilla/5.0 (Linux; Android 14; SAMSUNG SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Mobile Safari/537.36';browser=await launch({profileName:'samsung',userAgent:samsungUa,staleInstalled:true});page=browser.page;await openPreferences(page);await waitForDownload(page,'ordinary Samsung Internet did not keep Download visible');check(true,'ordinary Samsung Internet shows Download after uninstall/stale marker');await page.evaluate(()=>{deferredInstall=null;});await page.getByRole('button',{name:'Download',exact:true}).click();await page.locator('#sb-andinstall.open').waitFor();check((await page.locator('#sb-andinstall').innerText()).includes('Samsung Internet'),'Samsung Internet receives browser-specific install instructions when no native prompt is available');await browser.context.close();browser=await launch({profileName:'standalone',userAgent:chromeUa,standalone:true,staleInstalled:true});page=browser.page;await openPreferences(page);equal(await page.getByRole('button',{name:'Download',exact:true}).count(),0,'standalone PWA hides the redundant Download action');
  const identity=await page.evaluate(()=>TaxMateCore.VERSIONS);equal(identity.APP_VERSION,'2.1.15','browser gate runs TaxMate 2.1.15');equal(identity.PWA_CACHE_VERSION,currentCache,'browser gate runs the 2.1.15 cache');const unexpectedConsole=consoleErrors.filter(value=>!/Failed to load resource/.test(value));equal(unexpectedConsole.length,0,`browser gate has no unexpected errors (${unexpectedConsole.join(' | ')||'none'})`);const externalData=externalRequests.filter(value=>!/^https:\/\/apis\.google\.com\/js\/api\.js/.test(value));equal(externalData.length,0,'all account and backup data requests stay on local emulators');
  const result={status:'PASS',generatedAt:new Date().toISOString(),assertionCount,assertions,identity,syntheticIdentityHashes:{founder:sha(founder.localId),clean:sha(clean.localId),localA:sha(localA.localId),localB:sha(localB.localId)},founderBackup:founderBackup.preview,cleanBackup:cleanBackup.preview,serviceWorkerUpgrade:upgrade,externalDataRequestCount:externalData.length,sourceSha256:sha(fs.readFileSync(path.join(root,'src','app','app.js')))};fs.writeFileSync(resultPath,JSON.stringify(result,null,2)+'\n');process.stdout.write(`ACCOUNT_ISOLATION_BROWSER_PASS assertions=${assertionCount}\n`);
})().catch(error=>{fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(resultPath,JSON.stringify({status:'FAIL',generatedAt:new Date().toISOString(),assertionCount,safeErrorHash:sha(error&&error.stack||error)},null,2)+'\n');console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{for(const context of [...contexts])try{await context.close();}catch(_){}if(testEnv)try{await testEnv.cleanup();}catch(_){}if(server)await new Promise(resolve=>server.close(resolve));try{fs.rmSync(profileRoot,{recursive:true,force:true});}catch(_){};});
