'use strict';

const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {chromium}=require('playwright');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const firestore=require('firebase/firestore');
const LtdSync=require('../../src/core/ltd-sync');
const {make}=require('../test-fixture');

const root=path.resolve(__dirname,'../..');
const artifact=path.join(root,'.hosting-build','account-isolation-browser');
const evidence=path.resolve(process.env.TAXMATE_ACCOUNT_ISOLATION_EVIDENCE||path.join(root,'.hosting-build','account-isolation-evidence'));
const resultPath=path.join(evidence,'account-isolation-browser-result.json');
const runId=Date.now().toString(36),origin='http://127.0.0.1:4193',password='Account-Isolation-Only-20260901!';
const profileRoot=path.join(os.tmpdir(),`tm-isolate-${runId}`),profile=path.join(profileRoot,'shared');
const assertions=[],externalRequests=[],networkFailures=[],consoleErrors=[],switchRequests=[];
const contexts=new Set();
let assertionCount=0,testEnv,server,switchActive=false;
const forbidden=['Founder Isolation Trade','Founder Isolation Partnership','Synthetic Founder Ltd','8,765.43','8765.43','Founder-only receipt'];
const legacyBytes=' {"businesses":[{"name":"Unknown Legacy Owner"}],"entries":[{"amount":444.44}]}\r\n';
const oldCache='taxmate-v2-full-backup-founder-alias-production-1';
const currentCache=require('../../src/core/versions').VERSIONS.PWA_CACHE_VERSION;

function check(value,message){assert.ok(value,message);assertionCount++;assertions.push(message);}
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);assertionCount++;assertions.push(message);}
function sha(value){return crypto.createHash('sha256').update(String(value)).digest('hex');}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function waitFor(fn,message,timeout=60000){const started=Date.now();let last;while(Date.now()-started<timeout){try{last=await fn();if(last)return last;}catch(error){last=error.message;}await sleep(150);}throw new Error(`${message}; last=${String(last)}`);}
function chromePath(){for(const candidate of [process.env.TAXMATE_CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'])if(candidate&&fs.existsSync(candidate))return candidate;throw new Error('Installed Chrome not found');}
function business(id,name,structure,share,updatedAt,syncCode=null){return{id,name,structure,share,syncCode,recordType:'business',schemaVersion:5,createdAt:updatedAt,updatedAt,deletedAt:null,deviceId:'account-isolation-fixture'};}
function entry(id,bizId,kind,amount,updatedAt,extra={}){return{id,bizId,businessId:bizId,kind,amount,date:'2026-08-31',cat:kind==='income'?'sales':'other',pct:100,description:extra.description||'',receiptPath:extra.receiptPath||null,receiptUrl:null,recordType:'entry',schemaVersion:5,createdAt:updatedAt,updatedAt,deletedAt:null,deviceId:'account-isolation-fixture'};}
function emptyMeta(businesses,updatedAt){return{businesses,businessTombstones:[],folders:[],folderTombstones:[],customCats:{},activeCats:{},yearData:{},settings:{lang:'en',theme:'auto'},metaVersions:{},updatedAt,deviceId:'account-isolation-cloud'};}
function entitlement(tier){return{subscriptionStatus:tier==='pro'?'active':'inactive',paidTier:tier,currentPeriodEnd:tier==='pro'?Date.now()+86400000:0,serverVerifiedAt:Date.now()};}

function prepareArtifact(){
  const build=spawnSync(process.execPath,['scripts/build-hosting.js','production','account-isolation-browser'],{cwd:root,stdio:'inherit'});if(build.status!==0)throw new Error('Account-isolation Hosting artifact build failed');
  const firebaseFiles=['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js','firebase-storage-compat.js','firebase-app-check-compat.js'],vendor=path.join(artifact,'vendor','firebase');fs.mkdirSync(vendor,{recursive:true});
  for(const file of firebaseFiles)fs.copyFileSync(path.join(root,'node_modules','firebase',file),path.join(vendor,file));
  const htmlPath=path.join(artifact,'index.html');let html=fs.readFileSync(htmlPath,'utf8');
  for(const file of firebaseFiles)html=html.replace(new RegExp(`https://www\\.gstatic\\.com/firebasejs/[^"']+/${file}`,'g'),`vendor/firebase/${file}`);
  html=html.replace(/<script[^>]+https:\/\/(?:cdnjs\.cloudflare\.com|js-de\.sentry-cdn\.com)[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'').replace(/<noscript><link[^>]+https:\/\/fonts\.googleapis\.com[^>]*><\/noscript>\s*/gi,'');
  fs.writeFileSync(htmlPath,html);fs.writeFileSync(path.join(artifact,'src','app','sentry-bootstrap.js'),"'use strict';\nwindow.__TAXMATE_SENTRY_STATE__=Object.freeze({enabled:false,reason:'account_isolation_emulator',sdkRequested:false});\n");
  fs.writeFileSync(path.join(artifact,'firebase-environment.js'),`'use strict';
window.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:Object.freeze({apiKey:'demo-api-key',authDomain:'demo-taxmate.firebaseapp.com',projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com',messagingSenderId:'100000000000',appId:'1:100000000000:web:account-isolation'}),hosts:Object.freeze(['127.0.0.1','localhost']),appCheckKey:'demo-only'});
(function(){const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(config,name){const app=init(config,name),auth=firebase.auth(app);auth.useEmulator('http://127.0.0.1:9099',{disableWarnings:true});firebase.firestore(app).useEmulator('127.0.0.1',8080);firebase.storage(app).useEmulator('127.0.0.1',9199);auth.signInWithPopup=async function(){const email=localStorage.getItem('__tm_account_isolation_email');if(!email)throw new Error('No synthetic account selected');const credential=await auth.signInWithEmailAndPassword(email,${JSON.stringify(password)});return{user:credential.user,credential:null,additionalUserInfo:null,operationType:'signIn'};};return app;};firebase.appCheck=function(){return{activate:function(){},getToken:async function(){return{token:'emulator-app-check'};}};};})();
`);
}
function startServer(){const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.ico':'image/x-icon','.svg':'image/svg+xml','.xml':'application/xml','.txt':'text/plain; charset=utf-8'};server=http.createServer((request,response)=>{const pathname=new URL(request.url,origin).pathname,relative=decodeURIComponent(pathname==='/'?'/index.html':pathname).replace(/^\/+/,''),target=path.resolve(artifact,relative);if(!target.startsWith(path.resolve(artifact)+path.sep)||!fs.existsSync(target)){response.writeHead(404);response.end('Not found');return;}response.writeHead(200,{'content-type':mime[path.extname(target)]||'application/octet-stream','cache-control':relative==='sw.js'?'no-cache':'no-store'});fs.createReadStream(target).pipe(response);});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(4193,'127.0.0.1',resolve);});}
async function createUser(label){const email=`${label}-${runId}@taxmate.local`,response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-api-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});if(!response.ok)throw new Error('Auth emulator user creation failed');return{...(await response.json()),email};}
async function adminSet(pathName,value){await testEnv.withSecurityRulesDisabled(async context=>firestore.setDoc(firestore.doc(context.firestore(),...pathName.split('/')),value));}
async function adminGet(pathName){let value=null;await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDoc(firestore.doc(context.firestore(),...pathName.split('/')));value=snap.exists()?snap.data():null;});return value;}
async function adminRows(pathName){let rows=[];await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDocs(firestore.collection(context.firestore(),...pathName.split('/')));rows=snap.docs.map(doc=>doc.data());});return rows;}
async function accountCloudSummary(uid){const ltd={};for(const collection of LtdSync.COLLECTIONS)ltd[collection]=(await adminRows(`users/${uid}/ltd/v1/${collection}`)).length;return{meta:!!(await adminGet(`users/${uid}/app/meta`)),entries:(await adminRows(`users/${uid}/entries`)).length,ltd:Object.values(ltd).reduce((sum,count)=>sum+count,0)};}
async function seedFounder(user){
  const now=Date.now(),sole=business('founder-sole','Founder Isolation Trade','sole',100,now),partnership=business('founder-partnership','Founder Isolation Partnership','partnership',50,now,'ISO88888'),receiptPath=`receipts/${user.localId}/linked.jpg`;
  await adminSet(`users/${user.localId}/entitlements/current`,entitlement('pro'));await adminSet(`users/${user.localId}/app/meta`,emptyMeta([sole,partnership],now));await adminSet(`users/${user.localId}/entries/founder-income`,entry('founder-income',sole.id,'income',8765.43,now));await adminSet(`users/${user.localId}/entries/founder-receipt`,entry('founder-receipt',sole.id,'expense',12.34,now,{description:'Founder-only receipt',receiptPath}));
  await adminSet('partnerships/ISO88888',{createdBy:user.localId,bizId:partnership.id,name:partnership.name,businessUpdatedAt:now,businessDeviceId:'account-isolation-cloud'});await adminSet(`partnerships/ISO88888/members/${user.localId}`,{uid:user.localId,role:'owner',joinedAt:now});await adminSet('partnerships/ISO88888/entries/founder-partnership-income',entry('founder-partnership-income',partnership.id,'income',1000,now));
  const ltdState=JSON.parse(JSON.stringify(make('existing').driver.state)),company=ltdState.domain.entities.find(row=>row.type==='limited_company'),profile=ltdState.domain.companyProfiles.find(row=>row.entityId===company.id);company.name='Synthetic Founder Ltd';profile.legalName=company.name;const records=LtdSync.recordsForSync(ltdState);await adminSet(`users/${user.localId}/ltdControl/activeCompany`,{schemaVersion:1,status:'active_slot_claimed',activeCompanyId:company.id,releasePolicy:'retained_until_separately_approved_removal',claimedAt:now,updatedAt:now});for(const [collection,rows] of Object.entries(records))for(const row of rows){const envelope=LtdSync.envelope(collection,row,LtdSync.companyIdForRecord(collection,row,new Set([company.id])));await adminSet(LtdSync.documentPath(user.localId,collection,row.id),envelope);}
}
async function installGuard(context){await context.route('**/*',async route=>{const url=route.request().url(),external=/^https?:\/\//i.test(url)&&!/^http:\/\/(?:127\.0\.0\.1|localhost)(?::\d+)?\//i.test(url);if(/^https:\/\/www\.google\.com\/images\/cleardot\.gif/i.test(url)){await route.abort('blockedbyclient');return;}if(external){externalRequests.push(url);await route.abort('blockedbyclient');return;}await route.continue();});context.on('request',request=>{if(switchActive)switchRequests.push(request.url());});}
async function launch(options={}){const context=await chromium.launchPersistentContext(profile,{headless:true,executablePath:chromePath(),viewport:{width:390,height:844},serviceWorkers:'allow'});contexts.add(context);context.on('close',()=>contexts.delete(context));await installGuard(context);await context.addInitScript(({legacyBytes,forbidden})=>{if(!localStorage.getItem('__tm_account_isolation_seeded')){localStorage.setItem('__tm_account_isolation_seeded','1');localStorage.setItem('taxmateuk_v1',legacyBytes);localStorage.setItem('taxmateuk_analytics_consent','denied');}window.__tmLeakMonitorActive=localStorage.getItem('__tm_tammy_monitor')==='1';window.__tmForbiddenLeaks=[];const scan=source=>{if(!window.__tmLeakMonitorActive||!document.body)return;const text=document.body.innerText||'';for(const token of forbidden)if(text.includes(token))window.__tmForbiddenLeaks.push({source,token});};addEventListener('DOMContentLoaded',()=>{new MutationObserver(()=>scan('mutation')).observe(document.body,{subtree:true,childList:true,characterData:true});const frame=()=>{scan('frame');requestAnimationFrame(frame);};requestAnimationFrame(frame);});},{legacyBytes,forbidden});if(options.offline)await context.setOffline(true);const page=context.pages()[0]||await context.newPage();page.on('pageerror',error=>consoleErrors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!/(?:ERR_FAILED|ERR_BLOCKED_BY_CLIENT|ERR_INTERNET_DISCONNECTED|Could not reach Cloud Firestore backend|Failed to load resource)/.test(message.text()))consoleErrors.push(message.text());});page.on('response',response=>{if(response.status()>=400)networkFailures.push({status:response.status(),url:response.url()});});await page.goto(origin+'/',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>typeof window.ensureFB==='function'&&typeof window.firebase!=='undefined'&&window.TaxMateAccountStorage,null,{timeout:30000});return{context,page};}
async function signInDirect(page,user){await page.evaluate(async({email,password})=>{await ensureFB();await firebase.auth().signInWithEmailAndPassword(email,password);},{email:user.email,password});await page.waitForFunction(()=>firebase.auth().currentUser&&!firebase.auth().currentUser.isAnonymous,null,{timeout:30000});}
async function waitConverged(page,message){await waitFor(()=>page.evaluate(()=>{try{return !!cloudUser()&&CLOUD.hydrationState==='converged'&&CLOUD.partnershipHydrationState==='converged';}catch(_){return false;}}),message);check(true,message);}
async function installAccountInstrumentation(page){await page.evaluate(()=>{window.__tmAccountCalls={userRoots:[],partnerships:[],storagePaths:[]};const originalUserRoot=userRoot;userRoot=function(uid){window.__tmAccountCalls.userRoots.push(uid);return originalUserRoot(uid);};const originalSubscribe=subscribeSync;subscribeSync=function(code,bizId){window.__tmAccountCalls.partnerships.push(code);return originalSubscribe(code,bizId);};const storage=firebase.storage(),originalRef=storage.ref.bind(storage);storage.ref=function(value){window.__tmAccountCalls.storagePaths.push(String(value||''));return originalRef(value);};});}

(async()=>{
  fs.mkdirSync(evidence,{recursive:true});prepareArtifact();await startServer();testEnv=await initializeTestEnvironment({projectId:'demo-taxmate',firestore:{rules:fs.readFileSync(path.join(root,'firestore.rules'),'utf8')},storage:{rules:fs.readFileSync(path.join(root,'storage.rules'),'utf8')}});const founder=await createUser('founder'),tammy=await createUser('tammy'),localOwner=await createUser('local-owner');await seedFounder(founder);
  let browser=await launch(),page=browser.page;await page.waitForFunction(()=>ACTIVE_ACCOUNT_SCOPE&&ACTIVE_ACCOUNT_SCOPE.kind==='local'&&localStorage.getItem('taxmateuk_legacy_quarantine_v1:complete'),null,{timeout:30000});
  const quarantine=await page.evaluate(expected=>{const old=localStorage.getItem('taxmateuk_v1'),key=Object.keys(localStorage).find(name=>name.startsWith('taxmateuk_legacy_quarantine_v1:')&&name!=='taxmateuk_legacy_quarantine_v1:complete'),record=key?JSON.parse(localStorage.getItem(key)):null;return{oldRemoved:old===null,preserved:!!record&&record.entries.some(item=>item.key==='taxmateuk_v1'&&item.value===expected),rendered:(document.body.innerText||'').includes('Unknown Legacy Owner'),canonical:S.businesses.some(item=>item.name==='Unknown Legacy Owner')};},legacyBytes);equal(quarantine,{oldRemoved:true,preserved:true,rendered:false,canonical:false},'unknown-owner legacy bytes are quarantined, preserved, invisible and absent from canonical state');equal(await accountCloudSummary(tammy.localId),{meta:false,entries:0,ltd:0},'legacy quarantine creates zero writes in the clean account namespace');
  await signInDirect(page,founder);await waitConverged(page,'Founder synthetic account reaches full hydration');const founderView=await page.evaluate(()=>({businesses:S.businesses.map(row=>row.name),entries:S.entries.map(row=>row.id),partnership:S.businesses.some(row=>row.syncCode==='ISO88888'),receipt:S.entries.some(row=>row.receiptPath&&row.id==='founder-receipt'),ltd:(S.domain.companyProfiles||[]).some(row=>row.legalName==='Synthetic Founder Ltd')}));check(founderView.businesses.includes('Founder Isolation Trade')&&founderView.businesses.includes('Founder Isolation Partnership'),'Founder sees both owned business records');check(founderView.entries.includes('founder-income')&&founderView.entries.includes('founder-receipt'),'Founder sees owned entries and linked receipt record');equal(founderView.partnership,true,'Founder restores the owned partnership');equal(founderView.receipt,true,'Founder restores the owned receipt reference');equal(founderView.ltd,true,'Founder restores the owned Ltd domain');await page.evaluate(async()=>{const record=S.entries.find(row=>row.id==='founder-receipt'),bytes=new Uint8Array([255,216,255,224,0,16,74,70,73,70,255,217]);await firebase.storage().ref(record.receiptPath).put(bytes,{contentType:'image/jpeg'});await firebase.storage().ref('receipts/'+cloudUser().uid+'/orphan.jpg').put(new Uint8Array([255,216,255,225,0,8,255,217]),{contentType:'image/jpeg'});});check(true,'Founder synthetic browser uploads one linked and one orphan receipt inside its owned emulator namespace');
  const founderStorageCheck=await page.evaluate(async()=>{const record=S.entries.find(row=>row.id==='founder-receipt');try{const url=await firebase.storage().ref(record.receiptPath).getDownloadURL(),listed=await firebase.storage().ref('receipts/'+cloudUser().uid).listAll();return{resolved:!!url,listed:listed.items.length,errorClass:null};}catch(error){return{resolved:false,listed:null,errorClass:String(error&&error.code||error&&error.name||'unknown').replace(/[^a-z0-9_\/-]/gi,'_').slice(0,64)};}});equal(founderStorageCheck,{resolved:true,listed:2,errorClass:null},'Founder can resolve the linked receipt and list both owned Storage objects before Full Backup');
  const founderBackup=await page.evaluate(async()=>{const before=JSON.stringify(S),output=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(await output.archive.arrayBuffer());return{preview:inspected.preview,stateUnchanged:JSON.stringify(S)===before};});equal(founderBackup.preview.receipts,1,'Founder Full Backup includes the linked receipt binary');equal(founderBackup.preview.orphans,1,'Founder Full Backup includes the owned orphan receipt binary');equal(founderBackup.stateUnchanged,true,'Founder Full Backup leaves canonical state byte-for-byte unchanged');
  const upgrade=await page.evaluate(async({oldCache,currentCache})=>{const prior=await navigator.serviceWorker.ready;await prior.unregister();const old=await caches.open(oldCache);await old.put('/2.1.12-sentinel',new Response('2.1.12'));const registration=await navigator.serviceWorker.register('/sw.js?upgrade=2.1.13');await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('service worker upgrade timeout')),20000),worker=registration.installing||registration.waiting||registration.active;if(worker&&worker.state==='activated'){clearTimeout(timer);resolve();return;}worker.addEventListener('statechange',()=>{if(worker.state==='activated'){clearTimeout(timer);resolve();}});});await new Promise(resolve=>setTimeout(resolve,250));const keys=await caches.keys();return{oldRemoved:!keys.includes(oldCache),currentPresent:keys.includes(currentCache)};},{oldCache,currentCache});equal(upgrade,{oldRemoved:true,currentPresent:true},'2.1.12 cache upgrades atomically to the 2.1.13 service-worker cache');
  await installAccountInstrumentation(page);await page.evaluate(()=>{const uid=cloudUser().uid,box=TaxMateSync.enqueue(TaxMateSync.emptyOutbox(),{kind:'personal-state',uid,ownerUid:uid,updatedAt:Date.now(),deviceId:'synthetic-pending'},Date.now());window.__tmFounderOutboxKey=SYNC_OUTBOX_KEY;window.__tmFounderOutboxRaw=JSON.stringify(box);localStorage.setItem(window.__tmFounderOutboxKey,window.__tmFounderOutboxRaw);window.__tmAccountCalls={userRoots:[],partnerships:[],storagePaths:[]};const pending=doSignOut();localStorage.setItem('__tm_tammy_monitor','1');window.__tmLeakMonitorActive=true;return pending;});switchActive=true;await page.waitForFunction(()=>!firebase.auth().currentUser,null,{timeout:30000});await page.waitForFunction(()=>document.querySelector('#ob-root.active')&&[...document.querySelectorAll('button')].some(button=>/^Sign in/.test(button.textContent.trim())),null,{timeout:30000});
  await page.evaluate(email=>localStorage.setItem('__tm_account_isolation_email',email),tammy.email);await page.getByRole('button',{name:/^Sign in/}).first().click();await waitConverged(page,'Tammy reaches clean hydration after onboarding sign-in');await page.waitForFunction(()=>OB&&OB.screen==='entry'&&OB.loggedIn===true,null,{timeout:30000});check(true,'Tammy onboarding sign-in advances automatically to the next real step');
  const tammyView=await page.evaluate(forbidden=>({leaks:window.__tmForbiddenLeaks.slice(),stateLeak:forbidden.some(token=>JSON.stringify(S).includes(token)),businesses:S.businesses.length,entries:S.entries.length,ltd:(S.domain.companyProfiles||[]).length,screen:OB&&OB.screen,founderOutboxUnchanged:localStorage.getItem(window.__tmFounderOutboxKey)===window.__tmFounderOutboxRaw,calls:window.__tmAccountCalls}),forbidden);equal(tammyView.leaks,[],'Tammy renders zero Founder names or amounts across every observed mutation and animation frame');equal(tammyView.stateLeak,false,'Tammy canonical state contains zero Founder business, entry, partnership, receipt or Ltd data');equal({businesses:tammyView.businesses,entries:tammyView.entries,ltd:tammyView.ltd,screen:tammyView.screen},{businesses:0,entries:0,ltd:0,screen:'entry'},'Tammy starts with a clean account and the correct onboarding step');equal(tammyView.founderOutboxUnchanged,true,'Founder pending outbox bytes remain untouched in the Founder namespace while Tammy is active');equal(tammyView.calls.userRoots.every(uid=>uid===tammy.localId),true,'all post-switch personal cloud roots use only Tammy UID');equal(tammyView.calls.partnerships.includes('ISO88888'),false,'Tammy never subscribes to the Founder partnership code');equal(tammyView.calls.storagePaths.some(value=>value.includes(founder.localId)),false,'Tammy never addresses the Founder receipt namespace');equal(switchRequests.some(url=>url.includes(founder.localId)||url.includes('ISO88888')),false,'post-switch browser traffic contains no Founder Storage or partnership identifier');equal(await accountCloudSummary(tammy.localId),{meta:false,entries:0,ltd:0},'Tammy cloud stays empty until Tammy creates owned bookkeeping data');
  const tammyBackup=await page.evaluate(async()=>{const before=JSON.stringify(S),output=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(await output.archive.arrayBuffer());return{preview:inspected.preview,stateUnchanged:JSON.stringify(S)===before};});equal(tammyBackup.preview.receipts,0,'Tammy zero-receipt Full Backup succeeds with zero linked receipts');equal(tammyBackup.preview.orphans,0,'Tammy zero-receipt Full Backup succeeds with zero orphan receipts');equal(tammyBackup.stateUnchanged,true,'Tammy Full Backup leaves state byte-for-byte unchanged');
  await page.reload({waitUntil:'domcontentloaded'});await waitConverged(page,'Tammy survives an ordinary reload');equal(await page.evaluate(forbidden=>forbidden.some(token=>(document.body.innerText||'').includes(token)||JSON.stringify(S).includes(token)),forbidden),false,'Tammy reload renders zero Founder data');await page.evaluate(()=>navigator.serviceWorker.ready);await browser.context.close();browser=await launch({offline:true});page=browser.page;await page.waitForFunction(()=>window.TaxMateCore&&TaxMateCore.VERSIONS.APP_VERSION==='2.1.13',null,{timeout:30000});equal(await page.evaluate(forbidden=>forbidden.some(token=>(document.body.innerText||'').includes(token)||JSON.stringify(S).includes(token)),forbidden),false,'offline PWA terminate-and-reopen renders zero Founder data');check(await page.evaluate(()=>!!navigator.serviceWorker.controller),'offline reopen is controlled by the installed 2.1.13 service worker');await browser.context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.evaluate(async()=>{await ensureFB();const user=cloudUser();if(user)await startUserSync(user);});await waitConverged(page,'Tammy reconverges after offline PWA reopen');
  await installAccountInstrumentation(page);await page.evaluate(async()=>{await doSignOut();localStorage.removeItem('__tm_tammy_monitor');window.__tmLeakMonitorActive=false;});switchActive=false;await signInDirect(page,founder);await waitConverged(page,'Founder reconverges in the same persistent browser profile');const restored=await page.evaluate(()=>({businesses:S.businesses.map(row=>row.name).sort(),founderAmount:S.entries.find(row=>row.id==='founder-income')?.amount,partnership:S.businesses.some(row=>row.syncCode==='ISO88888'),receipt:S.entries.some(row=>row.id==='founder-receipt'&&!!row.receiptPath),ltd:(S.domain.companyProfiles||[]).some(row=>row.legalName==='Synthetic Founder Ltd')}));check(restored.businesses.includes('Founder Isolation Trade')&&restored.businesses.includes('Founder Isolation Partnership'),'switching back restores only Founder owned businesses');equal(restored.founderAmount,8765.43,'switching back restores the exact Founder owned entry');equal(restored.partnership,true,'switching back restores the Founder partnership');equal(restored.receipt,true,'switching back restores the Founder receipt reference');equal(restored.ltd,true,'switching back restores the Founder Ltd state');
  await page.evaluate(async email=>{await doSignOut();const now=Date.now();S.businesses=[{id:'local-owned-business',name:'Synthetic Local Trade',structure:'sole',share:100,recordType:'business',schemaVersion:5,createdAt:now,updatedAt:now,deletedAt:null,deviceId:DEVICE_ID}];S.entries=[{id:'local-owned-entry',bizId:'local-owned-business',businessId:'local-owned-business',kind:'income',amount:321,date:'2026-09-01',cat:'sales',pct:100,recordType:'entry',schemaVersion:5,createdAt:now,updatedAt:now,deletedAt:null,deviceId:DEVICE_ID}];save();localStorage.setItem('__tm_account_isolation_email',email);},localOwner.email);await page.evaluate(()=>signIn());await waitConverged(page,'local-only data associates with its first signed-in account');equal(await page.evaluate(()=>S.businesses.some(row=>row.name==='Synthetic Local Trade')&&S.entries.some(row=>row.id==='local-owned-entry')),true,'real browser local-only first sign-in preserves its owned canonical data');const localCloud=await accountCloudSummary(localOwner.localId);equal(localCloud.meta,true,'associated local-only business creates its first owned cloud meta only after sign-in');equal(localCloud.entries,1,'associated local-only entry writes only to its new owner namespace');
  const identity=await page.evaluate(()=>TaxMateCore.VERSIONS);equal(identity.APP_VERSION,'2.1.13','cross-account browser runs TaxMate 2.1.13');equal(identity.PWA_CACHE_VERSION,currentCache,'cross-account browser runs the isolated 2.1.13 cache');await page.screenshot({path:path.join(evidence,'account-isolation-final.png'),fullPage:true});equal(externalRequests.length,0,'cross-account regression makes zero external or production requests');const unexpectedConsole=consoleErrors.filter(message=>!/status of 400 \(Bad Request\)/.test(message));equal(unexpectedConsole.length,0,'cross-account regression has zero unexpected console or page errors');
  const result={status:'PASS',generatedAt:new Date().toISOString(),assertionCount,assertions,identity,syntheticIdentityHashes:{founder:sha(founder.localId),tammy:sha(tammy.localId),localOwner:sha(localOwner.localId)},zeroLeaks:true,zeroForeignRequests:true,zeroForeignWrites:true,founderBackup:{linked:founderBackup.preview.receipts,orphans:founderBackup.preview.orphans,stateUnchanged:founderBackup.stateUnchanged},tammyBackup:{linked:tammyBackup.preview.receipts,orphans:tammyBackup.preview.orphans,stateUnchanged:tammyBackup.stateUnchanged},serviceWorkerUpgrade:upgrade,externalRequestCount:externalRequests.length,networkFailureCount:networkFailures.length,unexpectedConsoleCount:unexpectedConsole.length,sourceSha256:sha(fs.readFileSync(path.join(root,'src','app','app.js')))};fs.writeFileSync(resultPath,JSON.stringify(result,null,2)+'\n');process.stdout.write(`ACCOUNT_ISOLATION_BROWSER_PASS assertions=${assertionCount}\n`);
})().catch(error=>{fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(resultPath,JSON.stringify({status:'FAIL',generatedAt:new Date().toISOString(),assertionCount,safeErrorHash:sha(error&&error.stack||error)},null,2)+'\n');console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{for(const context of [...contexts])try{await context.close();}catch(_){}if(testEnv)try{await testEnv.cleanup();}catch(_){}if(server)await new Promise(resolve=>server.close(resolve));try{fs.rmSync(profileRoot,{recursive:true,force:true});}catch(_){};});
