'use strict';
// Normal authenticated customer/staff workflows; isolated Firebase emulators
// plus a loopback Stripe protocol double. No adversarial or destructive tests.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright'),admin=require('firebase-admin'),Stripe=require('stripe');
const {createProvider}=require('../helpers/billing-provider-local'),{make}=require('../test-fixture'),LtdSync=require('../../src/core/ltd-sync');
const root=path.resolve(__dirname,'../..'),out=process.env.TAXMATE_NORMAL_EVIDENCE,origin='http://127.0.0.1:41895';
if(!out||process.env.GCLOUD_PROJECT!=='demo-taxmate'||process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:33880')throw Error('Isolated demo only');
const result={scope:'NORMAL_USE_ONLY',provider:'LOCAL_PROTOCOL_DOUBLE_NOT_STRIPE_TEST',status:'RUNNING',startedAt:new Date().toISOString(),assertions:[],captures:[],pageErrors:[],notRun:['Stripe TEST provider','production','adversarial/permissions/race/fault-injection/stress','destructive retention','legacy mixed aggregate suites','exact 2.1.18 old-data upgrade/restore']};
const check=(condition,label)=>{assert.ok(condition,label);result.assertions.push(label);},clone=v=>JSON.parse(JSON.stringify(v));
let browser,server,provider;const contexts=[];
function environment(){return `window.TAXMATE_FIREBASE_EMULATORS=true;window.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:{apiKey:'demo-api-key',authDomain:'demo-taxmate.firebaseapp.com',projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com',messagingSenderId:'100000000000',appId:'1:100000000000:web:billing-normal'},hosts:['127.0.0.1','localhost'],appCheckKey:'demo-only',functionsOrigin:'http://127.0.0.1:33501'});(function(){const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(c,n){const a=init(c,n);firebase.auth(a).useEmulator('http://127.0.0.1:33399',{disableWarnings:true});firebase.firestore(a).useEmulator('127.0.0.1',33880);firebase.storage(a).useEmulator('127.0.0.1',33999);return a;};firebase.appCheck=function(){return{activate(){},async getToken(){return{token:'emulator-app-check'}}};};})();`;}
async function serve(){server=http.createServer((req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,origin).pathname).slice(1)||'index.html';if(rel.includes('..'))throw Error('Invalid local asset path');let b;if(rel==='firebase-environment.js')b=Buffer.from(environment());else if(rel.startsWith('vendor/firebase/'))b=fs.readFileSync(path.join(root,'node_modules/firebase',path.basename(rel)));else b=fs.readFileSync(path.join(root,rel));if(rel==='index.html')b=Buffer.from(b.toString().replace(/https:\/\/www\.gstatic\.com\/firebasejs\/[^"']+\/(firebase-[^"']+\.js)/g,'vendor/firebase/$1').replace(/<script[^>]+https:\/\/cdnjs\.cloudflare\.com[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,''));res.writeHead(200,{'content-type':({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'})[path.extname(rel)]||'application/octet-stream','cache-control':'no-store'});res.end(b);}catch(_){res.writeHead(404).end();}});await new Promise(r=>server.listen(41895,'127.0.0.1',r));}
async function account(label,staff=false,mode='existing'){
  const user=await admin.auth().createUser({email:`billing-${label}-${Date.now()}@taxmate.local`,password:'Billing-Normal-2026!'});
  if(staff)await admin.auth().setCustomUserClaims(user.uid,{billingSupport:true,billingApprover:true,billingRefundOperator:true});
  const state=clone(make(mode).driver.state);for(const b of state.businesses)b.syncCode=null;for(const e of state.entries){delete e.receiptUrl;delete e.receiptPath;}state.settings.lang='en';state.settings.theme='light';state.tab='home';
  await admin.firestore().doc(`users/${user.uid}/entitlements/current`).set({paidTier:'plus',subscriptionStatus:'active',currentPeriodEnd:Date.now()+20*86400000,serverVerifiedAt:Date.now()});
  const companies=new Set(state.domain.entities.filter(e=>e.type==='limited_company'&&!e.deletedAt).map(e=>e.id));
  for(const [collection,rows]of Object.entries(LtdSync.recordsForSync(state)))for(const record of rows){const envelope=LtdSync.envelope(collection,record,LtdSync.companyIdForRecord(collection,record,companies));await admin.firestore().doc(`users/${user.uid}/ltd/v1/${collection}/${envelope.documentId}`).set(envelope);}
  const company=state.domain.companyProfiles.find(p=>!p.deletedAt);if(company)await admin.firestore().doc(`users/${user.uid}/ltdControl/activeCompany`).set({schemaVersion:1,status:'active_slot_claimed',activeCompanyId:company.entityId,releasePolicy:'founder_approval_required',claimedAt:Date.now(),updatedAt:Date.now()});
  const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',acceptDownloads:true});contexts.push(context);
  await context.route('**/*',r=>/^https?:/.test(r.request().url())&&!/^http:\/\/(127\.0\.0\.1|localhost):/.test(r.request().url())?r.abort():r.continue());
  await context.addInitScript(({state,uid})=>{localStorage.setItem(`taxmateuk_account_v1:firebase:${encodeURIComponent(uid)}:canonical`,JSON.stringify(state));localStorage.setItem(`taxmateuk_account_v1:firebase:${encodeURIComponent(uid)}:onboarding-done`,'1');localStorage.setItem('taxmateuk_analytics_consent','denied');},{state,uid:user.uid});
  const page=await context.newPage();page.on('pageerror',e=>result.pageErrors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>window.TaxMateLtdProductionAdapter?.isReady()&&typeof billingRefresh==='function');
  await page.evaluate(async c=>{await ensureFB();await firebase.auth().signInWithEmailAndPassword(c.email,c.password);},{email:user.email,password:'Billing-Normal-2026!'});
  await page.waitForFunction(()=>firebase.auth().currentUser&&CLOUD.hydrationState==='converged'&&syncStatus().state==='synced',null,{timeout:60000});
  return{user,page,context};
}
const click=async(page,action)=>{await page.locator('[data-tm-click='+JSON.stringify(action)+']:visible').first().click();};
const idle=page=>page.waitForFunction(()=>!BILLING_UI.loading&&!BILLING_UI.busy,null,{timeout:60000});
async function call(page,name,data={}){return page.evaluate(({name,data})=>callSecureFunction(name,data),{name,data});}
async function refresh(page){await page.evaluate(()=>billingRefresh());await idle(page);const error=await page.evaluate(()=>BILLING_UI.error);check(!error,'Billing refresh succeeds: '+(error||'ok'));}
async function shot(page,name){await page.evaluate(()=>document.fonts.ready);const file=name+'.png';const overlay=await page.locator('.sb.open,#ob-root.active').count()>0;await page.screenshot({path:path.join(out,file),fullPage:!overlay});const audit=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,theme:S.settings.theme,lang:S.settings.lang,color:getComputedStyle(document.body).backgroundColor,font:getComputedStyle(document.body).fontFamily,fontLoaded:document.fonts.check('800 16px "Plus Jakarta Sans"'),uid:firebase.auth().currentUser?.uid,buttons:[...document.querySelectorAll('.sb.open .btn,[data-billing-page] .btn')].filter(b=>b.getBoundingClientRect().width>0).map(b=>({text:b.innerText,width:b.getBoundingClientRect().width,scrollWidth:b.scrollWidth,clientWidth:b.clientWidth,scrollHeight:b.scrollHeight,clientHeight:b.clientHeight}))}));check(audit.scrollWidth<=audit.width,name+' no horizontal overflow');check(audit.fontLoaded,name+' font loaded');check(audit.buttons.every(b=>b.scrollWidth<=b.clientWidth+1&&b.scrollHeight<=b.clientHeight+1),name+' primary action text is not clipped');result.captures.push({file,...audit});}
async function shotRegion(page,selector,name){const file=name+'.png',element=page.locator(selector);check(await element.isVisible(),name+' source region is visible');await element.screenshot({path:path.join(out,file)});result.captures.push({file,region:selector,...await page.evaluate(()=>({lang:S.settings.lang,theme:S.settings.theme,width:innerWidth}))});}
async function event(type,object){const body=JSON.stringify({id:'evt_'+crypto.randomUUID().replaceAll('-',''),object:'event',created:Math.floor(Date.now()/1000),type,data:{object}}),signature=Stripe.webhooks.generateTestHeaderString({payload:body,secret:process.env.STRIPE_WEBHOOK_SECRET});const response=await fetch('http://127.0.0.1:33501/demo-taxmate/europe-west2/stripeWebhook',{method:'POST',headers:{'content-type':'application/json','stripe-signature':signature},body});check(response.ok,'Normal signed provider event '+type+' processed');}
async function request(page,paymentId){await page.evaluate(id=>openRefundRequest(id),paymentId);await page.locator('#refund-reason').selectOption('service_problem');await page.locator('#refund-extra').fill('Please review this payment. Ordinary local test request.');await click(page,'billingSubmitRefund()');await idle(page);await page.evaluate(()=>{if(document.getElementById('sb-notice')?.classList.contains('open'))closeSheet('notice');});const cases=await call(page,'getRefundCases');check(cases.cases.length>0,'Customer refund request saved');return cases.cases.find(c=>c.paymentId===paymentId);}
async function review(staff,c,decision,amount=100){await staff.evaluate(id=>billingStaffRead(id),c.id);await idle(staff);await staff.locator('#billing-decision').selectOption(decision);await staff.locator('#billing-basis').selectOption('goodwill');await staff.locator('#billing-reference').fill('Local simulated Founder case approval NORMAL-001');await staff.locator('#billing-calculation').fill('Normal test: refund approved amount; partial refund leaves access unchanged. Renewal unchanged.');await staff.locator('#billing-publicReason').fill('Your request has been reviewed.');await staff.locator('#billing-amount').fill(String(amount));await click(staff,'billingStaffPreview()');await idle(staff);const x=await staff.evaluate(()=>BILLING_UI.staffCase.context);check(x.status==='ready'&&x.payment.createdAt>0&&x.invoice?.lines.length>0,'CS reads trusted payment and funded-period context');check(await staff.getByText('Service problem',{exact:true}).isVisible(),'CS shows the selected customer reason');await click(staff,'billingStaffReview()');await idle(staff);check(!await staff.evaluate(()=>BILLING_UI.error),'CS review has no error');return(await call(staff,'getBillingSupportCase',{caseId:c.id})).case;}
async function executeCase(staff,c){const r=await call(staff,'getBillingSupportCase',{caseId:c.id});return call(staff,'executeReviewedRefund',{caseId:c.id,revision:r.case.revision,contextVersion:r.context.version});}
async function billingVisualAudit(page,keys=[]){
  const audit=await page.evaluate(keys=>{
    const root=document.querySelector('.sb.open [data-billing-body]')||document.querySelector('[data-billing-page]')||document.getElementById('page'),text=root.innerText;
    const rgb=hex=>{const value=hex.trim().replace('#','');return 'rgb('+[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)).join(', ')+')';},css=getComputedStyle(document.documentElement);
    return{keys:keys.map(k=>({key:k,expected:bt(k),visible:text.includes(bt(k)),wrong:S.settings.lang!=='en'&&bt(k)!==TaxMateBillingCopy.en[k]&&text.includes(TaxMateBillingCopy.en[k])})),money:[...root.querySelectorAll('[data-billing-money]')].filter(e=>e.getClientRects().length&&Number(e.dataset.minor)!==0).map(e=>({role:e.dataset.billingMoney,color:getComputedStyle(e).color,expected:rgb(css.getPropertyValue(e.dataset.billingMoney==='out'?'--money-out':'--money-in'))})),legacyEnglish:/Paid access ends on|Manage subscription/.test(text),retentionRepeated:(text.match(/Full Backup ZIP/g)||[]).length};
  },keys);
  check(audit.money.every(m=>m.color===m.expected),'Direction A payment red and refund-credit green: '+JSON.stringify(audit.money));
  check(audit.keys.every(k=>k.visible&&!k.wrong),'Normal state translated: '+JSON.stringify(audit.keys));
  check(!audit.legacyEnglish,'No legacy English entitlement reminder');
  return audit;
}
async function matrix(page,name,show,keys=[],widths=[390,1440]){
  const prior=await page.evaluate(()=>({lang:S.settings.lang,theme:S.settings.theme})),viewport=page.viewportSize();
  for(const width of widths)for(const lang of ['en','zh','pl','ro','es','ur'])for(const theme of ['light','dark']){
    await page.setViewportSize({width,height:900});
    await page.evaluate(({lang,theme})=>{for(const id of ['billing','refund'])closeSheet(id);setLang(lang);setTheme(theme);},{lang,theme});
    await show();await idle(page);await billingVisualAudit(page,keys);await shot(page,'review-'+name+'-'+lang+'-'+theme+'-'+width);
  }
  await page.setViewportSize(viewport);await page.evaluate(({lang,theme})=>{for(const id of ['billing','refund'])closeSheet(id);setLang(lang);setTheme(theme);},prior);await show();await idle(page);
}
async function annualRefundNormal(desk){
  result.annualRefund=[];
  for(const mode of ['annual-only','other-grant','grant-after-submission']){
    const owner=await account(mode),page=owner.page,stamp=Math.floor(Date.now()/1000),seed=provider.seed(owner.user.uid,'plus',{cadence:'yearly',start:stamp,end:stamp+365*86400});
    await admin.firestore().doc('billingCustomers/'+owner.user.uid).set({stripeCustomerId:seed.customerId});
    if(mode==='other-grant')provider.seed(owner.user.uid,'pro',{customerId:seed.customerId});
    await page.evaluate(()=>openBillingOverview());await idle(page);const requested=await request(page,seed.chargeId),approved=await review(desk,requested,'full');
    check(approved.approvedMinor===2999,'Annual full refund uses paid 2999 minor units: '+mode);
    const inspect=async(state,basis,tier)=>{
      await refresh(page);const c=(await call(page,'getRefundCases')).cases.find(c=>c.id===requested.id),x=c.refundImpact;
      check(c.state===state&&x.basis===basis&&x.afterTier===tier,'Annual case state and source: '+mode+' '+state);
      const show=async()=>{
        await page.evaluate(id=>billingCase(id),c.id);
        check(await page.locator('#sb-billing [data-billing-data-details]:not([open])').count()===1,'Refund data details start collapsed: '+mode+' '+state);
        await page.locator('#sb-billing [data-billing-data-details]>summary').click();
        const shown=await page.evaluate(()=>({text:document.querySelector('[data-refund-retention]').innerText,basis:document.querySelector('[data-customer-refund-impact]').dataset.basis}));
        const expected=await page.evaluate(r=>billingStaffRetention(r),x.retention);
        check(shown.text===expected&&shown.basis===basis,'Expanded refund text equals case-specific backend retention: '+mode+' '+state);
        if(tier==='free'){
          const boundary=await page.evaluate(()=>ENTITLEMENT.snapshot.accountRetention.scheduledDeletionDate);
          check(x.retention.deleteOnDate&&x.retention.retainThroughDate,'Free refund result includes known retention dates');
          if(state!=='refunded')check(boundary&&x.retention.deleteOnDate!==boundary,'Conditional annual dates differ from currently funded expiry dates');
        }
      };
      if(mode!=='grant-after-submission')await matrix(page,'annual-'+mode+'-'+state,show,[state,basis==='conditional'?'afterRefund':'refundResult','dataDetails'],state==='approved'?[390,1440]:[390]);else await show();
      await page.evaluate(()=>{closeSheet('billing');setLang('zh');setTheme('light');});await show();await shot(page,'b031-'+mode+'-'+state);await shotRegion(page,'[data-customer-refund-impact]','b031-'+mode+'-'+state+'-impact');
      result.annualRefund.push({mode,state,case:c,currentRetention:await page.evaluate(()=>ENTITLEMENT.snapshot.accountRetention),visibleText:await page.locator('#sb-billing [data-billing-body]').innerText()});
      await page.evaluate(()=>closeSheet('billing'));return c;
    };
    await inspect('approved','conditional',mode==='other-grant'?'pro':'free');
    await executeCase(desk,approved);const pending=await inspect('refund_pending','conditional',mode==='other-grant'?'pro':'free');
    // An ordinary, independently paid plan acquired while the refund is pending
    // must appear in the actual confirmed outcome, not the reviewed forecast.
    if(mode==='grant-after-submission')provider.seed(owner.user.uid,'pro',{customerId:seed.customerId});
    await event('refund.updated',provider.completeRefund(pending.refundId));
    const confirmed=await inspect('refunded','confirmed',mode==='annual-only'?'free':'pro');
    const actual=(await call(desk,'getBillingSupportCase',{caseId:confirmed.id})).context.current;
    check(JSON.stringify(confirmed.refundImpact.retention)===JSON.stringify(actual.retention)&&confirmed.refundImpact.afterTier===actual.tier,'Confirmed customer result matches reconciled funding, not old forecast: '+mode);
  }
}
async function main(){
  admin.initializeApp({projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com'});provider=createProvider();await provider.start();await serve();browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',headless:true});
  const customer=await account('customer'),staff=await account('staff',true),page=customer.page,desk=staff.page;
  const buyer=await account('new-purchase');await admin.firestore().doc(`users/${buyer.user.uid}/entitlements/current`).set({paidTier:'free',subscriptionStatus:'none',serverVerifiedAt:Date.now()});await buyer.page.evaluate(()=>loadEntitlementFromCloud(firebase.auth().currentUser.uid));
  await buyer.page.evaluate(()=>billingBeginPurchase('plus','monthly'));await idle(buyer.page);await shot(buyer.page,'checkout-01-precontract');check(await buyer.page.locator('#billing-terms').isChecked()===false&&await buyer.page.locator('#billing-early').isChecked()===false,'Checkout choices start unchecked');
  const offered=await buyer.page.evaluate(()=>BILLING_UI.purchaseOffer);check(offered.priceMinor===399&&offered.contract.termsHtml.includes('Cancellation and refunds'),'Trusted offer carries price and complete terms');
  for(const lang of ['en','zh','pl','ro','es','ur'])for(const theme of ['light','dark']){await buyer.page.evaluate(({lang,theme})=>{closeSheet('billing');setLang(lang);setTheme(theme);},{lang,theme});await buyer.page.evaluate(()=>billingBeginPurchase('plus','monthly'));await idle(buyer.page);await billingVisualAudit(buyer.page,['englishContract']);await shot(buyer.page,`locale-${lang}-${theme}-precontract`);}await buyer.page.evaluate(()=>{closeSheet('billing');setLang('en');setTheme('light');});await buyer.page.evaluate(()=>billingBeginPurchase('plus','monthly'));await idle(buyer.page);const finalOffer=await buyer.page.evaluate(()=>BILLING_UI.purchaseOffer);
  await buyer.page.locator('#billing-terms').check();await buyer.page.locator('#billing-early').check();await click(buyer.page,'billingAcceptOffer()');await idle(buyer.page);await shot(buyer.page,'checkout-02-addressed-record');
  let confirmations=(await call(buyer.page,'getPurchaseConfirmations')).records;check(confirmations.length===1&&confirmations[0].earlySupplyRequested===true,'Separate express request and addressed terms persist before payment');check(await buyer.page.evaluate(()=>currentTier())==='free','Checkout creation does not grant paid access');
  const checkout=Object.values(provider.data.sessions).find(s=>s.metadata?.firebaseUid===buyer.user.uid);check(!!checkout,'Checkout created through real callable and local SDK protocol');
  await buyer.page.evaluate(()=>closeSheet('billing'));await buyer.page.evaluate(()=>billingBeginPurchase('plus','monthly'));await idle(buyer.page);check(await buyer.page.evaluate(()=>BILLING_UI.purchaseOffer.id)===finalOffer.id,'Normal return resumes the same checkout offer');await buyer.page.locator('#billing-terms').check();await buyer.page.locator('#billing-early').check();await click(buyer.page,'billingAcceptOffer()');await idle(buyer.page);check(Object.values(provider.data.sessions).filter(s=>s.metadata?.firebaseUid===buyer.user.uid).length===1,'Normal resume retains one provider session');await buyer.page.evaluate(()=>closeSheet('billing'));
  await event('checkout.session.completed',provider.completeCheckout(checkout.id));await buyer.page.evaluate(()=>openBillingOverview());await idle(buyer.page);check(await buyer.page.evaluate(()=>currentTier())==='plus','Provider-paid checkout grants funded Plus');confirmations=(await call(buyer.page,'getPurchaseConfirmations')).records;check(confirmations[0].outcome.paymentStatus==='paid'&&confirmations[0].termsHtml===offered.contract.termsHtml,'Payment outcome does not mutate accepted contract');await buyer.page.evaluate(()=>billingPurchases());await idle(buyer.page);await shot(buyer.page,'checkout-03-purchase-records');await buyer.page.evaluate(()=>closeSheet('billing'));
  const initial=provider.seed(customer.user.uid,'plus');await admin.firestore().doc(`billingCustomers/${customer.user.uid}`).set({stripeCustomerId:initial.customerId});
  const onboarding=await account('onboarding',false,'fresh'),op=onboarding.page;await admin.firestore().doc(`users/${onboarding.user.uid}/entitlements/current`).set({paidTier:'free',subscriptionStatus:'none',serverVerifiedAt:Date.now()});await op.evaluate(async()=>{await loadEntitlementFromCloud(firebase.auth().currentUser.uid);startOnboarding();obGo('entry');});await click(op,"obGo('ltd-choice')");await click(op,"obChooseLtdPath('forming')");await click(op,"obChooseLtdRegistration('not_available')");await op.waitForFunction(()=>OB?.screen==='pro-gate');const intent=await op.evaluate(()=>JSON.stringify(OB.pendingIntent));await click(op,'obProUpgrade()');await idle(op);await shot(op,'onboarding-01-checkout');check(await op.locator('#billing-terms').isVisible(),'Onboarding checkout is visible');await op.locator('#billing-terms').check();await op.locator('#billing-early').check();await click(op,'billingAcceptOffer()');await idle(op);const os=Object.values(provider.data.sessions).find(s=>s.metadata?.firebaseUid===onboarding.user.uid);check(!!os,'Onboarding reaches real callable Checkout');
  await op.goto(origin+'?billing=cancelled');await op.waitForFunction(()=>CLOUD.hydrationState==='converged'&&OB?.screen==='pro-gate',null,{timeout:60000});check(await op.evaluate(()=>JSON.stringify(OB.pendingIntent))===intent,'Cancel return preserves pending company intent');await shot(op,'onboarding-02-cancel-return');
  await event('checkout.session.completed',provider.completeCheckout(os.id));await click(op,'obRefreshPaidAccess()');await op.waitForFunction(()=>document.body.classList.contains('ltd-active'),null,{timeout:60000});check(await op.evaluate(()=>currentTier())==='pro','Confirmed Pro resumes the original company flow');await shot(op,'onboarding-03-company-resumed');
  for(let n=0;n<24;n++){const c=clone(provider.data.charges[initial.chargeId]),i=clone(provider.data.invoices[initial.invoiceId]);c.id='ch_history_'+n;c.invoice='in_history_'+n;c.created-=86400*(31+n);i.id=c.invoice;i.created=c.created;i.lines.data[0].period={start:c.created-30*86400,end:c.created};provider.data.charges[c.id]=c;provider.data.invoices[i.id]=i;}
  await page.evaluate(()=>openBillingOverview());await idle(page);await shot(page,'01-billing-overview');
  await click(page,"billingScreen('history')");check(await page.locator('.review01-rows>.row').count()===20,'First history page has 20 real callable rows');await click(page,'billingMore()');await idle(page);check(await page.locator('.review01-rows>.row').count()===25,'Payment pagination retains all 25 records');await shot(page,'02-payment-history');
  const c=await request(page,'ch_history_0');check(c.state==='submitted','Request is submitted, not auto-approved');await shot(page,'03-request-submitted');
  await desk.evaluate(()=>openBillingOverview());await idle(desk);await desk.evaluate(()=>billingStaffOpen());await idle(desk);await shot(desk,'04-cs-case-list');
  const approved=await review(desk,c,'partial',100);check(approved.state==='approved','Human review does not submit money');await shot(desk,'05-cs-reviewed');
  await desk.evaluate(()=>billingStaffExecute());await desk.locator('#cf-yes').click();await idle(desk);let processed=(await call(desk,'getBillingSupportCase',{caseId:c.id})).case;check(processed.state==='refund_pending','Provider pending is not shown as refunded');await shot(desk,'06-cs-processing');await refresh(page);await matrix(page,'refund-pending',()=>page.evaluate(id=>billingCase(id),c.id),['refund_pending']);await page.evaluate(()=>closeSheet('billing'));
  const refund=provider.completeRefund(processed.refundId);await event('refund.updated',refund);await refresh(page);processed=(await call(page,'getRefundCases')).cases.find(x=>x.id===c.id);check(processed.state==='refunded'&&processed.approvedMinor===100,'Provider confirmation reaches user case');check(!('reviewedBy'in processed)&&!('reference'in processed),'Customer receives public case projection');await page.evaluate(id=>billingCase(id),c.id);await shot(page,'07-refund-confirmed');await matrix(page,'refund-confirmed',()=>page.evaluate(id=>billingCase(id),c.id),['refunded','refundAmount','refundResult']);await page.evaluate(()=>closeSheet('billing'));
  await page.evaluate(()=>openBillingPlans());await click(page,`billingQuote('${initial.subscriptionId}','pro')`);await idle(page);await shot(page,'08-upgrade-quote');const quote=await page.evaluate(()=>BILLING_UI.quote);check(quote.dueNowMinor>0&&quote.creditMinor>0,'Upgrade shows actual protocol quote difference and unused paid credit');await matrix(page,'upgrade-quote',()=>page.evaluate(q=>billingShowQuote(q,true),quote),['dueNow','credit','charge','upgradeNote']);check(!await page.locator('#sb-billing [data-billing-body]').innerText().then(t=>t.includes('Full Backup ZIP')),'Upgrade primary view omits unrelated backup responsibility');
  await click(page,`billingConfirmQuote('${quote.id}')`);await idle(page);check(await page.evaluate(()=>currentTier())==='plus','Pending upgrade keeps funded Plus');check((await call(page,'getSubscriptionStatus')).changes.find(q=>q.id===quote.id).state==='pending_payment','Pending upgrade visible');await matrix(page,'pending-upgrade',()=>page.evaluate(()=>openBillingPlans()),['pending_payment']);
  const paid=provider.completeUpgrade(initial.subscriptionId);await event('invoice.paid',paid);await refresh(page);check(await page.evaluate(()=>currentTier())==='pro','Paid upgrade enables Pro');check((await call(page,'getSubscriptionStatus')).changes.find(q=>q.id===quote.id).state==='applied','Paid quote resolves to applied');await shot(page,'09-pro-active');
  await click(page,`billingQuote('${initial.subscriptionId}','plus')`);await idle(page);const down=await page.evaluate(()=>BILLING_UI.quote);check(down.dueNowMinor===0&&down.effectiveAt===provider.data.subscriptions[initial.subscriptionId].current_period_end*1000,'Downgrade starts at paid end with no current charge');await click(page,`billingConfirmQuote('${down.id}')`);await idle(page);check(await page.evaluate(()=>currentTier())==='pro','Scheduled downgrade retains Pro');check(Object.values(provider.data.subscriptions).filter(s=>s.customer===initial.customerId).length===1,'Upgrade/downgrade retain the same subscription');await shot(page,'10-downgrade-scheduled');await matrix(page,'scheduled-downgrade',()=>page.evaluate(()=>openBillingPlans()),['scheduled','nextRenewal']);
  const renewal=(await call(page,'getSubscriptionStatus')).subscriptions.find(s=>s.id===initial.subscriptionId).nextRenewal;check(renewal?.tier==='plus'&&renewal.basePriceMinor===399,'Scheduled downgrade displays provider-backed next Plus renewal price');
  await click(page,`billingCancel('${initial.subscriptionId}')`);await shot(page,'11-cancel-warning');await matrix(page,'cancel-confirmation',()=>page.evaluate(id=>billingCancel(id),initial.subscriptionId),['cancelConfirm','dataDetails']);check(await page.locator('#sb-billing [data-billing-data-details]:not([open])').count()===1,'Cancel backup and retention details are collapsed once');await click(page,`billingConfirmCancel('${initial.subscriptionId}')`);await idle(page);check(provider.data.subscriptions[initial.subscriptionId].cancel_at_period_end===true,'Cancel renewal is saved by provider protocol');check(await page.evaluate(()=>currentTier())==='pro','Cancel renewal retains paid Pro');await shot(page,'12-renewal-stopped');
  await page.evaluate(()=>go('home'));await shot(page,'review-home-cancel-first');check(await page.locator('[data-billing-notice="paid-end"]').isVisible(),'Ordinary stop-renewal return to Home shows a structured reminder');
  await matrix(page,'home-canceled',()=>page.evaluate(()=>{const n=TaxMateEntitlement.notification(ENTITLEMENT.snapshot,Date.now());const key=accountSlotKey('notice:'+String(n.id).replace(/[^a-z0-9._-]/gi,'-'));localStorage.removeItem(key);go('home');}),[]);
  check(await page.locator('[data-billing-notice]').innerText().then(t=>!t.includes('Full Backup ZIP')),'Home cancellation reminder is concise');
  await page.evaluate(()=>openBillingOverview());await idle(page);
  const currentCharge=Object.values(provider.data.charges).find(c=>c.invoice===paid.id),full=await request(page,currentCharge.id);
  await desk.evaluate(id=>billingStaffRead(id),full.id);await idle(desk);let fullContext=await desk.evaluate(()=>BILLING_UI.staffCase.context);
  check(fullContext.preview.after.tier==='free'&&fullContext.preview.consumedCredit,'CS previews Free after full refund of same-subscription credited upgrade');
  await shot(desk,'review-cs-full-upgrade-free');await shotRegion(desk,'[data-refund-impact]','review-cs-upgrade-free-impact');const beforeAdditionalVersion=fullContext.version;
  const additional=provider.seed(customer.user.uid,'plus',{customerId:initial.customerId});
  await refresh(page);await desk.evaluate(id=>billingStaffRead(id),full.id);await idle(desk);fullContext=await desk.evaluate(()=>BILLING_UI.staffCase.context);check(fullContext.preview.after.tier==='plus'&&fullContext.preview.after.grants.some(g=>g.id===additional.subscriptionId),'CS previews independent Plus remaining');check(fullContext.version!==beforeAdditionalVersion,'An ordinary additional paid plan changes the review fact version');await shotRegion(desk,'[data-refund-impact]','review-cs-independent-plus-impact');check(fullContext.otherGrants.some(g=>g.id===additional.subscriptionId),'Other valid paid grants are explicitly listed for CS');await matrix(desk,'cs-review',()=>desk.evaluate(id=>billingStaffRead(id),full.id),['requestReason','reviewContext','paymentDate','availableAmount','afterRefund']);const fullApproved=await review(desk,full,'full');
  const reviewedVersion=(await call(desk,'getBillingSupportCase',{caseId:full.id})).context.version;await refresh(page);check((await call(desk,'getBillingSupportCase',{caseId:full.id})).context.version===reviewedVersion,'Ordinary status refresh without changed facts preserves approval context');await executeCase(desk,fullApproved);const pending=(await call(desk,'getBillingSupportCase',{caseId:full.id})).case;await event('refund.updated',provider.completeRefund(pending.refundId));await refresh(page);check(await page.evaluate(()=>currentTier())==='plus','Full Pro refund retains separately paid Plus');
  await page.evaluate(()=>openBillingPlans());check(await page.getByText('No funded access remains for this subscription.',{exact:true}).isVisible(),'Provider Active is distinguished from refunded-away funded access');
  const follow=await request(page,'ch_history_1');await review(desk,follow,'needs_information');await refresh(page);await matrix(page,'refund-needs-information',()=>page.evaluate(id=>billingCase(id),follow.id),['needs_information','reply']);await page.evaluate(id=>billingCase(id),follow.id);await page.locator('#billing-reply').fill('Additional normal customer information.');await click(page,`billingReply('${follow.id}')`);await idle(page);let next=(await call(page,'getRefundCases')).cases.find(c=>c.id===follow.id);check(next.state==='submitted','Requested customer information is persisted');next=await review(desk,next,'decline');check(next.state==='declined','Decline is recorded without refund');
  for(const lang of ['en','zh','pl','ro','es','ur'])for(const theme of ['light','dark']){await page.evaluate(({lang,theme})=>{setLang(lang);setTheme(theme);billingScreen('overview');},{lang,theme});await shot(page,`locale-${lang}-${theme}-overview`);await page.evaluate(()=>openRefundRequest());await shot(page,`locale-${lang}-${theme}-refund`);await page.evaluate(()=>closeSheet('refund'));}
  for(const width of [360,412,1440]){await page.setViewportSize({width,height:900});await page.evaluate(()=>{setLang('zh');setTheme('light');billingScreen('plans');});await shot(page,'plans-width-'+width);}
  const repeat=await request(page,'ch_history_0');check(repeat.id!==c.id,'A new normal request after completed partial refund has a new case identity');await desk.evaluate(id=>billingStaffRead(id),repeat.id);await idle(desk);check(await desk.evaluate(()=>BILLING_UI.staffCase.context.payment.availableMinor)===299,'After a partial refund, full means the remaining 299 minor units');await desk.locator('#billing-decision').selectOption('full');await desk.evaluate(()=>billingStaffPreview());await idle(desk);check(await desk.evaluate(()=>BILLING_UI.staffCase.context.preview.amountMinor)===299,'CS full-remaining preview is exact');await shot(desk,'review-cs-full-remaining');await shotRegion(desk,'[data-refund-impact]','review-cs-full-remaining-impact');await review(desk,repeat,'partial',50);await desk.evaluate(()=>billingStaffExecute());await desk.locator('#cf-yes').click();await idle(desk);const again=(await call(desk,'getBillingSupportCase',{caseId:repeat.id})).case;await event('refund.updated',provider.completeRefund(again.refundId,'failed'));check((await call(page,'getRefundCases')).cases.find(r=>r.id===repeat.id).state==='refund_failed','Normal provider failed refund stays distinct from success');await refresh(page);await matrix(page,'refund-failed',()=>page.evaluate(id=>billingCase(id),repeat.id),['refund_failed']);await page.evaluate(()=>closeSheet('billing'));
  const last=await request(page,'ch_history_0'),lastReview=await review(desk,last,'partial',50);await executeCase(desk,lastReview);const lastPending=(await call(desk,'getBillingSupportCase',{caseId:last.id})).case;await event('refund.updated',provider.completeRefund(lastPending.refundId,'canceled'));check((await call(page,'getRefundCases')).cases.find(r=>r.id===last.id).state==='refund_canceled','Normal provider canceled refund stays distinct from success');await refresh(page);await matrix(page,'refund-canceled',()=>page.evaluate(id=>billingCase(id),last.id),['refund_canceled']);await page.evaluate(()=>closeSheet('billing'));
  const replied=(await call(page,'getRefundCases')).cases.find(r=>r.id===follow.id);check(replied.acknowledgement.note.includes('Ordinary local test request')&&replied.customerNote.includes('Additional normal'),'Original acknowledgement is immutable when customer adds information');
  const sample=(await call(desk,'getBillingSupportCase',{caseId:c.id})).case;for(let n=0;n<105;n++){const id='case_normal_history_'+n;await admin.firestore().doc('billingRefundCases/'+id).set({...sample,id,state:'declined',updatedAt:sample.updatedAt-1000-n});}await desk.evaluate(()=>billingStaffOpen());await idle(desk);check(await desk.evaluate(()=>BILLING_UI.staffCases.length)===100&&await desk.evaluate(()=>BILLING_UI.staffHasMore),'Long normal staff history exposes next page');await desk.evaluate(()=>billingStaffMore());await idle(desk);check(await desk.evaluate(()=>BILLING_UI.staffCases.filter(c=>c.id.startsWith('case_normal_history_')).length)===105,'All 105 ordinary historical staff cases remain reachable');
  const issue=await account('renewal-issue'),issueSeed=provider.seed(issue.user.uid,'plus');provider.data.subscriptions[issueSeed.subscriptionId].status='past_due';await admin.firestore().doc(`billingCustomers/${issue.user.uid}`).set({stripeCustomerId:issueSeed.customerId});await issue.page.evaluate(()=>openBillingOverview());await idle(issue.page);await matrix(issue.page,'renewal-payment-issue',()=>issue.page.evaluate(()=>openBillingPlans()),['paymentIssue','paymentMethod']);
  await matrix(buyer.page,'precontract-desktop',()=>buyer.page.evaluate(()=>billingPurchaseRecord(BILLING_UI.purchaseRecords[0].id)),['englishContract'],[1440]);await buyer.page.evaluate(()=>closeSheet('billing'));
  await annualRefundNormal(desk);
  await page.evaluate(()=>{setLang('zh');setTheme('light');});
  for(const view of ['overview','history','cases','plans']){
    await page.evaluate(view=>{openBillingOverview();billingScreen(view);},view);await idle(page);await page.locator('.header-brand-lockup').click();
    check(await page.evaluate(()=>S.tab==='home'&&!BILLING_VIEW&&firebase.auth().currentUser.uid)===customer.user.uid,'Web Logo leaves billing '+view+' for same-account Home');
  }
  await shot(page,'logo-billing-return-home');
  check(result.pageErrors.length===0,'No browser page errors');
  result.status='COMPLETE_NORMAL_CHECKS';result.subscriptionIdentity={initial:initial.subscriptionId,other:additional.subscriptionId};
}
main().catch(e=>{result.status='FAILED';result.error=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{result.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));if(provider)fs.writeFileSync(path.join(out,'local-provider-requests.json'),JSON.stringify(provider.data.requests,null,2));if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));if(provider)await provider.close();console.log('BILLING_NORMAL '+result.status+' assertions='+result.assertions.length+' captures='+result.captures.length+' '+out);});
