'use strict';

const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {chromium}=require('playwright');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const firestore=require('firebase/firestore');
const LtdSync=require('../../src/core/ltd-sync');
const {make}=require('../test-fixture');

const root=path.resolve(__dirname,'../..'),artifact=path.join(root,'.hosting-build','ltd-actual-app');
const evidence=path.resolve(process.env.TAXMATE_LTD_ACTUAL_APP_EVIDENCE||path.join(root,'.ltd-actual-app-evidence'));
const reviewMode=process.env.TAXMATE_LTD_ACTUAL_APP_REVIEW==='1';
const resultPath=path.join(evidence,'ltd-actual-app-browser-result.json'),runId=Date.now().toString(36),origin='http://127.0.0.1:4177';
const profileRoot=path.join(os.tmpdir(),`tm-ltd-${runId}`),contexts=new Set(),assertions=[],externalRequests=[],sentryRequests=[],consoleErrors=[],networkFailures=[];
let testEnv,server,assertionCount=0;
const clone=value=>JSON.parse(JSON.stringify(value));
function check(value,message){assert.ok(value,message);assertionCount++;assertions.push(message);}
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);assertionCount++;assertions.push(message);}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitFor(fn,message,timeout=60000){const start=Date.now();let last;while(Date.now()-start<timeout){try{last=await fn();if(last)return last;}catch(error){last=error.message;}await sleep(150);}throw new Error(`${message}; last=${String(last)}`);}
function chromePath(){for(const candidate of [process.env.TAXMATE_CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'])if(candidate&&fs.existsSync(candidate))return candidate;throw new Error('Installed Chrome not found');}

function prepareArtifact(){
  const build=spawnSync(process.execPath,['scripts/build-hosting.js','production','ltd-actual-app'],{cwd:root,stdio:'inherit'});if(build.status!==0)throw new Error('Actual-app Hosting artifact build failed');
  const firebaseFiles=['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js','firebase-storage-compat.js','firebase-app-check-compat.js'],vendor=path.join(artifact,'vendor','firebase');fs.mkdirSync(vendor,{recursive:true});
  for(const file of firebaseFiles)fs.copyFileSync(path.join(root,'node_modules','firebase',file),path.join(vendor,file));
  const htmlPath=path.join(artifact,'index.html');let html=fs.readFileSync(htmlPath,'utf8');for(const file of firebaseFiles)html=html.replace(new RegExp(`https://www\\.gstatic\\.com/firebasejs/[^"']+/${file}`,'g'),`vendor/firebase/${file}`);html=html.replace(/<script[^>]+https:\/\/cdnjs\.cloudflare\.com[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'').replace(/<noscript><link[^>]+https:\/\/fonts\.googleapis\.com[^>]*><\/noscript>\s*/gi,'');fs.writeFileSync(htmlPath,html);
  fs.writeFileSync(path.join(artifact,'firebase-environment.js'),`'use strict';\nwindow.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:Object.freeze({apiKey:'demo-api-key',authDomain:'demo-taxmate.firebaseapp.com',projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com',messagingSenderId:'100000000000',appId:'1:100000000000:web:ltd-actual-app'}),hosts:Object.freeze(['127.0.0.1','localhost']),appCheckKey:'demo-only',functionsOrigin:'http://127.0.0.1:5001'});\n(function(){const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(config,name){const app=init(config,name);firebase.auth(app).useEmulator('http://127.0.0.1:9099',{disableWarnings:true});firebase.firestore(app).useEmulator('127.0.0.1',8080);firebase.storage(app).useEmulator('127.0.0.1',9199);return app;};firebase.appCheck=function(){return{activate:function(){},getToken:async function(){return{token:'emulator-app-check'};}};};})();\n`);
  const rendered=fs.readFileSync(htmlPath,'utf8');if(!/src\/integration\/ltd\/TaxMateLtdProductionAdapter\.js/.test(rendered)||!/id="taxmate-ltd-ui-root"/.test(rendered))throw new Error('Actual app does not contain the production Ltd mount');
}
function startServer(){const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.ico':'image/x-icon','.xml':'application/xml','.txt':'text/plain; charset=utf-8'};server=http.createServer((req,res)=>{const pathname=new URL(req.url,origin).pathname,relative=decodeURIComponent(pathname==='/'?'/index.html':pathname).replace(/^\/+/,''),target=path.resolve(artifact,relative);if(!target.startsWith(path.resolve(artifact)+path.sep)||!fs.existsSync(target)){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(target).pipe(res);});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(4177,'127.0.0.1',resolve);});}
async function createUser(label){const email=`${label}-${runId}@taxmate.local`,password='Ltd-Actual-App-20260828!';const response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-api-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});if(!response.ok)throw new Error(await response.text());return{...(await response.json()),email,password};}
async function adminSet(pathName,value){await testEnv.withSecurityRulesDisabled(async context=>firestore.setDoc(firestore.doc(context.firestore(),...pathName.split('/')),value));}
async function adminGet(pathName){let value=null;await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDoc(firestore.doc(context.firestore(),...pathName.split('/')));value=snap.exists()?snap.data():null;});return value;}
async function collectionRows(pathName){let rows=[];await testEnv.withSecurityRulesDisabled(async context=>{const snap=await firestore.getDocs(firestore.collection(context.firestore(),...pathName.split('/')));rows=snap.docs.map(doc=>doc.data());});return rows;}
const entitlement=(tier,status='active')=>({subscriptionStatus:status,paidTier:tier,currentPeriodEnd:status==='active'?Date.now()+86400000:Date.now()-86400000,serverVerifiedAt:Date.now()});
async function seedTier(user,tier,status='active'){await adminSet(`users/${user.localId}/entitlements/current`,entitlement(tier,status));}
function freshLegacyState(){const state=clone(make('fresh').driver.state);for(const business of state.businesses){business.syncCode=null;business.updatedAt=business.updatedAt||Date.now();}for(const entry of state.entries){delete entry.receiptPath;delete entry.receiptUrl;}state.settings.lang='en';state.settings.theme='light';return state;}
async function installNetworkGuard(context){await context.route('**/*',async route=>{const url=route.request().url(),external=/^https?:\/\//i.test(url)&&!/^http:\/\/(?:127\.0\.0\.1|localhost)(?::\d+)?\//i.test(url);if(external&&/(?:sentry|ingest\.)/i.test(url)){sentryRequests.push(url);await route.abort('blockedbyclient');return;}if(external){externalRequests.push(url);await route.abort('blockedbyclient');return;}await route.continue();});}
async function launch(name,state=null,viewport={width:390,height:844}){const profile=path.join(profileRoot,name),context=await chromium.launchPersistentContext(profile,{headless:!reviewMode,executablePath:chromePath(),viewport,serviceWorkers:'allow'});contexts.add(context);context.on('close',()=>contexts.delete(context));await installNetworkGuard(context);if(state)await context.addInitScript(value=>{localStorage.setItem('taxmateuk_v1',JSON.stringify(value));localStorage.setItem('tmOnboardDone','1');localStorage.setItem('taxmateuk_analytics_consent','denied');},state);else await context.addInitScript(()=>localStorage.setItem('taxmateuk_analytics_consent','denied'));const page=context.pages()[0]||await context.newPage();page.on('pageerror',error=>consoleErrors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!/(?:ERR_FAILED|ERR_BLOCKED_BY_CLIENT|status of 403)/.test(message.text()))consoleErrors.push(message.text());});page.on('response',response=>{if(response.status()>=400)networkFailures.push({url:response.url(),status:response.status()});});await page.goto(origin+'/',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>typeof window.ensureFB==='function'&&window.TaxMateLtdProductionAdapter&&TaxMateLtdProductionAdapter.isReady(),null,{timeout:30000});return{context,page};}
async function signIn(page,user){await page.evaluate(async credentials=>{await ensureFB();await firebase.auth().signInWithEmailAndPassword(credentials.email,credentials.password);},{email:user.email,password:user.password});await page.waitForFunction(()=>firebase.auth().currentUser&&!firebase.auth().currentUser.isAnonymous,null,{timeout:30000});}
async function waitSynced(page,label){try{await waitFor(()=>page.evaluate(()=>{try{return eval("CLOUD.hydrationState==='converged'&&syncStatus().state==='synced'");}catch(_){return false;}}),label);check(true,label);}catch(error){const diagnostic=await page.evaluate(()=>{try{return eval("({hydration:CLOUD.hydrationState,partnership:CLOUD.partnershipHydrationState,reconciliation:CLOUD.reconciliationState,ack:CLOUD.ackState,inbound:CLOUD.inboundError,write:CLOUD.writeError,status:syncStatus(),outbox:loadSyncOutbox().items.map(item=>({kind:item.kind,collection:item.collection,recordId:item.recordId,status:item.status,lastError:item.lastError,nextAttemptAt:item.nextAttemptAt})),anchor:CLOUD.ltdAnchor,localProfiles:S.domain&&S.domain.companyProfiles&&S.domain.companyProfiles.length,remote:(CLOUD.ltdRemote||[]).length})");}catch(inner){return{diagnosticError:inner.message};}});throw new Error(`${error.message}; diagnostic=${JSON.stringify(diagnostic)}`);}}
async function invoke(page,name,input={}){return page.evaluate(async({name,input})=>{const result=await window.TaxMateLtdUIFacade[name](input);return{status:result.status,nextRoute:result.nextRoute,data:result.data,fieldErrors:result.fieldErrors,reviewReasons:result.reviewReasons};},{name,input});}
async function route(page){return page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().navigation.routes.at(-1).screenId);}
async function openAddLtd(page){await page.getByRole('button',{name:/Add a business/i}).last().click();await page.locator('#taxmate-ltd-ui-root:not([hidden])').waitFor();await page.getByRole('button',{name:/Limited company/i}).click();await waitFor(()=>route(page).then(value=>value==='ltd.onboarding.step1'||value==='ltd.one-company-limit'), 'Limited company route did not resolve');}
async function seedLtdCloud(uid,state){const companyIds=new Set(state.domain.entities.filter(item=>item.type==='limited_company'&&item.deletedAt==null).map(item=>item.id)),records=LtdSync.recordsForSync(state);for(const collection of LtdSync.COLLECTIONS)for(const record of records[collection]){const envelope=LtdSync.envelope(collection,record,LtdSync.companyIdForRecord(collection,record,companyIds));await adminSet(`users/${uid}/ltd/v1/${collection}/${envelope.documentId}`,envelope);}const companyId=state.domain.companyProfiles.find(item=>item.deletedAt==null).entityId;await adminSet(`users/${uid}/ltdControl/activeCompany`,{schemaVersion:1,status:'active_slot_claimed',activeCompanyId:companyId,releasePolicy:'founder_approval_required',claimedAt:Date.now(),updatedAt:Date.now()});}

async function completeRegisteredJourney(page){
  await page.evaluate(()=>{TaxMateLtdUIFacade.driver.companiesHouseProvider={isNetworkProvider:false,lookup:async number=>number==='11111111'?{status:'found',verificationStatus:'verified',reasonCodes:[],retryable:false,company:{number,name:'TOODALOOP LTD',incorporationDate:'2025-12-15',status:'active',type:'ltd',registryUrl:'https://find-and-update.company-information.service.gov.uk/company/11111111'}}:number==='22222222'?{status:'not_found',reasonCode:'company_not_found',retryable:false}:{status:'unavailable',reasonCode:'companies_house_temporarily_unavailable',retryable:true}};});
  equal((await invoke(page,'onLookupCompaniesHouse',{companyNumber:'22222222'})).data.status,'not_found','Companies House not-found fixture remains a manual continuation state');
  equal((await invoke(page,'onLookupCompaniesHouse',{companyNumber:'33333333'})).data.status,'unavailable','Companies House unavailable fixture remains retryable and manual');
  const found=await invoke(page,'onLookupCompaniesHouse',{companyNumber:'11111111'});equal(found.data.verificationStatus,'verified','Companies House found fixture returns verified official facts');
  const step1=await invoke(page,'onContinueStep',{step:1,values:{companyNumberStatus:'provided',companyNumber:'11111111',legalName:'TOODALOOP LTD',incorporationDate:'2025-12-15'}});equal(step1.status,'ok','registered company identity saves through the canonical facade');
  await page.evaluate(()=>TaxMateLtdProductionBridge.exitToBusinesses());equal(await route(page),'ltd.onboarding.step2','saved draft keeps the exact resume route');
  await page.getByRole('button',{name:/Finish setup/i}).click();await waitFor(()=>route(page).then(value=>value==='ltd.onboarding.step2'),'draft did not resume at Step 2');check(true,'Home draft row resumes at the exact saved step');
  const plan=await invoke(page,'onPlanCompanyPeriods',{tradingStatus:'trading',tradingStartDate:'2025-12-20'});equal(plan.status,'ok','actual app plans the first company periods from explicit facts');
  equal((await invoke(page,'onContinueStep',{step:2,values:{tradingStatus:'trading',tradingStartDate:'2025-12-20',corporationTaxStatus:'registered'}})).status,'ok','Step 2 persists trading and Corporation Tax facts without defaults');
  equal((await invoke(page,'onContinueStep',{step:3,values:{founderName:'Founder',founderShares:51,otherShareholderName:'Other shareholder',otherShares:49,directorAnswer:'yes'}})).status,'ok','Step 3 persists director and 51/49 ownership facts');
  const risks={groupStructure:false,associatedCompanies:false,propertyOrInvestment:false,inventoryOrStock:false,fullVat:false};equal((await invoke(page,'onContinueStep',{step:4,values:{ordinaryServiceDigital:true,riskAnswers:risks}})).status,'ok','Step 4 stores every explicit factual answer');
  const finished=await invoke(page,'onContinueStep',{step:5,values:{confirmed:true}});check(['ok','review_required'].includes(finished.status),'Step 5 reaches bookkeeping with canonical eligibility');equal(await route(page),'ltd.workspace.overview','Finish setup opens Company Workspace Overview');
}

async function exerciseWorkspace(page){
  const profile=await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().company.profile),companyId=profile.entityId,legacyId=await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().businessList.find(row=>row.businessType!=='limited_company').id);
  const eventsBefore=await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().workspace.events.length);
  equal((await invoke(page,'onAddIncome',{amountMinor:200000,date:'2026-08-20',description:'Actual app income',invoicePartyId:'customer:actual-app',companyIncomeCategory:'trading',evidenceRefs:['local:invoice:actual-app']})).status,'ok','actual app posts company income');
  check(['ok','review_required'].includes((await invoke(page,'onAddExpense',{amountMinor:25000,date:'2026-08-20',description:'Actual app company expense',companyExpenseCategory:'day_to_day',taxFacts:{capitalUseOverOneYear:'no',specialCost:'no',invoiceToCompany:'yes',companyUseScope:'only_company'},evidenceRefs:['local:receipt:company']})).status),'actual app records a company-paid expense');
  check(['ok','review_required'].includes((await invoke(page,'onAddPersonallyPaidExpense',{amountMinor:10000,date:'2026-08-20',description:'Founder paid expense',companyExpenseCategory:'day_to_day',taxFacts:{capitalUseOverOneYear:'no',specialCost:'no',invoiceToCompany:'yes',companyUseScope:'only_company'},evidenceRefs:['local:receipt:personal']})).status),'actual app records a personally-paid company expense');
  const shared=await invoke(page,'onAddSharedExpense',{paidPersonally:true,amountMinor:10001,date:'2026-08-20',description:'Shared exact penny expense',companyExpenseCategory:'day_to_day',taxFacts:{capitalUseOverOneYear:'no',specialCost:'no',invoiceToCompany:'yes'},sharedAllocations:[{id:companyId,amountMinor:6001},{id:legacyId,amountMinor:3000},{id:'private-use',amountMinor:1000}]});equal(shared.data.event.sourceTransaction.sharedExpense.allocations.reduce((sum,item)=>sum+item.amountMinor,0),10001,'shared expense allocations reconcile to the exact penny');
  check(['ok','review_required'].includes((await invoke(page,'onAddDirectorLoanFunding',{amountMinor:50000,date:'2026-08-20',description:'Founder loan funding'})).status),'actual app records director/founder loan funding');
  check(['ok','review_required'].includes((await invoke(page,'onRecordDirectorLoanRepayment',{amountMinor:10000,date:'2026-08-21',description:'Founder loan repayment'})).status),'actual app records director/founder loan repayment');
  check(['ok','review_required'].includes((await invoke(page,'onRecordShareFunding',{amountMinor:5100,date:'2026-08-20',description:'Issued share funding',shareCapitalEvidenceConfirmed:true,evidenceRefs:['local:share-resolution']})).status),'actual app records share funding with evidence');
  const incomeEvent=await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().workspace.events.find(event=>event.sourceTransaction&&event.sourceTransaction.purpose==='Actual app income').id);equal((await invoke(page,'onOpenRecord',{eventId:incomeEvent})).data.recordView.eventId,incomeEvent,'record-specific detail opens the exact canonical event');
  const corrected=await invoke(page,'onCorrectRecord',{eventId:incomeEvent,reasonCode:'actual_app_correction',replacement:{description:'Actual app corrected income'}});equal(corrected.status,'ok','record correction reverses and replaces through the canonical ledger');
  const ct=await invoke(page,'onRunCtEstimate',{reviewTopics:{records:'yes',periods:'yes',losses:'yes'},ctFacts:{ukResidentConfirmed:true,ringFenceProfits:false,closeInvestmentHoldingCompany:false,associatedCompaniesConfirmedNone:true,qualifyingDistributionsMinor:0,accountsCompleteConfirmed:true,sameTradeContinues:true},lossUseMinorByPeriod:[0],asOfDate:'2026-08-24'});check(['ok','review_required'].includes(ct.status)&&ct.data.periodRecords.length>=1,'Corporation Tax estimate uses canonical period records');
  const beforeScenario=await page.evaluate(()=>JSON.stringify(TaxMateLtdUIFacade.driver.state.domain.economicEvents));const scenario=await invoke(page,'onRunScenario',{ordinaryFacts:{amountMinor:100000,when:'2026-08-24'},asOfDate:'2026-08-24'});check(['ok','review_required'].includes(scenario.status),'salary/dividend/retained-profit scenario returns a semantic result');equal(await page.evaluate(()=>JSON.stringify(TaxMateLtdUIFacade.driver.state.domain.economicEvents)),beforeScenario,'scenario comparison never posts to actual books');
  const salary=await page.evaluate(async()=>{const gross=100000,r=TaxMateCompanyRemunerationRules,employee=r.calculateEmployeeNi(gross),employer=r.calculateEmployerNi(gross),paye=r.calculatePayeEstimate(gross),profile=TaxMateLtdUIFacade.getSnapshot().company.profile;return TaxMateLtdUIFacade.onRecordSalary({salary:{id:'salary-record:actual-app',payDate:'2026-08-20',grossSalaryMinor:gross,payeWithheldMinor:paye.payeEstimateMinor,employeeNiMinor:employee.employeeNiMinor,employerNiMinor:employer.employerNiMinor,companyPaymentAccountId:`account-company-bank:${profile.entityId}`,personalPaymentAccountId:`account-personal:${profile.entityId}`,evidenceRefs:['local:payroll','local:bank'],directorServicesConfirmed:true,ordinaryRemunerationConfirmed:true,noBenefitsSalarySacrificeOrTerminationPayment:true,payrollResultConfirmed:true,payeRegistrationConfirmed:true,paidWithinNineMonthsConfirmed:true,payeReportingStatus:'reported_rti'}});});equal(salary.status,'ok','actual salary writes linked company and personal records exactly once');
  const declared=await invoke(page,'onDeclareDividend',{dividend:{id:'dividend-record:actual-app',declarationDate:'2026-08-20',paymentDate:'2026-08-21',totalDividendMinor:10000,confirmedDistributableProfitMinor:10000,independentAccountsConfirmation:true,corporationTaxEstimateOnly:false,distributableProfitEvidenceRefs:['local:interim-accounts'],boardApprovalEvidenceRef:'local:board',minutesArtifactRef:'local:minutes'}});equal(declared.status,'ok','dividend declaration is a separate supported action');equal((await invoke(page,'onRecordDividendPayment',{declarationId:'dividend-record:actual-app',voucherArtifactRefs:['local:voucher:founder','local:voucher:other']})).status,'ok','dividend payment links once into personal income');
  const ownership=await page.evaluate(async()=>{const profile=TaxMateLtdUIFacade.getSnapshot().company.profile,holder=profile.shareholders.find(item=>item.isAccountHolder),other=profile.shareholders.find(item=>!item.isAccountHolder);return TaxMateLtdUIFacade.onChangeOwnership({effectiveDate:'2026-09-01',shareholders:[{...holder,shares:60},{...other,shares:40}],reason:'Actual app ownership change',evidenceRefs:['local:ownership-resolution']});});equal(ownership.status,'ok','effective-dated ownership change is applied through profile history');
  const correction=await invoke(page,'onEditCompany',{field:'legalName',value:'TOODALOOP SERVICES LTD',reason:'Registered name correction',evidenceRefs:['local:company-correction']});check(['ok','review_required'].includes(correction.status),'company correction returns a fail-closed semantic outcome');
  const pack=await invoke(page,'onDownloadWorkingPack',{});check(['ok','review_required'].includes(pack.status)&&pack.data&&pack.data.payload,'actual app builds the company working pack');
  const after=await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().workspace.events);check(after.length>eventsBefore,'Money actions create canonical event records');check(after.every(event=>(event.journals||[]).flatMap(group=>group.postings||[]).reduce((sum,row)=>sum+row.debitMinor-row.creditMinor,0)===0),'every posted event remains balanced in integer pence');
}

async function backupAndPresentation(page){
  const backup=await page.evaluate(async()=>{const json=TaxMateState.createExport(S,{appVersion:TaxMateCore.VERSIONS.APP_VERSION,buildId:TaxMateCore.VERSIONS.BUILD_ID,deviceId:DEVICE_ID}),restored=TaxMateState.importBackup(json,Date.now(),'isolated-data-restore'),full=await buildPortableArchive(S),inspected=await TaxMatePortableBackup.inspectArchive(full.archive);return{jsonVersion:json.exportSchemaVersion,dataHash:JSON.stringify(TaxMateLtdSync.recordsForSync(restored)),sourceHash:JSON.stringify(TaxMateLtdSync.recordsForSync(S)),manifestEntries:full.manifest.length,manifestValidated:inspected.metadata.receiptCount===inspected.receipts.length,fullHash:JSON.stringify(TaxMateLtdSync.recordsForSync(inspected.state)),receiptCount:inspected.receipts.length};});equal(backup.dataHash,backup.sourceHash,'Data-only backup restores identical Ltd relationships in isolation');equal(backup.fullHash,backup.sourceHash,'Full Backup restores identical Ltd relationships in isolation');check(backup.manifestValidated,'Full Backup archive manifest validates exactly');
  for(const locale of ['en','zh-HK','pl','ro','es','ur']){await page.evaluate(locale=>{S.settings.lang=locale==='zh-HK'?'zh':locale;persistRemoteState();},locale);await windowOpen(page);const semantics=await page.locator('#taxmate-ltd-ui-root .tm-app').evaluate(node=>({lang:node.lang,dir:node.dir}));equal(semantics.lang,locale,`${locale} renders in the actual app`);equal(semantics.dir,locale==='ur'?'rtl':'ltr',`${locale} direction is correct in the actual app`);}
  await page.evaluate(()=>{S.settings.lang='en';S.settings.theme='dark';persistRemoteState();});await windowOpen(page);check((await page.locator('#taxmate-ltd-ui-root').evaluate(node=>getComputedStyle(node).display))!=='none','dark mode keeps the actual Ltd workspace visible');
  const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth);check(mobileOverflow,'390×844 actual app has no unexpected horizontal overflow');await page.screenshot({path:path.join(evidence,'actual-app-mobile-dark-en.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await windowOpen(page);check(await page.getByRole('tab',{name:'Overview'}).count()===1,'desktop actual app renders the Company Workspace');check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),'desktop actual app has no unexpected horizontal overflow');await page.screenshot({path:path.join(evidence,'actual-app-desktop-dark-en.png'),fullPage:true});
}
async function windowOpen(page){await page.evaluate(()=>TaxMateLtdProductionAdapter.openExistingCompany());await page.waitForFunction(()=>TaxMateLtdUIFacade.getSnapshot().navigation.routes.at(-1).screenId.startsWith('ltd.'));}

async function main(){
  fs.mkdirSync(evidence,{recursive:true});prepareArtifact();await startServer();testEnv=await initializeTestEnvironment({projectId:'demo-taxmate',firestore:{rules:fs.readFileSync(path.join(root,'firestore.rules'),'utf8')},storage:{rules:fs.readFileSync(path.join(root,'storage.rules'),'utf8')}});
  const legacy=freshLegacyState(),legacySignature=crypto.createHash('sha256').update(JSON.stringify({businesses:legacy.businesses,entries:legacy.entries})).digest('hex'),pro=await createUser('actual-pro');await seedTier(pro,'pro');const app=await launch('pro',legacy);await signIn(app.page,pro);await waitSynced(app.page,'Pro actual-app user reaches Cloud convergence');equal(await app.page.evaluate(()=>S.businesses.length),4,'actual TaxMate Home retains all four legacy businesses');equal(await app.page.evaluate(()=>S.entries.length),79,'actual TaxMate Home retains all 79 legacy records');equal(await app.page.evaluate(()=>TaxMateLtdProductionAdapter.getSnapshot().businessList.length),4,'production facade reads the actual Home businesses');await app.page.screenshot({path:path.join(evidence,'actual-app-home-before-ltd.png'),fullPage:true});
  await openAddLtd(app.page);equal(await route(app.page),'ltd.onboarding.step1','Add Business → Limited Company mounts the approved Fable UI in the actual app');const anchor=await adminGet(`users/${pro.localId}/ltdControl/activeCompany`);check(anchor&&anchor.status==='active_slot_claimed','actual app claims the trusted one-Ltd anchor before local profile creation');await completeRegisteredJourney(app.page);await exerciseWorkspace(app.page);await backupAndPresentation(app.page);
  equal(crypto.createHash('sha256').update(JSON.stringify(await app.page.evaluate(()=>({businesses:S.businesses,entries:S.entries.filter(item=>!item.origin||item.origin!=='company_v1_5')})))).digest('hex'),legacySignature,'legacy businesses and entries remain byte-semantic equivalent after Ltd use');await waitSynced(app.page,'all actual-app Ltd actions receive Cloud ACK before reload');
  await app.page.reload({waitUntil:'domcontentloaded'});await app.page.waitForFunction(()=>window.TaxMateLtdProductionAdapter&&TaxMateLtdProductionAdapter.isReady());await waitSynced(app.page,'reload restores canonical Ltd state and convergence');await windowOpen(app.page);check((await app.page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().workspace.events.length))>=7,'reload preserves the canonical company ledger');
  await app.page.evaluate(()=>navigator.serviceWorker.ready);await app.context.setOffline(true);const offline=await invoke(app.page,'onAddIncome',{amountMinor:1234,date:'2026-08-22',description:'Offline actual-app income',invoicePartyId:'customer:offline',companyIncomeCategory:'trading'});equal(offline.status,'ok','offline actual app accepts a Pro company record locally');equal(await app.page.evaluate(()=>eval('syncStatus().state')),'offline','offline Ltd write is never reported as Synced');await app.context.setOffline(false);await app.page.evaluate(()=>window.dispatchEvent(new Event('online')));await waitSynced(app.page,'offline Ltd outbox retries and ACKs before Synced');
  const clean=await launch('clean');await signIn(clean.page,pro);await waitSynced(clean.page,'clean device hydrates the existing Ltd account');check(await clean.page.evaluate(()=>S.domain.companyProfiles.length===1&&S.domain.economicEvents.some(event=>event.sourceTransaction&&event.sourceTransaction.purpose==='Offline actual-app income')),'clean device reconstructs the Ltd profile and offline-created record');await clean.context.close();

  await seedTier(pro,'free','inactive');const expired=await launch('expired');await signIn(expired.page,pro);await waitSynced(expired.page,'expired Pro clean device still completes inbound hydration');await windowOpen(expired.page);const retained=await expired.page.evaluate(async()=>{const before=TaxMateLtdUIFacade.getSnapshot().workspace.events.length,write=await TaxMateLtdUIFacade.onAddIncome({amountMinor:100,date:'2026-08-23',description:'Must not write',invoicePartyId:'customer:blocked',companyIncomeCategory:'trading'}),data=TaxMateState.createExport(S,{appVersion:TaxMateCore.VERSIONS.APP_VERSION,buildId:TaxMateCore.VERSIONS.BUILD_ID}),full=await buildPortableArchive(S);return{before,after:TaxMateLtdUIFacade.getSnapshot().workspace.events.length,writeStatus:write.status,writeReason:write.error&&write.error.reasonCode,dataHasLtd:data.data.domain.companyProfiles.length,fullBytes:full.archive.size||full.archive.byteLength||full.archive.length||0,restore:TaxMateCompanyAccess.decide({action:'restore',snapshot:ENTITLEMENT.snapshot,now:Date.now(),hasExistingLtdData:true})};});equal(retained.before,retained.after,'expired Pro cannot mutate existing Ltd records');equal(retained.writeReason,'pro_required','expired Pro active action returns the Pro gate');check(retained.dataHasLtd===1&&retained.fullBytes>0,`expired Pro can export Data-only and Full Backup (${JSON.stringify(retained)})`);equal(retained.restore.allowed,false,'expired Pro cannot restore/import');await expired.context.close();

  for(const tier of ['free','plus']){const user=await createUser(`actual-${tier}`);await seedTier(user,tier,tier==='free'?'inactive':'active');const blocked=await launch(tier,freshLegacyState());await signIn(blocked.page,user);await waitSynced(blocked.page,`${tier} actual-app account converges`);await blocked.page.getByRole('button',{name:/Add a business/i}).last().click();equal(await route(blocked.page),'business.category-choice',`${tier} sees the real Add Business chooser`);const result=await invoke(blocked.page,'onAddBusinessCategoryChosen',{category:'limited_company'});equal(result.status,'failure',`${tier} receives a semantic Pro-only failure`);equal(await route(blocked.page),'business.category-choice',`${tier} cannot enter Limited Company onboarding`);equal((await adminGet(`users/${user.localId}/ltdControl/activeCompany`)),null,`${tier} creates no trusted Ltd anchor`);await blocked.context.close();}

  const draftUser=await createUser('actual-unregistered');await seedTier(draftUser,'pro');const draft=await launch('unregistered',freshLegacyState());await signIn(draft.page,draftUser);await waitSynced(draft.page,'unregistered-draft account converges');await openAddLtd(draft.page);const unregistered=await invoke(draft.page,'onContinueStep',{step:1,values:{companyNumberStatus:'not_available',legalName:'Future TaxMate Company'}});equal(unregistered.status,'ok','not-yet-registered path saves a real draft');const draftFacts=await draft.page.evaluate(()=>{const profile=TaxMateLtdUIFacade.getSnapshot().company.profile;return{incorporationDate:profile.incorporationDate,companyNumber:profile.companyNumber,tradingStatus:profile.tradingStatus,verification:profile.registryVerification.status};});equal(draftFacts,{incorporationDate:undefined,companyNumber:undefined,tradingStatus:undefined,verification:'not_registered'},'unregistered draft invents no incorporation, company-number or trading facts');await draft.page.evaluate(()=>TaxMateLtdProductionBridge.exitToBusinesses());await windowOpen(draft.page);equal(await route(draft.page),'ltd.onboarding.registration-details','unregistered draft is durable and resumes at the exact registration checkpoint');await draft.context.close();

  const raceUser=await createUser('actual-race');await seedTier(raceUser,'pro');const raceA=await launch('race-a',freshLegacyState()),raceB=await launch('race-b',freshLegacyState());await Promise.all([signIn(raceA.page,raceUser),signIn(raceB.page,raceUser)]);await Promise.all([waitSynced(raceA.page,'race client A converges'),waitSynced(raceB.page,'race client B converges')]);await Promise.all([raceA.page.getByRole('button',{name:/Add a business/i}).last().click(),raceB.page.getByRole('button',{name:/Add a business/i}).last().click()]);const race=await Promise.all([invoke(raceA.page,'onAddBusinessCategoryChosen',{category:'limited_company'}),invoke(raceB.page,'onAddBusinessCategoryChosen',{category:'limited_company'})]);equal(race.filter(item=>item.status==='ok').length,1,'two clean actual-app clients produce exactly one successful Ltd claim');equal(race.filter(item=>item.status==='failure').length,1,'the losing actual-app client fails safely');const profiles=await Promise.all([raceA.page.evaluate(()=>S.domain.companyProfiles.length),raceB.page.evaluate(()=>S.domain.companyProfiles.length)]);equal(profiles.sort(),[0,1],'the losing client creates no partial orphan company profile');const raceAnchor=await adminGet(`users/${raceUser.localId}/ltdControl/activeCompany`);check(raceAnchor&&raceAnchor.activeCompanyId,'race leaves exactly one trusted active-company anchor');await raceA.context.close();await raceB.context.close();

  const identity=await app.page.evaluate(()=>TaxMateCore.VERSIONS);equal({APP_VERSION:identity.APP_VERSION,BUILD_ID:identity.BUILD_ID,PWA_CACHE_VERSION:identity.PWA_CACHE_VERSION},{APP_VERSION:'2.1.0',BUILD_ID:'2026-08-28.ltd-v1-5-actual-app.1',PWA_CACHE_VERSION:'taxmate-v2-ltd-v1-5-actual-app-1'},'actual app reports one consistent version/build/cache identity');equal(sentryRequests.length,0,'actual-app localhost/emulator journey emits zero production Sentry requests');equal(externalRequests.length,0,'actual-app acceptance emits no production or third-party request');const unexpectedConsole=consoleErrors.filter(message=>!/Failed to load resource/.test(message));equal(unexpectedConsole.length,0,'actual-app acceptance has zero fatal page/console errors');
  const result={status:'PASS',generatedAt:new Date().toISOString(),assertionCount,assertions,identity,journeys:{actualAppEntry:'index.html',emulators:['auth','firestore','storage','functions'],mobile:'390x844',desktop:'1440x1000',locales:['en','zh-HK','pl','ro','es','ur'],rtl:'ur',themes:['light','dark']},externalRequests,sentryRequests,networkFailures,consoleErrors,sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'src','app','app.js'))).digest('hex')};fs.writeFileSync(resultPath,JSON.stringify(result,null,2)+'\n');process.stdout.write(`LTD_ACTUAL_APP_BROWSER_PASS assertions=${assertionCount}\n`);if(reviewMode){process.stdout.write(`FOUNDER_ACTUAL_APP_REVIEW_READY ${origin}/ — use the opened Chrome window; press Ctrl+C here when finished.\n`);await new Promise(resolve=>process.once('SIGINT',resolve));}
}

main().catch(error=>{fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(resultPath,JSON.stringify({status:'FAIL',generatedAt:new Date().toISOString(),assertionCount,assertions,externalRequests,sentryRequests,networkFailures,consoleErrors,error:error.stack||String(error)},null,2)+'\n');console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{for(const context of [...contexts])try{await context.close();}catch(_){}if(testEnv)try{await testEnv.cleanup();}catch(_){}if(server)await new Promise(resolve=>server.close(resolve));try{fs.rmSync(profileRoot,{recursive:true,force:true});}catch(_){};});
