'use strict';
// Isolated Chrome profile, synthetic account and RPC fixture, real production
// adapter / driver / facade / renderer. External requests are blocked.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process'),{chromium}=require('playwright'),{make,PRO_ENTITLEMENT}=require('../test-fixture');
const {DEFAULT_NOW}=require('../../src/integration/ltd/CanonicalCompanyDriver');
const root=path.resolve(__dirname,'../..'),artifact=path.join(root,'.hosting-build/ltd-setup-browser'),evidence=path.join(root,'.hosting-build/ltd-status-evidence'),origin='http://127.0.0.1:4199';let server,browser,page;
async function run(){
 fs.mkdirSync(evidence,{recursive:true});assert.equal(spawnSync(process.execPath,['scripts/build-hosting.js','production','ltd-setup-browser'],{cwd:root,stdio:'inherit'}).status,0);
 server=http.createServer((req,res)=>{const url=new URL(req.url,origin),file=path.resolve(artifact,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(artifact+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'}[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});await new Promise(resolve=>server.listen(4199,'127.0.0.1',resolve));
 browser=await chromium.launch({headless:true,executablePath:['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(fs.existsSync)});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await context.addInitScript(()=>{localStorage.setItem('taxmateuk_account_v1:local:onboarding-done','1');localStorage.setItem('taxmateuk_analytics_consent','denied');});await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith(origin))return route.continue();const file=/\/firebasejs\/[^/]+\/(firebase-[a-z-]+-compat\.js)$/.exec(url);return file?route.fulfill({path:path.join(root,'node_modules/firebase',file[1]),contentType:'text/javascript'}):route.abort();});page=await context.newPage();const errors=[],results=[];page.on('pageerror',error=>errors.push(error.message));
 async function mount({reset=true,legacy=false,locale='en'}={}){
  await page.goto(origin);await page.waitForFunction(()=>typeof TaxMateLtdProductionAdapter!=='undefined');
  await page.evaluate(async({state,entitlement,now,reset,legacy,locale})=>{
   const clone=x=>JSON.parse(JSON.stringify(x)),base=TaxMateLtdProductionBridge,key=base.ltdDraftKey();TaxMateLtdProductionAdapter.dispose();if(reset){localStorage.removeItem(key);localStorage.removeItem(key+':setup');localStorage.setItem('setup-fixture-state',JSON.stringify(state));localStorage.setItem('setup-fixture-server',JSON.stringify({anchor:null,outcomes:{}}));}
   let canonical=JSON.parse(localStorage.getItem('setup-fixture-state'));const remote=()=>JSON.parse(localStorage.getItem('setup-fixture-server')),saveRemote=x=>localStorage.setItem('setup-fixture-server',JSON.stringify(x));S=clone(canonical);S.settings.language=locale;
   window.setupFixture={state:()=>clone(canonical),dropDiscardResponse:false,legacy};
   window.TaxMateLtdProductionBridge={...base,accountReady:()=>true,hasExistingCompany:()=>canonical.domain.companyProfiles.some(p=>p.deletedAt==null),loadState:()=>clone(canonical),replaceState:next=>{canonical=clone(next);S=clone(next);localStorage.setItem('setup-fixture-state',JSON.stringify(next));},entitlementSnapshot:()=>({...entitlement,currentPeriodEnd:Date.now()+86400000,serverVerifiedAt:Date.now()}),activeCompanyId:()=>remote().anchor?.companyId||null,locale:()=>locale,personalTaxJurisdiction:()=> 'EWNI',callTrusted:async(name,data)=>{
    const server=remote();if(name==='claimActiveLtdCompany'){if(server.outcomes[data.companyId])throw Error('retired');server.anchor={companyId:data.companyId,stage:'pending',legacy};saveRemote(server);return{status:'claimed',activeCompanyId:data.companyId,setupProtocol:legacy?null:'ltd-setup.1',setupState:legacy?null:'setup_pending'};}
    if(name!=='manageLtdSetup')throw Error('Unexpected RPC in synthetic test');const prior=server.outcomes[data.companyId];if(prior){if(data.action==='inspect')return{status:prior.status,companyId:data.companyId,canDiscard:false};if(data.action==='discard'&&data.operationId===prior.operationId)return prior;throw Error('already completed');}
    if(server.anchor?.legacy)return{status:'legacy',companyId:data.companyId,canDiscard:false,reason:'setup_legacy_slot'};
    if(data.action==='inspect')return{status:'pending',companyId:data.companyId,canDiscard:true,versionToken:'fixture-v1'};
    if(data.action==='complete'){server.anchor.stage='completed';server.outcomes[data.companyId]={status:'completed',companyId:data.companyId};saveRemote(server);return server.outcomes[data.companyId];}
    const profile=canonical.domain.companyProfiles.find(p=>p.entityId===data.companyId),entity=canonical.domain.entities.find(e=>e.id===data.companyId),stamp=Date.now()+1000,records=[['companyProfiles',profile],['entities',entity]].filter(([,record])=>record).map(([collection,record])=>TaxMateLtdSync.envelope(collection,{...record,deletedAt:stamp,updatedAt:stamp,revision:(record.revision||0)+1},data.companyId));server.anchor=null;const result={status:'discarded',companyId:data.companyId,operationId:data.operationId,records};server.outcomes[data.companyId]=result;saveRemote(server);if(setupFixture.dropDiscardResponse){setupFixture.dropDiscardResponse=false;throw Object.assign(Error('Lost response'),{code:'unavailable'});}return result;
   }};await TaxMateLtdProductionAdapter.initialise();TaxMateLtdProductionBridge.exitToBusinesses();
  },{state:make('fresh').driver.state,entitlement:PRO_ENTITLEMENT,now:DEFAULT_NOW,reset,legacy,locale});
 }
 const ui=()=>page.locator('#taxmate-ltd-ui-root'),route=()=>page.evaluate(()=>TaxMateLtdUIFacade.workflow.currentRoute().screenId),id=()=>page.evaluate(()=>TaxMateLtdUIFacade.driver.activeProfile()?.entityId);
 async function newDraft(){await page.evaluate(()=>TaxMateLtdProductionAdapter.openNewLimitedCompany({companyNumberStatus:'provided'}));await ui().locator('[data-field="legalName"]').waitFor();}
 async function capture(name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(evidence,'setup-'+name+'.png'),fullPage:true});results.push({case:name,status:'PASS'});}
 async function cancel(){await ui().getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('dialog').waitFor();}
 await mount();await newDraft();const first=await id();await ui().locator('[data-field="legalName"]').fill('Saved unfinished company');await cancel();assert.equal(await page.getByRole('button',{name:'Remove this unfinished draft',exact:true}).isEnabled(),true);await capture('exit-choice');await page.getByRole('button',{name:'Keep draft and exit',exact:true}).click();assert.equal(await route(),'home');assert.ok(await page.locator('[data-local-ltd-draft]').count());await capture('local-resume-entry');
 await mount({reset:false});await page.locator('[data-local-ltd-draft] button').click();assert.equal(await id(),first);assert.equal(await ui().locator('[data-field="legalName"]').inputValue(),'Saved unfinished company');await capture('reopened-same-answers');await cancel();await page.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await route(),'ltd.onboarding.step1');assert.equal(await page.getByRole('dialog').count(),0);await cancel();await page.getByRole('button',{name:'Remove this unfinished draft',exact:true}).click();assert.equal(await route(),'home');assert.equal(await page.locator('[data-local-ltd-draft]').count(),0);await newDraft();assert.notEqual(await id(),first);assert.equal(await ui().locator('[data-field="legalName"]').inputValue(),'');await capture('fresh-identity-after-local-remove');
 // Real Step 1 input submission, followed by a kept date edit in Step 2.
 await ui().locator('[data-field="companyNumber"]').fill('12345678');await ui().locator('[data-field="legalName"]').fill('Synthetic Setup Ltd');await ui().locator('[data-field="incorporationDate"]').fill('06/04/2026');await ui().getByRole('button',{name:'Continue',exact:true}).click();await page.waitForFunction(()=>TaxMateLtdUIFacade.workflow.currentRoute().screenId==='ltd.onboarding.step2');const claimed=await id();await ui().getByRole('button',{name:'Yes',exact:true}).first().click();await ui().locator('[data-field="tradingStartDate"]').fill('06/05/2026');await cancel();await page.getByRole('button',{name:'Keep draft and exit',exact:true}).click();await mount({reset:false});await page.evaluate(()=>TaxMateLtdProductionAdapter.openExistingCompany());assert.equal(await route(),'ltd.onboarding.step2');assert.equal(await id(),claimed);assert.equal(await ui().locator('[data-field="tradingStartDate"]').inputValue(),'06/05/2026');await capture('claimed-date-resumed');
 await ui().getByRole('button',{name:/Back/,exact:false}).first().click();assert.equal(await route(),'ltd.onboarding.step1');assert.equal(await page.getByRole('dialog').count(),0);await capture('back-between-steps');
 await cancel();await page.evaluate(()=>setupFixture.dropDiscardResponse=true);await page.getByRole('button',{name:'Remove this unfinished draft',exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/result is not confirmed/);assert.equal(await page.getByRole('button',{name:'Keep draft and exit',exact:true}).isEnabled(),false);await capture('uncertain-response');await page.getByRole('button',{name:'Keep editing',exact:true}).click();await ui().getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForFunction(()=>TaxMateLtdUIFacade.workflow.currentRoute().screenId==='home');assert.equal(await page.evaluate(()=>TaxMateLtdUIFacade.driver.activeProfile()),null);await newDraft();assert.notEqual(await id(),claimed);await capture('new-company-after-discard-retry');
 // Complete one synthetic modern setup, preserving completed removal policy.
 for(const [step,values]of [[1,{companyNumberStatus:'provided',companyNumber:'12345678',legalName:'Completed Synthetic Ltd',incorporationDate:'2026-04-06'}],[2,{tradingStatus:'trading',tradingStartDate:'2026-05-06',corporationTaxStatus:'registered'}],[3,{founderName:'Synthetic Founder',founderShares:100,directorAnswer:'yes'}],[4,{ordinaryServiceDigital:true,riskAnswers:{}}]]){const result=await page.evaluate(async({step,values})=>{if(step===4)values.riskAnswers=Object.fromEntries(TaxMateCompanyProfile.SETUP_RISK_FIELDS.map(field=>[field,false]));return TaxMateLtdUIFacade.onContinueStep({step,values});},{step,values});assert.ok(['ok','review_required'].includes(result.status),JSON.stringify(result.fieldErrors));assert.equal(await ui().getByText('Details',{exact:true}).count(),0);}
 await capture('step-five-no-remove-footer');const complete=await page.evaluate(()=>TaxMateLtdUIFacade.onContinueStep({step:5,values:{confirmed:true}}));assert.ok(['ok','review_required'].includes(complete.status),JSON.stringify(complete.fieldErrors));assert.equal(await route(),'ltd.workspace.overview');await page.evaluate(()=>TaxMateLtdUIFacade.onSetWorkspaceArea({area:'records'}));assert.ok(await ui().getByRole('button',{name:/Remove company/i}).count());await capture('completed-general-remove-preserved');
 await mount({legacy:true});await newDraft();await page.evaluate(()=>TaxMateLtdUIFacade.onContinueStep({step:1,values:{companyNumberStatus:'provided',companyNumber:'12345678',legalName:'Legacy Synthetic Ltd',incorporationDate:'2026-04-06'}}));await cancel();assert.match(await page.getByRole('dialog').innerText(),/older company slot/);assert.equal(await page.getByRole('button',{name:'Remove this unfinished draft',exact:true}).isEnabled(),false);assert.equal(await page.getByRole('button',{name:'Keep draft and exit',exact:true}).isEnabled(),true);await capture('legacy-limit-clear');
 await mount({locale:'zh-HK'});await newDraft();await ui().getByRole('button',{name:'取消',exact:true}).click();await capture('zh-exit-choice');assert.match(await page.getByRole('dialog').innerText(),/保留草稿並離開/);
 await mount({locale:'ur'});await newDraft();await page.evaluate(()=>TaxMateLtdUIFacade.onDismissRequested({reason:'cancel'}));await capture('ur-exit-choice');assert.equal(await ui().locator('[dir="rtl"]').count()>0,true);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(evidence,'setup-ui-results.json'),JSON.stringify({status:'PASS',scope:'LOCAL_SYNTHETIC_MOBILE_UI',results,errors,realDevice:'NOT_RUN',productionRpc:'NOT_RUN'},null,2));console.log(JSON.stringify({status:'PASS',scenarios:results.length,errors}));
}
run().catch(async error=>{console.error(error);if(page){await page.screenshot({path:path.join(evidence,'setup-failure.png'),fullPage:true}).catch(()=>{});console.log((await page.locator('#taxmate-ltd-ui-root').innerText().catch(()=>'' )).slice(0,2000));}process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));});
