'use strict';

const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {chromium}=require('playwright');
const {all}=require('../../ui-preview-harness/partnership-personal-share-fixtures');

const root=path.resolve(__dirname,'../..');
const artifact=path.join(root,'.hosting-build','partnership-personal-share-review');
const evidence=path.resolve(process.env.TAXMATE_PARTNERSHIP_SHARE_EVIDENCE||path.join(root,'.hosting-build','partnership-personal-share-evidence'));
const resultPath=path.join(evidence,'partnership-personal-share-browser-result.json');
const reviewMode=process.env.TAXMATE_PARTNERSHIP_SHARE_REVIEW==='1';
const origin='http://127.0.0.1:4188';
const fixtures=all(),assertions=[],externalRequests=[],sentryRequests=[],consoleErrors=[],screenshots=[];
let assertionCount=0,server,browser;
const check=(value,message)=>{assert.ok(value,message);assertionCount++;assertions.push(message);};
const equal=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);assertionCount++;assertions.push(message);};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitFor(fn,message,timeout=20000){const start=Date.now();let last;while(Date.now()-start<timeout){try{last=await fn();if(last)return last;}catch(error){last=error.message;}await sleep(100);}throw new Error(`${message}; last=${String(last)}`);}
function chromePath(){for(const candidate of [process.env.TAXMATE_CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'])if(candidate&&fs.existsSync(candidate))return candidate;throw new Error('Installed Chrome not found');}
function previewEnvironment(){
  const payload=JSON.stringify(fixtures).replace(/</g,'\\u003c');
  return `'use strict';
window.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:Object.freeze({}),hosts:Object.freeze(['127.0.0.1','localhost']),localReview:true});
(function(){
  const fixtures=${payload},names=Object.keys(fixtures),params=new URLSearchParams(location.search),requested=params.get('fixture'),fixture=names.includes(requested)?requested:'current',marker='taxmate-partnership-share-preview-fixture';
  localStorage.setItem('taxmateuk_analytics_consent','denied');
  const stateKey='taxmateuk_account_v1:local:canonical',outboxKey='taxmateuk_account_v1:local:sync-outbox';
  if(params.get('reset')==='1'||localStorage.getItem(marker)!==fixture||!localStorage.getItem(stateKey)){localStorage.setItem(stateKey,JSON.stringify(fixtures[fixture]));localStorage.setItem(marker,fixture);localStorage.removeItem(outboxKey);}
  window.TaxMatePartnershipSharePreview=Object.freeze({fixture,names,productionProviders:false});
  document.addEventListener('DOMContentLoaded',function(){
    const box=document.createElement('details');box.id='partnership-share-review-controls';box.style.cssText='position:fixed;z-index:12000;inset-block-end:84px;inset-inline-end:8px;background:#fff;color:#16202b;border:1px solid #0aa968;border-radius:12px;padding:6px 8px;font:12px/1.4 system-ui;box-shadow:0 4px 16px #0003;max-width:min(310px,calc(100vw - 16px));max-height:calc(100vh - 110px);overflow:auto';
    const labels={sole:'Sole trader only',single50:'Single 50% partnership',multi50:'Multiple 50% partnerships',mixed:'Sole + partnership',withLtd:'Partnership + Ltd',differentShares:'Different share percentages',current:'Current screenshot equivalent'};
    box.innerHTML='<summary style="cursor:pointer;font-weight:800;min-height:32px;display:flex;align-items:center">Partnership share review</summary><div style="display:grid;gap:6px;margin-top:8px">'+Object.entries(labels).map(([name,label])=>'<a style="display:flex;align-items:center;min-height:40px;color:#067a4b;font-weight:700" href="/?fixture='+name+'&reset=1">'+label+'</a>').join('')+'<small>Local-only fixtures. No Firebase, billing, analytics or production requests.</small></div>';document.body.appendChild(box);
  });
})();\n`;
}
function prepareArtifact(){
  fs.mkdirSync(evidence,{recursive:true});
  const built=spawnSync(process.execPath,['scripts/build-hosting.js','production','partnership-personal-share-review'],{cwd:root,stdio:'inherit'});if(built.status!==0)throw new Error('Founder Preview Hosting artifact build failed');
  const firebaseFiles=['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js','firebase-storage-compat.js','firebase-app-check-compat.js'],vendor=path.join(artifact,'vendor','firebase');fs.mkdirSync(vendor,{recursive:true});
  for(const file of firebaseFiles)fs.copyFileSync(path.join(root,'node_modules','firebase',file),path.join(vendor,file));
  const htmlPath=path.join(artifact,'index.html');let html=fs.readFileSync(htmlPath,'utf8');
  for(const file of firebaseFiles)html=html.replace(new RegExp(`https://www\\.gstatic\\.com/firebasejs/[^"']+/${file}`,'g'),`vendor/firebase/${file}`);
  html=html.replace(/<script[^>]+https:\/\/cdnjs\.cloudflare\.com[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'').replace(/<noscript><link[^>]+https:\/\/fonts\.googleapis\.com[^>]*><\/noscript>\s*/gi,'');
  fs.writeFileSync(htmlPath,html);fs.writeFileSync(path.join(artifact,'firebase-environment.js'),previewEnvironment());fs.writeFileSync(path.join(artifact,'src','app','sentry-bootstrap.js'),`'use strict';window.__TAXMATE_SENTRY_STATE__=Object.freeze({enabled:false,reason:'localhost_founder_review',sdkRequested:false});\n`);
  const swPath=path.join(artifact,'sw.js');let sw=fs.readFileSync(swPath,'utf8'),vendorShell=firebaseFiles.map(file=>`'/vendor/firebase/${file}'`).join(',');sw=sw.replace("'/src/core/versions.js'",vendorShell+",\n  '/src/core/versions.js'");fs.writeFileSync(swPath,sw);
}
function contentType(file){const ext=path.extname(file).toLowerCase();return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'})[ext]||'application/octet-stream';}
async function startServer(){server=http.createServer((request,response)=>{const url=new URL(request.url,origin),relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)),target=path.resolve(artifact,relative);if(!target.startsWith(artifact+path.sep)&&target!==path.join(artifact,'index.html')){response.writeHead(403);response.end('Forbidden');return;}if(!fs.existsSync(target)||fs.statSync(target).isDirectory()){response.writeHead(404,{'content-type':'text/plain'});response.end('Not found');return;}response.writeHead(200,{'content-type':contentType(target),'cache-control':'no-store'});fs.createReadStream(target).pipe(response);});await new Promise(resolve=>server.listen(4188,'127.0.0.1',resolve));}
async function launch(fixture,options={}){const context=await browser.newContext({viewport:options.viewport||{width:390,height:844},serviceWorkers:'allow'});context.on('request',request=>{const url=request.url();if(!url.startsWith(origin)){externalRequests.push(url);if(/sentry/i.test(url))sentryRequests.push(url);}});const page=await context.newPage();page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('pageerror',error=>consoleErrors.push(error.message));await page.goto(`${origin}/?fixture=${fixture}&reset=1`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('[data-home-personal-hero], [data-home-ltd-only-hero]'));return{context,page};}
async function snapshot(page){return page.evaluate(()=>{const tx=calcTax(S.year),rows=[...document.querySelectorAll('[data-home-business-row]')].map(node=>({id:node.dataset.homeBusinessRow,amountMinor:node.dataset.personalProfitMinor,text:node.textContent}));return{hero:document.querySelector('[data-home-ledger-profit]')?.dataset.personalProfitMinor||null,income:document.querySelector('[data-personal-income-minor]')?.dataset.personalIncomeMinor||null,expenses:document.querySelector('[data-personal-expenses-minor]')?.dataset.personalExpensesMinor||null,rows,hasShareNote:!!document.querySelector('[data-home-partnership-share-note]'),incomeLabel:document.querySelector('[data-personal-income-minor]')?.previousElementSibling?.textContent||'',expenseLabel:document.querySelector('[data-personal-expenses-minor]')?.previousElementSibling?.textContent||'',tax:{myProfitMinor:Math.round(tx.myProfit*100),partShareProfitMinor:Math.round(tx.partShareProfit*100),liabilityMinor:Math.round(tx.liability*100),supported:tx.taxEstimateSupported},businesses:JSON.stringify(S.businesses),entries:JSON.stringify(S.entries),ltd:!!activeLtdProfile()};});}
async function currentExample(){const app=await launch('current');try{let value=await snapshot(app.page);equal(value.hero,'674839','Founder example Hero is £6,748.39 personal profit');equal(value.income,'1001472','Founder example money in is the £10,014.72 personal share');equal(value.expenses,'326633','Founder example money out is the £3,266.33 personal share');equal(value.rows.map(row=>[row.id,row.amountMinor]),[['evri','710513'],['newset','0'],['taxmate-app','-35674']],'Evri, Newset and Taxmate app rows use exact personal shares');equal(value.rows.reduce((sum,row)=>sum+Number(row.amountMinor),0),Number(value.hero),'Home business rows sum exactly to the Hero');equal(value.tax,{myProfitMinor:674839,partShareProfitMinor:674839,liabilityMinor:0,supported:true},'personal tax uses the same attributable partnership profit exactly once');check(value.hasShareNote,'partnership conditional copy is visible');equal(value.incomeLabel,'Your share of money in','partnership Home uses the personal-share money-in label');equal(value.expenseLabel,'Your share of money out','partnership Home uses the personal-share money-out label');
  const before=await app.page.evaluate(()=>JSON.stringify({businesses:S.businesses,entries:S.entries}));await app.page.locator('[data-home-business-row="evri"] button').click();await app.page.locator('#bz-partnership-figures').waitFor();equal(await app.page.locator('[data-partnership-total-profit-minor]').getAttribute('data-partnership-total-profit-minor'),'1421025','partnership detail retains the full £14,210.25 profit');equal(await app.page.locator('[data-partnership-personal-profit-minor]').getAttribute('data-partnership-personal-profit-minor'),'710513','partnership detail shows the exact £7,105.13 personal share');equal(await app.page.evaluate(()=>JSON.stringify({businesses:S.businesses,entries:S.entries})),before,'opening partnership detail mutates no bookkeeping fact');await app.page.screenshot({path:path.join(evidence,'current-partnership-detail-mobile-light.png'),fullPage:true});screenshots.push('current-partnership-detail-mobile-light.png');await app.page.getByRole('button',{name:'Cancel',exact:true}).click();
  await app.page.reload({waitUntil:'domcontentloaded'});await app.page.waitForFunction(()=>document.querySelector('[data-home-ledger-profit]'));equal((await snapshot(app.page)).hero,'674839','normal refresh preserves the exact personal-share summary');
  await app.page.evaluate(()=>{const record=S.entries.find(entry=>entry.id==='evri-income');record.amount=20030.44;record.updatedAt=Date.now();persistCanonicalState(TaxMateState.migrate(S,Date.now(),DEVICE_ID));S=TaxMateState.migrate(S,Date.now(),DEVICE_ID);applyHydratedAccountResult({state:'converged',existingCloudAccount:true});});await waitFor(()=>app.page.locator('[data-home-ledger-profit]').getAttribute('data-personal-profit-minor').then(value=>value==='674889'),'cloud-style same-route repaint did not update personal share');equal((await snapshot(app.page)).hero,'674889','cloud-style same-route repaint displays the new canonical share without navigation');
  }finally{await app.context.close();}}
async function fixtureMatrix(){
  const expectations={single50:{hero:'674839',taxInput:674839,rowCount:1,ltd:false},multi50:{hero:'674839',taxInput:674839,rowCount:3,ltd:false},mixed:{hero:'140000',taxInput:60000,rowCount:2,ltd:false},withLtd:{hero:'674839',taxInput:674839,rowCount:3,ltd:true},differentShares:{hero:'25099',taxInput:25099,rowCount:3,ltd:false}};
  const soleApp=await launch('sole');try{const sole=await snapshot(soleApp.page);equal(sole.hero,'200000','sole-trader Hero remains the 100% business profit');equal(sole.incomeLabel,'Money in','sole-only Home keeps the simple money-in label');equal(sole.expenseLabel,'Money out','sole-only Home keeps the simple money-out label');equal(sole.hasShareNote,false,'sole-only Home has no partnership share note');}finally{await soleApp.context.close();}
  for(const [fixture,expected] of Object.entries(expectations)){const app=await launch(fixture);try{const value=await snapshot(app.page);equal(value.hero,expected.hero,`${fixture} has the expected exact personal Hero`);equal(value.rows.length,expected.rowCount,`${fixture} exposes every personal business row`);equal(value.rows.reduce((sum,row)=>sum+Number(row.amountMinor),0),Number(value.hero),`${fixture} rows reconcile to the Hero`);equal(value.income-value.expenses,Number(value.hero),`${fixture} personal money in less money out reconciles to the Hero`);equal(value.tax.myProfitMinor,expected.taxInput,`${fixture} tax input uses the partnership share exactly once while preserving the existing sole-trader allowance choice`);equal(value.ltd,expected.ltd,`${fixture} has the expected Ltd presence`);if(expected.ltd){check((await app.page.locator('[data-home-business-list]').textContent()).includes('ToodaLoop Ltd'),'partnership + Ltd shows the company row separately');equal(value.rows.length,3,'Ltd is excluded from personal row arithmetic');}}finally{await app.context.close();}}
  const missing=await launch('missingShare');try{const value=await snapshot(missing.page);equal(value.hero,null,'missing-share legacy data fails closed with no invented Hero amount');equal(value.tax.supported,false,'missing-share tax estimate is marked unsupported');check(await missing.page.locator('[data-home-partnership-review]').count()===1,'missing-share Home presents a concise review state');check((await missing.page.locator('[data-home-business-row]').textContent()).includes('Needs review'),'missing-share row never claims an invented 50% amount');}finally{await missing.context.close();}
}
async function presentationAndOffline(){const app=await launch('current');try{
  for(const [theme,lang,viewport,name] of [['light','en',{width:390,height:844},'personal-share-mobile-light-en.png'],['dark','en',{width:390,height:844},'personal-share-mobile-dark-en.png'],['auto','en',{width:768,height:1024},'personal-share-tablet-auto-en.png'],['light','ur',{width:1440,height:1000},'personal-share-desktop-urdu-rtl.png']]){await app.page.setViewportSize(viewport);await app.page.evaluate(({theme,lang})=>{S.settings.theme=theme;S.settings.lang=lang;applyTheme();applyStaticI18n();render();},{theme,lang});if(lang==='ur')equal(await app.page.locator('html').getAttribute('dir'),'rtl','Urdu personal-share Home renders RTL');const geometry=await app.page.evaluate(()=>({overflow:document.documentElement.scrollWidth-window.innerWidth,hero:!!document.querySelector('[data-home-ledger-profit]'),negative:getComputedStyle(document.querySelector('[data-home-business-row="taxmate-app"] .v')).color}));check(geometry.hero&&geometry.overflow<=1,`${name} renders without horizontal clipping`);await app.page.screenshot({path:path.join(evidence,name),fullPage:true});screenshots.push(name);}
  for(const lang of ['en','zh','pl','ro','es','ur']){await app.page.evaluate(lang=>{S.settings.lang=lang;applyStaticI18n();render();},lang);const text=await app.page.locator('[data-home-personal-hero]').textContent();check(!/home\.includesPartnershipShare|home\.shareIn|home\.shareOut|part\./.test(text),`${lang} renders the share summary without untranslated keys`);}
  await app.page.setViewportSize({width:195,height:422});await app.page.evaluate(()=>{S.settings.lang='en';S.settings.theme='light';applyTheme();applyStaticI18n();render();});check(await app.page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth<=1),'200% zoom-equivalent viewport has no horizontal clipping');
  await app.page.setViewportSize({width:390,height:844});await app.page.evaluate(()=>navigator.serviceWorker.ready);await app.page.reload({waitUntil:'domcontentloaded'});const before=await snapshot(app.page);await app.context.setOffline(true);await app.page.close();const offlinePage=await app.context.newPage();await offlinePage.goto(`${origin}/?fixture=current`,{waitUntil:'domcontentloaded'});await offlinePage.waitForFunction(()=>document.querySelector('[data-home-ledger-profit]'));equal((await snapshot(offlinePage)).hero,before.hero,'cold offline reopen preserves the exact personal-share Hero');await app.context.setOffline(false);await offlinePage.reload({waitUntil:'domcontentloaded'});equal((await snapshot(offlinePage)).hero,before.hero,'reconnect preserves the exact personal-share Hero');
  }finally{await app.context.close();}}
async function main(){prepareArtifact();await startServer();browser=await chromium.launch({headless:!reviewMode,executablePath:chromePath()});await currentExample();await fixtureMatrix();await presentationAndOffline();equal(externalRequests.length,0,'Founder Preview and browser regression emit zero external or production requests');equal(sentryRequests.length,0,'Founder Preview emits zero production Sentry requests');const unexpected=consoleErrors.filter(message=>!/Failed to load resource/.test(message));equal(unexpected.length,0,`Founder Preview has zero unexpected browser errors: ${JSON.stringify(unexpected)}`);const result={status:'PASS',generatedAt:new Date().toISOString(),assertionCount,assertions,identity:require('../../src/core/versions').VERSIONS,fixtures:Object.keys(fixtures),externalRequests,sentryRequests,consoleErrors,screenshots,sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'src','app','app.js'))).digest('hex')};fs.writeFileSync(resultPath,JSON.stringify(result,null,2)+'\n');process.stdout.write(`PARTNERSHIP_PERSONAL_SHARE_BROWSER_PASS assertions=${assertionCount}\n`);if(reviewMode){const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();await page.goto(`${origin}/?fixture=current&reset=1`,{waitUntil:'domcontentloaded'});process.stdout.write(`FOUNDER_PARTNERSHIP_SHARE_REVIEW_READY ${origin}/?fixture=current&reset=1\nSole: ${origin}/?fixture=sole&reset=1\nSingle 50%: ${origin}/?fixture=single50&reset=1\nMultiple 50%: ${origin}/?fixture=multi50&reset=1\nSole + partnership: ${origin}/?fixture=mixed&reset=1\nPartnership + Ltd: ${origin}/?fixture=withLtd&reset=1\nDifferent shares: ${origin}/?fixture=differentShares&reset=1\nPress Ctrl+C here when Founder review is finished.\n`);await new Promise(resolve=>process.once('SIGINT',resolve));}}
main().catch(error=>{fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(resultPath,JSON.stringify({status:'FAIL',generatedAt:new Date().toISOString(),assertionCount,assertions,externalRequests,sentryRequests,consoleErrors,error:error.stack||String(error)},null,2)+'\n');console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{if(browser)try{await browser.close();}catch(_){}if(server)await new Promise(resolve=>server.close(resolve));});
