'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),baseline=process.argv.includes('--baseline'),out=path.join(root,'.hosting-build/repeat-expense-review');
fs.mkdirSync(out,{recursive:true});
const results=[],errors=[];let server,browser,page,blocked=0;
async function scenario(name,run){await run();results.push({name,status:baseline?'BASELINE_REPRODUCED':'PASS_LOCAL_SYNTHETIC'});console.log(JSON.stringify(results.at(-1)));}
async function seed(date='2026-04-15',kind='expense',year='2026-27'){
 await page.evaluate(year=>{S=freshState();S.year=year;S.settings.lang='en';S.businesses=[{id:'newset',name:'Newset business',structure:'sole',share:100},{id:'other',name:'Other business',structure:'sole',share:100}];save();applyStaticI18n();render();},year);
 await page.evaluate(kind=>openEntry(kind),kind);await page.locator('#en-date').fill(date);await page.locator('#en-amount').fill('120');await page.locator('#en-desc').fill('Synthetic repeat');
}
const month=m=>page.locator(`[data-repeat-month="${m}"]`);
async function pick(months){await page.locator('#en-repeat-on').click();for(const m of months)await month(m).check();}
async function savedDates(){return page.evaluate(()=>S.entries.map(entry=>entry.date).sort());}
async function capture(name){await page.locator('#en-save').scrollIntoViewIfNeeded();const cd=await page.context().newCDPSession(page),image=await cd.send('Page.captureScreenshot',{format:'png',fromSurface:true});await cd.detach();fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(image.data,'base64'));}
async function main(){
 server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});
 const context=await browser.newContext({viewport:{width:390,height:900},isMobile:true,hasTouch:true,serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('taxmateuk_account_v1:local:onboarding-done','1');localStorage.setItem('taxmateuk_analytics_consent','denied');});
 await context.route('**/*',route=>{const url=route.request().url();if(new URL(url).origin===origin)return route.continue();blocked++;const sdk=/\/(firebase-[a-z-]+-compat\.js)$/.exec(url);return sdk?route.fulfill({path:path.join(root,'node_modules/firebase',sdk[1]),contentType:'text/javascript'}):route.abort();});
 page=await context.newPage();page.setDefaultTimeout(6000);page.on('pageerror',error=>errors.push(error.message));await page.goto(origin);await page.waitForFunction(()=>typeof openEntry==='function');
 if(baseline){
  await scenario('initially selected months toggle off; empty selection silently saves one',async()=>{await seed();await page.locator('#en-repeat-on').click();assert.equal(await page.locator('#en-repeat-months button.on').count(),12);for(let m=0;m<12;m++)await page.locator('#en-repeat-months button').nth(m).click();assert.equal(await page.evaluate(()=>EN.repeatMonths.size),0);await page.locator('#en-save').click();assert.equal(await page.evaluate(()=>S.entries.length),1);});
  await scenario('business repaint resets repeating mode before save',async()=>{await seed();await page.locator('#en-repeat-on').click();assert.equal(await page.evaluate(()=>EN.repeat),true);await page.locator('#en-biz').selectOption('other');assert.equal(await page.evaluate(()=>EN.repeat),false);await page.locator('#en-save').click();assert.equal(await page.evaluate(()=>S.entries.length),1);});
 } else {
  await scenario('repeat starts with unchecked months; empty save stays open with error and no write',async()=>{await seed();await page.locator('#en-repeat-on').click();assert.equal(await page.locator('#en-repeat-months input:checked').count(),0);assert.match(await page.locator('#en-repeat-summary').textContent(),/0/);await page.locator('#en-save').click();assert.equal(await page.evaluate(()=>S.entries.length),0);assert.equal(await page.locator('#en-repeat-error').isVisible(),true);assert.equal(await page.locator('#sb-entry').evaluate(el=>el.classList.contains('open')),true);await page.evaluate(()=>closeSheet('entry'));});
  await scenario('twelve checked months create twelve durable rows; original date once; duplicate save ignored',async()=>{await seed();await pick(Array.from({length:12},(_,m)=>m));assert.match(await page.locator('#en-repeat-summary').textContent(),/12/);await capture('selected-12-en');await page.locator('#en-save').click();await page.evaluate(()=>saveEntry());const rows=await page.evaluate(()=>S.entries);assert.equal(rows.length,12);assert.equal(new Set(rows.map(r=>r.date)).size,12);assert.equal(rows.filter(r=>r.date==='2026-04-15').length,1);assert.equal(new Set(rows.map(r=>r.rgid)).size,1);assert.equal(new Set(rows.map(r=>r.id)).size,12);await page.reload();await page.waitForFunction(()=>S.entries.length===12);assert.deepEqual(await savedDates(),rows.map(r=>r.date).sort());});
  await scenario('checkbox deselection removes month; business/category/percentage repaint preserves selections',async()=>{await seed();await pick([0,1,2,11]);await month(1).uncheck();await page.locator('#en-biz').selectOption('other');await page.locator('[data-tm-click="openCatSheet()"]').click();await page.locator('#cc-name').fill('Synthetic repeat category');await page.locator('[data-tm-click="saveCat()"]').click();await page.locator('[data-tm-click="expandPct()"]').click();await page.locator('[data-tm-click="setPct(50)"]').click();assert.equal(await page.evaluate(()=>EN.repeat),true);assert.deepEqual(await page.evaluate(()=>[...EN.repeatMonths].sort((a,b)=>a-b)),[0,2,11]);assert.equal(await page.locator('#en-repeat-months input:checked').count(),3);await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2026-04-15','2026-06-15','2027-03-15']);assert.equal(await page.evaluate(()=>S.entries.every(e=>e.bizId==='other'&&e.pct===50)),true);});
  await scenario('unchecking original month does not add an implicit original row',async()=>{await seed();await pick([0,1,2]);await month(0).uncheck();await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2026-05-15','2026-06-15']);});
  await scenario('switching off repeat preserves ordinary one-off expense and income behavior',async()=>{await seed();await pick([0,1,2]);await page.locator('#en-repeat-off').click();await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2026-04-15']);assert.equal(await page.evaluate(()=>S.entries[0].rgid||null),null);await seed('2026-06-20','income');assert.equal(await page.locator('#en-repeat-group').isVisible(),false);await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2026-06-20']);assert.equal(await page.evaluate(()=>S.entries[0].kind),'income');});
  await scenario('receipt-reserved new ID still creates selected repeat rows',async()=>{await seed();await pick([0,1,2]);await page.evaluate(()=>{EN.id='synthetic-receipt-reserved';paintEntry();});assert.equal(await page.locator('#en-repeat-group').isVisible(),true);assert.equal(await page.evaluate(()=>EN.repeat),true);await page.locator('#en-save').click();assert.equal(await page.evaluate(()=>S.entries.length),3);assert.equal(await page.evaluate(()=>S.entries.filter(e=>e.id==='synthetic-receipt-reserved').length),1);});
  await scenario('short months clamp to last day, including leap February',async()=>{await seed('2027-01-31');await pick([0,10]);await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2026-04-30','2027-02-28']);await seed('2028-01-31','expense','2027-28');await pick([10]);await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2028-02-29']);});
  await scenario('early-April date stays inside tax year and twelve selected months include original once',async()=>{await seed('2027-04-01');await pick(Array.from({length:12},(_,m)=>m));assert.match(await month(0).getAttribute('aria-label'),/2027/);await page.locator('#en-save').click();const dates=await savedDates();assert.equal(dates.length,12);assert.equal(dates.filter(d=>d==='2027-04-01').length,1);assert.ok(dates.every(d=>d>='2026-04-06'&&d<='2027-04-05'));assert.equal(dates[0],'2026-05-01');});
  await scenario('date change refreshes preview and selected dates without silent tax-year crossing',async()=>{await seed('2027-01-31');await pick([0,10]);await page.locator('#en-date').fill('2027-01-01');await page.locator('#en-desc').click();assert.match(await page.locator('#en-repeat-summary').textContent(),/Apr 2027/);await page.locator('#en-save').click();assert.deepEqual(await savedDates(),['2027-02-01','2027-04-01']);});
  await scenario('existing records and tombstones remain untouched; repeat translations and touch layout are clear',async()=>{await seed();await page.evaluate(()=>{S.entries=[{id:'kept-income',bizId:'other',kind:'income',cat:'sales',amount:99,date:'2026-08-10',desc:'Keep'},{id:'kept-deleted',bizId:'other',kind:'expense',cat:'vehicle',amount:9,date:'2026-08-11',deletedAt:1789000000000}];save();window.retainedBefore=JSON.stringify(S.entries);});await pick([0,1]);for(const lang of ['en','zh','pl','ro','es','ur']){await page.evaluate(lang=>{S.settings.lang=lang;applyStaticI18n();paintRepeatMonths();},lang);assert.doesNotMatch(await page.locator('#en-repeat-from').textContent(),/f\.repeat/);assert.equal(await page.locator('#en-repeat-months input:checked').count(),2);}await page.evaluate(()=>{S.settings.lang='zh';applyStaticI18n();paintRepeatMonths();});await capture('selected-2-zh');assert.equal(await page.locator('#en-repeat-months').evaluate(el=>el.scrollWidth<=el.clientWidth),true);await page.locator('#en-save').click();assert.equal(await page.evaluate(()=>JSON.stringify(S.entries.slice(0,2))===retainedBefore),true);assert.equal(await page.evaluate(()=>S.entries.length),4);});
  await scenario('failed local persistence queues no repeat rows and a retry creates only the selected batch',async()=>{await seed();await pick([0,1,2]);const result=await page.evaluate(()=>{const originalSave=save,originalPush=pushEntryRemote;let queued=0;save=()=>false;pushEntryRemote=()=>{queued++;};try{saveEntry();const failed={rows:S.entries.length,queued,committed:!!EN.repeatCommitted};save=originalSave;saveEntry();return{failed,rows:S.entries.length,queued};}finally{save=originalSave;pushEntryRemote=originalPush;}});assert.deepEqual(result,{failed:{rows:0,queued:0,committed:false},rows:3,queued:3});});
  await scenario('editing an existing repeating row changes only that row and preserves group identity',async()=>{await seed();await pick([0,1,2]);await page.locator('#en-save').click();const before=await page.evaluate(()=>S.entries.map(e=>({id:e.id,date:e.date,amount:e.amount,rgid:e.rgid})));await page.evaluate(id=>openEntry('expense',id),before[1].id);assert.equal(await page.locator('#en-repeat-group').isVisible(),false);await page.locator('#en-amount').fill('140');await page.locator('#en-save').click();await page.locator('#rec-one').click();const after=await page.evaluate(()=>S.entries.map(e=>({id:e.id,date:e.date,amount:e.amount,rgid:e.rgid})));assert.deepEqual(after,before.map((e,i)=>({...e,amount:i===1?140:e.amount})));});
 }
 assert.deepEqual(errors,[]);
}
main().catch(error=>{results.push({name:'failure',status:'FAIL',error:error.stack});process.exitCode=1;console.error(error);}).finally(async()=>{fs.writeFileSync(path.join(out,baseline?'baseline.json':'result.json'),JSON.stringify({checkedAt:new Date().toISOString(),mode:baseline?'BASELINE_REPRODUCTION':'FIXED_FOCUSED_VALIDATION',results,errors,blockedExternalRequests:blocked,productionAccountAccess:'NONE',actions:0},null,2));if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));});
