'use strict';
// R01-R05: ordinary UI journeys only. No attack, privilege probes, malformed
// input, fault injection, concurrency races, destructive retention or stress.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process'),{chromium}=require('playwright'),JSZip=require('../../vendor/jszip-3.10.1.min');
const admin=require('firebase-admin'),LtdSync=require('../../src/core/ltd-sync'),{make}=require('../test-fixture');
const root=path.resolve(__dirname,'../..'),out=process.env.TAXMATE_NORMAL_EVIDENCE,origin='http://127.0.0.1:41885';
if(!out||process.env.GCLOUD_PROJECT!=='demo-taxmate'||process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:32880')throw Error('Local demo emulator only');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),clone=v=>JSON.parse(JSON.stringify(v));
const tracked=execFileSync('git',['ls-files'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/);
function hashes(){return Object.fromEntries(tracked.map(p=>[p,sha(fs.readFileSync(path.join(root,p)))]));}
const sourceBefore=hashes(),results={scope:'NON_ADVERSARIAL_NORMAL_USE_ONLY',startedAt:new Date().toISOString(),status:'RUNNING',sourceHashes:sourceBefore,assertions:[],beforeFindings:[],captures:[],pageErrors:[],blockedExternal:[],runtimeAdaptations:['Local Firebase SDK URLs, demo environment and emulator auth only; no UI modules replaced.','Emulator Admin SDK seeds ordinary account fixture/Pro entitlement. It is setup, not a permission-bypass test.'],notRun:['All previous 14 aggregate gates are NOT RUN this round.','Mixed security/permission bypass, residual-state injection, malformed-input, concurrency/race, retention deletion, stress/soak and extreme-failure suites are outside this authorisation.','No provider, payment, refund, production account, deployment or existing-version restore acceptance.']};
let baseline,server,browser,phase='after';
function check(value,label){if(phase==='before'){results.beforeFindings.push({label,value:!!value});return;}assert.ok(value,label);results.assertions.push(label);}
async function shot(page,name,full=true){await page.evaluate(()=>document.fonts.ready);const file=phase+'/'+name+'.png';fs.mkdirSync(path.dirname(path.join(out,file)),{recursive:true});await page.screenshot({path:path.join(out,file),fullPage:full});const audit=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,authenticated:!!firebase.auth().currentUser,locale:S.settings.lang,theme:S.settings.theme}));results.captures.push({file,...audit});check(audit.scrollWidth<=audit.width,name+' no horizontal overflow');check(audit.authenticated,name+' real App demo account signed in');}
const settle=page=>page.waitForTimeout(120);
async function waitApp(page){await page.waitForFunction(()=>window.TaxMateLtdProductionAdapter?.isReady()&&typeof ensureFB==='function');}
async function invoke(page,name,input={}){const r=await page.evaluate(async({name,input})=>{const r=await TaxMateLtdUIFacade[name](input);return{status:r.status,error:r.error,fieldErrors:r.fieldErrors,data:r.data};},{name,input});assert.ok(['ok','review_required'].includes(r.status),name+': '+JSON.stringify(r));await settle(page);return r;}
async function presentation(page,lang='zh',theme='light',width=390){await page.setViewportSize({width,height:844});await page.evaluate(({lang,theme})=>{setLang(lang);setTheme(theme);},{lang,theme});await settle(page);}
async function personal(page,tab){await page.evaluate(tab=>{if(document.body.classList.contains('ltd-active'))TaxMateLtdProductionBridge.exitToBusinesses();go(tab);window.scrollTo({top:0,behavior:'instant'});},tab);await settle(page);}
async function closeLtd(page){await page.locator('.tm-dialog-close').click();await settle(page);}
async function openCompany(page){await page.evaluate(()=>TaxMateLtdProductionAdapter.openExistingCompany());await page.locator('.tm-workspace-shell').waitFor();await settle(page);}
async function nav(page,area){await page.locator(`.tm-workspace-shell button[data-area="${area}"]:visible`).click();await settle(page);}
function demoEnvironment(){return `window.TAXMATE_FIREBASE_EMULATORS=true;window.TAXMATE_FIREBASE_ENVIRONMENT=Object.freeze({firebaseConfig:{apiKey:'demo-api-key',authDomain:'demo-taxmate.firebaseapp.com',projectId:'demo-taxmate',storageBucket:'demo-taxmate.appspot.com',messagingSenderId:'100000000000',appId:'1:100000000000:web:normal-ui'},hosts:['127.0.0.1','localhost'],appCheckKey:'demo-only',functionsOrigin:'http://127.0.0.1:32501'});(function(){const init=firebase.initializeApp.bind(firebase);firebase.initializeApp=function(c,n){const a=init(c,n);firebase.auth(a).useEmulator('http://127.0.0.1:32399',{disableWarnings:true});firebase.firestore(a).useEmulator('127.0.0.1',32880);firebase.storage(a).useEmulator('127.0.0.1',32999);return a;};firebase.appCheck=function(){return{activate(){},async getToken(){return{token:'emulator-app-check'}}};};})();`;}
async function serve(){server=http.createServer(async(req,res)=>{try{let rel=decodeURIComponent(new URL(req.url,origin).pathname).replace(/^\//,'')||'index.html';if(rel.includes('..'))throw Error('Outside local asset scope');let b;if(rel==='firebase-environment.js')b=Buffer.from(demoEnvironment());else if(rel.startsWith('vendor/firebase/'))b=fs.readFileSync(path.join(root,'node_modules/firebase',path.basename(rel)));else if(phase==='before'){const f=baseline.file(rel);if(!f){res.writeHead(404).end();return;}b=await f.async('nodebuffer');}else{const f=path.join(root,rel);if(!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404).end();return;}b=fs.readFileSync(f);}if(rel==='index.html'){let html=b.toString();html=html.replace(/https:\/\/www\.gstatic\.com\/firebasejs\/[^"']+\/(firebase-[^"']+\.js)/g,'vendor/firebase/$1').replace(/<script[^>]+https:\/\/cdnjs\.cloudflare\.com[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'');b=Buffer.from(html);}res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'})[path.extname(rel)]||'application/octet-stream','Cache-Control':'no-store'});res.end(b);}catch(e){res.writeHead(500).end(String(e));}});await new Promise(r=>server.listen(41885,'127.0.0.1',r));}
async function account(label,count=null,mode='existing',contextOptions={}){
 const auth=admin.auth(),db=admin.firestore(),user=await auth.createUser({email:`normal-${label}-${Date.now()}@taxmate.local`,password:'Normal-Demo-2026!'});
 const state=clone(make(mode).driver.state);for(const b of state.businesses)b.syncCode=null;for(const e of state.entries){delete e.receiptUrl;delete e.receiptPath;}
 state.settings.lang='zh';state.settings.theme='light';state.tab='home';
 if(count!=null){state.entries=state.entries.filter(e=>e.kind!=='expense').concat(state.entries.filter(e=>e.kind==='expense').slice(0,count));}
 const entitlement={subscriptionStatus:'active',paidTier:'pro',currentPeriodEnd:Date.now()+86400000,serverVerifiedAt:Date.now()};
 await db.doc(`users/${user.uid}/entitlements/current`).set(entitlement);
 const companies=new Set(state.domain.entities.filter(e=>e.type==='limited_company'&&!e.deletedAt).map(e=>e.id));
 for(const [collection,rows]of Object.entries(LtdSync.recordsForSync(state)))for(const record of rows){const envelope=LtdSync.envelope(collection,record,LtdSync.companyIdForRecord(collection,record,companies));await db.doc(`users/${user.uid}/ltd/v1/${collection}/${envelope.documentId}`).set(envelope);}
 const company=state.domain.companyProfiles.find(p=>!p.deletedAt);if(company)await db.doc(`users/${user.uid}/ltdControl/activeCompany`).set({schemaVersion:1,status:'active_slot_claimed',activeCompanyId:company.entityId,releasePolicy:'founder_approval_required',claimedAt:Date.now(),updatedAt:Date.now()});
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',acceptDownloads:true,...contextOptions});
 await context.route('**/*',r=>{const url=r.request().url();if(/^https?:/.test(url)&&!/^http:\/\/(localhost|127\.0\.0\.1):/.test(url)){results.blockedExternal.push(url);return r.abort();}return r.continue();});
 await context.addInitScript(({state,uid})=>{localStorage.setItem(`taxmateuk_account_v1:firebase:${encodeURIComponent(uid)}:canonical`,JSON.stringify(state));localStorage.setItem(`taxmateuk_account_v1:firebase:${encodeURIComponent(uid)}:onboarding-done`,'1');localStorage.setItem('taxmateuk_analytics_consent','denied');},{state,uid:user.uid});
 const page=await context.newPage();page.on('pageerror',e=>results.pageErrors.push({phase,message:e.message}));await page.goto(origin);await waitApp(page);await page.evaluate(async c=>{await ensureFB();await firebase.auth().signInWithEmailAndPassword(c.email,c.password);},{email:user.email,password:'Normal-Demo-2026!'});
 await page.waitForFunction(()=>firebase.auth().currentUser&&hasFeature('receiptPhoto')&&S.entries.length>0);await page.waitForFunction(()=>CLOUD.hydrationState==='converged'&&syncStatus().state==='synced',null,{timeout:60000});
 return{page,context,state};
}
async function longList(page,kind='expenses',count=62){await personal(page,kind);const entries=await page.locator('.elist .entry').count();check(entries>=count,kind+' retains '+count+' history rows');const action=page.locator('.direction-a-list-action .btn');const box=await action.boundingBox();check(box&&box.y>=0&&box.y+box.height<844,kind+' add action on first screen');await shot(page,kind+'-'+page.viewportSize().width+'-first-screen',false);await shot(page,kind+'-'+page.viewportSize().width+'-full-list');if(phase==='after'){await action.click();check(await page.locator('#sb-entry.open').count()===1,kind+' primary action opens real entry');await page.evaluate(()=>closeSheet('entry'));await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await settle(page);const initialBox=await action.boundingBox();await page.waitForFunction(()=>{const b=document.querySelector('.direction-a-list-action .btn')?.getBoundingClientRect();return b&&b.y>=0&&b.bottom<844;},null,{timeout:5000});const after=await action.boundingBox();(results.layoutSettles||=[]).push({kind,width:page.viewportSize().width,initialBox,after});check(after&&after.y>=0&&after.y+after.height<844,kind+' add action remains reachable at list end');await shot(page,kind+'-'+page.viewportSize().width+'-list-end',false);await action.click();await page.evaluate(()=>closeSheet('entry'));}}
async function basicScreens(page){await presentation(page);for(const [tab,name]of[['home','01-home'],['income','02-income'],['expenses','03-expenses'],['tax','04-tax']]){await personal(page,tab);await shot(page,name,false);await shot(page,name+'-full');}await page.locator('[data-tax-calculation]>summary').click();const amounts=await page.locator('[data-tax-calculation] .frow').evaluateAll(rows=>rows.map(row=>({label:row.querySelector('.fl')?.innerText,amount:row.querySelector('.fv')?.innerText,color:row.querySelector('.fv')&&getComputedStyle(row.querySelector('.fv')).color})));results[phase+'TaxRows']=amounts;check(amounts.some(r=>r.amount?.startsWith('−£12,570')&&r.color==='rgb(189, 48, 55)'),'R05 allowance is red calculation deduction');await shot(page,'tax-detail');await personal(page,'home');const assistantOrigin=await page.evaluate(()=>scrollY);await page.locator('[data-tm-click="assistantOpen()"]').click();check(await page.locator('#assistant-task-list .review01-task-options').count()===0,'R03 no repeated options in assistant');check(await page.locator('#sb-assistant button[data-tm-click="closeSheet(\'assistant\')"]').count()===1,'R03 one close control');await shot(page,'10-assistant',false);await page.locator('.review01-close:visible').click();check(await page.evaluate(()=>document.activeElement?.getAttribute('data-tm-click'))==='assistantOpen()','R03 close restores opener focus');check(Math.abs(await page.evaluate(()=>scrollY)-assistantOrigin)<2,'R03 close restores original scroll');}
async function ltdScreens(page){
 await openCompany(page);await shot(page,'05-company',false);await nav(page,'money');await shot(page,'06-company-money',false);await nav(page,'tax');await shot(page,'08-company-year',false);
 await page.locator('[data-action="prepare-company-year"]').click();await page.locator('[data-figures-status]').waitFor();await shot(page,'07-year-figures',false);
 await page.locator('[data-action="download-self-filing-pack"]').click();await page.locator('[data-pack-status]').waitFor();check(await page.locator('.tm-todo-summary').count()===0,'R02 no aggregate group-count task');check(!await page.locator('[data-pack-file]').isVisible(),'R02 technical filename not first layer');check(await page.locator('.tm-yearhead').count()===0,'R02 no repeated company-year heading');await shot(page,'pack-first-screen',false);
 if(phase==='after'){const download=page.waitForEvent('download');await page.locator('[data-action="download-pack-file"]').click();const d=await download;await d.saveAs(path.join(out,'downloaded-pack.json'));check(d.suggestedFilename().endsWith('.json'),'R02 actual pack download preserved');await page.locator('[data-action="open-pack-guidance"]').click();check(await page.locator('[data-pack-file]').isVisible(),'R02 filename available in related details');await shot(page,'pack-guidance');await page.locator('[data-action="open-pack-guidance"]').click();await page.locator('[data-action="open-pack-details"]').click();check(await page.locator('.tm-disc[open] .tm-num').count()>4,'R05 full pack amount details retained');await shot(page,'pack-money-details');await page.locator('[data-action="open-pack-details"]').click();await page.locator('[data-action="open-checklist"]').click();check(await page.locator('[data-statutory-count]').count()>0,'R02 complete statutory checklist retained');await shot(page,'complete-obligations');await page.locator('[data-action="open-checklist"]').click();}
 const checks=page.locator('[data-todo-action="director"]');if(await checks.count()){await checks.click();const n=await page.locator('[data-review-fact]').count();check(n>0&&n<=4,'related N checks remain scoped');await shot(page,'11-checks',false);await closeLtd(page);}
 await nav(page,'overview');
 // Normal bookkeeping fixture creation via the same facade used by the UI.
 await invoke(page,'onAddIncome',{amountMinor:4321,date:'2026-08-22',description:'Customer payment — design work',invoicePartyId:'customer:normal-ui',companyIncomeCategory:'trading',evidenceRefs:['local:normal-demo:invoice']});
 await invoke(page,'onMatchBankStatement',{statement:{startDate:'2026-08-01',endDate:'2026-08-31',openingBalanceMinor:0,closingBalanceMinor:4321,lines:[{id:'normal-line',date:'2026-08-22',amountMinor:4321,description:'Customer payment — August design work'}],matches:[],evidenceRefs:['local:normal-demo:statement']}});
 await nav(page,'overview');await nav(page,'overview');await page.locator('[data-action="open-bank"]').click();
 check(await page.locator('.tm-sheet .tm-stitle').innerText()==='銀行對帳','R04 approved bank heading');check(await page.locator('.tm-sfoot button').count()===1,'R04 one primary footer action');check(await page.locator('.tm-sbody .tm-kick').count()===0,'R04 no repeated bank subtitle');await shot(page,'09-bank-match',false);
 if(phase==='after'){const candidate=page.locator('.tm-choice').filter({hasText:'Customer payment — design work'});await candidate.click();await page.locator('[data-action="bank-match-save"]').click();await page.waitForFunction(()=>!document.querySelector('.tm-dialog-close'));await nav(page,'overview');await page.locator('[data-action="open-bank"]').click();check(await page.locator('.tm-choice.on').filter({hasText:'Customer payment — design work'}).count()===1,'R04 normal match persists');if(!await page.locator('[data-action="bank-match-edit"]').isVisible())await page.locator('.tm-sbody .tm-disc>summary').click();await page.locator('[data-action="bank-match-edit"]').click();check(await page.locator('[data-action="bank-save"]').count()===1,'R04 statement editing remains available');await shot(page,'bank-edit');await closeLtd(page);await nav(page,'overview');await page.locator('[data-action="open-bank"]').click();await page.locator('.tm-choice').first().click();await page.locator('[data-action="bank-match-save"]').click();await page.waitForFunction(()=>!document.querySelector('.tm-dialog-close'));check(await page.evaluate(()=>TaxMateLtdUIFacade.getSnapshot().workspace.bankReconciliations.at(-1).matches.length)===0,'R04 normal unmatch persists');}else await closeLtd(page);
 await personal(page,'more');await page.locator('[data-tm-click="openBillingOverview()"]').click();await shot(page,'12-subscription',false);
}
async function normalAssistant(page){await personal(page,'home');await page.locator('[data-tm-click="assistantOpen()"]').click();const row=page.locator('#assistant-task-list .assistant-task').first();await row.locator('button').click();check(await page.locator('#page [data-task-context]').count()>0,'R03 reminder opens real receipt task with secondary options');await page.locator('[data-task-context]>summary').click();await page.locator('[data-task-context] button').click();await personal(page,'home');await page.locator('[data-tm-click="assistantOpen()"]').click();await page.locator('#assistant-show-hidden').click();check(await page.locator('#assistant-hidden-list .assistant-task').count()===1,'R03 ignored reminder can be found');await page.locator('#assistant-hidden-list button').click();check(await page.locator('#assistant-hidden-list .assistant-task').count()===0,'R03 normal restore preserved');await page.locator('.review01-close:visible').click();}
async function matrices(page){for(const lang of ['en','zh','pl','ro','es','ur'])for(const theme of ['light','dark']){await personal(page,'home');await presentation(page,lang,theme);await shot(page,`matrix-home-${lang}-${theme}`,false);await personal(page,'tax');await page.locator('[data-tax-calculation]>summary').click();const c=await page.locator('[data-money-role="calculation-deduction"]').evaluate(n=>getComputedStyle(n).color);check(c===(theme==='dark'?'rgb(255, 138, 143)':'rgb(189, 48, 55)'),`R05 ${lang} ${theme} deduction role`);await shot(page,`matrix-tax-detail-${lang}-${theme}`);await openCompany(page);await nav(page,'tax');await page.locator('[data-action="download-self-filing-pack"]').click();await shot(page,`matrix-pack-${lang}-${theme}`,false);await nav(page,'overview');await nav(page,'overview');await page.locator('[data-action="open-bank"]').click();check((await page.locator('.tm-sbody .tm-disc>summary').innerText()).includes(require('../../src/integration/ltd/approved-copy.json').canonical[lang==='zh'?'zh-HK':lang]['todo.details']),`R04 ${lang} contextual Details label`);await shot(page,`matrix-bank-${lang}-${theme}`,false);await closeLtd(page);}for(const width of [360,412,1440]){await personal(page,'expenses');await presentation(page,'zh','light',width);await longList(page,'expenses',62);await shot(page,`width-${width}-expenses`,false);await personal(page,'home');await page.locator('[data-tm-click="assistantOpen()"]').click();await shot(page,`width-${width}-assistant`,false);await page.locator('.review01-close:visible').click();await openCompany(page);await nav(page,'overview');await page.locator('[data-action="open-bank"]').click();await shot(page,`width-${width}-bank`,false);await closeLtd(page);}}
async function normalDraftAndDate(){
 const {page,context}=await account('draft',null,'fresh');await presentation(page,'en','light');await page.getByRole('button',{name:/Add a business/i}).last().click();await page.getByRole('button',{name:/Limited company/i}).click();check(await page.locator('.web-brand-home:visible').count()===0,'Required LTD setup does not gain a brand-navigation shortcut');check(await page.locator('[data-action="setup-remove-draft"]').count()===0,'R03 no remove action before a company draft exists');await invoke(page,'onContinueStep',{step:1,values:{companyNumberStatus:'not_available',legalName:'Normal future company'}});await page.locator('.tm-disc>summary').last().click();check(await page.locator('[data-action="setup-remove-draft"]').isVisible(),'R03 draft removal remains inside setup details');await page.locator('[data-action="setup-remove-draft"]').click();check(await page.locator('.tm-sheet').count()===1,'R03 existing remove confirmation opens');await closeLtd(page);await shot(page,'draft-task-options',false);await context.close();
}
async function main(){const bytes=fs.readFileSync(path.join(root,'.hosting-build/review01-handoff/SOURCE.zip'));assert.equal(sha(bytes),'6871d7d8817d8a6a05afd9e8eefb83b5697e51bd3a4e3b258ad1415d2ff88c2a');baseline=await JSZip.loadAsync(bytes);admin.initializeApp({projectId:'demo-taxmate'});await serve();browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});if(process.env.TAXMATE_NORMAL_WEB_LOGO_ONLY==='1'){results.variant='WEB_LOGO_ONLY';const {page,context}=await account('logo-target');await require('../helpers/web-logo-normal')({page,personal,presentation,openCompany,nav,shot,check});await context.close();const mobile=await account('logo-mobile-target',null,'existing',{...require('playwright').devices['Pixel 5'],serviceWorkers:'block'});await require('../helpers/web-logo-normal')({page:mobile.page,personal,presentation,openCompany,nav,shot,check,mobile:true});await mobile.context.close();check(results.pageErrors.length===0,'No page errors in targeted ordinary logo journeys');results.status='PASS';return;}results.variant='FULL_NORMAL';for(const p of ['before','after']){phase=p;console.log('Normal UI '+p);const {page,context}=await account(p);try{await longList(page);await longList(page,'income',15);await basicScreens(page);await ltdScreens(page);if(p==='after'){await normalAssistant(page);await matrices(page);await require('../helpers/web-logo-normal')({page,personal,presentation,openCompany,nav,shot,check});}}catch(e){await shot(page,'failure',false);throw e;}finally{await context.close();}}phase='after';await normalDraftAndDate();{const {page,context}=await account('logo-mobile',null,'existing',{...require('playwright').devices['Pixel 5'],serviceWorkers:'block'});await require('../helpers/web-logo-normal')({page,personal,presentation,openCompany,nav,shot,check,mobile:true});await context.close();}for(const count of [0,2]){const {page,context}=await account('count'+count,count);for(const width of [390,1440]){await presentation(page,'zh','light',width);await personal(page,'expenses');check(await page.locator('.elist .entry').count()===count,'R01 exact ordinary list length '+count);const action=page.locator('.direction-a-list-action .btn'),b=await action.boundingBox();check(b.y+b.height<844,'R01 '+count+' rows '+width+' first screen add');await shot(page,`expenses-${count}-${width}`,false);await action.click();check(await page.locator('#sb-entry.open').count()===1,'R01 '+count+' rows real add form');await page.evaluate(()=>closeSheet('entry'));}await context.close();}check(results.pageErrors.length===0,'no page errors in normal journeys');results.status='PASS';}
main().catch(e=>{results.status='FAIL';results.error=e.stack;console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await Promise.all(admin.apps.map(a=>a.delete()));results.sourceUnchanged=JSON.stringify(sourceBefore)===JSON.stringify(hashes());if(!results.sourceUnchanged){results.status='FAIL';process.exitCode=1;}results.completedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'normal-use-result.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({out,status:results.status,assertions:results.assertions.length,captures:results.captures.length,sourceUnchanged:results.sourceUnchanged}));});
