'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {chromium}=require('playwright');
const Backup=require('../../src/core/backup-export');
const Portable=require('../../src/core/portable-backup');
const CompanyAccess=require('../../src/core/company-access');

const root=path.resolve(__dirname,'../..'),artifact=path.join(root,'.hosting-build','six-issue-founder-preview'),evidence=path.resolve(process.env.TAXMATE_SIX_ISSUE_EVIDENCE||path.join(root,'.six-issue-founder-preview-evidence')),origin='http://127.0.0.1:4186';
const resultPath=path.join(evidence,'six-issue-founder-preview-result.json'),assertions=[],externalRequests=[];let assertionCount=0,server,browser;
function check(value,message){assert.ok(value,message);assertionCount++;assertions.push(message);}
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);assertionCount++;assertions.push(message);}
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function chromePath(){for(const candidate of [process.env.TAXMATE_CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'])if(candidate&&fs.existsSync(candidate))return candidate;throw new Error('Installed Chrome not found');}
function prepareArtifact(){
  const build=spawnSync(process.execPath,['scripts/build-hosting.js','production','six-issue-founder-preview'],{cwd:root,stdio:'inherit'});if(build.status!==0)throw new Error('Hosting artifact build failed');
  const firebaseFiles=['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js','firebase-storage-compat.js','firebase-app-check-compat.js'],vendor=path.join(artifact,'vendor','firebase');fs.mkdirSync(vendor,{recursive:true});for(const file of firebaseFiles)fs.copyFileSync(path.join(root,'node_modules','firebase',file),path.join(vendor,file));
  const htmlPath=path.join(artifact,'index.html');let html=fs.readFileSync(htmlPath,'utf8');for(const file of firebaseFiles)html=html.replace(new RegExp(`https://www\\.gstatic\\.com/firebasejs/[^"']+/${file}`,'g'),`vendor/firebase/${file}`);html=html.replace(/<script[^>]+https:\/\/cdnjs\.cloudflare\.com[\s\S]*?<\/script>\s*/gi,'').replace(/<link[^>]+https:\/\/fonts\.(?:googleapis|gstatic)\.com[^>]*>\s*/gi,'').replace(/<noscript><link[^>]+https:\/\/fonts\.googleapis\.com[^>]*><\/noscript>\s*/gi,'');fs.writeFileSync(htmlPath,html);
}
function startServer(){const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.ico':'image/x-icon','.svg':'image/svg+xml'};server=http.createServer((req,res)=>{const pathname=new URL(req.url,origin).pathname,relative=decodeURIComponent(pathname==='/'?'/index.html':pathname).replace(/^\/+/,''),target=path.resolve(artifact,relative);if(!target.startsWith(path.resolve(artifact)+path.sep)||!fs.existsSync(target)){res.writeHead(404);res.end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(target).pipe(res);});return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(4186,'127.0.0.1',resolve);});}
async function mobileContext(){
  const context=await browser.newContext({viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (Linux; Android 15; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36',acceptDownloads:true,serviceWorkers:'allow'});
  await context.addInitScript(()=>{localStorage.setItem('tmOnboardDone','1');localStorage.setItem('taxmateuk_analytics_consent','denied');});
  await context.route('**/*',async route=>{const url=route.request().url();if(/^https?:\/\//.test(url)&&!url.startsWith(origin)){externalRequests.push(url);await route.abort('blockedbyclient');return;}await route.continue();});return context;
}
async function main(){
  fs.mkdirSync(evidence,{recursive:true});prepareArtifact();await startServer();browser=await chromium.launch({headless:true,executablePath:chromePath()});const context=await mobileContext(),page=await context.newPage();await page.goto(origin+'/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof buildPortableArchive==='function');await page.evaluate(()=>navigator.serviceWorker.ready);
  const noReceipt=await page.evaluate(async()=>{const before=JSON.stringify(S),out=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(out.archive);return{before,after:JSON.stringify(S),bytes:out.archive.size,receiptCount:inspected.receipts.length,entryCount:inspected.state.entries.length};});equal(noReceipt.before,noReceipt.after,'no-receipt Full Backup mutates no state');equal(noReceipt.receiptCount,0,'no-receipt Full Backup validates with zero receipts');check(noReceipt.bytes>0,'no-receipt Full Backup is non-empty');
  const safeState={entries:[{id:'sanitised-entry',receiptPath:'receipts/sanitised/stale.jpg',receiptUrl:'https://example.test/sanitised-fallback.jpg'}]},safeBefore=JSON.stringify(safeState),safeDownload=async()=>({bytes:new Uint8Array([1,2,3,4]),mimeType:'image/jpeg'}),staleRows=await Backup.collectReceipts({state:safeState,user:{uid:'sanitised-user'},storageUrl:async()=>{throw Object.assign(new Error('missing'),{code:'storage/object-not-found'});},listStorage:async()=>[],download:safeDownload});equal(staleRows.length,1,'stale Storage path falls back to the same record URL without omitting its receipt');equal(JSON.stringify(safeState),safeBefore,'stale-reference handling mutates no state');
  const missingState={entries:[{id:'sanitised-missing',receiptPath:'receipts/sanitised/missing.jpg'}]},missingBefore=JSON.stringify(missingState),missingError=await Backup.collectReceipts({state:missingState,user:{uid:'sanitised-user'},storageUrl:async()=>{throw Object.assign(new Error('missing'),{code:'storage/object-not-found'});},listStorage:async()=>[],download:safeDownload}).then(()=>null,error=>error),missingDiagnostic=Backup.diagnostic(missingError);equal(missingDiagnostic.category,Backup.CATEGORIES.REFERENCED_RECEIPT,'missing referenced receipt stops with the exact safe category');equal(JSON.stringify(missingState),missingBefore,'missing referenced receipt failure mutates no state');
  const orphanRows=await Backup.collectReceipts({state:{entries:[]},user:{uid:'sanitised-user'},storageUrl:async()=>'',listStorage:async()=>[{fullPath:'receipts/sanitised/orphan.jpg',getDownloadURL:async()=> 'https://example.test/sanitised-orphan.jpg'}],download:safeDownload});equal(orphanRows.length,1,'orphan Storage receipt remains included in the Full Backup contract');
  const fbNotReady=await page.evaluate(async()=>{const before=JSON.stringify(S),original=FB.ready;let downloads=0,storageLists=0;try{FB.ready=false;const user={uid:'signed-in-founder-preview'},listStorage=FB.ready?async()=>{storageLists++;return[];}:null,error=await TaxMateBackupExport.collectReceipts({state:S,user,listStorage,download:async()=>{downloads++;return{bytes:new Uint8Array([1]),mimeType:'image/jpeg'};}}).then(()=>null,value=>value);return{diagnostic:TaxMateBackupExport.diagnostic(error),message:TaxMateBackupExport.message(error),downloads,storageLists,stateUnchanged:JSON.stringify(S)===before};}finally{FB.ready=original;}});equal(fbNotReady.diagnostic.category,Backup.CATEGORIES.STORAGE_LIST,'signed-in browser with FB.ready=false stops because orphan Storage listing is unavailable');equal(fbNotReady.downloads,0,'FB.ready=false browser stop occurs before any linked receipt download');equal(fbNotReady.storageLists,0,'FB.ready=false browser never attempts an unavailable Storage list operation');equal(fbNotReady.stateUnchanged,true,'FB.ready=false browser stop mutates no app state');check(/couldn't check your receipt files/i.test(fbNotReady.message),'FB.ready=false browser shows the safe Storage-list message');
  const categoryErrors=[Object.assign(new Error('offline'),{code:'auth/network-request-failed'}),Backup.failure(Backup.CATEGORIES.STORAGE_LIST),Backup.failure(Backup.CATEGORIES.REFERENCED_RECEIPT,{count:1}),Backup.failure(Backup.CATEGORIES.RECEIPT_DOWNLOAD,{count:1}),new Error('Receipt payload exceeds the portable-backup limit'),new Error('ZIP support is unavailable'),new Error('Receipt manifest is invalid'),Backup.failure(Backup.CATEGORIES.BROWSER_DOWNLOAD),new Error('unknown safe fallback')],failureDiagnostics=categoryErrors.map(error=>({...Backup.diagnostic(error),message:Backup.message(error)}));equal(new Set(failureDiagnostics.map(item=>item.category)).size,9,'all required Full Backup failures retain distinct safe categories');equal(new Set(failureDiagnostics.map(item=>item.message)).size,9,'all required Full Backup failures retain distinct actionable messages');
  const entitlementNow=2_000_000_000_000,entitlementSnapshots={free:{paidTier:'free',subscriptionStatus:'inactive'},plus:{paidTier:'plus',subscriptionStatus:'active',currentPeriodEnd:entitlementNow+86400000,serverVerifiedAt:entitlementNow},pro:{paidTier:'pro',subscriptionStatus:'active',currentPeriodEnd:entitlementNow+86400000,serverVerifiedAt:entitlementNow},expired:{paidTier:'free',lastPaidTier:'pro',subscriptionStatus:'expired',currentPeriodEnd:entitlementNow-1,serverVerifiedAt:entitlementNow}},entitlementEvidence=Object.fromEntries(Object.entries(entitlementSnapshots).map(([tier,snapshot])=>[tier,CompanyAccess.decide({action:'full_backup',snapshot,now:entitlementNow,hasExistingLtdData:true}).allowed]));equal(entitlementEvidence,{free:true,plus:true,pro:true,expired:true},'Free, Plus, Pro and expired users retain Full Backup export access');
  await page.evaluate(origin=>{const now=Date.now();S.businesses=[{id:'backup-trade',name:'Sanitised test trade',structure:'sole',share:100,recordType:'business',createdAt:now,updatedAt:now,deletedAt:null,deviceId:'six-issue-test',schemaVersion:5}];S.entries=[{id:'receipt-one',bizId:'backup-trade',businessId:'backup-trade',kind:'expense',date:'2026-08-30',amount:10,cat:'other',pct:100,receiptPath:null,receiptUrl:origin+'/favicon-48x48.png?v=20260831-2',description:'Sanitised receipt one',recordType:'entry',createdAt:now,updatedAt:now,deletedAt:null,deviceId:'six-issue-test',schemaVersion:5},{id:'receipt-two',bizId:'backup-trade',businessId:'backup-trade',kind:'expense',date:'2026-08-31',amount:20,cat:'other',pct:100,receiptPath:null,receiptUrl:origin+'/favicon-32x32.png?v=20260831-2',description:'Sanitised receipt two',recordType:'entry',createdAt:now+1,updatedAt:now+1,deletedAt:null,deviceId:'six-issue-test',schemaVersion:5}];S.tab='more';save();render();},origin);
  const before=await page.evaluate(()=>JSON.stringify(S)),built=await page.evaluate(async()=>{try{const out=await buildPortableArchive(),inspected=await TaxMatePortableBackup.inspectArchive(out.archive);return{ok:true,bytes:out.archive.size,receiptCount:inspected.receipts.length};}catch(error){return{ok:false,diagnostic:TaxMateBackupExport.diagnostic(error)};}});equal(built.ok,true,`two-receipt browser archive builds before download: ${JSON.stringify(built)}`);equal(built.receiptCount,2,'two-receipt browser archive validates before download');
  const [download]=await Promise.all([page.waitForEvent('download',{timeout:30000}),page.evaluate(()=>exportPortableBackup())]),zipPath=path.join(evidence,'android-chrome-pwa-full-backup.zip');await download.saveAs(zipPath);check(fs.statSync(zipPath).size>0,'Android-Chrome-shaped PWA Full Backup downloads a non-empty ZIP');const inspected=await Portable.inspectArchive(fs.readFileSync(zipPath));equal(inspected.receipts.length,2,'downloaded ZIP contains both linked receipt binaries');equal(inspected.metadata.receiptCount,2,'downloaded ZIP metadata matches its receipt manifest');equal(inspected.state.entries.map(entry=>entry.id),['receipt-one','receipt-two'],'isolated archive inspection restores the exact sanitised records');equal(await page.evaluate(()=>JSON.stringify(S)),before,'successful Full Backup download mutates no app state');
  for(const theme of ['light','dark']){await page.evaluate(theme=>{S.tab='home';S.settings.theme=theme;applyTheme();render();},theme);const colour=await page.locator('.home-add-income').evaluate(node=>getComputedStyle(node).color);equal(colour,'rgb(255, 255, 255)',`Home Add income computed colour is white in ${theme} theme`);await page.screenshot({path:path.join(evidence,`home-add-income-mobile-${theme}.png`),fullPage:true});}
  const card=await context.newPage();await card.setViewportSize({width:980,height:780});await card.setContent(`<style>body{margin:0;padding:34px;background:#e9edf1;font:600 18px Arial;color:#17212b}.card{width:720px;background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 8px 28px #0002}.card img{display:block;width:720px;height:378px}.copy{padding:22px;white-space:pre-wrap}.url{color:#146c43;margin-top:14px}</style><h1>Local WhatsApp/social-card preview</h1><div class="card"><img src="${origin}/taxmate-share-20260831-v2.png" alt="TaxMate — May your income always be with you."><div class="copy">I’ve invited you to connect to ‘Sanitised test trade’ on TaxMate. 🤝<br><br>Open TaxMate and enter this Partner Sync code manually:<br><br>CONNECT8<div class="url">https://www.taxmate.uk/</div></div></div>`);await card.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth===1200));equal(await card.locator('.url').count(),1,'local social-card preview renders one canonical URL');await card.screenshot({path:path.join(evidence,'local-social-card-one-url.png'),fullPage:true});await card.close();
  const iconSamples=[['16×16','favicon-16x16.png?v=20260831-2'],['32×32','favicon-32x32.png?v=20260831-2'],['48×48','favicon-48x48.png?v=20260831-2'],['Apple 180×180','apple-touch-icon.png?v=20260831-2'],['PWA 192×192','icon-192.png?v=20260831-2'],['PWA 512×512','icon-512.png?v=20260831-2'],['Maskable 512×512','icon-512-maskable.png?v=20260831-2']],tiles=theme=>iconSamples.map(([label,src])=>`<div class="tile ${theme}"><div>${label}</div><img src="${origin}/${src}" alt="${label}"></div>`).join(''),contact=await context.newPage();await contact.setViewportSize({width:1240,height:980});await contact.setContent(`<style>body{margin:0;padding:28px;background:#dfe5ea;color:#111827;font:700 16px Arial}h1{margin:0 0 18px}h2{margin:22px 0 12px}.row{display:flex;gap:14px;flex-wrap:wrap}.tile{width:138px;min-height:172px;border-radius:18px;padding:14px;text-align:center;box-shadow:0 3px 10px #0002}.tile.light{background:#fff;color:#111827}.tile.dark{background:#0f1620;color:#fff;border:1px solid #2a3442}.tile img{display:block;width:112px;height:112px;object-fit:contain;margin:12px auto 0}</style><h1>TaxMate favicon and PWA contact sheet</h1><h2>Light browser/icon background</h2><div class="row">${tiles('light')}</div><h2>Dark browser/icon background</h2><div class="row">${tiles('dark')}</div>`);await contact.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));equal(await contact.locator('img').count(),14,'favicon contact sheet renders every required output on light and dark backgrounds');await contact.screenshot({path:path.join(evidence,'favicon-contact-sheet-light-dark.png'),fullPage:true});await contact.close();
  const shortcut=await context.newPage();await shortcut.setViewportSize({width:760,height:420});await shortcut.setContent(`<style>body{margin:0;padding:34px;background:#f1f3f5;font:700 18px Arial;color:#202124}.shortcuts{display:flex;gap:54px}.shortcut{text-align:center}.tile{width:96px;height:96px;border-radius:50%;background:white;display:grid;place-items:center;box-shadow:0 2px 8px #0002;margin-bottom:12px}.tile img{width:72px;height:72px}.fb{width:72px;height:72px;border-radius:18px;background:#1877f2;color:white;font:bold 68px Arial;line-height:82px}</style><h1>Chrome shortcut foreground comparison</h1><div class="shortcuts"><div class="shortcut"><div class="tile"><img src="${origin}/icon-192.png?v=20260831-2" alt="TaxMate"></div>TaxMate</div><div class="shortcut"><div class="tile"><div class="fb">f</div></div>Facebook-sized reference</div></div>`);await shortcut.waitForFunction(()=>[...document.images].every(image=>image.complete&&image.naturalWidth>0));await shortcut.screenshot({path:path.join(evidence,'chrome-shortcut-size-comparison.png'),fullPage:true});await shortcut.close();
  const socialSource=path.join(root,'taxmate-share-20260831-v2.png'),socialEvidence=path.join(evidence,'social-image-exact-1200x630.png');fs.copyFileSync(socialSource,socialEvidence);equal(sha(socialEvidence),'132a70b72f79ef6002b6856a3b6fe565d966e68113a1584bae869d3bacdd6624','evidence social PNG is byte-identical to the Founder-approved asset');equal(externalRequests.length,0,'Founder Preview made zero external or production requests');
  const result={status:'PASS',generatedAt:new Date().toISOString(),assertionCount,assertions,identity:require('../../src/core/versions').VERSIONS,backup:{zip:'android-chrome-pwa-full-backup.zip',bytes:fs.statSync(zipPath).size,receiptCount:inspected.receipts.length,archiveStateParity:true,noReceipt,stalePathFallback:true,fbNotReady,missingReference:{...missingDiagnostic,message:Backup.message(missingError),stateUnchanged:JSON.stringify(missingState)===missingBefore},orphanReceiptCount:orphanRows.length,failureDiagnostics,entitlementEvidence},social:{file:'social-image-exact-1200x630.png',sha256:sha(socialEvidence)},visuals:['home-add-income-mobile-light.png','home-add-income-mobile-dark.png','local-social-card-one-url.png','favicon-contact-sheet-light-dark.png','chrome-shortcut-size-comparison.png','social-image-exact-1200x630.png'],externalRequests};fs.writeFileSync(resultPath,JSON.stringify(result,null,2)+'\n');process.stdout.write(`SIX_ISSUE_FOUNDER_PREVIEW_PASS assertions=${assertionCount} evidence=${evidence}\n`);await context.close();
}
main().catch(error=>{fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(resultPath,JSON.stringify({status:'FAIL',generatedAt:new Date().toISOString(),assertionCount,assertions,externalRequests,error:error.stack||String(error)},null,2)+'\n');console.error(error.stack||error);process.exitCode=1;}).finally(async()=>{if(browser)try{await browser.close();}catch(_){}if(server)await new Promise(resolve=>server.close(resolve));});
