'use strict';
// Actual app/auth/hydration/rendering with controlled synthetic reads. No provider or account access.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process'),{chromium}=require('playwright');
const red=process.argv.includes('--red'),root=path.resolve(__dirname,'../..'),artifact=path.join(root,red?'.hosting-build/ltd-setup-review-2':'.hosting-build/startup-sync-browser'),evidence=path.join(root,'.hosting-build/ltd-status-evidence');
const results=[];let server,browser,context,page,origin;
async function mount({query='',storedTab='home',staleIntent=false,returnMarker=null}={}){
 if(context)await context.close();context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});
 await context.addInitScript(()=>{localStorage.setItem('taxmateuk_account_v1:local:onboarding-done','1');localStorage.setItem('taxmateuk_analytics_consent','denied');});
 await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith(origin))return route.continue();const file=/\/firebasejs\/[^/]+\/(firebase-[a-z-]+-compat\.js)$/.exec(url);return file?route.fulfill({path:path.join(root,'node_modules/firebase',file[1]),contentType:'text/javascript'}):route.abort();});
 page=await context.newPage();page.testErrors=[];page.on('pageerror',error=>page.testErrors.push(error.message));let documents=0;page.on('request',request=>{if(request.isNavigationRequest()&&request.resourceType()==='document')documents++;});page.documentRequests=()=>documents;await page.goto(origin+'/'+query);await page.waitForFunction(()=>typeof watchAuth==='function');
 await page.evaluate(({storedTab,staleIntent,returnMarker})=>{
  const clone=value=>JSON.parse(JSON.stringify(value)),defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
  const uid='synthetic-startup-owner',scope=TaxMateAccountStorage.firebaseScope(uid),state=freshState();state.tab=storedTab;state.settings.lang='en';state.businesses=[TaxMateSync.touch({id:'synthetic-business',name:'Synthetic business',structure:'sole',share:100},DEVICE_ID,Date.now()-5000)];
  localStorage.setItem(TaxMateAccountStorage.key(scope,'canonical'),JSON.stringify(state));localStorage.setItem(TaxMateAccountStorage.key(scope,'onboarding-done'),'1');
  if(returnMarker)sessionStorage.setItem(TaxMateAccountStorage.sessionKey(scope,'billing-return'),JSON.stringify({uid,startedAt:Date.now(),...returnMarker}));
  if(staleIntent){const draft=obDefaultState(true);draft.screen='pro-gate';draft.pendingIntent={source:'ltd',companyNumberStatus:'provided',returnScreen:'ltd-choice'};localStorage.setItem(TaxMateAccountStorage.key(scope,'onboarding-draft'),JSON.stringify(draft));}
  const f=window.startupFixture={uid,scope,defer,gates:{controls:defer(),meta:defer()},listeners:new Map(),outbound:0,reads:[],billingReturns:0};
  f.user={uid,isAnonymous:false,email:'synthetic@example.invalid',getIdToken:async()=> 'synthetic',getIdTokenResult:async()=>({claims:{}})};
  f.meta={businesses:clone(state.businesses),accountOwnerUid:uid,settings:{lang:'en'},updatedAt:Date.now()-5000};f.entries=[];f.controls={reset:null,retention:null};
  const data=p=>p.endsWith('/app/meta')?f.meta:p.endsWith('/entitlements/current')?{subscriptionStatus:'active',paidTier:'pro',currentPeriodEnd:Date.now()+86400000,serverVerifiedAt:Date.now()}:p==='accountResets/'+uid?f.controls.reset:p.endsWith('/retention/current')?f.controls.retention:null;
  const snap=p=>{const value=data(p),rows=p.endsWith('/entries')?f.entries:[];return{exists:value!==null,data:()=>clone(value),metadata:{fromCache:false},docs:rows.map(row=>({id:row.id,data:()=>clone(row)})),forEach:fn=>rows.forEach(row=>fn({id:row.id,data:()=>clone(row)}))};};
  const ref=p=>({path:p,collection:name=>ref(p+'/'+name),doc:id=>ref(p+'/'+id),where:()=>ref(p),get:async()=>{f.reads.push(p);if(p==='accountResets/'+uid){await f.gates.controls.promise;if(f.controlsError)throw Object.assign(Error('synthetic-offline'),{code:'unavailable'});}if(p.endsWith('/app/meta'))await f.gates.meta.promise;return snap(p);},onSnapshot:(...args)=>{const callback=args.find(x=>typeof x==='function');if(!f.listeners.has(p))f.listeners.set(p,new Set());f.listeners.get(p).add(callback);return()=>f.listeners.get(p).delete(callback);}});
  f.emit=p=>{for(const fn of f.listeners.get(p)||[])fn(snap(p));};
  window.firebase={apps:[{}],auth:()=>({currentUser:f.user,onAuthStateChanged:callback=>{f.auth=callback;},signOut:async()=>{f.user=null;return f.auth(null);}})};
  FB.ready=true;FB.db={collection:name=>ref(name)};FB.subs={};
  // Outbound transport is synthetic; inbound merge and local persistence remain actual app code.
  pushUserState=async()=>{f.outbound++;return{state:'acked',pending:0};};scheduleOutboxFlush=()=>{};
  billingRefresh=async()=>{f.billingReturns++;};
  watchAuth.done=false;watchAuth();f.authPromise=f.auth(f.user);
 },{storedTab,staleIntent,returnMarker});
 return()=>documents;
}
async function releaseControls(){await page.evaluate(()=>startupFixture.gates.controls.resolve());await page.waitForFunction(()=>startupFixture.reads.some(p=>p.endsWith('/app/meta')));}
async function releaseHydration(){await page.evaluate(()=>startupFixture.gates.meta.resolve());await page.evaluate(()=>startupFixture.authPromise);}
async function scenario(name,run){try{await run();assert.deepEqual(page.testErrors,[],'No uncaught browser errors');results.push({name,status:'PASS',documentRequests:page.documentRequests()});}catch(error){results.push({name,status:'FAIL',error:error.message,documentRequests:page?.documentRequests(),uncaughtErrors:page?.testErrors});}console.log(JSON.stringify(results.at(-1)));}
async function run(){
 fs.mkdirSync(evidence,{recursive:true});if(!red)assert.equal(spawnSync(process.execPath,['scripts/build-hosting.js','production','startup-sync-browser'],{cwd:root,stdio:'inherit'}).status,0);
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.resolve(artifact,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(artifact+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(fs.existsSync)});
 await scenario('ordinary cold entry starts Home, ignoring a stored tab',async()=>{const documents=await mount({storedTab:'more'});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>S.tab),'home');assert.equal(await page.evaluate(()=>BILLING_VIEW),false);assert.equal(documents(),1);});
 await scenario('unowned stale billing URL does not open Change Plan',async()=>{const documents=await mount({query:'?billing=success'});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>BILLING_VIEW),false);assert.equal(await page.evaluate(()=>S.tab),'home');assert.equal(documents(),1);});
 await scenario('stored pending intent does not reopen setup on ordinary entry',async()=>{await mount({staleIntent:true});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>firstSyncSurfaceOpen()||document.body.classList.contains('ltd-active')),false);assert.equal(await page.evaluate(()=>S.tab),'home');});
 await scenario('typed LTD setup input and focus survive delayed hydration and later updates',async()=>{const documents=await mount();await releaseControls();await page.evaluate(()=>TaxMateLtdProductionAdapter.openNewLimitedCompany({companyNumberStatus:'provided'}));const field=page.locator('#taxmate-ltd-ui-root [data-field="legalName"]');await field.fill('Unsubmitted synthetic company');await field.focus();await page.evaluate(()=>{window.startupField=document.activeElement;startupField.setSelectionRange(5,10);});await releaseHydration();assert.equal(await field.inputValue(),'Unsubmitted synthetic company');assert.equal(await page.evaluate(()=>document.activeElement===startupField&&startupField.isConnected),true);await page.evaluate(()=>{startupFixture.meta.businesses[0].name='Cloud updated business';startupFixture.meta.businesses[0].updatedAt=Date.now()+1000;startupFixture.emit('users/'+startupFixture.uid+'/app/meta');});assert.equal(await page.evaluate(()=>document.activeElement===startupField&&startupField.selectionStart===5&&startupField.selectionEnd===10),true);assert.equal(documents(),1);});
 await scenario('same-account auth refresh preserves an open business form',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>openBiz('synthetic-business'));await page.locator('#bz-name').fill('Unsaved form input');await page.locator('#bz-name').focus();await page.evaluate(()=>{window.startupField=document.activeElement;startupFixture.authPromise=startupFixture.auth(startupFixture.user);});await page.evaluate(()=>startupFixture.authPromise);assert.equal(await page.locator('#sb-biz').evaluate(el=>el.classList.contains('open')),true);assert.equal(await page.locator('#bz-name').inputValue(),'Unsaved form input');assert.equal(await page.evaluate(()=>document.activeElement===startupField),true);});
 if(!red){
 await scenario('navigation, scroll and current figures survive delayed hydration',async()=>{await mount();await releaseControls();await page.evaluate(()=>{go('tax');window.scrollTo(0,400);window.startupScroll=scrollY;});await releaseHydration();assert.equal(await page.evaluate(()=>S.tab),'tax');assert.ok(await page.evaluate(()=>Math.abs(scrollY-startupScroll)<2));await page.evaluate(()=>{go('home');startupFixture.meta.businesses[0].name='Cloud updated business';startupFixture.meta.businesses[0].updatedAt=Date.now()+1000;startupFixture.emit('users/'+startupFixture.uid+'/app/meta');});assert.ok(await page.locator('#page').getByText('Cloud updated business',{exact:true}).count());assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(STORE_KEY)).businesses[0].name),'Cloud updated business');assert.ok(await page.evaluate(()=>startupFixture.outbound>0));});
 await scenario('retry and reconnect retain input while reporting failed sync honestly',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>{openBiz('synthetic-business');startupFixture.controlsError=true;});await page.locator('#bz-name').fill('Keep through reconnect');await page.locator('#bz-name').focus();await page.evaluate(async()=>{window.startupField=document.activeElement;CLOUD.controlsCached=true;await refreshCachedAccountControls();});assert.equal(await page.evaluate(()=>CLOUD.hydrationState),'failed');assert.equal(await page.evaluate(()=>document.activeElement===startupField),true);await page.evaluate(()=>{startupFixture.controlsError=false;window.dispatchEvent(new Event('online'));});await page.waitForFunction(()=>!CLOUD.controlsCached&&CLOUD.hydrationState==='converged');assert.equal(await page.locator('#bz-name').inputValue(),'Keep through reconnect');assert.equal(await page.evaluate(()=>document.activeElement===startupField),true);assert.equal(await page.locator('#sb-biz').evaluate(el=>el.classList.contains('open')),true);});
 for(const status of ['success','cancelled'])await scenario('owned '+status+' Checkout return is consumed once',async()=>{await mount({query:'?billing='+status,returnMarker:{}});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>BILLING_VIEW&&BILLING_UI.view==='plans'),true);assert.equal(await page.evaluate(()=>sessionStorage.getItem(TaxMateAccountStorage.sessionKey(ACTIVE_ACCOUNT_SCOPE,'billing-return'))),null);await page.evaluate(async()=>{go('home');await billingHandleReturn();});assert.equal(await page.evaluate(()=>BILLING_VIEW),false);});
 for(const marker of [{uid:'different-account'},{startedAt:1}])await scenario('unowned or expired return is ignored: '+(marker.uid?'owner':'age'),async()=>{await mount({query:'?billing=success',returnMarker:marker});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>BILLING_VIEW),false);});
 await scenario('user navigation before Checkout hydration wins over return presentation',async()=>{await mount({query:'?billing=success',returnMarker:{}});await releaseControls();await page.locator('#nav [data-tm-click="go(\'tax\')"]').click();await releaseHydration();assert.equal(await page.evaluate(()=>S.tab),'tax');assert.equal(await page.evaluate(()=>BILLING_VIEW),false);});
 await scenario('only opening the actual Checkout link records a return marker',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>{billingShowPurchase({id:'synthetic-offer',addressee:'Synthetic',providedAt:Date.now(),termsHtml:'<p>synthetic terms</p>'},location.origin+'/synthetic-checkout');document.querySelector('#sb-billing a[data-tm-click]').addEventListener('click',event=>event.preventDefault());});assert.equal(await page.evaluate(()=>sessionStorage.getItem(TaxMateAccountStorage.sessionKey(ACTIVE_ACCOUNT_SCOPE,'billing-return'))),null);await page.locator('#sb-billing a[data-tm-click]').click();assert.equal(await page.evaluate(()=>JSON.parse(sessionStorage.getItem(TaxMateAccountStorage.sessionKey(ACTIVE_ACCOUNT_SCOPE,'billing-return'))).uid),await page.evaluate(()=>startupFixture.uid));});
 await scenario('actual account switch still closes the old form and rejects old snapshots',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>{openBiz('synthetic-business');startupFixture.oldCallbacks=[...(startupFixture.listeners.get('users/'+startupFixture.uid+'/app/meta')||[])];startupFixture.user={...startupFixture.user,uid:'synthetic-other-owner'};startupFixture.authPromise=startupFixture.auth(startupFixture.user);});await page.evaluate(()=>startupFixture.authPromise);assert.equal(await page.locator('#sb-biz').evaluate(el=>el.classList.contains('open')),false);await page.evaluate(()=>{for(const fn of startupFixture.oldCallbacks)fn({data:()=>({accountOwnerUid:startupFixture.uid,businesses:[{id:'forbidden-old',name:'Old account'}]})});});assert.equal(await page.evaluate(()=>ACTIVE_ACCOUNT_SCOPE.uid),'synthetic-other-owner');assert.equal(await page.evaluate(()=>S.businesses.some(b=>b.id==='synthetic-business'||b.id==='forbidden-old')),false);});
 await scenario('a real server reset still crosses the safety boundary',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>{openBiz('synthetic-business');startupFixture.controls.reset={status:'complete',resetEpoch:2};startupFixture.meta={accountOwnerUid:startupFixture.uid};CLOUD.controlsCached=true;});await page.evaluate(()=>refreshCachedAccountControls());assert.equal(await page.locator('#sb-biz').evaluate(el=>el.classList.contains('open')),false);assert.equal(await page.evaluate(()=>localStorage.getItem(TaxMateAccountStorage.key(ACTIVE_ACCOUNT_SCOPE,'reset-epoch'))),'2');assert.equal(await page.evaluate(()=>S.businesses.length),0);});
 await scenario('partial date text and the open LTD exit sheet survive background data',async()=>{await mount();await releaseControls();await page.evaluate(()=>TaxMateLtdProductionAdapter.openNewLimitedCompany({companyNumberStatus:'provided'}));const field=page.locator('#taxmate-ltd-ui-root [data-field="incorporationDate"]');await field.fill('06/0');await field.focus();await page.evaluate(()=>{window.startupField=document.activeElement;});await releaseHydration();assert.equal(await field.inputValue(),'06/0');assert.equal(await page.evaluate(()=>document.activeElement===startupField),true);await field.fill('06/04/2026');await page.locator('#taxmate-ltd-ui-root').getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('dialog').waitFor();await page.evaluate(()=>startupFixture.emit('users/'+startupFixture.uid+'/app/meta'));assert.equal(await page.getByRole('dialog').count(),1);await page.getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await field.inputValue(),'06/04/2026');});
 await scenario('owned onboarding Checkout return resumes setup without opening plans',async()=>{await mount({query:'?billing=success',staleIntent:true,returnMarker:{pendingIntent:{source:'ltd',companyNumberStatus:'provided',returnScreen:'ltd-choice'}}});await page.evaluate(()=>{billingFetch=async()=>({});});await releaseControls();await releaseHydration();await page.waitForFunction(()=>document.body.classList.contains('ltd-active'));assert.equal(await page.evaluate(()=>BILLING_VIEW),false);assert.equal(await page.evaluate(()=>TaxMateLtdUIFacade.workflow.currentRoute().screenId),'ltd.onboarding.step1');});
 await scenario('a real Checkout return can finish after a failed first hydration',async()=>{await mount({query:'?billing=success',returnMarker:{}});await releaseControls();await page.evaluate(()=>startupFixture.gates.meta.reject(Object.assign(Error('synthetic-network'),{code:'unavailable'})));await page.evaluate(()=>startupFixture.authPromise);assert.equal(await page.evaluate(()=>CLOUD.hydrationState),'failed');assert.equal(await page.evaluate(()=>BILLING_VIEW),false);await page.evaluate(async()=>{startupFixture.gates.meta=startupFixture.defer();startupFixture.gates.meta.resolve();await startUserSync(startupFixture.user);});assert.equal(await page.evaluate(()=>BILLING_VIEW&&BILLING_UI.view==='plans'),true);assert.equal(await page.evaluate(()=>startupFixture.listeners.get('users/'+startupFixture.uid+'/app/meta').size),1);});
 await scenario('a server deletion lock still closes the form and blocks account writes',async()=>{await mount();await releaseControls();await releaseHydration();await page.evaluate(()=>{openBiz('synthetic-business');startupFixture.controls.reset={status:'deleting',resetEpoch:3};CLOUD.controlsCached=true;});await page.evaluate(()=>refreshCachedAccountControls());assert.equal(await page.locator('#sb-biz').evaluate(el=>el.classList.contains('open')),false);assert.equal(await page.evaluate(()=>CLOUD.deletionBlocked),true);assert.equal(await page.evaluate(()=>syncStatus().state),'failed');assert.equal(await page.evaluate(()=>{try{assertAccountWriteBoundary();return false;}catch(_){return true;}}),true);});
 await scenario('empty-account hydration preserves onboarding already opened by the user',async()=>{await mount();await releaseControls();await page.evaluate(()=>{S.businesses=[];startupFixture.meta=null;localStorage.removeItem(accountSlotKey('onboarding-done'));OB=obDefaultState(true);OB.screen='biz';TaxMateOnboardingRoot.open(document);obRender();window.startupOnboarding=OB;});const field=page.locator('#ob-root input[type="text"]').first();await field.fill('Unfinished new business');await field.focus();await page.evaluate(()=>{window.startupField=document.activeElement;});await releaseHydration();assert.equal(await page.evaluate(()=>OB===startupOnboarding&&OB.screen==='biz'),true);assert.equal(await field.inputValue(),'Unfinished new business');assert.equal(await page.evaluate(()=>document.activeElement===startupField),true);});
 await scenario('initial controls retain newer same-account bytes without disposing the adapter twice',async()=>{await mount();await page.evaluate(()=>{const latest=JSON.parse(localStorage.getItem(STORE_KEY));latest.businesses[0].name='Saved in another tab';latest.businesses[0].updatedAt=Date.now()+1000;latest.entries.push(TaxMateSync.touch({id:'other-tab-entry',bizId:'synthetic-business',kind:'income',date:'2026-09-09',amount:17,desc:'Synthetic saved entry',cat:'sales'},DEVICE_ID,Date.now()+1000));localStorage.setItem(STORE_KEY,JSON.stringify(latest));window.startupReadyEvents=0;window.addEventListener('taxmate:account-ready',()=>startupReadyEvents++);});await releaseControls();await releaseHydration();assert.equal(await page.evaluate(()=>S.businesses[0].name),'Saved in another tab');assert.equal(await page.evaluate(()=>S.entries.some(e=>e.id==='other-tab-entry'&&e.amount===17)),true);assert.equal(await page.evaluate(()=>startupReadyEvents),0);});
 }
 const report={checkedAt:new Date().toISOString(),phase:red?'BEFORE_CORRECTION':'AFTER_CORRECTION',scope:'LOCAL_SYNTHETIC_CONTROLLED_SYNC',results,providerAcceptance:'NOT_RUN',realPhoneAcceptance:'NOT_RUN'};fs.writeFileSync(path.join(evidence,red?'startup-sync-red.json':'startup-sync-green.json'),JSON.stringify(report,null,2)+'\n');
 if(!red)assert.ok(results.every(row=>row.status==='PASS'),'Focused startup sync regression failed');else assert.ok(results.some(row=>row.status==='FAIL'),'Expected the released code to reproduce the problem');
}
run().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));});
