'use strict';
const assert=require('node:assert/strict');
const test=require('node:test');
const Ledger=require('../src/core/company-ledger');
const RemunerationRules=require('../src/core/company-remuneration-rules');
const {make}=require('./test-fixture');

test('Money callback posts through the canonical balanced integer-pence ledger',async()=>{
  const {facade}=make(),before=facade.getSnapshot().workspace.events.length,result=await facade.onAddIncome({amountMinor:12345,date:'2026-08-20',description:'Fable contract test income',invoicePartyId:'customer:contract-test',companyIncomeCategory:'trading',evidenceRefs:['local:invoice:contract-test']});assert.equal(result.status,'ok');const snapshot=facade.getSnapshot(),event=snapshot.workspace.events.find(item=>item.sourceTransaction.purpose==='Fable contract test income');assert.ok(event);assert.equal(snapshot.workspace.events.length,before+1);const ledger=Ledger.reconcile(snapshot.workspace.events,snapshot.company.profile.entityId);assert.equal(ledger.balanceStatus,'reconciled');assert.equal(ledger.totalDebitMinor,ledger.totalCreditMinor);
});

test('record correction validates replacement before atomically storing reversal and replacement',async()=>{
  const {facade}=make(),prior=facade.getSnapshot().workspace.events.find(item=>item.status==='committed'&&item.sourceTransaction.companyTransactionType==='company_expense'),result=await facade.onCorrectRecord({eventId:prior.id,reasonCode:'founder_correction',replacement:{description:'Corrected hosting description'}});assert.equal(result.status,'ok');const events=facade.getSnapshot().workspace.events,reversed=events.find(item=>item.id===prior.id),replacement=events.find(item=>item.sourceTransaction.purpose==='Corrected hosting description');assert.equal(reversed.status,'reversed');assert.equal(reversed.revision,2);assert.ok(replacement);assert.equal(replacement.status,'committed');const ledger=Ledger.reconcile(events,facade.getSnapshot().company.profile.entityId);assert.equal(ledger.balanceStatus,'reconciled');assert.equal(ledger.totalDebitMinor,ledger.totalCreditMinor);
});

test('CT review, working pack and projection use canonical engines',async()=>{
  const {facade}=make();const ct=await facade.onRunCtEstimate({reviewTopics:{records:'yes',periods:'yes',losses:'yes'},ctFacts:{ukResidentConfirmed:true,ringFenceProfits:false,closeInvestmentHoldingCompany:false,associatedCompaniesConfirmedNone:true,qualifyingDistributionsMinor:0,accountsCompleteConfirmed:true,sameTradeContinues:true},lossUseMinorByPeriod:[0],asOfDate:'2026-08-24'});assert.ok(['ok','review_required'].includes(ct.status));assert.ok(ct.data.periodRecords.length>=1);const pack=await facade.onDownloadWorkingPack({});assert.ok(['ok','review_required'].includes(pack.status));assert.equal(pack.data.mimeType,'application/json');assert.equal(pack.data.payload.limitations.isCT600,false);assert.equal(pack.data.payload.limitations.isStatutoryAccounts,false);
});

test('scenario comparison is canonical, includes an explicit user-split mix, and never mutates actual books',async()=>{
  const {facade}=make();await facade.onRunCtEstimate({reviewTopics:{records:'yes',periods:'yes',losses:'yes'},ctFacts:{ukResidentConfirmed:true,ringFenceProfits:false,closeInvestmentHoldingCompany:false,associatedCompaniesConfirmedNone:true,qualifyingDistributionsMinor:0,accountsCompleteConfirmed:true,sameTradeContinues:true},lossUseMinorByPeriod:[0],asOfDate:'2026-08-24'});const before=JSON.stringify(facade.getSnapshot().workspace.events),confirmations={noActualSalaryOrDividendInBaseline:true,directorClass1CategoryA:true,directorForFullTaxYear:true,standardTaxCode1257L:true,noOtherEmploymentOrPayeAdjustments:true,employmentAllowanceUnavailableConfirmed:true,useMaximumEligibleCarriedLoss:true,otherShareholderPersonalTaxDataAbsent:true},scenarioInput=[{id:'salary',salaryGrossMinor:100000,dividendTotalMinor:0},{id:'dividend',salaryGrossMinor:0,dividendTotalMinor:100000},{id:'mix',salaryGrossMinor:50000,dividendTotalMinor:50000},{id:'retained',salaryGrossMinor:0,dividendTotalMinor:0}],definitions=facade.driver.scenarioDefinitions({scenarios:scenarioInput}),result=await facade.onRunScenario({asOfDate:'2026-08-24',accountsEvidenceRefs:['local:working-records'],confirmations,scenarios:scenarioInput});assert.deepEqual(definitions[2],scenarioInput[2]);assert.ok(['ok','review_required'].includes(result.status));assert.equal(result.data.nonPosting,true);assert.equal(result.data.results.length,4);assert.ok(result.data.results.some(item=>item.id==='mix'));assert.equal(JSON.stringify(facade.getSnapshot().workspace.events),before);
});

test('actual salary uses exact payroll rules and writes real linked records',async()=>{
  const {facade}=make(),profile=facade.getSnapshot().company.profile,gross=500000,employee=RemunerationRules.calculateEmployeeNi(gross),employer=RemunerationRules.calculateEmployerNi(gross),paye=RemunerationRules.calculatePayeEstimate(gross),result=await facade.onRecordSalary({salary:{id:'salary-record:fable-contract',personId:'person:account-holder',personalTaxJurisdiction:'EWNI',payDate:'2026-08-20',grossSalaryMinor:gross,payeWithheldMinor:paye.payeEstimateMinor,employeeNiMinor:employee.employeeNiMinor,employerNiMinor:employer.employerNiMinor,companyPaymentAccountId:`account-company-bank:${profile.entityId}`,personalPaymentAccountId:`account-personal:${profile.entityId}`,evidenceRefs:['preview:payroll','preview:bank'],directorServicesConfirmed:true,ordinaryRemunerationConfirmed:true,noBenefitsSalarySacrificeOrTerminationPayment:true,payrollResultConfirmed:true,payeRegistrationConfirmed:true,paidWithinNineMonthsConfirmed:true,payeReportingStatus:'reported_rti'}});assert.equal(result.status,'ok');const snapshot=facade.getSnapshot();assert.equal(snapshot.workspace.salaryRecords.length,1);assert.ok(snapshot.workspace.events.some(item=>item.sourceTransaction.companyTransactionType==='director_salary'));
});

test('dividend declaration and payment remain separate actual-book actions',async()=>{
  const {facade}=make(),declared=await facade.onDeclareDividend({dividend:{id:'dividend-record:fable-contract',declarationDate:'2026-08-20',paymentDate:'2026-08-21',totalDividendMinor:100000,confirmedDistributableProfitMinor:100000,independentAccountsConfirmation:true,corporationTaxEstimateOnly:false,distributableProfitEvidenceRefs:['preview:interim-accounts'],boardApprovalEvidenceRef:'preview:board',minutesArtifactRef:'preview:minutes'}});assert.equal(declared.status,'ok');assert.equal(declared.data.record.status,'declared');const paid=await facade.onRecordDividendPayment({declarationId:'dividend-record:fable-contract',voucherArtifactRefs:['preview:voucher:other','preview:voucher:founder']});assert.equal(paid.status,'ok');assert.equal(paid.data.record.status,'paid');assert.equal(paid.data.record.revision,2);assert.equal(paid.data.personalIncomeLink.grossAmountMinor,51000);
});

test('effective-dated ownership change is applied by profile-history engine',async()=>{
  const {facade}=make(),profile=facade.getSnapshot().company.profile,holder=profile.shareholders.find(item=>item.isAccountHolder),other=profile.shareholders.find(item=>!item.isAccountHolder);const result=await facade.onChangeOwnership({effectiveDate:'2026-09-01',shareholders:[{...holder,shares:60},{...other,shares:40}],reason:'Preview contract ownership test',evidenceRefs:['preview:ownership-resolution']});assert.equal(result.status,'ok');const history=facade.getSnapshot().workspace.ownershipHistory;assert.equal(history.length,2);assert.equal(history[0].effectiveTo,'2026-09-01');assert.equal(history[1].effectiveFrom,'2026-09-01');assert.deepEqual(history[1].shareholders.map(item=>item.ownershipBasisPoints),[6000,4000]);
});

test('reset restores the deterministic existing fixture',async()=>{
  const {facade}=make();await facade.onAddIncome({amountMinor:100,date:'2026-08-20',description:'Temporary income',invoicePartyId:'customer:temporary',companyIncomeCategory:'trading',evidenceRefs:['local:temporary']});assert.equal(facade.getSnapshot().workspace.events.length,4);await facade.onResetPreview();const snapshot=facade.getSnapshot();assert.equal(snapshot.workspace.events.length,3);assert.equal(snapshot.businessList.length,5);assert.equal(snapshot.navigation.routes.at(-1).screenId,'home');
});
