'use strict';
const assert=require('node:assert/strict');
const test=require('node:test');
const CompanyBooks=require('../src/core/company-books');
const CompanyTax=require('../src/core/company-tax');
const Ledger=require('../src/core/company-ledger');
const {make}=require('./test-fixture');

const INCOME={ordinaryTradingIncomeConfirmed:true,nonTradingIncome:false,chargeableGain:false};
const EXPENSE={revenueExpenseConfirmed:true,whollyAndExclusivelyBusiness:true,specificallyDisallowed:false,capitalExpense:false};

function setup(){const value=make();value.driver.now=()=>Date.UTC(2027,1,2,12);return value;}
function balances(facade){const snapshot=facade.getSnapshot();return Ledger.reconcile(snapshot.workspace.events,snapshot.company.profile.entityId).balances;}

test('generic correction refuses company-book events without changing either side of the books',async()=>{
  const {facade,driver}=setup();const created=await facade.onCreateSalesInvoice({invoice:{id:'invoice:guard',number:'INV-GUARD',customerName:'Guard customer',issueDate:'2026-08-20',dueDate:'2026-09-20',amountMinor:120000,evidenceRefs:['local:guard-invoice']},taxFacts:INCOME});assert.equal(created.status,'ok');const before=JSON.stringify(driver.state),eventId=created.data.record.recognitionEventId;
  const result=await facade.onCorrectRecord({eventId,reasonCode:'amount_entered_wrong',replacement:{amountMinor:100000}});assert.equal(result.status,'field_error');assert.equal(result.fieldErrors[0].reasonCode,'company_book_specific_correction_required');assert.equal(JSON.stringify(driver.state),before);assert.equal(facade.getSnapshot().workspace.salesInvoices[0].amountMinor,120000);assert.equal(balances(facade).TRADE_RECEIVABLES,120000);
});

test('invoice correction, payment reversal and void keep the record and journal in lockstep',async()=>{
  const {facade,driver}=setup();await facade.onCreateSalesInvoice({invoice:{id:'invoice:lifecycle',number:'INV-LIFE',customerName:'Lifecycle customer',issueDate:'2026-08-20',dueDate:'2026-09-20',amountMinor:120000,evidenceRefs:['local:lifecycle-invoice']},taxFacts:INCOME});await facade.onRecordSalesInvoicePayment({invoiceId:'invoice:lifecycle',payment:{id:'payment:lifecycle',date:'2026-08-22',amountMinor:20000,evidenceRefs:['local:lifecycle-payment']}});
  const correctionRequest={invoiceId:'invoice:lifecycle',correctionId:'invoice-correction:lifecycle',reversalEventId:'invoice-reversal:lifecycle',replacement:{amountMinor:100000},reasonCode:'amount_entered_wrong',evidenceRefs:['local:lifecycle-correction']},corrected=await facade.onCorrectSalesInvoice(correctionRequest);assert.equal(corrected.status,'ok');let record=facade.getSnapshot().workspace.salesInvoices.find(item=>item.id==='invoice:lifecycle');assert.equal(record.amountMinor,100000);assert.equal(record.paidMinor,20000);assert.equal(record.outstandingMinor,80000);assert.equal(record.status,'part_paid');assert.equal(record.correctionHistory.length,1);assert.equal(balances(facade).TRADE_RECEIVABLES,80000);const correctedRetry=await facade.onCorrectSalesInvoice(correctionRequest);assert.equal(correctedRetry.status,'ok');assert.equal(correctedRetry.data.status,'existing');assert.equal(facade.getSnapshot().workspace.salesInvoices.find(item=>item.id==='invoice:lifecycle').correctionHistory.length,1);assert.equal(balances(facade).TRADE_RECEIVABLES,80000);
  const beforeBad=JSON.stringify(driver.state),bad=await facade.onCorrectSalesInvoice({invoiceId:'invoice:lifecycle',replacement:{amountMinor:10000},reasonCode:'wrong_again',evidenceRefs:['local:bad-correction']});assert.equal(bad.status,'field_error');assert.equal(JSON.stringify(driver.state),beforeBad);
  const reverseRequest={recordType:'sales_invoice',recordId:'invoice:lifecycle',paymentId:'payment:lifecycle',reversalEventId:'payment-reversal:lifecycle',reasonCode:'payment_matched_wrong_invoice',evidenceRefs:['local:payment-reversal']},reversed=await facade.onReverseCompanyBookPayment(reverseRequest);assert.equal(reversed.status,'ok');record=facade.getSnapshot().workspace.salesInvoices.find(item=>item.id==='invoice:lifecycle');assert.equal(record.status,'open');assert.equal(record.paidMinor,0);assert.equal(record.outstandingMinor,100000);assert.equal(balances(facade).TRADE_RECEIVABLES,100000);const reverseRetry=await facade.onReverseCompanyBookPayment(reverseRequest);assert.equal(reverseRetry.status,'ok');assert.equal(reverseRetry.data.status,'existing');assert.equal(balances(facade).TRADE_RECEIVABLES,100000);
  const voidRequest={invoiceId:'invoice:lifecycle',reversalEventId:'invoice-void:lifecycle',reasonCode:'invoice_created_in_error',evidenceRefs:['local:invoice-void']},voided=await facade.onVoidSalesInvoice(voidRequest);assert.equal(voided.status,'ok');record=facade.getSnapshot().workspace.salesInvoices.find(item=>item.id==='invoice:lifecycle');assert.equal(record.status,'voided');assert.equal(record.outstandingMinor,0);assert.equal(balances(facade).TRADE_RECEIVABLES,0);const voidRetry=await facade.onVoidSalesInvoice(voidRequest);assert.equal(voidRetry.status,'ok');assert.equal(voidRetry.data.status,'existing');assert.equal(balances(facade).TRADE_RECEIVABLES,0);
});

test('bill and fixed-asset correction lifecycles are atomic and reversible',async()=>{
  const {facade}=setup();await facade.onCreateSupplierBill({bill:{id:'bill:lifecycle',number:'B-LIFE',supplierName:'Lifecycle supplier',billDate:'2026-08-20',dueDate:'2026-09-20',category:'office_costs',amountMinor:30000,evidenceRefs:['local:bill']},taxFacts:EXPENSE});let result=await facade.onCorrectSupplierBill({billId:'bill:lifecycle',correctionId:'bill-correction:lifecycle',replacement:{amountMinor:25000},reasonCode:'amount_entered_wrong',evidenceRefs:['local:bill-correction']});assert.equal(result.status,'ok');assert.equal(facade.getSnapshot().workspace.supplierBills.find(item=>item.id==='bill:lifecycle').outstandingMinor,25000);assert.equal(balances(facade).TRADE_PAYABLES,25000);result=await facade.onVoidSupplierBill({billId:'bill:lifecycle',reasonCode:'duplicate_bill',evidenceRefs:['local:bill-void']});assert.equal(result.status,'ok');assert.equal(balances(facade).TRADE_PAYABLES,0);
  await facade.onRegisterCompanyAsset({asset:{id:'asset:lifecycle',description:'Laptop entered wrong',purchaseDate:'2026-08-20',costMinor:36000,residualValueMinor:0,usefulLifeMonths:36,paymentStatus:'unpaid',evidenceRefs:['local:asset']}});result=await facade.onCorrectCompanyAsset({assetId:'asset:lifecycle',correctionId:'asset-correction:lifecycle',replacement:{description:'Laptop',costMinor:30000},reasonCode:'cost_entered_wrong',evidenceRefs:['local:asset-correction']});assert.equal(result.status,'ok');assert.equal(balances(facade).FIXED_ASSET_COST,30000);result=await facade.onRecordCompanyDepreciation({assetId:'asset:lifecycle'});assert.equal(result.status,'ok');const depreciationId=result.data.record.depreciationEntries[0].id;result=await facade.onReverseCompanyDepreciation({assetId:'asset:lifecycle',depreciationId,reasonCode:'wrong_depreciation_period',evidenceRefs:['local:depreciation-reversal']});assert.equal(result.status,'ok');assert.equal(facade.getSnapshot().workspace.fixedAssets.find(item=>item.id==='asset:lifecycle').depreciationEntries.length,0);result=await facade.onVoidCompanyAsset({assetId:'asset:lifecycle',reasonCode:'asset_belongs_to_owner',evidenceRefs:['local:asset-void']});assert.equal(result.status,'ok');assert.equal(facade.getSnapshot().workspace.fixedAssets.find(item=>item.id==='asset:lifecycle').status,'voided');assert.equal(balances(facade).FIXED_ASSET_COST,0);
  await facade.onRegisterCompanyAsset({asset:{id:'asset:paid-at-purchase',description:'Paid printer',purchaseDate:'2026-08-20',costMinor:20000,residualValueMinor:0,usefulLifeMonths:36,paymentStatus:'paid',evidenceRefs:['local:paid-asset']}});const paidAsset=facade.getSnapshot().workspace.fixedAssets.find(item=>item.id==='asset:paid-at-purchase'),reverseInitial={recordType:'fixed_asset',recordId:paidAsset.id,paymentId:paidAsset.purchaseEventId,reversalEventId:'paid-asset-payment-reversal',reasonCode:'payment_recorded_wrongly',evidenceRefs:['local:paid-asset-reversal']};result=await facade.onReverseCompanyBookPayment(reverseInitial);assert.equal(result.status,'ok');assert.equal(result.data.record.paidAtPurchaseMinor,0);assert.equal(result.data.record.outstandingMinor,20000);assert.equal(balances(facade).TRADE_PAYABLES,20000);result=await facade.onReverseCompanyBookPayment(reverseInitial);assert.equal(result.status,'ok');assert.equal(result.data.status,'existing');assert.equal(balances(facade).TRADE_PAYABLES,20000);
});

test('removing a reconciliation retains an audit tombstone and stops it proving year-end readiness',async()=>{
  const {facade}=setup(),profile=facade.getSnapshot().company.profile;await facade.onCreateSalesInvoice({invoice:{id:'invoice:bank',number:'INV-BANK',customerName:'Bank customer',issueDate:'2026-08-20',dueDate:'2026-09-20',amountMinor:10000,evidenceRefs:['local:bank-invoice']},taxFacts:INCOME});await facade.onRecordSalesInvoicePayment({invoiceId:'invoice:bank',payment:{id:'payment:bank',date:'2026-08-22',amountMinor:10000,evidenceRefs:['local:bank-payment']}});const events=facade.getSnapshot().workspace.events,movements=CompanyBooks.cashMovements(events,profile.entityId,profile.accountingPeriod.startDate,profile.accountingPeriod.endDate),closing=movements.reduce((sum,row)=>sum+row.amountMinor,0),statement={id:'reconciliation:delete',startDate:profile.accountingPeriod.startDate,endDate:profile.accountingPeriod.endDate,openingBalanceMinor:0,closingBalanceMinor:closing,lines:movements.map((row,index)=>({id:'line:'+(index+1),date:row.date,amountMinor:row.amountMinor})),matches:movements.map((row,index)=>({statementLineId:'line:'+(index+1),bookEventId:row.eventId})),evidenceRefs:['local:statement']};assert.equal((await facade.onMatchBankStatement({statement})).status,'ok');const removed=await facade.onDeleteBankReconciliation({reconciliationId:'reconciliation:delete',reasonCode:'wrong_statement',evidenceRefs:['local:statement-removal']});assert.equal(removed.status,'ok');const stored=facade.getSnapshot().workspace.bankReconciliations.find(item=>item.id==='reconciliation:delete');assert.equal(stored.status,'voided');assert.equal(stored.voidReasonCode,'wrong_statement');const year=await facade.onPrepareCompanyYear({});assert.ok(year.data.figures.reasonCodes.includes('year_end_bank_statement_not_reconciled'));
});

test('AIA ceiling is pro-rated and company-year reserves reconcile exactly',()=>{
  assert.equal(CompanyTax.maximumSimpleAiaMinorForPeriod({startDate:'2026-01-01',endDate:'2026-06-30'}),50000000);assert.equal(CompanyTax.maximumSimpleAiaMinorForPeriod({startDate:'2026-01-01',endDate:'2027-01-31'}),Math.floor(100000000*13/12));assert.deepEqual(CompanyTax.capitalAllowanceAccountsPeriodReasons({capitalAllowanceClaims:[{entityId:'company:test',purchaseDate:'2026-01-10',amountMinor:50000001}],period:{startDate:'2026-01-01',endDate:'2026-06-30'}},{entityId:'company:test',accountingPeriod:{startDate:'2026-01-01',endDate:'2026-06-30'}}),['capital_allowance_claim_exceeds_supported_aia_limit']);const {driver}=setup(),figures=driver.companyYearFigures(),sheet=figures.balanceSheet;assert.equal(sheet.profitAndLossReserveMinor,sheet.netAssetsMinor-sheet.shareCapitalMinor);assert.equal(sheet.shareholdersFundsMinor,sheet.shareCapitalMinor+sheet.profitAndLossReserveMinor);
});
