const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {initializeApp,deleteApp}=require('firebase/app');
const {getAuth,connectAuthEmulator,signInAnonymously}=require('firebase/auth');
const {getFunctions,connectFunctionsEmulator,httpsCallable}=require('firebase/functions');
const {doc,getDoc,setDoc}=require('firebase/firestore');
const {getStorage,connectStorageEmulator,ref,uploadBytes,getBytes}=require('firebase/storage');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
let env,app,user,storage,joinPartnership,leavePartnership,deleteAccountData,redeemPromotion;
test.before(async()=>{env=await initializeTestEnvironment({projectId:'demo-taxmate',firestore:{rules:fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8')},storage:{rules:fs.readFileSync(path.join(__dirname,'../../storage.rules'),'utf8')}});app=initializeApp({projectId:'demo-taxmate',apiKey:'emulator-api-key',storageBucket:'demo-taxmate.appspot.com'},'functions-integration');const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});user=(await signInAnonymously(auth)).user;storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',9199);const functions=getFunctions(app,'europe-west2');connectFunctionsEmulator(functions,'127.0.0.1',5001);joinPartnership=httpsCallable(functions,'joinPartnership');leavePartnership=httpsCallable(functions,'leavePartnership');deleteAccountData=httpsCallable(functions,'deleteAccountData');redeemPromotion=httpsCallable(functions,'redeemPromotion');});
test.after(async()=>{if(env)await env.cleanup();if(app)await deleteApp(app);});
async function seed(code,others=[]){await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,`partnerships/${code}`),{createdBy:'seed-owner',bizId:`biz-${code}`,name:`Partnership ${code}`});for(const uid of others)await setDoc(doc(db,`partnerships/${code}/members/${uid}`),{uid,role:'member'});});}
test('callable join validates the parent before granting membership and last-member leave deletes it',async()=>{await seed('JOINCODE');await assert.rejects(()=>joinPartnership({code:'MISSING1'}),/not found/i);const joined=await joinPartnership({code:'JOINCODE'});assert.equal(joined.data.bizId,'biz-JOINCODE');const client=env.authenticatedContext(user.uid).firestore();assert.equal((await getDoc(doc(client,`partnerships/JOINCODE/members/${user.uid}`))).exists(),true);const left=await leavePartnership({code:'JOINCODE'});assert.equal(left.data.partnershipDeleted,true);await env.withSecurityRulesDisabled(async c=>assert.equal((await getDoc(doc(c.firestore(),'partnerships/JOINCODE'))).exists(),false));});
test('callable leave removes only the departing member when another member remains',async()=>{await seed('SHARE123',['remaining']);await joinPartnership({code:'SHARE123'});const left=await leavePartnership({code:'SHARE123'});assert.equal(left.data.partnershipDeleted,false);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();assert.equal((await getDoc(doc(db,'partnerships/SHARE123'))).exists(),true);assert.equal((await getDoc(doc(db,`partnerships/SHARE123/members/${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,'partnerships/SHARE123/members/remaining'))).exists(),true);});});
test('Founder promotion redemption is transactional, canonical and non-enumerable',async()=>{await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'founderPromotions/FOUNDER90'),{code:'FOUNDER90',tier:'pro',durationDays:90,maxRedemptions:1,active:true,redemptionCount:0,createdAt:1});await setDoc(doc(c.firestore(),'founderPromotions/HKGER'),{code:'HKGER',active:false,configurationState:'pending-founder-values',redemptionCount:0,createdAt:1});});const result=await redeemPromotion({code:'founder90'});assert.equal(result.data.tier,'pro');await assert.rejects(()=>redeemPromotion({code:'FOUNDER90'}),/already redeemed/i);await assert.rejects(()=>redeemPromotion({code:'HKGER'}),/not currently redeemable/i);const client=env.authenticatedContext(user.uid).firestore();await assert.rejects(()=>getDoc(doc(client,'founderPromotions/FOUNDER90')));await env.withSecurityRulesDisabled(async c=>{const db=c.firestore(),entitlement=(await getDoc(doc(db,`users/${user.uid}/entitlements/current`))).data(),promotion=(await getDoc(doc(db,'founderPromotions/FOUNDER90'))).data();assert.equal(entitlement.promotions.FOUNDER90.tier,'pro');assert.equal(promotion.redemptionCount,1);});});
test('authenticated account deletion removes personal cloud, receipt, promotion and membership data',async()=>{await seed('DELKEEP1',['remaining',user.uid]);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,`users/${user.uid}/entries/delete-me`),{id:'delete-me',createdAt:1,updatedAt:1,deletedAt:null,deviceId:'d',schemaVersion:5});await setDoc(doc(db,`promotionRedemptions/promo_${user.uid}`),{uid:user.uid});});const receipt=ref(storage,`receipts/${user.uid}/delete.jpg`);await uploadBytes(receipt,new Uint8Array([255,216,255,217]),{contentType:'image/jpeg'});const result=await deleteAccountData({});assert.equal(result.data.deleted,true);assert.equal(result.data.partnershipRecordsRetained,1);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();assert.equal((await getDoc(doc(db,`users/${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,`promotionRedemptions/promo_${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,'partnerships/DELKEEP1'))).exists(),true);assert.equal((await getDoc(doc(db,`partnerships/DELKEEP1/members/${user.uid}`))).exists(),false);});await assert.rejects(()=>getBytes(receipt));});
