const nodeTest=require('node:test');const emulatorReady=!!(process.env.FIRESTORE_EMULATOR_HOST&&process.env.FIREBASE_AUTH_EMULATOR_HOST&&process.env.FIREBASE_STORAGE_EMULATOR_HOST);const test=emulatorReady?nodeTest:nodeTest.skip;const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {initializeApp,deleteApp}=require('firebase/app');
const {getAuth,connectAuthEmulator,signInAnonymously}=require('firebase/auth');
const {getFunctions,connectFunctionsEmulator,httpsCallable}=require('firebase/functions');
const {doc,getDoc,setDoc}=require('firebase/firestore');
const {getStorage,connectStorageEmulator,ref,uploadBytes,getBytes}=require('firebase/storage');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
let env,app,user,storage,createPartnership,joinPartnership,leavePartnership,deleteAccountData,redeemPromotion,createCheckoutSession,lookupCompaniesHouse,claimActiveLtdCompany;
if(emulatorReady)nodeTest.before(async()=>{env=await initializeTestEnvironment({projectId:'demo-taxmate',firestore:{rules:fs.readFileSync(path.join(__dirname,'../../firestore.rules'),'utf8')},storage:{rules:fs.readFileSync(path.join(__dirname,'../../storage.rules'),'utf8')}});app=initializeApp({projectId:'demo-taxmate',apiKey:'emulator-api-key',storageBucket:'demo-taxmate.appspot.com'},'functions-integration');const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});user=(await signInAnonymously(auth)).user;storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',9199);const functions=getFunctions(app,'europe-west2');connectFunctionsEmulator(functions,'127.0.0.1',5001);createPartnership=httpsCallable(functions,'createPartnership');joinPartnership=httpsCallable(functions,'joinPartnership');leavePartnership=httpsCallable(functions,'leavePartnership');deleteAccountData=httpsCallable(functions,'deleteAccountData');redeemPromotion=httpsCallable(functions,'redeemPromotion');createCheckoutSession=httpsCallable(functions,'createCheckoutSession');lookupCompaniesHouse=httpsCallable(functions,'lookupCompaniesHouse');claimActiveLtdCompany=httpsCallable(functions,'claimActiveLtdCompany');});
nodeTest.after(async()=>{if(env)await env.cleanup();if(app)await deleteApp(app);});
async function seed(code,others=[]){await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,`partnerships/${code}`),{createdBy:'seed-owner',bizId:`biz-${code}`,name:`Partnership ${code}`});for(const uid of others)await setDoc(doc(db,`partnerships/${code}/members/${uid}`),{uid,role:'member'});});}
async function seedTier(tier,status='active'){await env.withSecurityRulesDisabled(async c=>setDoc(doc(c.firestore(),`users/${user.uid}/entitlements/current`),{paidTier:tier,subscriptionStatus:status,currentPeriodEnd:Date.now()+86400000}));}
test('trusted one-Ltd claim is Pro-only, idempotent and race-safe for two clean clients',async()=>{await seedTier('plus');await assert.rejects(()=>claimActiveLtdCompany({companyId:'company:first'}),/Pro access required/i);await seedTier('pro');const race=await Promise.allSettled([claimActiveLtdCompany({companyId:'company:first'}),claimActiveLtdCompany({companyId:'company:second'})]);assert.equal(race.filter(result=>result.status==='fulfilled').length,1);assert.equal(race.filter(result=>result.status==='rejected').length,1);const winner=race.find(result=>result.status==='fulfilled').value.data.activeCompanyId,retry=await claimActiveLtdCompany({companyId:winner});assert.equal(retry.data.status,'existing');assert.equal(retry.data.idempotent,true);await env.withSecurityRulesDisabled(async c=>{const anchor=(await getDoc(doc(c.firestore(),`users/${user.uid}/ltdControl/activeCompany`))).data();assert.equal(anchor.activeCompanyId,winner);assert.equal(anchor.status,'active_slot_claimed');assert.equal(anchor.releasePolicy,'founder_approval_required');});});
test('Companies House callable requires authentication, Pro and a valid identifier before provider access',async()=>{await assert.rejects(()=>lookupCompaniesHouse({companyNumber:'bad'}),/Invalid company number/i);await seedTier('plus');await assert.rejects(()=>lookupCompaniesHouse({companyNumber:'00000000'}),/Pro access required/i);await seedTier('free','inactive');const guestApp=initializeApp({projectId:'demo-taxmate',apiKey:'emulator-api-key'},'companies-house-guest'),guestFunctions=getFunctions(guestApp,'europe-west2');connectFunctionsEmulator(guestFunctions,'127.0.0.1',5001);await assert.rejects(()=>httpsCallable(guestFunctions,'lookupCompaniesHouse')({companyNumber:'00000000'}),/Sign in required/i);await deleteApp(guestApp);});
test('callable join requires Pro, validates the parent and last-member leave deletes it',async()=>{await seed('JOINCODE');await assert.rejects(()=>joinPartnership({code:'JOINCODE'}),/Pro access required/i);await seedTier('pro');await assert.rejects(()=>joinPartnership({code:'MISSING1'}),/not found/i);const joined=await joinPartnership({code:'JOINCODE'});assert.equal(joined.data.bizId,'biz-JOINCODE');const client=env.authenticatedContext(user.uid).firestore();assert.equal((await getDoc(doc(client,`partnerships/JOINCODE/members/${user.uid}`))).exists(),true);const left=await leavePartnership({code:'JOINCODE'});assert.equal(left.data.partnershipDeleted,true);await env.withSecurityRulesDisabled(async c=>assert.equal((await getDoc(doc(c.firestore(),'partnerships/JOINCODE'))).exists(),false));});
test('callable creates partnership and owner membership durably for Pro only',async()=>{const created=await createPartnership({code:'OWNR1234',bizId:'biz-owner',name:'Owner partnership'});assert.equal(created.data.code,'OWNR1234');await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();assert.equal((await getDoc(doc(db,'partnerships/OWNR1234'))).data().createdBy,user.uid);assert.equal((await getDoc(doc(db,`partnerships/OWNR1234/members/${user.uid}`))).data().role,'owner');});await assert.rejects(()=>createPartnership({code:'OWNR1234',bizId:'biz-owner-2',name:'Duplicate'}),/already exists/i);});
test('callable leave removes only the departing member when another member remains',async()=>{await seed('SHARE123',['remaining']);await joinPartnership({code:'SHARE123'});const left=await leavePartnership({code:'SHARE123'});assert.equal(left.data.partnershipDeleted,false);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();assert.equal((await getDoc(doc(db,'partnerships/SHARE123'))).exists(),true);assert.equal((await getDoc(doc(db,`partnerships/SHARE123/members/${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,'partnerships/SHARE123/members/remaining'))).exists(),true);});});
test('Founder promotion redemption is transactional, canonical and non-enumerable',async()=>{await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'founderPromotions/FOUNDER90'),{code:'FOUNDER90',tier:'pro',startsAt:Date.now()-1000,durationDays:90,maxRedemptions:1,active:true,redemptionCount:0,createdAt:1});await setDoc(doc(c.firestore(),'founderPromotions/HKGER'),{code:'HKGER',active:false,configurationState:'pending-founder-values',redemptionCount:0,createdAt:1});});const result=await redeemPromotion({code:'founder90'});assert.equal(result.data.tier,'pro');await assert.rejects(()=>redeemPromotion({code:'FOUNDER90'}),/already redeemed/i);await assert.rejects(()=>redeemPromotion({code:'HKGER'}),/Promotion code not found/i);const client=env.authenticatedContext(user.uid).firestore();await assert.rejects(()=>getDoc(doc(client,'founderPromotions/FOUNDER90')));await env.withSecurityRulesDisabled(async c=>{const db=c.firestore(),entitlement=(await getDoc(doc(db,`users/${user.uid}/entitlements/current`))).data(),promotion=(await getDoc(doc(db,'founderPromotions/FOUNDER90'))).data();assert.equal(entitlement.promotions.FOUNDER90.tier,'pro');assert.equal(entitlement.promotionAccess.proExpiresAt> Date.now(),true);assert.equal(entitlement.promotionAccess.plusExpiresAt,entitlement.promotionAccess.proExpiresAt);assert.equal(promotion.redemptionCount,1);});});
test('fixed, permanent and concurrent-final-slot Founder promo rules are enforced',async()=>{
  const now=Date.now(),fixedExpiry=now+10*86400000;
  await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await Promise.all([
    setDoc(doc(db,'founderPromotions/BEFORESTART'),{code:'BEFORESTART',tier:'pro',startsAt:now+86400000,expiresAt:fixedExpiry,maxRedemptions:2,active:true,redemptionCount:0}),
    setDoc(doc(db,'founderPromotions/ALREADYEXPIRED'),{code:'ALREADYEXPIRED',tier:'plus',startsAt:now-2000,expiresAt:now-1,maxRedemptions:2,active:true,redemptionCount:0}),
    setDoc(doc(db,'founderPromotions/FIXEDEND'),{code:'FIXEDEND',tier:'plus',startsAt:now-1000,expiresAt:fixedExpiry,maxRedemptions:2,active:true,redemptionCount:0}),
    setDoc(doc(db,'founderPromotions/PERMANENTPRO'),{code:'PERMANENTPRO',tier:'pro',startsAt:now-1000,permanent:true,maxRedemptions:3,active:true,redemptionCount:0}),
    setDoc(doc(db,'founderPromotions/FINALONE'),{code:'FINALONE',tier:'pro',startsAt:now-1000,expiresAt:fixedExpiry,maxRedemptions:1,active:true,redemptionCount:0})
  ]);});
  await assert.rejects(()=>redeemPromotion({code:'BEFORESTART'}),/not available yet/i);await assert.rejects(()=>redeemPromotion({code:'ALREADYEXPIRED'}),/has ended/i);
  const fixed=await redeemPromotion({code:'FIXEDEND'});assert.equal(fixed.data.expiresAt,fixedExpiry);
  const permanent=await redeemPromotion({code:'PERMANENTPRO'});assert.equal(permanent.data.expiresAt,null);assert.equal(permanent.data.message,'Permanent Pro access unlocked.');
  await env.withSecurityRulesDisabled(async c=>{const entitlement=(await getDoc(doc(c.firestore(),`users/${user.uid}/entitlements/current`))).data();assert.equal(entitlement.promotionAccess.proPermanent,true);assert.equal(entitlement.promotionAccess.plusPermanent,true);});
  await assert.rejects(()=>createCheckoutSession({tier:'plus',cadence:'monthly'}),/already have permanent Pro access/i);
  async function concurrentClient(name){const clientApp=initializeApp({projectId:'demo-taxmate',apiKey:'emulator-api-key'},name),clientAuth=getAuth(clientApp);connectAuthEmulator(clientAuth,'http://127.0.0.1:9099',{disableWarnings:true});await signInAnonymously(clientAuth);const clientFunctions=getFunctions(clientApp,'europe-west2');connectFunctionsEmulator(clientFunctions,'127.0.0.1',5001);return{clientApp,redeem:httpsCallable(clientFunctions,'redeemPromotion')};}
  const first=await concurrentClient('promo-final-one-a'),second=await concurrentClient('promo-final-one-b');const results=await Promise.allSettled([first.redeem({code:'FINALONE'}),second.redeem({code:'FINALONE'})]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.filter(result=>result.status==='rejected').length,1);await deleteApp(first.clientApp);await deleteApp(second.clientApp);
  await env.withSecurityRulesDisabled(async c=>assert.equal((await getDoc(doc(c.firestore(),'founderPromotions/FINALONE'))).data().redemptionCount,1));
});
test('authenticated account deletion removes personal cloud, receipt, promotion and membership data',async()=>{await seed('DELKEEP1',['remaining',user.uid]);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,`users/${user.uid}/entries/delete-me`),{id:'delete-me',createdAt:1,updatedAt:1,deletedAt:null,deviceId:'d',schemaVersion:5});await setDoc(doc(db,`promotionRedemptions/promo_${user.uid}`),{uid:user.uid});});const receipt=ref(storage,`receipts/${user.uid}/delete.jpg`);await uploadBytes(receipt,new Uint8Array([255,216,255,217]),{contentType:'image/jpeg'});const result=await deleteAccountData({});assert.equal(result.data.deleted,true);assert.equal(result.data.partnershipRecordsRetained,1);await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();assert.equal((await getDoc(doc(db,`users/${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,`promotionRedemptions/promo_${user.uid}`))).exists(),false);assert.equal((await getDoc(doc(db,'partnerships/DELKEEP1'))).exists(),true);assert.equal((await getDoc(doc(db,`partnerships/DELKEEP1/members/${user.uid}`))).exists(),false);});await assert.rejects(()=>getBytes(receipt));});
