'use strict';
// Presentation only. Billing records never enter bookkeeping state or backups.
let BILLING_UI={uid:null,generation:0,view:'overview',loading:false,busy:false,error:null,payments:[],cases:[],subscriptions:[],changes:[],claims:{},hasMore:false,cursor:null,staffCases:[],staffCase:null,quote:null};
function bt(key,vars){let value=window.TaxMateBillingCopy[S.settings.lang]?.[key]||window.TaxMateBillingCopy.en[key]||key;for(const [name,text]of Object.entries(vars||{}))value=value.split('{'+name+'}').join(text);return value;}
function billingResetState(){const generation=BILLING_UI.generation+1;BILLING_UI={uid:null,generation,view:'overview',loading:false,busy:false,error:null,payments:[],cases:[],subscriptions:[],changes:[],claims:{},hasMore:false,cursor:null,staffCases:[],staffCase:null,quote:null};for(const id of ['refund','billing']){const el=document.getElementById('sb-'+id);if(el){el.classList.remove('open');const body=el.querySelector('[data-billing-body]');if(body)body.replaceChildren();}}if(!document.querySelector('.sb.open'))document.body.classList.remove('sheet-open');}
function billingMoney(value,currency='gbp'){return new Intl.NumberFormat(locale(),{style:'currency',currency:currency.toUpperCase()}).format(Number(value||0)/100);}
function billingDate(value){return Number(value)>0?new Date(Number(value)).toLocaleString(locale(),{dateStyle:'medium',timeStyle:'short'}):'—';}
function billingButton(label,action,primary=false){return `<button class="btn${primary?'':' ghost'}" data-tm-click="${esc(action)}" ${BILLING_UI.busy?'disabled':''}>${esc(label)}</button>`;}
function billingRow(label,action,detail='',money=null){return `<button class="row noicon" data-tm-click="${esc(action)}"><span class="grow"><span class="t">${esc(label)}</span>${detail?`<span class="small">${esc(detail)}</span>`:''}</span>${money?billingMoneySpan(money.minor,money.currency,money.role):''}<span aria-hidden="true">›</span></button>`;}
function billingKv(label,value){return `<div class="review01-billing-kv"><span class="small">${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function billingMoneySpan(minor,currency,role){return `<span class="num ${moneyCls(minor,role)}" data-billing-money="${esc(role)}" data-minor="${minor}">${esc(billingMoney(minor,currency))}</span>`;}
function billingMoneyKv(label,minor,currency,role,date=null){return `<div class="review01-billing-kv"><span class="small">${esc(label)}</span><strong>${date?`<span class="small">${esc(billingDate(date))}</span> · `:''}${billingMoneySpan(minor,currency,role)}</strong></div>`;}
function billingDataDetails(){return `<details class="card" data-billing-data-details><summary>${esc(bt('dataDetails'))}</summary>${retentionStatusCard()}</details>`;}
function billingRefundImpact(c){
  const x=c.refundImpact;if(!x)return'';
  if(!['conditional','confirmed'].includes(x.basis)||!x.afterTier||!x.retention)return `<p data-refund-result-checking>${esc(bt('refundImpactChecking'))}</p>`;
  const confirmed=x.basis==='confirmed';
  return `<div data-customer-refund-impact data-basis="${x.basis}">${!confirmed?`<p>${esc(bt(x.changesAccess?'accessChanges':'noAccessChange'))}</p>`:''}${billingKv(bt(confirmed?'refundResult':'afterRefund'),t('tier.'+x.afterTier))}<details class="card" data-billing-data-details><summary>${esc(bt('dataDetails'))}</summary>${!confirmed?`<p class="small">${esc(bt('conditionalPreview'))}</p>`:''}${billingKv(bt('checkedAt'),billingDate(x.observedAt))}<p data-refund-retention>${esc(billingStaffRetention(x.retention))}</p><p class="small">${esc(t('ret.duty'))}</p></details></div>`;
}
function billingError(error){return error?.reason==='review_context_changed'?bt('contextChanged'):error?.reason==='review_context_incomplete'?bt('contextIncomplete'):error?.reason==='review_impact_required'?bt('previewRequired'):error?.reason==='consumer_disclosures_not_verified'?bt('notReady'):error?.reason==='checkout_already_open'?bt('offerResume'):/quote_|subscription_change|multiple_subscriptions|refunded_time|unpaid_time|price_alignment|checkout_offer/.test(error?.reason||'')?bt('reviewNeeded'):error?.reason==='money_operations_not_enabled'?bt('disabledMoney'):bt('unavailable');}
function billingRender(){if(BILLING_VIEW&&S.tab==='more')render();}
async function billingFetch(name,data={}){const uid=cloudUser()?.uid,generation=BILLING_UI.generation;if(!uid||uid!==BILLING_UI.uid)throw new Error('billing-account-changed');const result=await callSecureFunction(name,data);if(cloudUser()?.uid!==uid||generation!==BILLING_UI.generation)throw new Error('billing-account-changed');return result;}
function billingRefresh(){if(BILLING_UI.loading)return BILLING_UI.loadPromise;const promise=billingLoad();BILLING_UI.loadPromise=promise;return promise;}
async function billingLoad(){
  const user=cloudUser();if(!user)return;
  if(BILLING_UI.uid!==user.uid){billingResetState();BILLING_UI.uid=user.uid;}
  const generation=BILLING_UI.generation;BILLING_UI.loading=true;BILLING_UI.error=null;billingRender();
  try{
    const [history,cases,status,token]=await Promise.all([billingFetch('getBillingHistory'),billingFetch('getRefundCases'),billingFetch('getSubscriptionStatus'),user.getIdTokenResult()]);
    if(generation!==BILLING_UI.generation||cloudUser()?.uid!==user.uid)return;
    Object.assign(BILLING_UI,{payments:history.payments,hasMore:history.hasMore,cursor:history.cursor,cases:cases.cases,subscriptions:status.subscriptions,changes:status.changes,moneyEnabled:status.moneyOperationsEnabled,claims:token.claims});
    await loadEntitlementFromCloud(user.uid);
  }catch(error){if(generation===BILLING_UI.generation)BILLING_UI.error=billingError(error);}
  finally{if(generation===BILLING_UI.generation){BILLING_UI.loading=false;billingRender();}}
}
function openBillingOverview(){if(!requireLoginForTier())return;S.tab='more';BILLING_VIEW=true;BILLING_UI.view='overview';save();render();window.scrollTo(0,0);billingRefresh();}
function billingScreen(view){BILLING_UI.view=view;billingRender();window.scrollTo(0,0);if(!BILLING_UI.uid)billingRefresh();}
function openBillingPlans(){if(!BILLING_VIEW)openBillingOverview();billingScreen('plans');}
function openRefundStatus(){if(!BILLING_VIEW)openBillingOverview();billingScreen('cases');}
async function billingMore(){if(BILLING_UI.busy||!BILLING_UI.hasMore)return;await billingOperation(async()=>{const data=await billingFetch('getBillingHistory',{cursor:BILLING_UI.cursor});BILLING_UI.payments.push(...data.payments);BILLING_UI.hasMore=data.hasMore;BILLING_UI.cursor=data.cursor;},false);}
async function billingOperation(run,refresh=true){
  if(BILLING_UI.busy)return;const generation=BILLING_UI.generation;BILLING_UI.busy=true;BILLING_UI.error=null;billingRender();document.querySelectorAll('#sb-refund button,#sb-billing button').forEach(b=>b.disabled=true);
  try{await run();if(refresh&&generation===BILLING_UI.generation)await billingRefresh();}
  catch(error){if(generation===BILLING_UI.generation){BILLING_UI.error=billingError(error);const target=document.querySelector('.sb.open [data-billing-error]');if(target)target.textContent=BILLING_UI.error;}}
  finally{if(generation===BILLING_UI.generation){BILLING_UI.busy=false;billingRender();document.querySelectorAll('#sb-refund button,#sb-billing button').forEach(b=>b.disabled=false);}}
}
function billingSheet(title,body,id='billing'){const root=document.getElementById('sb-'+id);root.querySelector('[data-billing-title]').textContent=title;root.querySelector('[data-billing-body]').innerHTML=body+'<p class="ferr" data-billing-error role="status"></p>';openSheet(id);}
function pageBilling(){
  const access=TaxMateEntitlement.resolve(ENTITLEMENT.snapshot,Date.now(),!navigator.onLine),ui=BILLING_UI,view=ui.view;
  const title={overview:t('review01.billing'),history:bt('history'),cases:t('review01.refundStatus'),plans:bt('plans'),staff:bt('support'),'staff-case':bt('caseDetails')}[view];
  let body='';
  if(view==='overview')body=`<div class="card"><div class="small">${t('review01.currentPlan')}</div><h2>${t('tier.'+access.tier)}</h2><p class="small">${esc(bt('fundedNote'))}</p></div><div class="review01-rows" data-billing-overview>${billingRow(bt('plans'),"openBillingPlans()")}${billingRow(bt('history'),"billingScreen('history')")}${billingRow(bt('purchaseRecords'),"billingPurchases()")}${billingRow(t('review01.cancelRenewal'),"billingScreen('plans')")}${billingRow(t('review01.refund'),"openRefundRequest()")}${billingRow(t('review01.refundStatus'),"openRefundStatus()")}${billingRow(bt('paymentMethod'),"billingPaymentMethod()")}${ui.claims.billingSupport?billingRow(bt('support'),"billingStaffOpen()"):''}</div>`;
  if(view==='history')body=`<div class="review01-rows">${ui.payments.map(p=>billingRow(bt(p.status),`billingPayment('${p.id}')`,billingDate(p.createdAt),{minor:p.amountMinor,currency:p.currency,role:'out'})).join('')}</div>${!ui.loading&&!ui.payments.length?`<p class="small">${esc(bt('emptyPayments'))}</p>`:''}${ui.hasMore?billingButton(bt('more'),'billingMore()'):''}`;
  if(view==='cases')body=`<div class="review01-rows">${ui.cases.map(c=>billingRow(bt(c.state),`billingCase('${c.id}')`,billingDate(c.createdAt),{minor:c.approvedMinor??c.payment.amountMinor,currency:c.currency,role:c.approvedMinor!==undefined?'in':'out'})).join('')}</div>${!ui.loading&&!ui.cases.length?`<p class="small">${esc(bt('emptyCases'))}</p>`:''}`;
  if(view==='plans')body=billingPlansPage();
  if(view==='staff')body=`<div class="review01-rows">${ui.staffCases.map(c=>billingRow(bt(c.state),`billingStaffRead('${c.id}')`,c.id,{minor:c.payment.amountMinor,currency:c.currency,role:'out'})).join('')}</div>${ui.staffHasMore?billingButton(bt('more'),'billingStaffMore()'):''}`;
  if(view==='staff-case')body=billingStaffPage();
  return `<section data-billing-page><h1 class="h1 review01-page-title">${esc(title)}</h1><button class="link review01-back" data-tm-click="${view==='overview'?"go('more')":"billingScreen('overview')"}">‹ ${t('review01.back')}</button>${ui.loading?`<p role="status">${esc(bt('loading'))}</p>`:''}${ui.error?`<div class="notice amber" role="status">${esc(ui.error)}</div>`:''}${body}${billingButton(bt('refresh'),view==='staff-case'&&ui.staffCase?`billingStaffRead('${ui.staffCase.case.id}')`:'billingRefresh()')}<p class="small"><button class="link" data-tm-click="openLegal('terms')">${esc(bt('terms'))}</button></p></section>`;
}
function billingPlansPage(){const ui=BILLING_UI;return ui.subscriptions.map(s=>`<div class="card"><h2>${t('tier.'+s.tier)}</h2><p>${esc(s.paidUntil>Date.now()?bt('currentUntil',{date:billingDate(s.paidUntil)}):bt('noFundedAccess'))}</p>${s.nextRenewal?billingKv(bt('plans'),t('tier.'+s.nextRenewal.tier))+billingMoneyKv(bt('nextRenewal'),s.nextRenewal.basePriceMinor,s.nextRenewal.currency,'out',s.nextRenewal.at)+`<p class="small">${esc(bt('renewalEstimate'))}</p>`:''}<p class="small">${esc(bt('providerStatus'))}: ${esc(bt(s.status))}${s.cancelAtPeriodEnd?' · '+esc(bt('noRenewal')):''}</p>${['past_due','unpaid','incomplete'].includes(s.status)?`<div class="notice amber">${esc(bt('paymentIssue'))}<p>${esc(bt('fundedNote'))}</p>${billingButton(bt('paymentMethod'),'billingPaymentMethod()')}</div>`:''}${!s.cancelAtPeriodEnd&&!s.pendingUpdate&&!s.scheduleId?billingButton(t('tier.'+(s.tier==='pro'?'plus':'pro')),`billingQuote('${s.id}','${s.tier==='pro'?'plus':'pro'}')`):''}${!s.cancelAtPeriodEnd?billingButton(bt('cancelConfirm'),`billingCancel('${s.id}')`):''}</div>`).join('')+(!ui.loading&&!ui.subscriptions.length?`<p class="small">${t('review01.noPaidSubscription')}</p>${billingButton('Plus',"billingStartPurchase('plus')")}${billingButton('Pro',"billingStartPurchase('pro')")}`:'')+(ui.changes.length?`<h2>${esc(bt('changes'))}</h2><div class="review01-rows">${ui.changes.map(q=>billingRow(bt(q.state)+' · '+t('tier.'+q.tier),`billingChange('${q.id}')`,billingDate(q.effectiveAt))).join('')}</div>`:'');}
function billingPayment(id){const p=BILLING_UI.payments.find(p=>p.id===id);if(!p)return;billingSheet(bt('history'),billingMoneyKv(bt('paidAmount'),p.amountMinor,p.currency,'out')+billingMoneyKv(bt('refundedAmount'),p.refundedMinor,p.currency,'in')+billingMoneyKv(bt('pendingAmount'),p.pendingRefundMinor,p.currency,'in')+`<p>${esc(bt(p.status))}</p>${p.receiptUrl?`<a class="btn ghost" target="_blank" rel="noopener noreferrer" href="${esc(p.receiptUrl)}">${esc(bt('receipt'))}</a>`:''}`+(p.paid?billingButton(bt('request'),`billingRefundFor('${id}')`):''));}
function billingRefundFor(id){closeSheet('billing');openRefundRequest(id);}
async function openRefundRequest(id){if(!BILLING_VIEW)openBillingOverview();if(!BILLING_UI.uid||BILLING_UI.loading){await billingRefresh();if(!BILLING_UI.uid)return;}BILLING_UI.refundRequestId=crypto.randomUUID();const payments=BILLING_UI.payments.filter(p=>p.paid);billingSheet(bt('request'),`<p class="small">${esc(bt('submittedNote'))}</p><label class="flabel" for="refund-payment">${esc(bt('selectPayment'))}</label><select id="refund-payment" data-tm-change="billingRefundSelected()"><option value="">—</option>${payments.map(p=>`<option value="${esc(p.id)}" ${p.id===id?'selected':''}>${esc(billingDate(p.createdAt)+' · '+p.id.slice(-6))}</option>`).join('')}</select><div id="refund-selected-amount"></div><label class="flabel" for="refund-reason">${t('review01.reason')}</label><select id="refund-reason">${['cancel_service','payment_question','service_problem','other'].map(r=>`<option value="${r}">${esc(bt(r))}</option>`).join('')}</select><label class="flabel" for="refund-extra">${t('review01.extra')}</label><textarea id="refund-extra" maxlength="2000"></textarea><p class="small">${esc(bt('noteHint'))}</p>${billingButton(bt('submit'),'billingSubmitRefund()',true)}`,'refund');billingRefundSelected();}
function billingRefundSelected(){const p=BILLING_UI.payments.find(p=>p.id===document.getElementById('refund-payment')?.value),target=document.getElementById('refund-selected-amount');if(target)target.innerHTML=p?billingMoneyKv(bt('paidAmount'),p.amountMinor,p.currency,'out'):'';}
function billingSubmitRefund(){const data={requestId:BILLING_UI.refundRequestId,paymentId:document.getElementById('refund-payment').value,reason:document.getElementById('refund-reason').value,note:document.getElementById('refund-extra').value};if(!data.paymentId){document.querySelector('#sb-refund [data-billing-error]').textContent=bt('selectPayment');return;}billingOperation(async()=>{const result=await billingFetch('submitRefundRequest',data);closeSheet('refund');BILLING_UI.cases=[result.case,...BILLING_UI.cases.filter(c=>c.id!==result.case.id)];BILLING_UI.view='cases';showNotice(bt('request'),bt('submittedNote'));});}
function billingCase(id){const c=BILLING_UI.cases.find(c=>c.id===id);if(!c)return;billingSheet(bt('caseDetails'),`<p>${esc(bt(c.state))}</p>${billingMoneyKv(bt('paidAmount'),c.payment.amountMinor,c.currency,'out')}${c.approvedMinor!==undefined?billingMoneyKv(bt('refundAmount'),c.approvedMinor,c.currency,'in'):''}<p>${esc(c.publicReason||'')}</p>${billingRefundImpact(c)}${c.renewalAction?`<p>${esc(bt(c.renewalAction==='stop_at_period_end'?'stopRenewal':'unchanged'))}${c.renewalAction==='stop_at_period_end'?' · '+esc(bt(c.renewalState==='not_requested'?'approved':c.renewalState)):''}</p>`:''}${c.state==='needs_information'?`<label class="flabel" for="billing-reply">${esc(bt('reply'))}</label><textarea id="billing-reply" maxlength="2000"></textarea>${billingButton(bt('reply'),`billingReply('${id}')`,true)}`:''}${billingButton(bt('download'),`billingDownloadCase('${id}')`)}`);}
function billingReply(id){const note=document.getElementById('billing-reply').value.trim();if(!note)return;billingOperation(async()=>{await billingFetch('replyRefundRequest',{caseId:id,note});closeSheet('billing');});}
function billingDownloadCase(id){const record=BILLING_UI.cases.find(c=>c.id===id);if(record)billingDownload('TaxMate-refund-'+id+'.json',{...record,notice:bt('submittedNote')});}
function billingDownload(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function billingPaymentMethod(){if(!requireLoginForTier())return;startBillingAction('createBillingPortal',{});}
function billingQuote(id,tier){billingOperation(async()=>{const r=await billingFetch('previewPlanChange',{subscriptionId:id,tier});BILLING_UI.quote=r.quote;billingShowQuote(r.quote,true);},false);}
function billingShowQuote(q,confirm=false){billingSheet(bt('plans'),`<h3>${t('tier.'+q.fromTier)} → ${t('tier.'+q.tier)}</h3>${billingMoneyKv(bt('dueNow'),q.dueNowMinor,q.currency,'out')}${billingMoneyKv(bt('credit'),q.creditMinor,q.currency,'in')}${billingMoneyKv(bt('charge'),q.chargeMinor,q.currency,'out')}${billingKv(bt('effective'),billingDate(q.effectiveAt))}${billingMoneyKv(bt('nextPayment'),q.nextPriceMinor,q.currency,'out',q.nextPaymentAt)}<p>${esc(bt(q.direction==='upgrade'?'upgradeNote':'scheduledNote'))}</p>${q.state!=='quoted'?`<p>${esc(bt(q.state))}</p>`:''}${q.invoiceUrl?`<a class="btn" href="${esc(q.invoiceUrl)}" target="_blank" rel="noopener noreferrer">${esc(bt('continuePayment'))}</a>`:''}${confirm?billingButton(bt('confirmChange'),`billingConfirmQuote('${q.id}')`,true):''}`);}
function billingChange(id){const q=BILLING_UI.changes.find(q=>q.id===id);if(q)billingShowQuote(q);}
function billingConfirmQuote(id){billingOperation(async()=>{const r=await billingFetch('confirmPlanChange',{quoteId:id});closeSheet('billing');BILLING_UI.quote=r.quote;BILLING_UI.view='plans';});}
function billingCancel(id){const sub=BILLING_UI.subscriptions.find(s=>s.id===id);if(!sub)return;const losesPaid=sub.paidUntil>Date.now()&&TaxMateEntitlement.resolve(ENTITLEMENT.snapshot,sub.paidUntil+1,false).tier==='free';billingSheet(bt('cancelConfirm'),`<p>${esc(bt('currentUntil',{date:billingDate(sub.paidUntil)}))}</p>${losesPaid?`<p class="small">${esc(bt('cancelDataHint'))}</p>`:''}${billingButton(bt('cancelConfirm'),`billingConfirmCancel('${id}')`,true)}${billingDataDetails()}`);}
function billingConfirmCancel(id){billingOperation(async()=>{await billingFetch('cancelSubscriptionRenewal',{subscriptionId:id});closeSheet('billing');BILLING_UI.view='plans';});}
async function billingStaffOpen(){await billingOperation(async()=>{const r=await billingFetch('getBillingSupportCases');BILLING_UI.staffCases=r.cases;BILLING_UI.staffHasMore=r.hasMore;BILLING_UI.staffCursor=r.cursor;BILLING_UI.view='staff';},false);}
async function billingStaffRead(id){await billingOperation(async()=>{BILLING_UI.staffCase=await billingFetch('getBillingSupportCase',{caseId:id});BILLING_UI.staffDraft=null;BILLING_UI.staffPreviewConfirmed=false;BILLING_UI.view='staff-case';},false);}
function billingStaffRetention(r){return bt(r.status==='paid'?'retentionPaid':r.status==='retained'?'retentionRetained':r.status==='expired'?'retentionExpired':'retentionUnknown',{date:retentionDateLabel(r.retainThroughDate),deleteOn:retentionDateLabel(r.deleteOnDate)});}
function billingStaffAccess(value,label){if(!value)return'';return `<div data-staff-access><h3>${esc(label)} · ${esc(t('tier.'+value.tier))}</h3><p>${esc(billingStaffRetention(value.retention))}</p><details><summary>${esc(bt('grantDetails'))}</summary>${value.grants.map(g=>billingKv(t('tier.'+g.tier),billingDate(g.until))+`<p class="small review01-billing-id">${esc(g.id)} · ${esc(g.invoiceId)}</p>`).join('')}${value.promotions.map(g=>billingKv(t('tier.'+g.tier),g.permanent?bt('permanentGrant'):billingDate(g.until))).join('')}${!value.grants.length&&!value.promotions.length?`<p>${esc(bt('noOtherGrants'))}</p>`:''}</details></div>`;}
function billingStaffContext(context){if(!context)return'';const x=context,p=x.payment,preview=x.preview;return `<div class="card" data-staff-context><h2>${esc(bt('reviewContext'))}</h2>${billingKv(bt('checkedAt'),billingDate(x.observedAt))}${p?billingKv(bt('paymentDate'),billingDate(p.createdAt))+billingMoneyKv(bt('paidAmount'),p.amountMinor,p.currency,'out')+billingMoneyKv(bt('refundedAmount'),p.refundedMinor,p.currency,'in')+billingMoneyKv(bt('pendingAmount'),p.pendingRefundMinor,p.currency,'in')+billingMoneyKv(bt('availableAmount'),p.availableMinor,p.currency,'in'):''}${x.status!=='ready'?`<p class="notice amber" data-context-incomplete>${esc(bt('contextIncomplete'))}</p>`:''}${billingStaffAccess(x.current,bt(preview?'beforeRefund':'currentAccess'))}<p data-other-grants>${esc(bt('otherGrants'))}: ${x.otherGrants?.length?x.otherGrants.map(g=>esc(t('tier.'+g.tier)+' · '+(g.permanent?bt('permanentGrant'):billingDate(g.until)))).join(' / '):esc(bt('noOtherGrants'))}</p>${preview?`<div data-refund-impact>${billingMoneyKv(bt('refundThisTime'),preview.amountMinor,p.currency,'in')}${billingStaffAccess(preview.after,bt('afterRefund'))}<p>${esc(bt(preview.changesAccess?'accessChanges':'noAccessChange'))}</p><p class="small">${esc(bt(preview.fullPaymentRefunded?'fullPayment':'partialPayment'))}</p>${preview.consumedCredit&&preview.fullInvoiceRefunded?`<p class="notice amber" data-consumed-credit>${esc(bt('consumedCredit'))}</p>`:''}<p class="small">${esc(bt('conditionalPreview'))}</p></div>`:''}${x.remaining&&x.remaining.amountMinor!==preview?.amountMinor?`<details data-remaining-impact><summary>${esc(bt('remainingPreview'))} · ${billingMoneySpan(x.remaining.amountMinor,p.currency,'in')}</summary>${billingStaffAccess(x.remaining.after,bt('afterRefund'))}${x.remaining.consumedCredit?`<p>${esc(bt('consumedCredit'))}</p>`:''}</details>`:''}<details data-staff-source><summary>${esc(bt('sourceRecords'))}</summary><p class="small review01-billing-id">${esc(bt('contextVersion'))}: ${esc(x.version||'—')}</p>${x.invoice?billingKv(bt('invoice'),x.invoice.id)+billingKv(bt('subscription'),x.invoice.subscriptionId)+x.invoice.lines.map(l=>billingKv(bt('plans'),t('tier.'+l.tier))+billingKv(bt('period'),billingDate(l.startAt)+' — '+billingDate(l.endAt))+billingMoneyKv(l.amountMinor<0?bt('credit'):bt('charge'),Math.abs(l.amountMinor),x.invoice.currency,l.amountMinor<0?'in':'out')).join(''):''}<pre class="review01-billing-source">${esc(JSON.stringify({missing:x.missing,recordRefs:x.recordRefs,subscription:x.subscription,refunds:x.refunds},null,2))}</pre></details></div>`;}
function billingStaffPage(){
  const record=BILLING_UI.staffCase;if(!record)return'';const c=record.case,d=BILLING_UI.staffDraft||{},x=record.context;
  const options=(values,selected)=>values.map(v=>`<option value="${v}" ${v===selected?'selected':''}>${esc(bt(v==='full'?'fullRemaining':v))}</option>`).join('');
  const editable=['submitted','needs_information','approved'].includes(c.state);
  const form=`<div class="card" data-staff-review><label class="flabel" for="billing-decision">${esc(bt('decision'))}</label><select id="billing-decision" data-tm-change="billingStaffDraftChange()">${options(BILLING_UI.claims.billingApprover?['needs_information','full','partial','decline']:['needs_information'],d.decision)}</select><label class="flabel" for="billing-basis">${esc(bt('basis'))}</label><select id="billing-basis">${options(['statutory_cancellation','statutory_remedy','contractual','goodwill','payment_correction'],d.basis)}</select>${['reference','calculation','publicReason','amount'].map(k=>`<label class="flabel" for="billing-${k}">${esc(bt(k))}</label>${k==='amount'?`<input type="number" min="0" step="1" id="billing-amount" value="${esc(d.amount||'')}" data-tm-input="billingStaffDraftChange()">`:`<textarea id="billing-${k}" maxlength="2000">${esc(d[k]||'')}</textarea>`}`).join('')}<label class="flabel" for="billing-renewal">${esc(bt('renewal'))}</label><select id="billing-renewal">${options(['unchanged','stop_at_period_end'],d.renewal)}</select>${billingButton(bt('previewImpact'),'billingStaffPreview()')}${billingButton(bt('saveReview'),'billingStaffReview()',true)}</div>`;
  return `<div class="card"><p class="review01-billing-id">${esc(c.id)}</p><h2>${esc(bt(c.state))}</h2>${billingKv(bt('requestReason'),c.reason?bt(c.reason):bt('reasonMissing'))}<p>${esc(c.customerNote||'')}</p>${c.approvedMinor!==undefined?billingMoneyKv(bt('refundAmount'),c.approvedMinor,c.currency,'in'):''}${c.decision?`<p>${esc(bt(c.decision))}</p>`:''}<p>${esc(c.publicReason||'')}</p></div>${billingStaffContext(x)}${editable?(c.state==='approved'?`<details class="card"><summary>${esc(bt('reviewAgain'))}</summary>${form}</details>`:form):''}${BILLING_UI.claims.billingRefundOperator&&['approved','refund_submitting'].includes(c.state)?billingButton(bt('execute'),'billingStaffExecute()',true):''}${BILLING_UI.claims.billingRefundOperator&&c.decision!=='needs_information'&&c.renewalAction==='stop_at_period_end'&&c.renewalState==='not_requested'?billingButton(bt('stopRenewal'),'billingStaffRenewal()'):''}${billingButton(bt('reconcile'),'billingStaffReconcile()')}<details class="card"><summary>${esc(bt('events'))}</summary>${record.events.map(e=>`<div class="review01-billing-event"><strong>${esc(billingDate(e.at))}</strong><p>${esc(bt({submitted:'submitted',review:'saveReview',customer_reply:'reply',execute_requested:'execute',refund_status:'reconcile',stop_renewal:'stopRenewal'}[e.action]||'events'))}${e.status?' · '+esc(bt(e.status)):''}</p><p>${esc(e.publicReason||e.note||'')}</p>${e.calculation?`<p>${esc(e.calculation)}</p>`:''}${e.reference?`<p>${esc(e.reference)}</p>`:''}${e.contextVersion?`<p class="small review01-billing-id">${esc(bt('contextVersion'))}: ${esc(e.contextVersion)}</p>`:''}</div>`).join('')}</details>`;
}
function billingStaffForm(){const get=id=>document.getElementById('billing-'+id).value;return Object.fromEntries(['decision','basis','reference','calculation','publicReason','amount','renewal'].map(id=>[id,get(id)]));}
function billingStaffDraftChange(){BILLING_UI.staffDraft=billingStaffForm();BILLING_UI.staffPreviewConfirmed=false;}
function billingStaffPreview(){const c=BILLING_UI.staffCase.case,d=billingStaffForm();BILLING_UI.staffDraft=d;const amount=d.decision==='full'?BILLING_UI.staffCase.context.payment?.availableMinor:d.decision==='partial'?Number(d.amount):0;billingOperation(async()=>{BILLING_UI.staffCase=await billingFetch('getBillingSupportCase',{caseId:c.id,previewAmountMinor:amount});BILLING_UI.staffPreviewConfirmed=true;},false);}
function billingStaffReview(){const record=BILLING_UI.staffCase,c=record.case,d=billingStaffForm(),amount=d.decision==='full'?record.context.payment?.availableMinor:d.decision==='partial'?Number(d.amount):0;BILLING_UI.staffDraft=d;if(d.decision!=='needs_information'&&(!BILLING_UI.staffPreviewConfirmed||record.context.preview?.amountMinor!==amount)){BILLING_UI.error=bt('previewRequired');billingRender();return;}const data={caseId:c.id,revision:c.revision,decision:d.decision,basis:d.basis,reference:d.reference,calculation:d.calculation,publicReason:d.publicReason,amountMinor:Number(d.amount),renewalAction:d.renewal,contextVersion:record.context.version||null,impactConfirmedMinor:record.context.preview?.amountMinor??null};billingOperation(async()=>{await billingFetch('reviewRefundRequest',data);BILLING_UI.staffCase=await billingFetch('getBillingSupportCase',{caseId:c.id});BILLING_UI.staffDraft=null;BILLING_UI.staffPreviewConfirmed=false;},false);}
function billingStaffExecute(){const c=BILLING_UI.staffCase.case;confirmAction(bt('execute'),'',()=>billingStaffAction('executeReviewedRefund'));document.getElementById('cf-msg').innerHTML=billingMoneyKv(bt('refundThisTime'),c.approvedMinor,c.currency,'in')+`<p class="small review01-billing-id">${esc(c.id)}</p>`;}
function billingStaffReconcile(){billingStaffAction('reconcileRefundRequest');}
function billingStaffMore(){billingOperation(async()=>{const r=await billingFetch('getBillingSupportCases',{cursor:BILLING_UI.staffCursor});const byId=new Map([...BILLING_UI.staffCases,...r.cases].map(c=>[c.id,c]));BILLING_UI.staffCases=[...byId.values()];BILLING_UI.staffHasMore=r.hasMore;BILLING_UI.staffCursor=r.cursor;},false);}
function billingStaffRenewal(){billingStaffAction('applyRefundRenewalDecision');}
function billingStaffAction(name){const c=BILLING_UI.staffCase.case;billingOperation(async()=>{await billingFetch(name,{caseId:c.id,revision:c.revision,contextVersion:BILLING_UI.staffCase.context?.version||null});BILLING_UI.staffCase=await billingFetch('getBillingSupportCase',{caseId:c.id});},false);}
function billingStartPurchase(tier){startBillingAction('createCheckoutSession',{tier,cadence:BILLING_CADENCE});}
async function billingHandleReturn(){const state=window.TAXMATE_BILLING_RETURN;if(!state)return;window.TAXMATE_BILLING_RETURN=null;if(OB?.pendingIntent){await obRefreshPaidAccess();return;}openBillingOverview();billingScreen('plans');await billingRefresh();}
async function billingBeginPurchase(tier,cadence){
  if(!requireLoginForTier())return{status:'login-required'};
  if(!BILLING_UI.uid||BILLING_UI.uid!==cloudUser().uid){billingResetState();BILLING_UI.uid=cloudUser().uid;}
  await billingOperation(async()=>{const r=await billingFetch('getCheckoutOffer',{tier,cadence});BILLING_UI.purchaseOffer=r.offer;BILLING_UI.checkoutReady=r.moneyOperationsEnabled&&r.consumerDisclosuresReady;
    const q=r.offer;billingSheet(bt('precontract'),`<h3>${t('tier.'+q.tier)}</h3>${billingMoneyKv(bt('dueNow'),q.priceMinor,q.currency,'out')}<p>${esc(bt('renewalInfo',{interval:t(q.cadence==='yearly'?'billing.yearly':'billing.monthly')}))}</p><details class="card"><summary>${esc(bt('terms'))} · ${esc(bt('englishContract'))}</summary>${q.contract.termsHtml}</details>${billingButton(bt('contractDownload'),'billingDownloadOffer()')}<label class="review01-billing-consent"><input type="checkbox" id="billing-terms"> <span>${esc(bt('termsAccept'))}</span></label><label class="review01-billing-consent"><input type="checkbox" id="billing-early"> <span>${esc(bt('earlySupply'))}</span></label><p class="small">${esc(bt('earlySupplyHelp'))}</p><p class="small">${esc(bt('waitStart'))} <a href="mailto:support@taxmate.uk">support@taxmate.uk</a></p>${BILLING_UI.checkoutReady?billingButton(bt('continuePayment'),'billingAcceptOffer()',true):`<div class="notice amber">${esc(bt('notReady'))}</div>`}`);
  },false);return{status:'precontract'};
}
function billingDownloadHtml(name,html){const blob=new Blob(['<!doctype html><meta charset="utf-8"><title>TaxMate record</title><main>'+html+'</main>'],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function billingDownloadOffer(){const q=BILLING_UI.purchaseOffer;if(q)billingDownloadHtml('TaxMate-offer-'+q.id+'.html',`<h1>${esc(q.tier)}</h1><p>${esc(billingMoney(q.priceMinor,q.currency)+' · '+q.cadence)}</p>${q.contract.termsHtml}<p>${esc(q.earlySupplyText)}</p>`);}
function billingAcceptOffer(){const q=BILLING_UI.purchaseOffer;if(!q)return;const data={offerId:q.id,termsAccepted:document.getElementById('billing-terms').checked,earlySupplyRequested:document.getElementById('billing-early').checked};if(!data.termsAccepted||!data.earlySupplyRequested){document.querySelector('#sb-billing [data-billing-error]').textContent=bt('consentRequired');return;}
  billingOperation(async()=>{const r=await billingFetch('createCheckoutSession',data);BILLING_UI.purchaseRecord=r.confirmation;BILLING_UI.checkoutUrl=r.url;billingShowPurchase(r.confirmation,r.url);},false);
}
function billingShowPurchase(r,url){billingSheet(bt('purchaseRecords'),`<p>${esc(r.addressee)}</p>${billingKv(bt('effective'),billingDate(r.providedAt))}<p>${esc(bt(r.outcome?.paymentStatus==='paid'?'paid':'pending_payment'))}</p><p>${esc(bt('confirmationNote'))}</p><details class="card"><summary>${esc(bt('terms'))} · ${esc(bt('englishContract'))}</summary>${r.termsHtml}</details>${billingButton(bt('contractDownload'),`billingDownloadPurchase('${r.id}')`)}${url?`<a class="btn" target="_self" rel="noopener noreferrer" href="${esc(url)}">${esc(bt('openPayment'))}</a>`:''}`);}
async function billingPurchases(){await billingOperation(async()=>{const r=await billingFetch('getPurchaseConfirmations');BILLING_UI.purchaseRecords=r.records;billingSheet(bt('purchaseRecords'),r.records.length?`<div class="review01-rows">${r.records.map(c=>billingRow(billingDate(c.providedAt),`billingPurchaseRecord('${c.id}')`,t('tier.'+c.tier)+' · '+bt(c.outcome?.paymentStatus==='paid'?'paid':'pending_payment'))).join('')}</div>`:`<p>${esc(bt('emptyPayments'))}</p>`);},false);}
function billingPurchaseRecord(id){const r=BILLING_UI.purchaseRecords?.find(c=>c.id===id);if(r){BILLING_UI.purchaseRecord=r;billingShowPurchase(r);}}
function billingDownloadPurchase(id){const r=BILLING_UI.purchaseRecord;if(r?.id===id)billingDownloadHtml('TaxMate-purchase-'+id+'.html',`<h1>TaxMate</h1><p>${esc(r.addressee)}</p><p>${esc(new Date(r.providedAt).toISOString())}</p><p>${esc(r.tier+' · '+r.cadence+' · '+billingMoney(r.priceMinor,r.currency))}</p><p>${esc(r.earlySupplyText)}</p><p>${esc(bt('confirmationNote'))}</p>${r.termsHtml}`);}
