(function(root,factory){
  const node=typeof module==='object'&&module.exports,api=factory(node?require('./money'):root.TaxMateMoney,node?require('./domain-schema'):root.TaxMateDomain,node?require('./company-profile'):root.TaxMateCompanyProfile,node?require('./company-treatment'):root.TaxMateCompanyTreatment,node?require('./company-tax-rules'):root.TaxMateCompanyTaxRules,node?require('./company-ledger'):root.TaxMateCompanyLedger,node?require('./revision-sync'):root.TaxMateRevisionSync);
  if(node)module.exports=api;root.TaxMateCompanyTax=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(Money,Domain,CompanyProfile,CompanyTreatment,CompanyTaxRules,CompanyLedger,RevisionSync){
  'use strict';
  if(!Money||!Domain||!CompanyProfile||!CompanyTreatment||!CompanyTaxRules||!CompanyLedger||!RevisionSync)throw new Error('TaxMate company-tax dependencies are required');
  const TAX_PERIOD_SCHEMA_VERSION=2,LOSS_SCHEMA_VERSION=1,LOSS_RULE_VERSION='uk-company-loss.2026-08-22.1';
  const clone=value=>JSON.parse(JSON.stringify(value)),plain=value=>value!==null&&typeof value==='object'&&!Array.isArray(value),text=(value,max=512)=>typeof value==='string'&&value.trim().length>0&&value.trim().length<=max,unique=values=>Array.from(new Set(values));
  const addDays=(date,days)=>{const value=new Date(date+'T00:00:00Z');value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);},maxDate=(a,b)=>a>b?a:b,minDate=(a,b)=>a<b?a:b;
  function addCalendarMonths(date,months){const source=new Date(date+'T00:00:00Z'),day=source.getUTCDate(),target=new Date(Date.UTC(source.getUTCFullYear(),source.getUTCMonth()+months,1)),lastDay=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();target.setUTCDate(Math.min(day,lastDay));return target.toISOString().slice(0,10);}
  function lastDayOfTwelveMonths(startDate){const source=new Date(startDate+'T00:00:00Z'),day=source.getUTCDate(),target=new Date(Date.UTC(source.getUTCFullYear()+1,source.getUTCMonth(),1)),lastDay=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();target.setUTCDate(day>lastDay?lastDay:day);if(day<=lastDay)target.setUTCDate(target.getUTCDate()-1);return target.toISOString().slice(0,10);}
  function originalId(source){return source.id.startsWith('company-source:')?source.id.slice('company-source:'.length):source.id;}
  function factsFromEvent(event){
    Domain.validateEconomicEventEnvelope(event);const source=event.sourceTransaction,allocation=(event.allocations||[]).find(item=>item.scope==='business')||event.allocations[0],facts={type:source.companyTransactionType,id:originalId(source),entityId:source.beneficiaryEntityId,date:source.date,amountMinor:source.amountMinor,description:source.purpose||'Company transaction',category:allocation&&allocation.category,treatmentBasis:event.treatmentDecision&&event.treatmentDecision.basis,evidenceRefs:clone(source.evidenceRefs||[])};if(source.salarySnapshot)facts.salarySnapshot=clone(source.salarySnapshot);
    for(const field of ['invoicePartyId','payerPaymentAccountId','receiverPaymentAccountId','payerOwnerType','receiverOwnerType','reimbursementExpected','sharedExpense'])if(source[field]!=null)facts[field]=clone(source[field]);return facts;
  }
  function applyTreatment(event,profile,confirmations,options={}){
    Domain.validateEconomicEventEnvelope(event);if(event.status!=='committed')return{status:'review_required',reasons:['only_committed_company_event_can_receive_tax_treatment'],event:clone(event)};const facts=factsFromEvent(event);if(!CompanyTreatment.P_AND_L_TYPES.includes(facts.type))return{status:'review_required',reasons:['company_event_has_no_profit_and_loss_tax_treatment'],event:clone(event)};
    const decision=CompanyTreatment.assessFacts(facts,profile,confirmations);if(decision.status==='review_required')return{status:'review_required',reasons:decision.reasonCodes,decision,event:clone(event)};if(JSON.stringify(event.sourceTransaction.companyTaxTreatment||null)===JSON.stringify(decision))return{status:'existing',reasons:[],decision,event:clone(event)};
    const next=clone(event),revision=event.revision+1,stamp=Number(options.now)||Date.now();next.revision=revision;next.previousRevisionId=RevisionSync.revisionId(event);next.idempotencyKey='company-ledger:'+facts.id+':tax:'+revision;next.updatedAt=stamp;next.deviceId=options.deviceId||event.deviceId;next.sourceTransaction.companyTaxTreatment=clone(decision);next.treatmentDecision=Object.assign({},next.treatmentDecision,{taxTreatmentStatus:decision.status,companyTaxRulesetVersion:decision.companyTaxRulesetVersion,taxEffectiveDate:decision.taxEffectiveDate,taxTreatment:decision.taxTreatment});next.journals.forEach(group=>{group.journal.revision=revision;});facts.companyTaxTreatment=decision;next.sourceSignature=CompanyLedger.signature(facts);Domain.validateEconomicEventEnvelope(next);RevisionSync.validateRevisionTransition(event,next);return{status:'treated',reasons:[],decision,event:next};
  }
  function buildPeriods(profile,asOfDate,ruleset=CompanyTaxRules.RULESET){
    const gate=CompanyProfile.transactionGate(profile);if(!gate.allowed)return{status:gate.status,reasons:gate.reasons};if(profile.tradingStatus!=='trading'||!Domain.isoDate(profile.tradingStartDate))return{status:'review_required',reasons:['company_trading_period_required']};const accountsStart=profile.accountingPeriod.startDate,accountsEnd=profile.accountingPeriod.endDate;
    const firstStart=maxDate(accountsStart,profile.tradingStartDate);if(firstStart>accountsEnd)return{status:'review_required',reasons:['corporation_tax_period_has_not_started']};const boundaries=[];let startDate=firstStart;
    while(startDate<=accountsEnd){const endDate=minDate(lastDayOfTwelveMonths(startDate),accountsEnd);boundaries.push({startDate,endDate,sourceDateStart:boundaries.length===0?accountsStart:startDate,sourceDateEnd:endDate});startDate=addDays(endDate,1);}
    const count=boundaries.length,periods=[];for(const [index,boundary] of boundaries.entries()){const coverage=CompanyTaxRules.rulesForPeriod(boundary.startDate,boundary.endDate,asOfDate,ruleset),identity={entityId:profile.entityId,accountsStartDate:accountsStart,accountsEndDate:accountsEnd,...boundary,accountsPeriodIndex:index+1,accountsPeriodCount:count};if(coverage.status!=='supported_calculated')return{...coverage,...identity};periods.push({status:'supported_calculated',reasons:[],id:'company-tax-period:'+profile.entityId+':'+boundary.startDate+':'+boundary.endDate,...identity,days:coverage.days,segments:coverage.segments});}
    return{status:'supported_calculated',reasons:[],periods};
  }
  function buildPeriod(profile,asOfDate,ruleset=CompanyTaxRules.RULESET,selector){
    const built=buildPeriods(profile,asOfDate,ruleset);if(built.status!=='supported_calculated')return built;if(built.periods.length===1)return built.periods[0];const selected=typeof selector==='string'?built.periods.find(period=>period.id===selector):Number.isSafeInteger(selector)?built.periods.find(period=>period.accountsPeriodIndex===selector):null;return selected||{status:'review_required',reasons:['corporation_tax_period_selection_required'],periods:built.periods};
  }
  function treatmentForEvent(event,profile){
    try{const facts=factsFromEvent(event),decision=event.sourceTransaction.companyTaxTreatment;CompanyTreatment.validateDecision(decision,facts,profile);return{status:decision.status,decision,facts};}catch(_){return{status:'review_required',reasons:['company_event_tax_treatment_unassessed']};}
  }
  function validateCtFacts(facts,profile){
    const reasons=[];if(!plain(facts))return['corporation_tax_facts_required'];if(facts.ukResidentConfirmed!==true)reasons.push('uk_company_residence_confirmation_required');if(facts.ringFenceProfits!==false)reasons.push('ring_fence_profit_review_required');if(facts.closeInvestmentHoldingCompany!==false)reasons.push('close_investment_holding_company_review_required');if(facts.associatedCompaniesConfirmedNone!==true||profile.riskAnswers.associatedCompanies!==false)reasons.push('associated_company_review_required');if(facts.qualifyingDistributionsMinor!==0)reasons.push('qualifying_distribution_review_required');if(facts.accountsCompleteConfirmed!==true)reasons.push('company_accounts_completeness_confirmation_required');if(facts.sameTradeContinues!==true)reasons.push('company_trade_continuity_review_required');for(const field of CompanyProfile.RISK_FIELDS){const answer=profile.riskAnswers&&profile.riskAnswers[field];if(answer===true||answer==='not_sure')reasons.push('company_profile_'+field+'_tax_review_required');}return Array.from(new Set(reasons));
  }
  function createOpeningLossRecord(input){
    if(!plain(input)||!text(input.id,128)||!text(input.entityId,128)||!Domain.isoDate(input.arisingDate)||!Number.isSafeInteger(input.amountMinor)||input.amountMinor<=0||input.arisingDate<'2017-04-01'||input.sameTradeConfirmed!==true||!Array.isArray(input.evidenceRefs)||!input.evidenceRefs.length||input.evidenceRefs.some(ref=>!text(ref,512)))throw new Error('Invalid supported opening company loss');const stamp=Number(input.now)||Date.now(),record={id:input.id,entityId:input.entityId,schemaVersion:LOSS_SCHEMA_VERSION,kind:'trading_loss',sourceKind:'opening_confirmed',sourcePeriodId:null,arisingDate:input.arisingDate,amountMinor:input.amountMinor,uses:[],usedMinor:0,remainingMinor:input.amountMinor,status:'active',reliefScope:'company_only_carry_forward',sameTradeConfirmed:true,rulesetVersion:CompanyTaxRules.RULESET_VERSION,lossRuleVersion:LOSS_RULE_VERSION,evidenceRefs:clone(input.evidenceRefs),revision:1,createdAt:stamp,updatedAt:stamp,deviceId:input.deviceId||'company-tax'};Domain.validateCompanyLossRecord(record);return record;
  }
  function validatedLosses(records,entityId){const seen=new Set();return(records||[]).map(record=>{Domain.validateCompanyLossRecord(record);if(record.entityId!==entityId)throw new Error('Company loss belongs to another entity');if(seen.has(record.id))throw new Error('Duplicate company loss record');seen.add(record.id);return clone(record);});}
  function activeLosses(records,entityId){return validatedLosses(records,entityId).filter(record=>record.status==='active'&&record.remainingMinor>0).sort((a,b)=>a.arisingDate.localeCompare(b.arisingDate)||a.id.localeCompare(b.id));}
  function availableLossForPeriod(records,periodId,eligibleRecordIds){const eligible=eligibleRecordIds&&new Set(eligibleRecordIds);return Money.sumMinor(records.filter(record=>record.status!=='superseded'&&(!eligible||eligible.has(record.id))).map(record=>{const priorUse=(record.uses||[]).find(use=>use.periodId===periodId);return Money.sumMinor([record.remainingMinor,priorUse&&priorUse.amountMinor||0],'Available company loss');}),'Available company losses');}
  function consumeLosses(records,amountMinor,options={}){
    Money.assertMinor(amountMinor,'Carried-forward loss use',{nonNegative:true});if(!text(options.periodId,128))throw new Error('Loss-use Corporation Tax period is required');const stamp=Number(options.now)||Date.now(),eligible=options.eligibleRecordIds?new Set(options.eligibleRecordIds):null,prepared=records.map(original=>{const priorUse=(original.uses||[]).find(use=>use.periodId===options.periodId);if(priorUse&&eligible&&!eligible.has(original.id))throw new Error('Corporation Tax period references an ineligible company loss');const record=clone(original),uses=(record.uses||[]).filter(use=>use.periodId!==options.periodId);record.uses=uses;record.usedMinor=Money.sumMinor(uses.map(use=>use.amountMinor),'Company loss uses');record.remainingMinor=record.amountMinor-record.usedMinor;record.status=record.remainingMinor===0?'exhausted':(record.status==='superseded'?'superseded':'active');return{original,record};}),ordered=prepared.filter(item=>item.record.status!=='superseded'&&item.record.remainingMinor>0&&(!eligible||eligible.has(item.record.id))).sort((a,b)=>a.record.arisingDate.localeCompare(b.record.arisingDate)||a.record.id.localeCompare(b.record.id));let remaining=amountMinor;
    for(const item of ordered){if(remaining===0)break;const used=Math.min(remaining,item.record.remainingMinor);if(used){item.record.uses.push({periodId:options.periodId,amountMinor:used});item.record.usedMinor+=used;item.record.remainingMinor-=used;item.record.status=item.record.remainingMinor===0?'exhausted':'active';remaining-=used;}}
    if(remaining!==0)throw new Error('Carried-forward loss use exceeds the available balance');return prepared.map(({original,record})=>{record.uses.sort((a,b)=>a.periodId.localeCompare(b.periodId));const changed=JSON.stringify([record.uses,record.usedMinor,record.remainingMinor,record.status])!==JSON.stringify([original.uses,original.usedMinor,original.remainingMinor,original.status]);if(changed){record.revision=original.revision+1;record.previousRevisionId=original.id+':'+original.revision;record.updatedAt=stamp;record.deviceId=options.deviceId||record.deviceId;}Domain.validateCompanyLossRecord(record);return record;});
  }
  function periodCalculationPayload(record){const payload=clone(record);for(const field of ['calculationSignature','revision','previousRevisionId','createdAt','updatedAt','deviceId'])delete payload[field];return payload;}
  function finalizePeriodRecord(record,prior,stamp,deviceId){
    const next=clone(record);next.calculationSignature=RevisionSync.fingerprint(periodCalculationPayload(next));if(prior!=null){Domain.validateCompanyTaxPeriod(prior);if(prior.id!==next.id||prior.entityId!==next.entityId)throw new Error('Prior Corporation Tax period identity does not match');if(prior.calculationSignature===next.calculationSignature)return clone(prior);next.revision=prior.revision+1;next.previousRevisionId=prior.id+':'+prior.revision;next.createdAt=prior.createdAt;}else{next.revision=1;delete next.previousRevisionId;next.createdAt=stamp;}next.updatedAt=stamp;next.deviceId=deviceId;Domain.validateCompanyTaxPeriod(next);return next;
  }
  function reviseCalculatedLoss(records,period,amountMinor,options={}){
    const id='company-loss:'+period.id,index=records.findIndex(record=>record.id===id),stamp=Number(options.now)||Date.now();if(index<0){if(amountMinor===0)return records;const record={id,entityId:period.entityId,schemaVersion:LOSS_SCHEMA_VERSION,kind:'trading_loss',sourceKind:'calculated_period',sourcePeriodId:period.id,arisingDate:period.endDate,amountMinor,uses:[],usedMinor:0,remainingMinor:amountMinor,status:'active',reliefScope:'company_only_carry_forward',sameTradeConfirmed:true,rulesetVersion:CompanyTaxRules.RULESET_VERSION,lossRuleVersion:LOSS_RULE_VERSION,evidenceRefs:[],revision:1,createdAt:stamp,updatedAt:stamp,deviceId:options.deviceId||'company-tax'};Domain.validateCompanyLossRecord(record);return[...records,record];}
    const original=records[index];if(original.sourceKind!=='calculated_period'||original.sourcePeriodId!==period.id)throw new Error('Company loss period identity conflict');if(original.usedMinor>0&&original.amountMinor!==amountMinor)throw new Error('A used company loss cannot be recalculated safely');let next=clone(original);if(amountMinor===0){if(original.usedMinor>0)throw new Error('A used company loss cannot be removed safely');next.status='superseded';next.uses=[];next.usedMinor=0;next.remainingMinor=next.amountMinor;}else if(original.usedMinor===0){next.amountMinor=amountMinor;next.uses=[];next.usedMinor=0;next.remainingMinor=amountMinor;next.status='active';}const changed=JSON.stringify([next.amountMinor,next.uses,next.usedMinor,next.remainingMinor,next.status])!==JSON.stringify([original.amountMinor,original.uses,original.usedMinor,original.remainingMinor,original.status]);if(changed){next.revision=original.revision+1;next.previousRevisionId=original.id+':'+original.revision;next.updatedAt=stamp;next.deviceId=options.deviceId||next.deviceId;}Domain.validateCompanyLossRecord(next);const output=records.slice();output[index]=next;return output;
  }
  function reviewResult(profile,period,reasons,accounting,events,stamp,deviceId,prior){
    const accountsStart=period&&period.accountsStartDate||profile.accountingPeriod.startDate,accountsEnd=period&&period.accountsEndDate||profile.accountingPeriod.endDate,startDate=period&&period.startDate||maxDate(accountsStart,profile.tradingStartDate),endDate=period&&period.endDate||accountsEnd,index=period&&period.accountsPeriodIndex||1,count=period&&period.accountsPeriodCount||Math.max(1,index),sourceStart=period&&period.sourceDateStart||accountsStart,sourceEnd=period&&period.sourceDateEnd||endDate,status=period&&['stale_rule','unknown_rule'].includes(period.status)?period.status:'review_required',draft={id:period&&period.id||'company-tax-period:'+profile.entityId+':'+startDate+':'+endDate,entityId:profile.entityId,schemaVersion:TAX_PERIOD_SCHEMA_VERSION,status,reasonCodes:unique(reasons),accountsStartDate:accountsStart,accountsEndDate:accountsEnd,startDate,endDate,sourceDateStart:sourceStart,sourceDateEnd:sourceEnd,accountsPeriodIndex:index,accountsPeriodCount:count,rulesetVersion:CompanyTaxRules.RULESET_VERSION,rulesVerifiedAt:CompanyTaxRules.VERIFIED_AT,accountingProfitMinor:accounting,accountingToTaxAdjustmentMinor:null,preLossTaxableProfitMinor:null,lossUsedMinor:null,taxableProfitMinor:null,currentTradingLossMinor:null,corporationTaxEstimateMinor:null,marginalReliefMinor:null,afterTaxAccountingProfitMinor:null,rateBand:null,sourceEventRevisionIds:unique(events.map(RevisionSync.revisionId)).sort(),lossRecordIds:[],provisional:true},record=finalizePeriodRecord(draft,prior,stamp,deviceId);return{status,reasons:record.reasonCodes,periodRecord:record,lossRecords:[]};
  }
  function computePeriodEstimate(input,period){
    const profile=input&&input.profile,events=input&&input.events||[],stamp=Number(input&&input.now)||Date.now(),deviceId=input&&input.deviceId||'company-tax',prior=input&&input.priorPeriodRecord||null;if(period.status!=='supported_calculated')return reviewResult(profile,period,period.reasons,0,[],stamp,deviceId,prior);
    const reasons=[...validateCtFacts(input.ctFacts,profile)],relevant=[],income=[],deductions=[],eventIds=new Set();let accountingIncome=0,accountingExpenses=0;
    for(const event of events){if(!event||event.sourceTransaction&&event.sourceTransaction.beneficiaryEntityId!==profile.entityId)continue;if(text(event.id,128)){if(eventIds.has(event.id)){reasons.push('duplicate_company_economic_event_identity');continue;}eventIds.add(event.id);}try{Domain.validateEconomicEventEnvelope(event);}catch(_){reasons.push('invalid_company_economic_event');continue;}const source=event.sourceTransaction,type=source.companyTransactionType;if(!CompanyTreatment.P_AND_L_TYPES.includes(type)||source.date<period.sourceDateStart||source.date>period.sourceDateEnd)continue;relevant.push(event);if(event.status==='reversed')continue;if(event.status==='draft'){reasons.push('unresolved_company_transaction_review_required');continue;}if(type==='company_income')accountingIncome=Money.sumMinor([accountingIncome,source.amountMinor],'Company accounting income');else accountingExpenses=Money.sumMinor([accountingExpenses,source.amountMinor],'Company accounting expense');const treatment=treatmentForEvent(event,profile);if(treatment.status==='review_required'){reasons.push(...(treatment.reasons||['company_event_tax_treatment_unassessed']));continue;}const decision=treatment.decision;if(type==='company_income'){if(decision.taxTreatment!=='taxable_trading_income')reasons.push('company_income_tax_treatment_review_required');else if(decision.taxEffectiveDate>=period.startDate&&decision.taxEffectiveDate<=period.endDate)income.push(source.amountMinor);else reasons.push('company_income_outside_tax_period_review_required');}else{if(['deductible_revenue_expense','pre_trading_revenue_deduction','deductible_director_remuneration'].includes(decision.taxTreatment)&&decision.taxEffectiveDate>=period.startDate&&decision.taxEffectiveDate<=period.endDate)deductions.push(source.amountMinor);else if(decision.taxTreatment!=='non_deductible_add_back')reasons.push('company_expense_tax_treatment_review_required');}
    }
    const accountingProfit=Money.sumMinor([accountingIncome,-accountingExpenses],'Company accounting profit'),taxableIncome=Money.sumMinor(income,'Taxable company income'),deductibleExpense=Money.sumMinor(deductions,'Deductible company expense'),preLossSigned=Money.sumMinor([taxableIncome,-deductibleExpense],'Pre-loss taxable company result');let losses;
    let allLosses=[],eligibleLossIds=[];try{allLosses=validatedLosses(input.lossRecords||[],profile.entityId);losses=allLosses.filter(record=>record.status!=='superseded'&&record.sourcePeriodId!==period.id&&record.arisingDate<period.startDate);eligibleLossIds=losses.map(record=>record.id);}catch(_){reasons.push('company_loss_pool_review_required');losses=[];allLosses=[];}const availableLoss=availableLossForPeriod(losses,period.id,eligibleLossIds);
    if(reasons.length)return reviewResult(profile,period,reasons,accountingProfit,relevant,stamp,deviceId,prior);
    let lossUse=0;if(preLossSigned>0&&availableLoss>0){if(!Number.isSafeInteger(input.lossUseMinor)||input.lossUseMinor<0)reasons.push('carried_forward_loss_use_confirmation_required');else{lossUse=input.lossUseMinor;if(lossUse>availableLoss||lossUse>preLossSigned)reasons.push('carried_forward_loss_use_exceeds_supported_balance');if(preLossSigned>CompanyTaxRules.RULESET.supportedPredicates.maximumSimpleLossProfitMinor&&lossUse>0)reasons.push('carried_forward_loss_restriction_review_required');}}else if(input.lossUseMinor!=null&&input.lossUseMinor!==0)reasons.push('carried_forward_loss_use_not_available');
    if(reasons.length)return reviewResult(profile,period,reasons,accountingProfit,relevant,stamp,deviceId,prior);
    const currentLoss=preLossSigned<0?-preLossSigned:0,taxableProfit=Math.max(0,preLossSigned-lossUse),year=period.segments[0].year,rate=CompanyTaxRules.calculateEstimate(taxableProfit,taxableProfit,period.days,year),adjustment=Money.sumMinor([preLossSigned,-accountingProfit],'Accounting-to-tax adjustment'),afterTax=Money.sumMinor([accountingProfit,-rate.corporationTaxEstimateMinor],'After-tax accounting result');let updatedLosses;
    try{updatedLosses=consumeLosses(allLosses,lossUse,{periodId:period.id,eligibleRecordIds:eligibleLossIds,now:stamp,deviceId});updatedLosses=reviseCalculatedLoss(updatedLosses,period,currentLoss,{now:stamp,deviceId});}catch(_){return reviewResult(profile,period,['company_loss_period_identity_conflict'],accountingProfit,relevant,stamp,deviceId,prior);}
    const usedIds=updatedLosses.filter(record=>(record.uses||[]).some(use=>use.periodId===period.id)).map(record=>record.id),lossRecordIds=unique([...usedIds,...(currentLoss?['company-loss:'+period.id]:[])]).sort(),draft={id:period.id,entityId:profile.entityId,schemaVersion:TAX_PERIOD_SCHEMA_VERSION,status:'supported_calculated',reasonCodes:[],accountsStartDate:period.accountsStartDate,accountsEndDate:period.accountsEndDate,startDate:period.startDate,endDate:period.endDate,sourceDateStart:period.sourceDateStart,sourceDateEnd:period.sourceDateEnd,accountsPeriodIndex:period.accountsPeriodIndex,accountsPeriodCount:period.accountsPeriodCount,rulesetVersion:CompanyTaxRules.RULESET_VERSION,rulesVerifiedAt:CompanyTaxRules.VERIFIED_AT,accountingProfitMinor:accountingProfit,accountingToTaxAdjustmentMinor:adjustment,preLossTaxableProfitMinor:Math.max(0,preLossSigned),lossUsedMinor:lossUse,taxableProfitMinor:taxableProfit,currentTradingLossMinor:currentLoss,corporationTaxEstimateMinor:rate.corporationTaxEstimateMinor,marginalReliefMinor:rate.marginalReliefMinor,afterTaxAccountingProfitMinor:afterTax,rateBand:rate.band,sourceEventRevisionIds:relevant.map(RevisionSync.revisionId).sort(),lossRecordIds,provisional:true},record=finalizePeriodRecord(draft,prior,stamp,deviceId);return{status:'supported_calculated',reasons:[],periodRecord:record,lossRecords:updatedLosses,rate,taxableIncomeMinor:taxableIncome,deductibleExpenseMinor:deductibleExpense,companyLossNotice:currentLoss>0?'This loss belongs to the company, not to you personally.':null};
  }
  function requestedLossUse(input,period){const byPeriod=input&&input.lossUseMinorByPeriod;if(Array.isArray(byPeriod))return byPeriod[period.accountsPeriodIndex-1];if(plain(byPeriod)&&Object.prototype.hasOwnProperty.call(byPeriod,period.id))return byPeriod[period.id];return input&&input.lossUseMinor;}
  function computeEstimate(input){
    const profile=input&&input.profile,ruleset=input&&input.ruleset||CompanyTaxRules.RULESET,built=buildPeriods(profile,input&&input.asOfDate,ruleset),stamp=Number(input&&input.now)||Date.now(),deviceId=input&&input.deviceId||'company-tax';if(built.status!=='supported_calculated')return reviewResult(profile,built,built.reasons,0,[],stamp,deviceId,input&&input.priorPeriodRecord||null);let period=built.periods[0];if(built.periods.length>1){period=typeof input.periodId==='string'?built.periods.find(item=>item.id===input.periodId):Number.isSafeInteger(input.periodIndex)?built.periods.find(item=>item.accountsPeriodIndex===input.periodIndex):null;if(!period)return{status:'review_required',reasons:['corporation_tax_period_selection_required'],periodRecord:null,periodRecords:[],periodDefinitions:built.periods,lossRecords:clone(input.lossRecords||[])};}
    return computePeriodEstimate(input,period);
  }
  function computeEstimates(input){
    const profile=input&&input.profile,ruleset=input&&input.ruleset||CompanyTaxRules.RULESET,built=buildPeriods(profile,input&&input.asOfDate,ruleset),stamp=Number(input&&input.now)||Date.now(),deviceId=input&&input.deviceId||'company-tax';if(built.status!=='supported_calculated'){const result=reviewResult(profile,built,built.reasons,0,[],stamp,deviceId,null);return{status:result.status,reasons:result.reasons,split:false,periodResults:[result],periodRecords:[result.periodRecord],lossRecords:clone(input&&input.lossRecords||[]),accountingProfitMinor:result.periodRecord.accountingProfitMinor,corporationTaxEstimateMinor:null};}
    const priors=Array.isArray(input&&input.priorPeriodRecords)?input.priorPeriodRecords:[],results=[];let runningLosses=clone(input&&input.lossRecords||[]),status='supported_calculated',reasons=[];
    for(const period of built.periods){const prior=priors.find(record=>record&&record.id===period.id)||null,result=computePeriodEstimate({...input,lossRecords:runningLosses,lossUseMinor:requestedLossUse(input,period),priorPeriodRecord:prior},period);results.push(result);if(result.status!=='supported_calculated'){status=result.status;reasons=unique([...reasons,...result.reasons]);break;}runningLosses=result.lossRecords;}
    const records=results.map(result=>result.periodRecord).filter(Boolean),accountingProfit=Money.sumMinor(records.map(record=>record.accountingProfitMinor),'Accounts-period accounting profit'),complete=status==='supported_calculated'&&results.length===built.periods.length,corporationTax=complete?Money.sumMinor(records.map(record=>record.corporationTaxEstimateMinor),'Accounts-period Corporation Tax estimate'):null;
    return{status:complete?'supported_calculated':status,reasons,split:built.periods.length>1,accountsStartDate:built.periods[0].accountsStartDate,accountsEndDate:built.periods[0].accountsEndDate,periodResults:results,periodRecords:records,periodDefinitions:built.periods,lossRecords:runningLosses,accountingProfitMinor:accountingProfit,corporationTaxEstimateMinor:corporationTax};
  }
  return{TAX_PERIOD_SCHEMA_VERSION,LOSS_SCHEMA_VERSION,LOSS_RULE_VERSION,factsFromEvent,applyTreatment,addCalendarMonths,lastDayOfTwelveMonths,buildPeriods,buildPeriod,treatmentForEvent,validateCtFacts,createOpeningLossRecord,validatedLosses,activeLosses,availableLossForPeriod,consumeLosses,periodCalculationPayload,finalizePeriodRecord,computePeriodEstimate,computeEstimate,computeEstimates};
});
