(function(root,factory){const node=typeof module==='object'&&module.exports,api=factory(node?require('./revision-sync'):root.TaxMateRevisionSync);if(node)module.exports=api;root.TaxMateLtdSync=api;})(typeof globalThis!=='undefined'?globalThis:this,function(RevisionSync){
  'use strict';
  const SYNC_SCHEMA_VERSION=1,MAX_DOCUMENT_BYTES=900*1024,COLLECTIONS=Object.freeze(['persons','entities','companyProfiles','companyProfileRevisions','companyOwnershipVersions','projects','paymentAccounts','economicEvents','companyTaxPeriods','companyLossRecords','salaryRecords','dividendDeclarations','personalIncomeLinks']);
  const clone=value=>JSON.parse(JSON.stringify(value)),bytes=value=>new TextEncoder().encode(JSON.stringify(value)).length,stamp=record=>Number(record&&record.deletedAt||record&&record.updatedAt||record&&record.createdAt||0),device=record=>String(record&&record.deviceId||''),revision=record=>Number(record&&record.revision||0),recordKey=(collection,id)=>`${collection}|${id}`;
  function docId(recordId){const source=new TextEncoder().encode(String(recordId)),raw=typeof Buffer!=='undefined'?Buffer.from(source).toString('base64'):btoa(String.fromCharCode(...source));return raw.replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  function documentPath(uid,collection,recordId){if(typeof uid!=='string'||!uid||!COLLECTIONS.includes(collection)||typeof recordId!=='string'||!recordId)throw new Error('Invalid Ltd sync identity');return`users/${uid}/ltd/v1/${collection}/${docId(recordId)}`;}
  function companyEntityIds(domain){return new Set((domain.entities||[]).filter(item=>item.type==='limited_company').map(item=>item.id));}
  function companyIdForRecord(collection,record,companyIds){
    if(collection==='entities')return record.id;
    if(record&&typeof record.entityId==='string'&&record.entityId)return record.entityId;
    if(record&&record.sourceTransaction&&typeof record.sourceTransaction.beneficiaryEntityId==='string')return record.sourceTransaction.beneficiaryEntityId;
    if(record&&record.ownerType==='entity'&&typeof record.ownerId==='string')return record.ownerId;
    if(companyIds.size===1)return Array.from(companyIds)[0];
    throw new Error('Ltd sync record company identity is ambiguous');
  }
  function recordsForSync(state){const domain=state&&state.domain||{},ids=companyEntityIds(domain),personIds=new Set((domain.persons||[]).filter(item=>item.id==='person:account-holder').map(item=>item.id)),out={};for(const collection of COLLECTIONS)out[collection]=[];if(ids.size===0)return out;out.entities=(domain.entities||[]).filter(item=>ids.has(item.id));for(const profile of domain.companyProfiles||[]){if(!ids.has(profile.entityId))continue;const base=clone(profile),revisions=base.profileRevisionHistory||[],ownership=base.ownershipHistory||[];delete base.profileRevisionHistory;delete base.ownershipHistory;out.companyProfiles.push(base);out.companyProfileRevisions.push(...revisions.map(item=>({...clone(item),entityId:profile.entityId,profileId:profile.id})));out.companyOwnershipVersions.push(...ownership.map(item=>({...clone(item),entityId:profile.entityId,profileId:profile.id})));}out.persons=(domain.persons||[]).filter(item=>personIds.has(item.id));out.projects=(domain.projects||[]).filter(item=>ids.has(item.entityId));out.paymentAccounts=(domain.paymentAccounts||[]).filter(item=>ids.has(item.ownerId)||item.ownerType==='person'&&personIds.has(item.ownerId));out.economicEvents=(domain.economicEvents||[]).filter(item=>item.origin==='company_v1_5'&&item.sourceTransaction&&ids.has(item.sourceTransaction.beneficiaryEntityId));for(const collection of ['companyTaxPeriods','companyLossRecords','salaryRecords','dividendDeclarations','personalIncomeLinks'])out[collection]=(domain[collection]||[]).filter(item=>ids.has(item.entityId));return out;}
  function envelope(collection,record,companyId){if(!COLLECTIONS.includes(collection)||!record||typeof record.id!=='string'||!record.id||typeof companyId!=='string'||!companyId)throw new Error('Invalid Ltd sync record');const value={schemaVersion:SYNC_SCHEMA_VERSION,companyId,collection,documentId:docId(record.id),recordId:record.id,revision:revision(record),updatedAt:stamp(record),deviceId:device(record),deletedAt:record.deletedAt==null?null:Number(record.deletedAt),payload:clone(record),checksum:RevisionSync.fingerprint(record)};if(bytes(value)>MAX_DOCUMENT_BYTES)throw Object.assign(new Error('Ltd sync document exceeds size limit'),{code:'ltd_sync_document_too_large',collection,recordId:record.id});return value;}
  function validateEnvelope(value){if(!value||value.schemaVersion!==SYNC_SCHEMA_VERSION||typeof value.companyId!=='string'||!value.companyId||!COLLECTIONS.includes(value.collection)||typeof value.recordId!=='string'||!value.recordId||value.documentId!==docId(value.recordId)||!value.payload||value.payload.id!==value.recordId||value.checksum!==RevisionSync.fingerprint(value.payload)||bytes(value)>MAX_DOCUMENT_BYTES)throw new Error('Invalid Ltd sync envelope');return true;}
  function compare(left,right){const a=left.payload||left,b=right.payload||right,da=Number(a.deletedAt||0),db=Number(b.deletedAt||0);if(da||db){if(da!==db)return da>db?1:-1;if(!!da!==!!db)return da?1:-1;}const sa=stamp(a),sb=stamp(b);if(sa!==sb)return sa>sb?1:-1;const ra=revision(a),rb=revision(b);if(ra!==rb)return ra>rb?1:-1;return device(a).localeCompare(device(b));}
  function reconcile(state,remoteEnvelopes,uid){const local=recordsForSync(state),companyIds=companyEntityIds(state&&state.domain||{}),remote=new Map();for(const item of remoteEnvelopes||[]){validateEnvelope(item);remote.set(recordKey(item.collection,item.recordId),item);}const uploads=[],downloads=[],conflicts=[];for(const collection of COLLECTIONS){for(const record of local[collection]){const localEnvelope=envelope(collection,record,companyIdForRecord(collection,record,companyIds)),key=recordKey(collection,record.id),remoteEnvelope=remote.get(key);if(!remoteEnvelope){uploads.push({kind:'ltd-record',uid,companyId:localEnvelope.companyId,collection,recordId:record.id,path:documentPath(uid,collection,record.id),record:localEnvelope,updatedAt:localEnvelope.updatedAt,deviceId:localEnvelope.deviceId});continue;}remote.delete(key);if(remoteEnvelope.companyId!==localEnvelope.companyId){conflicts.push({collection,recordId:record.id,reasonCode:'company_anchor_mismatch'});continue;}const order=compare(localEnvelope,remoteEnvelope);if(order>0)uploads.push({kind:'ltd-record',uid,companyId:localEnvelope.companyId,collection,recordId:record.id,path:documentPath(uid,collection,record.id),record:localEnvelope,updatedAt:localEnvelope.updatedAt,deviceId:localEnvelope.deviceId});else if(order<0)downloads.push(remoteEnvelope);else if(localEnvelope.checksum!==remoteEnvelope.checksum)conflicts.push({collection,recordId:record.id,reasonCode:'same_version_different_payload',localChecksum:localEnvelope.checksum,remoteChecksum:remoteEnvelope.checksum});}}
    for(const remoteEnvelope of remote.values())downloads.push(remoteEnvelope);return{uploads,downloads,conflicts,converged:uploads.length===0&&conflicts.length===0};}
  function applyDownloads(state,envelopes){const next=clone(state),ordered=(envelopes||[]).slice().sort((a,b)=>COLLECTIONS.indexOf(a.collection)-COLLECTIONS.indexOf(b.collection));for(const envelopeValue of ordered){validateEnvelope(envelopeValue);const record=clone(envelopeValue.payload);if(envelopeValue.collection==='companyProfileRevisions'||envelopeValue.collection==='companyOwnershipVersions'){const profile=(next.domain.companyProfiles||[]).find(item=>item.id===record.profileId&&item.entityId===record.entityId);if(!profile)throw Object.assign(new Error('Ltd sync history references a missing company profile'),{code:'ltd_sync_parent_missing'});const field=envelopeValue.collection==='companyProfileRevisions'?'profileRevisionHistory':'ownershipHistory',list=Array.isArray(profile[field])?profile[field]:[],index=list.findIndex(item=>item.id===record.id),nested=clone(record);delete nested.profileId;if(index<0)list.push(nested);else if(compare(record,{...list[index],profileId:record.profileId})>=0)list[index]=nested;profile[field]=list;continue;}const list=next.domain[envelopeValue.collection],index=list.findIndex(item=>item.id===envelopeValue.recordId);if(index<0)list.push(record);else if(compare(record,list[index])>=0){if(envelopeValue.collection==='companyProfiles'){if(record.profileRevisionHistory==null&&list[index].profileRevisionHistory!=null)record.profileRevisionHistory=clone(list[index].profileRevisionHistory);if(record.ownershipHistory==null&&list[index].ownershipHistory!=null)record.ownershipHistory=clone(list[index].ownershipHistory);}list[index]=record;}}return next;}
  function assertNoMegaDocument(doc){if(bytes(doc)>MAX_DOCUMENT_BYTES)throw new Error('Ltd sync document exceeds size limit');return true;}
  return{SYNC_SCHEMA_VERSION,MAX_DOCUMENT_BYTES,COLLECTIONS,docId,documentPath,recordsForSync,companyIdForRecord,envelope,validateEnvelope,compare,reconcile,applyDownloads,assertNoMegaDocument};
});
