(function(root,factory){
  const api=factory(typeof module==='object'&&module.exports?require('jszip'):root.JSZip,typeof module==='object'&&module.exports?require('./state-schema'):root.TaxMateState);
  if(typeof module==='object'&&module.exports)module.exports=api;root.TaxMatePortableBackup=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(JSZip,State){
  'use strict';
  const BACKUP_SCHEMA_VERSION=1,MANIFEST_SCHEMA_VERSION=1,MAX_RECEIPTS=2000,MAX_RECEIPT_BYTES=10*1024*1024,MAX_TOTAL_BYTES=250*1024*1024;
  const MIME_EXT={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','image/heic':'heic','image/heif':'heif'};
  function bytesOf(value){if(value instanceof Uint8Array)return value;if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);throw new Error('Receipt binary is missing or invalid');}
  function tokenFor(value){const bytes=new TextEncoder().encode(String(value));let raw='';bytes.forEach(x=>raw+=String.fromCharCode(x));return (typeof btoa==='function'?btoa(raw):Buffer.from(bytes).toString('base64')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  function extensionFor(mime){return MIME_EXT[String(mime||'').toLowerCase()]||'bin';}
  async function sha256(bytes){const b=bytesOf(bytes);if(globalThis.crypto&&globalThis.crypto.subtle){const out=await globalThis.crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(out),x=>x.toString(16).padStart(2,'0')).join('');}return require('node:crypto').createHash('sha256').update(b).digest('hex');}
  function safePath(path){return typeof path==='string'&&!path.includes('\\')&&!path.startsWith('/')&&!/(^|\/)\.\.?($|\/)/.test(path)&&/^receipts\/(entries|orphans)\/[A-Za-z0-9_-]+\.[a-z0-9]+$/.test(path);}
  function validateReceiptInputs(state,receipts){
    if(!Array.isArray(receipts)||receipts.length>MAX_RECEIPTS)throw new Error('Receipt count exceeds the portable-backup limit');
    const entries=new Map(state.entries.map(e=>[e.id,e])),linked=new Set(),storage=new Set();let total=0;
    receipts.forEach((r,i)=>{if(!r||r.status==='missing')throw new Error(`Referenced receipt ${i+1} is missing`);const b=bytesOf(r.bytes);if(!b.length||b.length>MAX_RECEIPT_BYTES)throw new Error(`Receipt ${i+1} has an invalid size`);total+=b.length;if(total>MAX_TOTAL_BYTES)throw new Error('Receipt payload exceeds the portable-backup limit');if(r.entryId!=null){if(!entries.has(r.entryId))throw new Error('Receipt references an unknown entry');if(linked.has(r.entryId))throw new Error('Duplicate receipt association for entry '+r.entryId);linked.add(r.entryId);}const key=r.originalPath?'path:'+String(r.originalPath):'entry:'+String(r.entryId);if(storage.has(key))throw new Error('Duplicate receipt input');storage.add(key);});
    state.entries.filter(e=>e.receiptPath||e.receiptUrl).forEach(e=>{if(!linked.has(e.id))throw new Error('Referenced receipt is missing for entry '+e.id);});
  }
  async function createArchive(input){
    if(!JSZip)throw new Error('ZIP support is unavailable');const state=State.migrate(input.state,Date.now(),input.identity&&input.identity.deviceId);State.validateState(state);const receipts=input.receipts||[];validateReceiptInputs(state,receipts);
    const exportedAt=input.exportedAt||new Date().toISOString(),backupId=`tm-${tokenFor(exportedAt+'|'+(input.identity&&input.identity.buildId||''))}`;const zip=new JSZip(),manifest=[];
    for(let i=0;i<receipts.length;i++){const r=receipts[i],binary=bytesOf(r.bytes),orphan=r.entryId==null,token=tokenFor(orphan?(r.originalPath||`orphan-${i}`):r.entryId),path=`receipts/${orphan?'orphans':'entries'}/${token}.${extensionFor(r.mimeType)}`;if(!safePath(path))throw new Error('Unsafe receipt archive path');manifest.push({entryId:orphan?null:r.entryId,archivePath:path,originalPath:r.originalPath||null,mimeType:r.mimeType||'application/octet-stream',size:binary.length,sha256:await sha256(binary),status:orphan?'orphan':'linked'});zip.file(path,binary,{binary:true,compression:'DEFLATE',compressionOptions:{level:6}});}
    const receiptSummary=manifest.map(x=>({entryId:x.entryId,archivePath:x.archivePath,status:x.status,mimeType:x.mimeType,size:x.size,sha256:x.sha256}));const data=State.createExport(state,input.identity||{},receiptSummary);data.receiptBinariesIncluded=true;data.receiptNotice='Receipt binaries are included in this portable ZIP and verified by the receipt manifest.';
    const metadata={format:'taxmate-portable-backup',backupSchemaVersion:BACKUP_SCHEMA_VERSION,manifestSchemaVersion:MANIFEST_SCHEMA_VERSION,backupId,appVersion:input.identity&&input.identity.appVersion,buildId:input.identity&&input.identity.buildId,stateSchemaVersion:State.STATE_SCHEMA_VERSION,exportedAt,receiptCount:manifest.length,linkedReceiptCount:manifest.filter(x=>x.status==='linked').length,orphanReceiptCount:manifest.filter(x=>x.status==='orphan').length};
    zip.file('taxmate-backup.json',JSON.stringify({metadata,data},null,2));zip.file('receipt-manifest.json',JSON.stringify({manifestSchemaVersion:MANIFEST_SCHEMA_VERSION,backupId,receipts:manifest},null,2));
    const type=typeof Blob!=='undefined'&&!input.nodeBuffer?'blob':'nodebuffer';return{archive:await zip.generateAsync({type,compression:'DEFLATE',compressionOptions:{level:6},platform:'UNIX'}),metadata,manifest};
  }
  async function inspectArchive(input){
    if(!JSZip)throw new Error('ZIP support is unavailable');let zip;try{zip=await JSZip.loadAsync(input,{checkCRC32:true});}catch(e){throw new Error('Corrupt or unsupported ZIP archive');}
    const names=Object.keys(zip.files);for(const name of names){const f=zip.files[name],original=f.unsafeOriginalName||name;if(original!==name||name.includes('\\')||name.startsWith('/')||/(^|\/)\.\.?($|\/)/.test(name))throw new Error('Unsafe archive path');if(!f.dir&&name!=='taxmate-backup.json'&&name!=='receipt-manifest.json'&&!safePath(name))throw new Error('Unexpected archive file: '+name);}
    const dataFile=zip.file('taxmate-backup.json'),manifestFile=zip.file('receipt-manifest.json');if(!dataFile||!manifestFile)throw new Error('Portable backup metadata is incomplete');let envelope,manifestDoc;try{envelope=JSON.parse(await dataFile.async('string'));manifestDoc=JSON.parse(await manifestFile.async('string'));}catch(e){throw new Error('Backup JSON is corrupt');}
    const meta=envelope&&envelope.metadata;if(!meta||meta.format!=='taxmate-portable-backup')throw new Error('Not a TaxMate portable backup');if(meta.backupSchemaVersion>BACKUP_SCHEMA_VERSION||manifestDoc.manifestSchemaVersion>MANIFEST_SCHEMA_VERSION)throw new Error('Backup uses an unsupported future schema');if(meta.backupSchemaVersion!==BACKUP_SCHEMA_VERSION||manifestDoc.manifestSchemaVersion!==MANIFEST_SCHEMA_VERSION||meta.backupId!==manifestDoc.backupId)throw new Error('Backup schema or identity is invalid');
    const state=State.importBackup(envelope.data,Date.now(),input&&input.deviceId);const receipts=manifestDoc.receipts;if(!Array.isArray(receipts)||receipts.length>MAX_RECEIPTS)throw new Error('Receipt manifest is invalid');const entryIds=new Set(state.entries.map(e=>e.id)),linked=new Set(),paths=new Set(),binaries=[];let total=0;
    for(const r of receipts){if(!r||!['linked','orphan'].includes(r.status)||!safePath(r.archivePath)||paths.has(r.archivePath))throw new Error('Receipt manifest contains an invalid or duplicate path');paths.add(r.archivePath);if(r.status==='linked'){if(!entryIds.has(r.entryId)||linked.has(r.entryId))throw new Error('Receipt manifest contains an invalid or duplicate entry association');linked.add(r.entryId);}else if(r.entryId!==null)throw new Error('Orphan receipt must not reference an entry');const file=zip.file(r.archivePath);if(!file)throw new Error('Receipt manifest references a missing file');const bytes=await file.async('uint8array');total+=bytes.length;if(bytes.length!==r.size||bytes.length>MAX_RECEIPT_BYTES||total>MAX_TOTAL_BYTES||await sha256(bytes)!==r.sha256)throw new Error('Receipt binary failed integrity validation');binaries.push({...r,bytes});}
    names.filter(n=>safePath(n)&&!zip.files[n].dir).forEach(n=>{if(!paths.has(n))throw new Error('Archive contains an orphan file not declared in the manifest');});state.entries.filter(e=>e.receiptPath||e.receiptUrl).forEach(e=>{if(!linked.has(e.id))throw new Error('Entry references a receipt missing from the archive');});if(Number(meta.receiptCount)!==receipts.length)throw new Error('Receipt count does not match archive metadata');
    return{metadata:meta,state,receipts:binaries,preview:{businesses:state.businesses.length,entries:state.entries.length,receipts:binaries.filter(x=>x.status==='linked').length,orphans:binaries.filter(x=>x.status==='orphan').length,totalReceiptBytes:total}};
  }
  return{BACKUP_SCHEMA_VERSION,MANIFEST_SCHEMA_VERSION,MAX_RECEIPTS,MAX_RECEIPT_BYTES,MAX_TOTAL_BYTES,tokenFor,safePath,createArchive,inspectArchive};
});
