(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.TaxMateLegal=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const POLICY_VERSION='2026-08-20',LAST_UPDATED='20 August 2026';
  const PUBLIC_CORRESPONDENCE_ADDRESS='Unit 170198, PO Box 7169, Poole, BH15 9EL';
  const HELP_GROUPS=[
    ['Getting started',[
      ['How do I add my first business?','Open TaxMate and choose <strong>Add a business</strong>. Give it a name and choose whether you are a sole trader or partnership. TaxMate then uses that business for your income, expenses and tax estimate.'],
      ['How do I add income?','Open <strong>Income</strong> and tap <strong>Add income</strong>. Enter the amount, date, business and category, then save. Your tax estimate updates from the saved record.'],
      ['How do I add an expense?','Open <strong>Expenses</strong> and tap <strong>Add expense</strong>. Enter the amount, date, category and business-use percentage where needed, then save.'],
      ['Can I add earlier months?','Yes. Use the catch-up flow to enter earlier months without rebuilding your current records.'],
      ['Can I change categories?','Yes. You can use built-in categories, rename where supported, and organise records with the available category and folder tools.']]],
    ['Tax & estimates',[
      ['How is my tax estimate calculated?','TaxMate uses the supported tax-year rules and the income and expense information you enter. It is a planning estimate, not your final HMRC calculation.'],
      ['What is the £1,000 trading allowance?','For eligible sole-trader income, TaxMate can compare the £1,000 trading allowance with actual expenses and show which produces the lower estimated taxable profit.'],
      ['What are payments on account?','Payments on account are advance payments HMRC may require towards the following tax year. TaxMate can include the figures you enter from your HMRC position when estimating what may be due.'],
      ['Does TaxMate file my Self Assessment?','No. TaxMate helps you keep records, understand figures and prepare references and exports. You still file with HMRC or another filing solution.'],
      ['What does TaxMate do for MTD?','TaxMate can help keep records, show eligibility guidance and prepare record summaries. It does not submit MTD updates to HMRC.'],
      ['How does mileage work?','TaxMate currently tracks an annual mileage total and, on Plus or Pro, can compare the mileage method with actual vehicle costs. It is not a trip-by-trip mileage diary.']]],
    ['Receipts',[
      ['How do I add a receipt photo?','On Plus or Pro, open an expense and choose <strong>Take photo</strong> or <strong>Choose existing photo</strong>. The image is linked to that expense.'],
      ['Can I add receipts later?','Yes. Use the Receipts workflow to find expenses that still need a receipt and attach images later.'],
      ['What happens to receipt photos if I downgrade?','Existing receipt images are kept. You can still access your records and include existing receipt data in backups. New premium receipt uploads require Plus or Pro.'],
      ['Can I delete a receipt photo?','Yes. Open the linked receipt and use the delete action. Deleting the receipt image does not delete the expense entry itself.']]],
    ['Plans & billing',[
      ['What is included in Free?','Free covers core bookkeeping, one business, tax estimates, cloud sync, backups and the other functions shown in the Free plan card.'],
      ['What is Plus?','Plus adds multiple businesses, receipt photos, mileage comparison and the PDF tax report.'],
      ['What is Pro?','Pro includes Plus and adds Partner Sync, the SA104 partnership working paper, Receipt Pack PDF and quarterly record summaries.'],
      ['Monthly or yearly?','Plus costs £3.99 monthly or £29.99 yearly. Pro costs £7.99 monthly or £59.99 yearly. Monthly and yearly subscriptions renew until cancelled.'],
      ['How do I cancel?','Open <strong>Manage subscription</strong>. Cancellation stops the next renewal; access normally continues until the end of the period already paid for.'],
      ['Will cancelling delete my records?','No.'],
      ['How do promotion codes work?','A valid TaxMate promotion can grant Plus or Pro without starting a paid subscription. Some promotions have fixed campaign dates or redemption limits. A promotion never starts an automatic paid subscription by itself.']]],
    ['Cloud & backup',[
      ['Do I need an account?','No for local core use. Sign-in is required for cloud sync and cloud-dependent features.'],
      ['Which sign-in method does TaxMate use?','Google only.'],
      ['How does cloud sync work?','When signed in, supported personal records sync through TaxMate’s Firebase services so they can follow the same account across devices.'],
      ['What backup should I use?','Use <strong>Full backup</strong> for a ZIP containing TaxMate records and available receipt image binaries. JSON is a data-only backup and does not include receipt binaries.'],
      ['How do I restore?','Choose <strong>Restore from backup</strong>, select a valid TaxMate backup and review the confirmation. The app validates the backup before replacing current local data.'],
      ['What happens when I delete my account?','The app removes your personal account and cloud records through the authenticated deletion flow. Shared partnership records may remain for other authorised members.']]],
    ['Partnerships',[
      ['How do I join a partnership?','Open <strong>Your businesses → Join a partnership</strong>, enter the partnership code and follow the Pro access flow if needed.'],
      ['How do I invite my partner?','From the relevant partnership business, use Partner Sync to share the partnership code through the available share or copy option.'],
      ['What happens if I leave?','Your membership is removed. Shared records remain for other authorised members. If the last member leaves, the approved deletion lifecycle applies.']]],
    ['Troubleshooting',[
      ["I can't sign in",'Use Google Sign-In in a normal supported browser. Check that popups are allowed and your connection is working. If the problem continues, contact support.'],
      ['My data is not syncing','Confirm you are signed into the expected Google account and online. If local records are important, create a backup before troubleshooting further.'],
      ['My receipt will not upload','Check that you are online, signed in and have Plus or Pro access. Use an image file within the supported size limit.'],
      ['Checkout does not open','Try again once. If the payment service is temporarily unavailable, no plan should change. Contact support if it persists.'],
      ['I changed phone','Sign in with the same Google account to retrieve supported synced records. Keep a full ZIP backup as additional protection.'],
      ['How do I install TaxMate?',"Use the app's install guidance for your device and browser. On iPhone, use Safari's Add to Home Screen flow."]]]
  ];
  const PRIVACY_SECTIONS=[
    ['What information does TaxMate use?','TaxMate can process business names and types; income, expense, mileage, category, date and note records; tax-year adjustments; receipt images; backup files; partnership membership and shared records; and app preferences. Google sign-in supplies an account identifier and may supply your name, email and profile image. Billing records can include a Stripe customer identifier, subscription status, plan, renewal or cancellation status and promotion redemption. Support messages and limited technical diagnostics are also processed. Do not enter special-category information or another person’s information unless it is genuinely needed for your records and you are entitled to use it.'],
    ['Why does TaxMate use it?','TaxMate uses account, bookkeeping, receipt, backup, sync, partnership and entitlement information to provide the service or take steps you request before a contract. Payment and accounting records are used to perform paid services and meet legal obligations. Necessary security, abuse-prevention, promotion-integrity and strictly minimised error diagnostics support the legitimate interests of protecting and operating TaxMate. Optional usage measurement is based on consent and is off unless you enable it. TaxMate does not sell personal information or use bookkeeping records for advertising.'],
    ['Where is my data stored?','The app can work locally without an account; local records remain in your browser until you clear, reset or delete them. Signed-in personal records use Firebase Authentication, Cloud Firestore and Cloud Storage. The production Firestore database and server functions use the London region. Receipt Storage uses its configured United States location.'],
    ['Who receives my data?','Google and Firebase process sign-in, app security checks, cloud records, receipts and server functions. Stripe processes checkout, payment methods, invoices and subscriptions; TaxMate does not receive complete card details. Sentry processes minimised error reports. If you opt in, Google Analytics 4 processes a small approved set of value-free usage events. Namecheap forwards messages sent to the support address and Microsoft Outlook is the destination mailbox service. Browsers also connect to Google Fonts and software content-delivery networks for app assets. Professional advisers, regulators, courts or law-enforcement bodies may receive information where necessary and lawful.'],
    ['How long is it kept?','Local data remains until you remove it. Active-account cloud records remain while the account is used. Provider backups, logs, fraud-prevention records and legally required transaction records may remain for limited provider-defined or legally required periods.'],
    ['How do I delete my data?','Use <strong>Delete all my data</strong> for the authenticated deletion workflow. This removes the personal Firestore tree, receipt objects, promotion-redemption records, TaxMate’s Stripe customer object and Firebase Auth identity. If a partnership has another member, shared records remain for them and your membership is removed; if you are the last member, the partnership is deleted. A deletion request is complete only when the app reports server-side success.'],
    ['What are my privacy rights?','You can use TaxMate locally, correct records, export JSON, export a full ZIP containing available receipt binaries, withdraw analytics consent and request deletion. Depending on the lawful basis and circumstances, you may have rights of access, correction, erasure, restriction, objection and portability. You may object to processing based on legitimate interests by contacting TaxMate. Withdrawing consent does not affect earlier processing.'],
    ['Who runs TaxMate & how do I contact them?',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader and the controller for this service. ICO registration: <strong>ZC174150</strong>. Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>. Public correspondence and contact address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. TaxMate has not appointed a data protection officer.`],
    ['International transfers','Google, Stripe, Sentry and their subprocessors may process information in the UK, EEA, United States and elsewhere. Provider terms describe applicable adequacy arrangements, the UK Extension to the Data Privacy Framework and contractual safeguards such as the UK Addendum to standard contractual clauses. Contact TaxMate for further information about applicable safeguards.'],
    ['Analytics & error reporting','Optional analytics is off by default and limited to approved value-free events. Error reports are minimised to remove account identity, bookkeeping values, business names, notes, receipt content and unnecessary request details. You can change analytics consent in Settings.'],
    ['Complaints','Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a> about privacy or to exercise a right. You may complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>. Material policy changes will be dated and communicated appropriately.']
  ];
  const TERMS_SHORT=['TaxMate helps you keep records and estimate tax.','TaxMate does not file tax returns or MTD submissions.','Paid subscriptions renew until cancelled.','Downgrading never deletes your bookkeeping records.'];
  const TERMS_SECTIONS=[
    ['Using TaxMate','You must be at least 18 and able to enter a contract. By using TaxMate you agree to these terms. TaxMate helps UK self-employed users keep records, estimate selected Self Assessment amounts and create summaries or working-paper exports. You are responsible for lawful and accurate input, protecting your account and devices, keeping suitable backups, reviewing calculations and meeting deadlines. Do not upload unlawful content, malware or information you lack authority to use.'],
    ['Free, Plus & Pro','Free costs £0 and provides the core functions shown in the Free plan. Plus costs £3.99 per month or £29.99 per year and adds multiple businesses, receipt photos, mileage comparison and the PDF tax report. Pro costs £7.99 per month or £59.99 per year and adds Partner Sync, the SA104 partnership working paper, Receipt Pack PDF and quarterly record summaries. Paid access starts when the subscription is confirmed.'],
    ['Prices and renewal','Monthly and yearly options are recurring subscriptions. Before payment, Checkout shows the selected final price, renewal interval, included plan and payment method. Stripe Tax is off and no VAT amount is added to the listed price. Paid subscriptions renew until cancelled. A future price change applies only as disclosed for a future billing period.'],
    ['Cancellation and refunds','Cancel through <strong>Manage subscription</strong> or contact support. Cancellation stops future renewal and access normally continues until the end of the paid period. Cancelling does not delete records. Consumers may have a statutory cancellation period, normally 14 days for a distance service contract. By completing Checkout and using paid features immediately, you request that the service begin during that period. Contact support to exercise a cancellation right or request the model cancellation form. A successful full refund ends the refunded paid entitlement; an independent active promotion can still apply. A partial refund is marked for manual review and does not automatically change access. Nothing removes mandatory statutory rights.'],
    ['Promotion codes','A valid TaxMate promotion grants fixed-period or permanent Plus or Pro access. It requires no card, creates no Stripe subscription and never starts an automatic charge by itself. A fixed campaign ends at its stated expiry even if redeemed later. Disabling a code stops future redemptions but does not cancel grants already redeemed. A specific revocation is separate. TaxMate applies the highest active paid or promotional tier, and records remain preserved when access changes.'],
    ['Tax estimates and HMRC','TaxMate provides planning estimates and working aids, not tax, accounting or legal advice. It does not file Self Assessment returns or MTD updates, is not HMRC submission software and is not affiliated with HMRC. Exports are not official filings or proof that HMRC will accept a claim. Verify important figures with current HMRC guidance or a qualified adviser.'],
    ['Accounts and partnerships','Google is the only sign-in provider. A partnership code grants access to shared records, so share it only with an intended partner. Members can see shared records; new collaboration and write actions require Pro. If Pro ends, authorised historical access remains but new Pro-only collaboration stops. Account deletion removes your membership; records remain for other members and are deleted when the last member leaves.'],
    ['Data and backups','You retain rights in your records and permit TaxMate to process them only to provide the service as you direct. Keep suitable backups. Downgrading, cancelling or promotion expiry never deletes bookkeeping records, secondary businesses, existing receipt images or partnership history. Use the separate deletion control if you want account data removed.'],
    ['Availability and liability','TaxMate uses reasonable care and skill but cannot promise uninterrupted availability or compatibility with every device. TaxMate is responsible for foreseeable loss resulting from breach or failure to use reasonable care and skill, but not loss caused by inaccurate input, ignoring a clear warning, failing to keep a backup or treating an estimate as professional advice. Nothing limits liability where the law does not allow it, including fraud or death or personal injury caused by negligence.'],
    ['Who provides TaxMate & contact',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader. Public correspondence, contact and complaints address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. These terms are governed by the law of England and Wales; mandatory consumer protections where you live continue to apply. Questions, complaints, cancellation requests and requests for the model cancellation form: <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.`]
  ];
  function accordion(sections){return sections.map(([title,body])=>`<details class="content-accordion"><summary>${title}</summary><div class="content-body">${body}</div></details>`).join('');}
  function helpGroups(){return HELP_GROUPS.map(([group,items])=>`<section class="content-group"><h2>${group}</h2>${accordion(items)}</section>`).join('');}
  const helpHtml=`<div class="stitle">Help &amp; support</div><div class="s content-lede">Practical help for using TaxMate.</div>${helpGroups()}<div class="notice green"><strong>Still need help?</strong><br>Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.</div>`;
  const privacyHtml=`<div class="stitle">Privacy</div><div class="s content-lede">How TaxMate uses your information.</div><div class="s content-date">Last updated: ${LAST_UPDATED}</div>${accordion(PRIVACY_SECTIONS)}`;
  const termsHtml=`<div class="stitle">Terms of use</div><div class="s content-date">Last updated: ${LAST_UPDATED}</div><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>${accordion(TERMS_SECTIONS)}`;
  function publicPage(kind){
    const config={help:{title:'Help & Support | TaxMate UK',description:'Practical help for TaxMate bookkeeping, tax estimates, receipts, plans, backups and partnerships.',robots:'index,follow,max-image-preview:large',heading:'Help & support',lede:'Practical help for using TaxMate.',body:helpGroups()+`<div class="public-contact"><strong>Still need help?</strong><br>Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.</div>`},privacy:{title:'Privacy | TaxMate UK',description:'How TaxMate uses account, bookkeeping, receipt, billing, analytics and error-reporting information.',robots:'noindex,follow',heading:'Privacy',lede:'How TaxMate uses your information.',body:`<p class="public-date">Last updated: ${LAST_UPDATED}</p>`+accordion(PRIVACY_SECTIONS)},terms:{title:'Terms of use | TaxMate UK',description:'Terms for TaxMate Free, Plus, Pro and promotion access.',robots:'noindex,follow',heading:'Terms of use',lede:'The terms for using TaxMate.',body:`<p class="public-date">Last updated: ${LAST_UPDATED}</p><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>`+accordion(TERMS_SECTIONS)}}[kind];
    if(!config)throw new Error('Unknown public page');
    return`<!doctype html>\n<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${config.title}</title><meta name="description" content="${config.description}"><meta name="robots" content="${config.robots}"><link rel="canonical" href="https://www.taxmate.uk/${kind}.html"><style>html{background:#f3f6f4}@media(prefers-color-scheme:dark){html{background:#101714}}html[data-theme=dark]{background:#101714}html[data-theme=light]{background:#f3f6f4}</style><script src="/src/app/public-theme.js"></script><link rel="stylesheet" href="/src/app/public-pages.css"></head>\n<body><main class="public-shell"><a class="brand" href="/">TaxMate</a><header><h1>${config.heading}</h1><p>${config.lede}</p></header>${config.body}<nav class="public-nav"><a href="/">TaxMate</a><a href="/help.html">Help</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></nav></main></body></html>\n`;
  }
  return Object.freeze({POLICY_VERSION,LAST_UPDATED,PUBLIC_CORRESPONDENCE_ADDRESS,HELP_GROUPS,PRIVACY_SECTIONS,TERMS_SHORT,TERMS_SECTIONS,helpHtml,privacyHtml,termsHtml,publicPage});
});
