(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.TaxMateLegal=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const POLICY_VERSION='2026-09-14.store-auth.1',LAST_UPDATED='14 September 2026',PRIVACY_LAST_UPDATED='14 September 2026';
  const PUBLIC_CORRESPONDENCE_ADDRESS='Unit 170198, PO Box 7169, Poole, BH15 9EL';
  const HELP_GROUPS=[
    ['Account, sign-in & first steps',[
      ['Can I use TaxMate if I do not understand accounting?','Yes. TaxMate is designed for people who want to record what came in and what went out without learning accounting jargon. Add each item in plain language and TaxMate organises the supported totals and estimates.'],
      ['Do I need an account to start?','No. Choose <strong>Start without an account</strong> to use the core app on that device. Sign in when you want cloud backup, cross-device sync or a feature that requires an account.'],
      ['How do I create a TaxMate account?','Choose <strong>Sign in</strong> or <strong>Continue with Google</strong> and complete the provider screen. Google Sign-In creates or opens the linked TaxMate account, so there is no separate TaxMate password-registration form.'],
      ['Which sign-in method should I use?','Use an option actually shown in your version. Google Sign-In is available on Web and Android. Sign in with Apple appears only in a supported iOS version.'],
      ['Do I need a TaxMate verification code?','TaxMate does not send a separate email or SMS login code for Google Sign-In. Google or your device may ask you to confirm your identity. Partner Sync codes and promotion codes are different and cannot be used to sign in.'],
      ['Does TaxMate charge an account or verification fee?','No. TaxMate does not charge a separate fee to create an account, sign in, verify a Google identity or check Companies House details. A paid plan starts only after you review and confirm the price shown by the payment provider.'],
      ["I can't sign in",'Check that you are online, allow the Google sign-in popup if you are using a browser, and choose the intended Google account. Close duplicate sign-in windows and try once more. If it still fails, use the troubleshooting details below before contacting support.'],
      ['Why did Google ask me to verify my identity?','Google controls its own account-security checks. Complete them only on a genuine Google screen. TaxMate never needs your Google password, backup codes or complete card details.'],
      ['I signed in with the wrong Google account','Sign out, then sign in again and choose the Google account that owns your TaxMate data. Do not restore or overwrite records until the app has shown whether that account already contains data.'],
      ['Why am I being asked to choose between device data and cloud data?','TaxMate avoids silently combining two different record sets. Review which account contains the records you want. If the data matters, make a local backup before choosing or replacing anything.'],
      ['Can I switch from device-only use to an account later?','Yes. Sign in from the Account section. TaxMate will check the selected cloud account before associating or opening data so that existing records are not silently mixed.'],
      ['What happens when I sign out?','Your supported cloud data remains linked to the signed-in account, and data already stored on this device is not automatically erased. Sign in with the same account to reconnect.'],
      ['How do I begin after signing in?','Choose a guided setup for a sole trader or partnership, set up a Limited Company if eligible, enter a Partner Sync code, or go directly to the dashboard if you already know what you need.']]],
    ['Businesses & catch-up setup',[
      ['How do I add my first business?','Choose <strong>Add a business</strong>, enter a name and select the correct structure. TaxMate then uses that business for its income, expenses and supported tax calculations.'],
      ['Should I choose sole trader or partnership?','Choose sole trader when you work for yourself and keep the business profit. Choose partnership when two or more people run the business and your tax position uses your agreed share of partnership profit.'],
      ['What should I use as the business name?','Use a name that helps you recognise the work. A sole trader can use a simple description such as the trade or client-facing name; a partnership should use the partnership name used for its records.'],
      ['What does my partnership profit share mean?','It is the percentage of partnership profit treated as yours in TaxMate. Enter the agreed share, not the percentage of individual expenses you happened to pay.'],
      ['Can I add more than one business?','Free includes one business. Multiple businesses require Plus or Pro. The plan screen shows the current feature limits before you upgrade.'],
      ['Can I add earlier months?','Yes. Use the catch-up flow, choose the correct business and start month, then add income, expenses and supported mileage month by month.'],
      ['Why does the catch-up flow ask for a start month?','It uses the first month you want to enter and then takes you through the remaining months in that UK tax year. It does not invent records for months you skip.'],
      ['Can I leave catch-up and finish later?','Yes. Save the records you have entered and return to ordinary Income or Expenses screens later. Review the dashboard for items that still need tidying.'],
      ['How do I edit a business?','Open <strong>Settings → Your businesses</strong>, choose the business and edit the supported details. Structural changes can affect calculations, so review the tax estimate afterwards.'],
      ['What happens if I delete a business?','Deleting a business also deletes its linked income and expense entries from the affected data set. Export a backup first because there is no ordinary undo. Shared partnership and cloud deletion rules may require additional confirmation.'],
      ['Why is the UK tax year April to April?','TaxMate groups sole-trader and partnership records by the UK tax year, which runs from 6 April to 5 April. Select the year that contains the transaction date.']]],
    ['Income, expenses & organising records',[
      ['How do I add income?','Open <strong>Income</strong> and tap <strong>Add income</strong>. Enter the amount, date, business and category, then save. The supported totals and tax estimate update from the saved record.'],
      ['How do I add an expense?','Open <strong>Expenses</strong> and tap <strong>Add expense</strong>. Enter the amount, date, business, category and business-use percentage where needed, then save.'],
      ['What amount should I enter?','Enter the actual transaction amount shown by your record. Do not enter a zero or negative amount; choose the correct income or expense flow and use the note field for useful context.'],
      ['What does the business-use percentage mean?','Use it when only part of a cost was for business. For example, enter 50% when half of a bill was business use. Use a fair, supportable split and keep evidence.'],
      ['Why did an entry appear in another tax year?','TaxMate places an entry in the UK tax year containing its date. Edit the date if it is wrong; do not duplicate the entry just to move it.'],
      ['Can I edit an income or expense later?','Yes. Open the entry, choose Edit, make the change and save. Review any tax estimate or report that used the old value.'],
      ['Can I delete a single entry?','Yes. Open the entry and use <strong>Delete this entry</strong>. The deletion is permanent for that record, so check the business, date and amount first.'],
      ['How does Repeat monthly work?','Select only the months that genuinely contain the same repeating expense. The original month counts once, and a shorter month uses its last valid day when needed. Review the summary before saving.'],
      ['Why was no repeating expense added?','Choose at least one month or switch the item to One-off. Months outside the selected tax year cannot be added by that repeat action.'],
      ['Can I change or create categories?','Yes. Use <strong>My categories</strong> to add, rename or reset supported categories. Suggested categories are optional and can be changed later.'],
      ['What happens if I remove a category?','Existing entries keep their transaction data. Depending on the category state, they may keep the old label or display as Other until you reclassify them.'],
      ['What are folders for?','Folders are optional labels for organising entries. Removing a folder does not delete the entries inside it.'],
      ['Can I filter records by business, folder or category?','Use the filters shown on the Income or Expenses screen. A filter changes what you see; it does not delete or alter the underlying records.'],
      ['Can I record mileage instead of vehicle receipts?','TaxMate can track a supported annual business-mileage total and, on Plus or Pro, compare mileage with logged vehicle costs. Do not claim both methods for the same vehicle costs; confirm the appropriate method for your circumstances.']]],
    ['Tax estimates, HMRC & deadlines',[
      ['How is my tax estimate calculated?','TaxMate uses the supported tax-year rules and the income, expense and adjustment information you enter. It is a planning estimate, not your final HMRC calculation.'],
      ['Why did my tax estimate change?','It updates when you add, edit or remove relevant income, expenses, business-use percentages, mileage or HMRC-position adjustments. Check the selected year and completeness of every business before relying on it.'],
      ['Does TaxMate submit my tax return?','No. TaxMate organises records, prepares supported figures and guides you to an official or eligible filing route. You still submit the return separately. TaxMate is not affiliated with HMRC.'],
      ['Is the estimate my official tax bill?','No. HMRC determines the official position after the required return and information are submitted. Treat the TaxMate amount as a planning figure and check material decisions with HMRC or a qualified adviser.'],
      ['Which UK tax regions are supported?','The personal estimate uses the supported rates for England, Wales and Northern Ireland. Scottish Income Tax bands differ, so do not treat that estimate as a complete Scottish calculation.'],
      ['What income is not included in the simple estimate?','The ordinary estimate assumes the supported self-employed and partnership information entered in TaxMate. PAYE employment, savings interest, dividends, student loans and other personal circumstances may need separate treatment unless the screen explicitly supports them.'],
      ['What is the £1,000 trading allowance?','For eligible sole-trader income, TaxMate can compare the £1,000 trading allowance with actual expenses and show which produces the lower estimated taxable profit. It does not apply to partnership income.'],
      ['Why did TaxMate choose allowance instead of expenses?','Auto selects the supported option that gives the lower taxable profit from the information entered. You can inspect the comparison before relying on it.'],
      ['What is Personal Allowance?','It is the supported tax-free amount used in the estimate, subject to the rules and reductions shown for the selected year. Other income outside TaxMate can change how much allowance remains.'],
      ['What are Class 2 and Class 4 National Insurance?','They are National Insurance treatments linked to self-employed profits. TaxMate shows the supported position for the selected year, including when voluntary Class 2 may be relevant; confirm eligibility before paying.'],
      ['What are payments on account?','They are advance payments HMRC may require towards the following tax year. TaxMate can estimate them and include the figures you enter from your HMRC position.'],
      ['Why is 31 January larger than 31 July?','The January amount can include a balancing payment for the earlier year plus the first payment on account. July normally shows the second payment on account. Your actual HMRC statement controls.'],
      ['What should I enter as payments on account already made?','Enter the total advance payments HMRC asked for and that apply to the selected year, or zero if none. Use your HMRC records rather than guessing.'],
      ['What is an adjustment from last year?','Use a positive amount for an earlier underpayment carried forward and a negative amount for an overpayment being deducted, following the HMRC position shown to you.'],
      ['What if the estimate suggests a refund or overpayment?','It is only an indication from the entered data. HMRC decides the final amount due or refundable after filing and reconciliation.'],
      ['Can I reduce payments on account?','HMRC may allow a reduction when you reasonably expect lower profit, but interest can apply if you reduce too far. TaxMate does not submit that request for you.'],
      ['How does TaxMate help with Self Assessment?','It organises records and maps supported figures to SA103 sole-trader or SA104 partnership references. The mapping is a working aid, not a filed return.'],
      ['Why are future Self Assessment boxes unavailable?','TaxMate does not guess a form mapping before the official short-form mapping for that tax year is bundled. Keep the records and wait for a supported mapping or use current official guidance.'],
      ['What does TaxMate do for Making Tax Digital (MTD)?','TaxMate helps keep digital records, assess supported thresholds and prepare MTD quarterly updates, then guides you to an HMRC-compatible submission route when available. It does not itself submit an MTD update.'],
      ['Why does MTD say my information is incomplete?','Add all relevant gross qualifying income requested by the screen. TaxMate withholds a conclusion when required income or an official threshold mapping is missing.'],
      ['Can I add the tax deadlines to my calendar?','Yes. Use the calendar export to download the available UK tax dates with reminders, then open the file in your calendar app. Always check the final deadline against your HMRC position.']]],
    ['Receipts, reports & exports',[
      ['How do I add a receipt photo?','On Plus or Pro, open an expense and choose <strong>Take photo</strong> or <strong>Choose existing photo</strong>. The image is linked to that expense.'],
      ['Can I add receipts later?','Yes. Use the Receipts workflow to filter expenses that still need evidence and attach an image later.'],
      ['What file can I use for a receipt?','Use a supported image file. Make sure the supplier, date and amount are readable before uploading.'],
      ['Can I attach two receipts to one expense?','The current workflow expects one receipt image for an expense. If two pieces of evidence belong together, place them clearly side by side in one image without hiding any details.'],
      ['Does taking a receipt photo automatically create the expense?','No. The supported receipt flow links an image to an expense record. Check that the expense amount, date, business and category are saved correctly.'],
      ['Can I delete a receipt without deleting the expense?','Yes. Deleting the linked receipt image does not delete the expense entry.'],
      ['What happens to receipt photos if I downgrade?','New paid receipt uploads and Receipt Pack PDF export stop on Free. Download the Receipt Pack and keep a Full Backup ZIP while paid access is active.'],
      ['What is the Receipt Pack?','It is a paid PDF export that arranges linked receipt photos with their details for review. It is not an HMRC submission or a restore file.'],
      ['What is the PDF tax report?','It is a paid summary of supported records and estimates for review or sharing. It is not tax advice, an official return or proof of filing.'],
      ['Why are PDF reports in English?','TaxMate currently generates its PDF reports in English. Use English for business or category names that must display reliably in the PDF.'],
      ['What is the accountant pack or CSV export?','It is a tabular export of supported entries for review in spreadsheet or accounting workflows. Check the selected year and filters before sending it.'],
      ['Why is my report empty?','Confirm you selected the correct tax year and business and that saved entries exist in that period. Filters can also hide otherwise valid records.']]],
    ['Plans, checkout & billing',[
      ['What is included in Free?','Free covers core income and expense records, one business, supported tax estimates, basic mileage totals, SA103 reference, cloud sync and backup or restore as shown on the current Free plan card.'],
      ['What is Plus?','Plus adds multiple businesses, receipt photos, Receipt Pack PDF, mileage comparison, Helper features and the PDF tax report as shown on the current plan card.'],
      ['What is Pro?','Pro includes Plus and adds Partner Sync, the SA104 partnership working paper, MTD quarterly record preparation and one active Limited Company. Limited Company actions are Pro-only.'],
      ['Do Plus or Pro require an account?','Yes. Sign-in lets TaxMate bind paid access to the correct account and verify it across supported devices.'],
      ['What do monthly and yearly mean?','They are renewal intervals. The checkout screen must show the selected plan, final price and interval before you confirm payment.'],
      ['What are the current listed prices?','Plus is £3.99 monthly or £29.99 yearly. Pro is £9.99 monthly at launch, with an approved standard monthly price of £11.99, or £99.99 yearly. Check the final provider screen before paying.'],
      ['Will TaxMate charge VAT or a verification fee at checkout?','TaxMate does not add a separate account or verification fee. The current Web checkout contract has Stripe Tax off, so the amount to confirm should be the displayed plan price after any valid discount. Do not approve an unexpected amount.'],
      ['Why does my bank show a pending card check?','A bank or payment provider can display its own pending authorisation or security check. It is not proof that TaxMate access has started. Check the final receipt and plan status; contact the payment provider about an unexplained bank hold.'],
      ['What confirmation should I see before payment?','Review the plan, renewal interval, final amount, included access and payment method. Do not continue if the confirmation is incomplete or different from what you selected.'],
      ['Why is checkout unavailable?','Purchases stay disabled when required payment, consumer or supplier information is not ready, or when the provider cannot safely verify the account. No plan should change without a successful confirmed payment.'],
      ['What happens after a successful payment?','The provider result must be verified and projected to your TaxMate account before paid access is active. If payment succeeded but the plan does not update, avoid paying again and use the troubleshooting steps below.'],
      ['What happens if payment fails or is abandoned?','Your existing funded access remains until its valid end. An unsuccessful checkout does not grant the new plan and should not create an extra free paid period.'],
      ['How do I change from Plus to Pro?','Review the upgrade quote before confirming. Pro becomes active only after the required difference payment succeeds; the quote can account for eligible unused paid time.'],
      ['How do I change from Pro to Plus?','A supported downgrade normally keeps Pro until the paid period ends and then renews the same subscription as Plus. Review the effective date shown before confirming.'],
      ['How do I cancel?','Open <strong>Manage subscription</strong> and follow the provider route shown. Cancellation stops the next renewal; funded access normally continues to the end of the period already paid for.'],
      ['Is cancelling the same as requesting a refund?','No. Cancelling stops a future renewal. A refund request asks for review of a payment already made. Use the correct action for what you want.'],
      ['How do I request a refund?','Open <strong>Manage subscription → Request a refund</strong> and choose the relevant payment. A refund request is separate from cancelling renewal. TaxMate records the request and review status; any approved refund is returned through the payment provider.'],
      ['When will an approved refund appear?','TaxMate records provider submission and confirmation separately. The payment provider or card issuer controls when confirmed funds become visible, so a request status is not the same as money already returned.'],
      ['What happens to access after a refund?','A successful full refund removes the entitlement funded by that payment, not unrelated valid access. A partial refund does not automatically change the plan.'],
      ['Where can I find my invoice or payment record?','Open <strong>Manage subscription</strong> and use the invoice or payment link provided for your billing route. TaxMate never needs your complete card number.'],
      ['How do promotion codes work?','A valid promotion can grant Plus or Pro without a card or paid subscription. It never starts an automatic charge by itself and may have a fixed expiry or redemption limit.'],
      ['Why was my promotion code rejected?','Check every character, expiry and eligibility. A code may be invalid, exhausted, already redeemed, disabled for new redemptions or linked to a different account. Do not confuse it with a Partner Sync code.'],
      ['What happens to my records after paid access ends?','Paid reports and paid features stop at effective expiry. If you remain Free, historical account data follows the tax-year retention rule described in the app. Download needed reports and make a Full Backup ZIP before access ends.']]],
    ['Cloud sync, backup & devices',[
      ['How does cloud sync work?','When signed in, supported personal records sync through TaxMate’s Firebase services so they can follow the same account across devices.'],
      ['Can I use TaxMate offline?','Core local use can continue offline. Cloud sync, sign-in, receipt upload, provider checks and other network-dependent actions wait until a connection is available.'],
      ['What do Synced, Syncing and Waiting mean?','Synced means the current supported changes reached the cloud. Syncing means work is in progress. Offline, waiting or retrying means some changes have not yet been confirmed remotely. Keep the app open and reconnect before changing devices.'],
      ['I changed phone — how do I get my data?','Sign in with the same TaxMate account and wait for the cloud check to finish. Keep a Full Backup ZIP as independent protection, especially before replacing or wiping the old phone.'],
      ['Can two devices edit at the same time?','Signed-in supported records can sync, but simultaneous offline edits can take time to reconcile. Wait for Synced before switching devices and review important records afterwards.'],
      ['What backup should I use?','Use <strong>Full backup</strong> for a ZIP containing TaxMate records and available receipt image files. JSON is data-only and does not include receipt binaries.'],
      ['Is a PDF or CSV a backup I can restore?','No. PDF and CSV exports are for reading or review. Use a TaxMate JSON or Full Backup ZIP accepted by the Restore flow.'],
      ['How do I restore a backup?','Choose <strong>Restore from backup</strong>, select a valid TaxMate backup and review the confirmation. Restore replaces current local data, so create a fresh backup first.'],
      ['Why does restore say the file is invalid?','Use an unmodified TaxMate backup of a supported type. A report, screenshot, random ZIP or manually edited JSON is not a valid restore file.'],
      ['Will restoring a paid backup unlock paid features?','No. Restore returns eligible records and available receipt files; it does not grant Plus or Pro. Current account entitlement still controls paid actions.'],
      ['What happens to receipt files restored on Free?','Eligible receipt files can remain on the restoring device, but new paid receipt actions and paid exports remain locked. Include those files in the next Full Backup ZIP you keep.'],
      ['Should I back up if cloud sync is on?','Yes. Cloud sync supports continuity, while a local Full Backup ZIP gives you an independent copy for recovery and record keeping.']]],
    ['Partnerships & Partner Sync',[
      ['How do I create a partnership business?','Add a business, choose Partnership and enter your agreed profit share. You can keep local figures without Partner Sync, or connect members with Pro.'],
      ['What is a Partner Sync code?','It is an 8-character code used to connect an intended partner to one partnership business. It is not a login code, payment code, promotion code or HMRC code.'],
      ['How do I join a partnership?','Sign in, choose <strong>Enter a Partner Sync code</strong> or the join action, enter the 8-character code and review <strong>Connect this business?</strong> before confirming. Pro access is required for new collaboration.'],
      ['How do I invite my partner?','Save the partnership business first, then use <strong>Invite my partner</strong> to copy or share the secure joining link or code.'],
      ['Why does the partnership code not work?','Check all eight characters, your connection, sign-in account and Pro access. The code may be mistyped, unavailable or linked to a partnership you cannot join.'],
      ['Can my partner see my personal records?','No. Partner Sync shares the connected partnership business records. Your separate personal and sole-trader records stay private.'],
      ['What records can partnership members see?','Authorised members can see records belonging to the connected partnership. Do not enter unrelated personal or sole-trader records into that shared business.'],
      ['What happens if Pro ends?','New Pro-only collaboration and write actions stop. Authorised retained history follows the entitlement and retention rules shown by the app.'],
      ['How do I stop syncing or leave?','Use the stop-sync or leave action for the relevant partnership. Your membership is removed; shared records remain for other authorised members.'],
      ['What happens when the last partner leaves?','When no authorised member remains, the approved partnership deletion lifecycle applies. Make any required records or backups before leaving.']]],
    ['Limited companies & Companies House',[
      ['Can TaxMate manage a Limited Company?','Pro supports one active UK private limited company within the documented scope. It is separate from sole-trader or partnership records.'],
      ['Can I start before the company is registered?','Yes. Choose the forming-company route to save a working name and continue later. Official Companies House facts cannot be labelled verified until the registered company is checked.'],
      ['How do I add an existing registered company?','Choose the registered-company route, enter the Companies House number, run the check and review the returned legal name, date, status and type before saving.'],
      ['What does the Companies House check verify?','It retrieves a public-record snapshot for the company number. You must still review the facts. Editing a verified fact marks it as needing checking while retaining the last official snapshot.'],
      ['Does the Companies House check cost a verification fee?','No. TaxMate does not charge a separate Companies House verification fee. Pro entitlement may be required for Limited Company actions, but the verification check is not an extra paid item.'],
      ['Why could TaxMate not find my company?','Check the eight-digit company number and whether registration is complete. A temporary provider problem is different from a not-found result; retry later or enter supported facts manually when the app allows it.'],
      ['What does needs checking mean?','It means a fact is manual, changed since the official snapshot, unsupported or otherwise not currently verified. Review it against Companies House or another authoritative record.'],
      ['What company income and costs can I record?','The company workspace supports the documented company money flows, including company income, company costs and supported personally paid or shared-expense treatments. Use the correct owner and payment account.'],
      ['What does Company owes you mean?','It records supported amounts the company owes to you, such as qualifying personally funded company costs or director-loan movements. It is not ordinary personal income.'],
      ['How do salary and dividends work?','Use the dedicated salary and dividend flows and enter only amounts actually supported by company records and decisions. TaxMate does not run payroll, create legal dividend paperwork or replace professional advice.'],
      ['Can I record money lent to or repaid by my company?','Yes, use the dedicated director-loan or company-repayment action so the direction and balance are recorded correctly. Do not enter the same movement again as ordinary income or expense.'],
      ['How is Corporation Tax estimated?','TaxMate uses supported company events, accounting periods, tax adjustments, losses and eligible allowances. The result is a planning estimate and working calculation, not an HMRC assessment.'],
      ['Does TaxMate file CT600 or company accounts?','No. TaxMate prepares supported figures and working packs and guides you to the appropriate HMRC or Companies House filing route. It does not submit statutory accounts or a CT600.'],
      ['Why is my Limited Company calculation incomplete?','Required company dates, transactions, ownership, adjustments, evidence or confirmations may be missing or need review. Follow the outstanding tasks instead of treating a partial figure as final.'],
      ['Can I add a second Limited Company or invite a company collaborator?','The current documented scope supports one active Limited Company and does not support a second company or Limited Company collaboration.'],
      ['What happens to Limited Company data if Pro ends?','New Pro-only company actions stop. Plus can retain eligible LTD history without enabling Pro operations; Free follows the whole-account tax-year retention rule. Make a Full Backup ZIP before access changes.']]],
    ['Install, language & appearance',[
      ['How do I install TaxMate on Android?','Use the in-app Download or Install action when available. Otherwise open the browser menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.'],
      ['How do I install TaxMate on iPhone?','Open TaxMate in Safari, use the Share button, choose <strong>Add to Home Screen</strong> and confirm Add. The iPhone web install flow does not work the same way in Chrome.'],
      ['Why do I only see Add to Home Screen instead of Install app?','Browser support and cache state can affect the prompt. Close and reopen the site, check the browser menu and follow the device-specific instructions shown by TaxMate.'],
      ['Do I have to install the app?','No. You can use the supported Web version in a browser. Installing adds a convenient home-screen app experience.'],
      ['How do I change language?','Open <strong>Settings → Language</strong> and choose an available language. User-entered names remain as you typed them.'],
      ['Why is part of a PDF still in English?','PDF reports are currently generated in English. Type important business and category names in English when they must appear reliably in the exported PDF.'],
      ['How do I change light or dark mode?','Open <strong>Settings → Appearance</strong> and choose Auto, Light or Dark. Auto follows the supported device or browser preference.'],
      ['Will changing language or theme change my records?','No. It changes presentation, not saved transaction amounts, dates or business ownership.']]],
    ['Privacy, security & deleting data',[
      ['Where is my data stored?','Device-only records remain in the local app or browser storage. Signed-in supported records use TaxMate cloud services. Receipt storage and provider systems can use the locations described in the Privacy notice.'],
      ['Does TaxMate sell my bookkeeping data or use it for advertising?','No. TaxMate does not sell bookkeeping data or use it for advertising. Optional usage measurement remains off unless you enable it.'],
      ['What should I never send to support?','Never send passwords, Google backup codes, complete card details or unnecessary sensitive receipt images. Describe the screen, device, time and error without exposing secrets.'],
      ['Is TaxMate affiliated with HMRC or Companies House?','No. TaxMate uses supported rules and public Companies House information but is not HMRC, Companies House or an official filing service.'],
      ['How long should I keep my own records?','You remain responsible for the statutory records required for your circumstances. TaxMate retention is a service rule, not a replacement for legal record-keeping duties; keep suitable exports and backups.'],
      ['What is the difference between deleting this device and deleting my account data?','<strong>Delete all data on this device</strong> clears the local copy. <strong>Delete all my data</strong> is the authenticated cloud deletion flow and also removes the supported personal cloud data after required checks.'],
      ['What happens when I delete my account data?','The confirmed flow removes supported personal TaxMate app data from this device and cloud, removes your partnership membership and signs you out. It does not delete the Firebase Authentication sign-in identity. An account-reset marker, server-only provider billing records and deletion tombstones can remain for security, fraud prevention, refunds, disputes, legal obligations and later provider events. Shared partnership records needed by other authorised members can also remain.'],
      ['Why can an active subscription block deletion?','TaxMate must reconcile active, pending or uncertain provider billing before deleting the app data, otherwise a later provider event could recreate inconsistent access. Manage the subscription and retry.'],
      ['Can deleted data be recovered by signing in again?','No. Signing in again starts a fresh, empty TaxMate data lifecycle for that sign-in identity. Restore only from a backup you kept; restoring does not return paid entitlement.']]],
    ['Troubleshooting',[
      ['My data is not syncing','Confirm that you are online and signed into the expected account. Keep the app open until the status changes, and create a local backup before signing out, clearing storage or reinstalling.'],
      ['My receipt will not upload','Check your connection, sign-in state, Plus or Pro access and that the selected file is a supported image. Retry once without changing the expense.'],
      ['Checkout does not open','Check the connection and popup or provider window, then retry once. If it remains unavailable, no plan should change; do not create repeated payments.'],
      ['I paid but my plan did not update','Do not pay again. Confirm the provider receipt, use the same TaxMate account, reconnect and wait for verification. If it still does not update, contact support with the provider, plan, time and non-sensitive receipt reference.'],
      ['The app says my purchase could not be verified','Make sure the purchase belongs to the same signed-in account and provider. Reconnect and retry the restore or verification action. Do not share a purchase token or complete payment details by email.'],
      ['A feature is locked even though I previously paid','Check the current account, provider status, paid period and whether the feature belongs to Plus or Pro. A cancelled but still funded period should remain until its effective end; an expired or refunded entitlement may not.'],
      ['My promotion or Partner Sync code is not accepted','Confirm which type of code you have. Promotion codes unlock a plan; Partner Sync codes connect a partnership. Check characters, account, expiry or eligibility, then retry the matching flow.'],
      ['My tax estimate looks wrong','Check the tax year, business structure, dates, amounts, business-use percentages, missing records and HMRC-position adjustments. Also consider income types TaxMate does not include.'],
      ['An entry or business has disappeared','Clear active filters, switch to the correct tax year and business, and wait for sync. Do not restore an older backup until you have checked the current cloud account and exported what remains.'],
      ['My figures are duplicated','Check whether catch-up, Repeat monthly, restore or multi-device work added the same transaction twice. Compare dates, amounts and businesses before deleting only the confirmed duplicate.'],
      ['A download or export did not appear','Check browser download permissions, available storage and the selected year. Try once more and look in the device Downloads folder; avoid repeatedly generating large Receipt Packs.'],
      ['The app will not install or update','Use a supported browser, reconnect and reopen the site. On iPhone use Safari Add to Home Screen; on Android check the browser install menu. Do not clear app data unless you have a backup or confirmed cloud sync.'],
      ['The screen is blank or stuck','Reconnect, close duplicate tabs and reopen TaxMate. If records are visible elsewhere, create a backup before clearing site data, reinstalling or resetting anything.'],
      ['What information should I include when contacting support?','Include what you were trying to do, the exact screen and message, device and browser or app version, approximate time, sign-in provider and whether sync showed Synced. Remove passwords, codes, card details and sensitive record images.'],
      ['When should I contact HMRC or an accountant instead of TaxMate support?','Contact HMRC or a qualified adviser for official filing status, tax treatment, payment arrangements or advice specific to your circumstances. TaxMate support can help with how the app behaves, not decide your legal tax position.']]]
  ];
  const PRIVACY_SECTIONS=[
    ["What information does TaxMate use?","TaxMate can process business and Limited Company names and types; Companies House identity checks and public-record snapshots; incorporation, trading, accounting-period and Corporation Tax facts; director, shareholder and effective-dated ownership records; income, expense, salary, dividend, loan, share-funding, evidence, mileage, category, date and note records; tax-year adjustments; receipt images; backup files; partnership membership and shared records; and app preferences. Your chosen sign-in provider supplies a provider-linked account identifier and may supply your name, email address and profile information made available through that provider. Billing records can include Stripe customer, Checkout session, subscription, invoice, payment, charge and refund identifiers and statuses; Google Play obfuscated account identifiers, purchase tokens and token hashes, product details and subscription status; and App Store app-account tokens or hashes, transaction and original-transaction identifiers or hashes, product and subscription status, and signed transaction, renewal and notification data used for server verification. Promotion redemptions, support messages and limited technical diagnostics are also processed. Do not enter another person’s information unless it is genuinely needed for company records and you are entitled to use it. Billing support also records payment and refund amounts, customer requests, replies, staff decisions and calculation references, status history, plan-change quotes and versioned purchase confirmations. Access to private casework is restricted to authorised staff; bookkeeping backups do not include it."],
    ['Why does TaxMate use it?','TaxMate uses account, bookkeeping, receipt, backup, sync, partnership and entitlement information to provide the service or take steps you request before a contract. Payment and accounting records are used to perform paid services and meet legal obligations. Necessary security, abuse-prevention, promotion-integrity and strictly minimised error diagnostics support the legitimate interests of protecting and operating TaxMate. Optional usage measurement is based on consent and is off unless you enable it. TaxMate does not sell personal information or use bookkeeping records for advertising.'],
    ['Where is my data stored?','The app can work locally without an account; local records remain in your browser until you clear, reset or delete them. Signed-in personal records use Firebase Authentication, Cloud Firestore and Cloud Storage. The production Firestore database and server functions use the London region. Receipt Storage uses its configured United States location.'],
    ['Who receives my data?','Google and Firebase process sign-in, app security checks, cloud records, receipts and server functions. Stripe processes web checkout, payment methods, invoices and subscriptions; TaxMate does not receive complete card details. Google Play processes Android in-app subscription purchases and status. If an iOS App Store version is available and you use it, Apple processes its subscription purchases, signed transaction verification, subscription status and refunds. Sentry processes minimised error reports. If you opt in, Google Analytics 4 processes a small approved set of value-free usage events. Namecheap forwards messages sent to the support address and Microsoft Outlook is the destination mailbox service. Browsers also connect to Google Fonts and software content-delivery networks for app assets. Professional advisers, regulators, courts or law-enforcement bodies may receive information where necessary and lawful.'],
    ['How long is it kept?','Effective Plus or Pro retains historical bookkeeping data across the whole account. If paid access ends and you remain Free, that history is kept through the following 5 April and deleted from 6 April. This covers ordinary and self-employed records, your partnership history, LTD records and associated receipts. New-year Free records, authentication and billing data, and shared records needed by other members are protected. Connected devices remove expired local history, rollback copies and stale queued writes when they receive the server deletion control; an offline device cannot receive that control until it reconnects. A device-only account without a verified paid-end date is not assigned an invented expiry. After account-data deletion, TaxMate retains the Firebase Authentication sign-in identity and account-reset marker, together with server-only Stripe, Google Play and App Store billing mappings, provider-event records and deletion tombstones. Retention of these records is determined by security, fraud-prevention, refund or dispute, legal record-keeping and provider-lifecycle needs. They are separated from a later account lifecycle and are not used to restore deleted app data. This service retention period does not replace your statutory record-keeping duties. Provider backups, logs, fraud-prevention records and legally required transaction records may remain for provider-defined or legally required periods.'],
    ['How do I delete my data?','Use <strong>Delete all my data</strong> for the authenticated deletion workflow. Before deletion can proceed, any active, pending or otherwise uncertain Stripe, Google Play or App Store subscription must be managed with the relevant provider or reconciled by TaxMate. After server-side success, the app removes your personal Firestore tree, receipt objects, promotion-redemption records and local TaxMate data, then signs you out. It does not delete the Firebase Authentication sign-in identity. That authentication record, including the account identifier and provider-linked sign-in details, is retained with an account-reset marker and server-only provider billing links, status history and deletion tombstones needed for security, legal obligations and later provider events. If a partnership has another member, shared records remain for them and your membership is removed; if you are the last member, the partnership is deleted. Signing in again with the same sign-in account starts a fresh, empty TaxMate data lifecycle; deleted data is not restored. A deletion request is complete only when the app reports server-side success.'],
    ['What are my privacy rights?','You can use TaxMate locally, correct records, export JSON, export a full ZIP containing available receipt binaries, withdraw analytics consent and request deletion. Depending on the lawful basis and circumstances, you may have rights of access, correction, erasure, restriction, objection and portability. You may object to processing based on legitimate interests by contacting TaxMate. Withdrawing consent does not affect earlier processing.'],
    ['Who runs TaxMate & how do I contact them?',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader and the controller for this service. ICO registration: <strong>ZC174150</strong>. Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>. Public correspondence and contact address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. TaxMate has not appointed a data protection officer.`],
    ['International transfers','Google, Stripe, Apple, Sentry and their subprocessors may process information in the UK, EEA, United States and elsewhere. Provider terms describe applicable adequacy arrangements, the UK Extension to the Data Privacy Framework and contractual safeguards such as the UK Addendum to standard contractual clauses. Contact TaxMate for further information about applicable safeguards.'],
    ['Analytics & error reporting','Optional analytics is off by default and limited to approved value-free events. Error reports are minimised to remove account identity, bookkeeping values, business names, notes, receipt content and unnecessary request details. You can change analytics consent in Settings.'],
    ['Complaints','Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a> about privacy or to exercise a right. You may complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>. Material policy changes will be dated and communicated appropriately.']
  ];
  const TERMS_SHORT=['TaxMate helps you keep records, estimate tax and prepare figures for official filing routes.','Paid subscriptions renew until cancelled.','Paid PDF exports lock when paid access ends.','If you remain Free after paid access ends, whole-account historical data is deleted from 6 April after that UK tax year; download and retain the records you need.'];
  const TERMS_SECTIONS=[
    ['Using TaxMate','You must be at least 18 and able to enter a contract. By using TaxMate you agree to these terms. TaxMate helps UK self-employed users and directors keep bookkeeping records, estimate selected Self Assessment and Corporation Tax amounts and create summaries or working-paper exports. TaxMate does not file statutory accounts, CT600 returns or Companies House accounts. You are responsible for lawful and accurate input, protecting your account and devices, keeping suitable backups, reviewing calculations and meeting deadlines. Do not upload unlawful content, malware or information you lack authority to use.'],
    ['Free, Plus & Pro','Free costs £0 and provides the core functions shown in the Free plan. Plus costs £3.99 per month or £29.99 per year and adds multiple businesses, receipt photos, Receipt Pack PDF, mileage comparison and the PDF tax report. Pro includes Plus, Partner Sync, the SA104 partnership working paper, MTD quarterly record preparation and one active Limited Company. Limited Company creation, editing, posting, calculation, restore and outbound cloud writes require effective Pro access. The approved Pro prices are the launch price of £9.99 per month, the standard monthly price of £11.99 per month and £99.99 per year. Paid or Founder-promotion Pro resolves to the same effective Limited Company access.'],
    ['Prices and renewal','Before payment, Checkout shows the selected final price, renewal interval, included plan and payment method. Stripe Tax is off and no VAT amount is added to the listed price. Paid subscriptions renew until cancelled. A future price change applies only as disclosed for a future billing period. During the launch promotion, the monthly Pro plan displays the standard price of £11.99 struck through beside the £9.99 launch price; this comparison identifies the approved standard and launch prices and does not claim that a customer was previously charged £11.99.'],
    ["Cancellation and refunds","Cancel through <strong>Manage subscription</strong> or contact support. Stopping renewal is separate from requesting a refund; the already paid period remains available. Download paid PDF reports before their features end and keep a Full Backup ZIP. Other valid Plus or Pro grants retain whole-account history. If you remain Free, historical records are kept through 5 April at the end of the UK tax year in which paid access ended, then deleted from 6 April; new-year Free records and shared data needed by other members remain protected. Later payment does not recover deleted history. For an applicable distance service contract, consumers normally have 14 days after the day of contract formation to cancel; missing required information can extend this. An express early-start request is recorded separately: mere use does not waive cancellation rights. Lawful proportionate charges for services supplied before cancellation apply only where the statutory request and information conditions were met. Applicable cancellation refunds are made without undue delay, within the legal deadline, normally by the original payment method without a refund fee. Service-quality remedies and other mandatory rights are separate and unaffected. Contact support with any clear cancellation statement. We record receipt, review, provider submission and provider confirmation separately. Outside legal and contractual obligations, additional full, partial or declined refunds are decided individually, with no automatic extra refund promise. A successful full refund removes its corresponding funded entitlement, not unrelated valid plans or later paid periods. A partial refund does not automatically change access. Your payment provider or issuer controls when confirmed funds appear."],
    ["Plan changes and unsuccessful payments","Plus to Pro: before you confirm, we show the actual difference, credit for paid unused time, effective time and next payment. Pro applies only after successful difference payment. Unpaid or previously credited time is not credited again. Pro to Plus: the paid Pro period continues to its end, then the same subscription renews as Plus. No overlapping subscription is opened for that change. Your existing billing interval is retained; complex subscriptions require individual support review. If payment fails, unexpired funded access and other valid grants remain. No extra free grace period is added; the unpaid expired tier ends without early deletion of your records."],
    ['Cancellation form — supplier-address verification pending',`<p>This candidate is not cleared for new consumer sales. The supplier establishment address and completed statutory model form require verification before checkout is enabled. The existing PO Box is a correspondence address, not a verified establishment address.</p><p>You can send any clear cancellation statement to <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>; no special wording or form is required. A working service-cancellation template is below. The <a href="https://www.legislation.gov.uk/uksi/2013/3134/schedule/3">official model form is in Schedule 3, Part B</a>.</p><blockquote>Recipient: Hau Ying Ou-Yang, trading as TaxMate UK; support@taxmate.uk.<br>Geographical establishment address: awaiting verification.<br>I am cancelling my TaxMate service contract.<br>Service or plan: __________<br>Contract or order date: __________<br>Customer name and postal address: __________<br>Date of this notice: __________<br>Signature if sent on paper: __________</blockquote>`],
    ['Promotion codes','A valid TaxMate promotion grants fixed-period or permanent Plus or Pro access. It requires no card, creates no Stripe subscription and never starts an automatic charge by itself. A fixed campaign ends at its stated expiry even if redeemed later. Disabling a code stops future redemptions but does not cancel grants already redeemed. A specific revocation is separate. TaxMate applies the highest active paid or promotional tier. When a fixed promotion ends, the same paid-feature and tax-year retention rules apply; download paid reports and make a backup before access ends.'],
    ['Tax estimates, HMRC and Companies House','TaxMate provides planning estimates and working aids, not tax, accounting or legal advice. It does not file Self Assessment returns, MTD updates, statutory accounts, CT600 Corporation Tax returns or Companies House accounts, is not HMRC submission software and is not affiliated with HMRC or Companies House. Exports are not official filings or proof that an authority will accept a treatment. Verify important figures with current guidance or a qualified adviser.'],
    ['Accounts and partnerships','Google Sign-In is available on Web and Android. Sign in with Apple is available only when it is displayed in a supported iOS version. Use only the sign-in options displayed in your version of TaxMate. A partnership code grants access to shared records, so share it only with an intended partner. Members can see shared records; new collaboration and write actions require Pro. If Pro ends, authorised historical access remains but new Pro-only collaboration stops. Account deletion removes your membership; records remain for other members and are deleted when the last member leaves.'],
    ['Data and backups','You retain rights in your records and permit TaxMate to process them only to provide the service as you direct. Free basic JSON backup and Full Backup ZIP restore remain available for eligible records; unavailable LTD records do not block ordinary records. A Full Backup ZIP includes receipt binaries; JSON is data-only, and a PDF is a reference report, not a restore file. Free restore keeps receipt binaries on the restoring device; include them in your next ZIP. Paid reports stop at actual effective entitlement expiry. Plus or Pro retains whole-account history; if you remain Free it is deleted from 6 April after that tax year ends. Restore of your own backup after deletion is explicit and does not grant paid features. You are responsible for keeping legally required records, normally for six years where the applicable rule requires it. The separate account deletion control remains available.'],
    ['Availability and liability','TaxMate uses reasonable care and skill but cannot promise uninterrupted availability or compatibility with every device. TaxMate is responsible for foreseeable loss resulting from breach or failure to use reasonable care and skill, but not loss caused by inaccurate input, ignoring a clear warning, failing to keep a backup or treating an estimate as professional advice. Nothing limits liability where the law does not allow it, including fraud or death or personal injury caused by negligence.'],
    ['Who provides TaxMate & contact',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader. Public correspondence, contact and complaints address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. These terms are governed by the law of England and Wales; mandatory consumer protections where you live continue to apply. Questions, complaints, cancellation requests and requests for the model cancellation form: <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.`]
  ];
  function accordion(sections){return sections.map(([title,body])=>`<details class="content-accordion"><summary>${title}</summary><div class="content-body">${body}</div></details>`).join('');}
  const FAQ_POPULAR=[
    'How do I create a TaxMate account?',
    "I can't sign in",
    'Does TaxMate charge an account or verification fee?',
    'How is my tax estimate calculated?',
    'How do I add a receipt photo?',
    'What is included in Free?'
  ];
  function faqId(groupIndex,itemIndex){return`faq-${groupIndex+1}-${itemIndex+1}`;}
  function faqItem(groupIndex,itemIndex,title,body){return`<details class="content-accordion" id="${faqId(groupIndex,itemIndex)}" data-faq-item><summary>${title}</summary><div class="content-body">${body}</div></details>`;}
  function helpGroups(){return`<div data-faq-groups>${HELP_GROUPS.map(([group,items],groupIndex)=>`<section class="content-group" data-faq-group data-faq-category="${groupIndex}"><h2>${group}</h2>${items.map(([title,body],itemIndex)=>faqItem(groupIndex,itemIndex,title,body)).join('')}</section>`).join('')}</div>`;}
  function faqPopular(){return FAQ_POPULAR.map(title=>{for(let groupIndex=0;groupIndex<HELP_GROUPS.length;groupIndex++){const itemIndex=HELP_GROUPS[groupIndex][1].findIndex(item=>item[0]===title);if(itemIndex>=0)return`<button type="button" class="faq-popular-button" data-faq-open="${faqId(groupIndex,itemIndex)}">${title}<span aria-hidden="true">›</span></button>`;}return'';}).join('');}
  function faqFilters(){return`<button type="button" class="faq-filter is-active" data-faq-filter="all" aria-pressed="true">All topics</button>${HELP_GROUPS.map(([group],index)=>`<button type="button" class="faq-filter" data-faq-filter="${index}" aria-pressed="false">${group}</button>`).join('')}`;}
  function helpExperience(contactClass){return`<div data-faq-root><div class="faq-search-wrap"><label for="faq-search"><span>What can we help with?</span><input id="faq-search" type="search" inputmode="search" autocomplete="off" placeholder="Search sign-in, receipts, tax, billing or anything else" data-faq-search></label><button type="button" class="faq-clear" data-faq-clear hidden>Clear</button></div><section class="faq-popular" data-faq-popular><h2>Popular questions</h2><div class="faq-popular-grid">${faqPopular()}</div></section><div class="faq-filter-wrap"><div class="faq-filter-label">Browse by topic</div><div class="faq-filter-row" role="group" aria-label="FAQ topics">${faqFilters()}</div></div><div class="faq-empty" data-faq-empty hidden><strong>No matching answer yet.</strong><br>Try a shorter search or contact support below.</div>${helpGroups()}<div class="${contactClass}"><strong>Still need help?</strong><p>Tell us what you were trying to do, what happened and which device you use. Do not send passwords, complete card details or sensitive receipt images.</p><a class="faq-support-link" href="mailto:support@taxmate.uk?subject=TaxMate%20support">Email support@taxmate.uk</a></div></div>`;}
  const helpHtml=`<div class="stitle">Help &amp; support</div><div class="s content-lede">Find a quick answer before contacting support.</div>${helpExperience('notice green faq-contact')}`;
  const privacyHtml=`<div class="stitle">Privacy</div><div class="s content-lede">How TaxMate uses your information.</div><div class="s content-date">Last updated: ${PRIVACY_LAST_UPDATED}</div>${accordion(PRIVACY_SECTIONS)}`;
  const termsHtml=`<div class="stitle">Terms of use</div><div class="s content-date">Last updated: ${LAST_UPDATED}</div><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>${accordion(TERMS_SECTIONS)}`;
  function publicPage(kind){
    const config={help:{title:'Help & Support | TaxMate UK',description:'Practical help for TaxMate bookkeeping, tax estimates, receipts, plans, backups and partnerships.',robots:'index,follow,max-image-preview:large',heading:'Help & support',lede:'Find a quick answer before contacting support.',body:helpExperience('public-contact faq-contact')},privacy:{title:'Privacy | TaxMate UK',description:'How TaxMate uses account, bookkeeping, receipt, billing, analytics and error-reporting information.',robots:'noindex,follow',heading:'Privacy',lede:'How TaxMate uses your information.',body:`<p class="public-date">Last updated: ${PRIVACY_LAST_UPDATED}</p>`+accordion(PRIVACY_SECTIONS)},terms:{title:'Terms of use | TaxMate UK',description:'Terms for TaxMate Free, Plus, Pro and promotion access.',robots:'noindex,follow',heading:'Terms of use',lede:'The terms for using TaxMate.',body:`<p class="public-date">Last updated: ${LAST_UPDATED}</p><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>`+accordion(TERMS_SECTIONS)}}[kind];
    if(!config)throw new Error('Unknown public page');
    return`<!doctype html>\n<html lang="en-GB" data-direction-a="true"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${config.title}</title><meta name="description" content="${config.description}"><meta name="robots" content="${config.robots}"><link rel="canonical" href="https://www.taxmate.uk/${kind}.html"><style>html{background:#F6F3EC}@media(prefers-color-scheme:dark){html{background:#111A26}}html[data-theme=dark]{background:#111A26}html[data-theme=light]{background:#F6F3EC}</style><script src="/src/app/public-theme.js"></script>${kind==='help'?'<script defer src="/src/app/help.js"></script>':''}<link rel="stylesheet" href="/src/ui/direction-a.css?v=20260905-1"><link rel="stylesheet" href="/src/app/public-pages.css"></head>\n<body><div class="public-topbar"><div class="public-topbar-inner"><a class="public-brand-lockup" href="/" aria-label="TaxMate home"><img src="/assets/brand/derived/taxmate-brand-logo-dark.svg" alt="TaxMate"></a></div></div><main class="public-shell"><header class="public-page-heading"><h1>${config.heading}</h1><p>${config.lede}</p></header>${config.body}<nav class="public-nav"><a href="/">TaxMate home</a><a href="/help.html">Help</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></nav></main></body></html>\n`;
  }
  return Object.freeze({POLICY_VERSION,LAST_UPDATED,PRIVACY_LAST_UPDATED,PUBLIC_CORRESPONDENCE_ADDRESS,HELP_GROUPS,PRIVACY_SECTIONS,TERMS_SHORT,TERMS_SECTIONS,helpHtml,privacyHtml,termsHtml,publicPage});
});
