(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.TaxMateLegal=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const POLICY_VERSION='2026-09-07.billing.1',LAST_UPDATED='7 September 2026';
  const PUBLIC_CORRESPONDENCE_ADDRESS='Unit 170198, PO Box 7169, Poole, BH15 9EL';
  const HELP_GROUPS=[
    ['Getting started',[
      ['How do I add my first business?','Open TaxMate and choose <strong>Add a business</strong>. Give it a name and choose whether you are a sole trader or partnership. TaxMate then uses that business for your income, expenses and tax estimate.'],
      ['How do I add income?','Open <strong>Income</strong> and tap <strong>Add income</strong>. Enter the amount, date, business and category, then save. Your tax estimate updates from the saved record.'],
      ['How do I add an expense?','Open <strong>Expenses</strong> and tap <strong>Add expense</strong>. Enter the amount, date, category and business-use percentage where needed, then save.'],
      ['Can I add earlier months?','Yes. Use the catch-up flow to enter earlier months without rebuilding your current records.'],
      ['Can I change categories?','Yes. You can use built-in categories, rename where supported, and organise records with the available category and folder tools.']]],
    ['Tax & estimates',[
      ['How is my tax estimate calculated?','TaxMate uses the supported tax-year rules and the income and expense information you enter. It is a planning estimate, not your final HMRC calculation.'],
      ['What is the £1,000 trading allowance?','For eligible sole-trader income, TaxMate can compare the £1,000 trading allowance with actual expenses and show which produces the lower estimated taxable profit.'],
      ['What are payments on account?','Payments on account are advance payments HMRC may require towards the following tax year. TaxMate can include the figures you enter from your HMRC position when estimating what may be due.'],
      ['How does TaxMate help with Self Assessment?','TaxMate organises your records, calculates the supported estimates and maps figures to official SA103 or SA104 references. When your figures are ready, it guides you to complete submission through HMRC or an appropriate filing route.'],
      ['What does TaxMate do for MTD?','TaxMate helps you keep digital records, check eligibility and prepare MTD quarterly updates. When an update is due, it guides you to an HMRC-compatible submission route.'],
      ['How does mileage work?','TaxMate currently tracks an annual mileage total and, on Plus or Pro, can compare the mileage method with actual vehicle costs. It is not a trip-by-trip mileage diary.']]],
    ['Receipts',[
      ['How do I add a receipt photo?','On Plus or Pro, open an expense and choose <strong>Take photo</strong> or <strong>Choose existing photo</strong>. The image is linked to that expense.'],
      ['Can I add receipts later?','Yes. Use the Receipts workflow to find expenses that still need a receipt and attach images later.'],
      ['What happens to receipt photos if I downgrade?','Paid receipt uploads and Receipt Pack PDF export stop when your account becomes Free. Download your Receipt Pack while Plus or Pro is active. Basic machine-readable backup remains available on Free, so keep your own backup of any records and receipt data you need.'],
      ['Can I delete a receipt photo?','Yes. Open the linked receipt and use the delete action. Deleting the receipt image does not delete the expense entry itself.']]],
    ['Plans & billing',[
      ['What is included in Free?','Free covers core bookkeeping, one business, tax estimates, cloud sync, backups and the other functions shown in the Free plan card.'],
      ['What is Plus?','Plus adds multiple businesses, receipt photos, Receipt Pack PDF, mileage comparison and the PDF tax report.'],
      ['What is Pro?','Pro includes Plus, Partner Sync, the SA104 partnership working paper, MTD quarterly record preparation and one active Limited Company. Limited Company actions are Pro-only. The approved Pro prices are the launch price of £9.99/month, the standard monthly price of £11.99/month and £99.99/year.'],
      ['Monthly or yearly?','Plus costs £3.99 monthly or £29.99 yearly. Pro costs £9.99 monthly at launch, with a standard monthly price of £11.99, or £99.99 yearly. Subscriptions renew on the interval shown at Checkout until cancelled.'],
      ['How do I cancel?','Open <strong>Manage subscription</strong>. Cancellation stops the next renewal; paid access normally continues until the end of the period already paid for. Before it ends, download any paid PDF reports you need and make a backup.'],
      ['What happens to my records after cancellation?','Paid reports and paid features stop when effective paid access ends. Plus or Pro keeps historical data across the whole account. If you remain Free, historical ordinary, self-employed, partnership and Limited Company data is kept through 5 April at the end of the UK tax year in which paid access ended, then deleted from 6 April. New-year Free records, authentication and billing records, and shared records needed by other members are protected. Download your paid reports before paid access ends and make a Full Backup ZIP before deletion. Paying again after deletion does not recover deleted data; restore your own backup.'],
      ['How do promotion codes work?','A valid TaxMate promotion can grant Plus or Pro without starting a paid subscription. Founder Pro and paid Pro resolve to the same effective Limited Company entitlement. Some promotions have fixed campaign dates or redemption limits. A promotion never starts an automatic paid subscription by itself.']]],
    ['Limited companies',[
      ['What Limited Company support is included?','Pro supports one active UK private limited company for bookkeeping records, company income and expenses, personally paid and shared expenses, ownership history, salary and dividend records, Corporation Tax estimates, scenarios and a working pack. V1.5 does not support an additional Limited Company or company collaboration.'],
      ['What does the Companies House check do?','TaxMate can check a company number through its protected server and show the official legal name, incorporation date, status, type and public-record link. You review editable facts before saving. Manual facts are never labelled verified, and changing verified facts marks them as needing checking while the last official snapshot is retained.'],
      ['How does TaxMate help with company accounts and Corporation Tax?','TaxMate prepares supported company records, Corporation Tax estimates and working-pack figures for CT600 and company accounts. When the records are ready, it guides you to the appropriate HMRC and Companies House filing routes. Estimates and working records are not professional tax, accounting or legal advice.'],
      ['What happens if Pro ends?','Pro-only Limited Company actions stop when effective Pro access ends. Effective Plus retains LTD history without enabling Pro operations. If the account becomes Free, the whole-account tax-year retention rule applies to LTD as well as ordinary and partnership history. Eligible data remains available for basic JSON or Full Backup ZIP backup and restore. New LTD edits and reports require Pro; restoring a backup does not grant paid features.']]],
    ['Cloud & backup',[
      ['Do I need an account?','No for local core use. Sign-in is required for cloud sync and cloud-dependent features.'],
      ['Which sign-in method does TaxMate use?','Google only.'],
      ['How does cloud sync work?','When signed in, supported personal records sync through TaxMate’s Firebase services so they can follow the same account across devices.'],
      ['What backup should I use?','Use <strong>Full backup</strong> for a ZIP containing TaxMate records and available receipt image binaries. JSON is a data-only backup and does not include receipt binaries.'],
      ['How do I restore?','Choose <strong>Restore from backup</strong>, select a valid TaxMate backup and review the confirmation. The app validates the backup before replacing current local data.'],
      ['What happens when I delete my account?','The app removes your personal account and cloud records through the authenticated deletion flow. Shared partnership records may remain for other authorised members.']]],
    ['Partnerships',[
      ['How do I join a partnership?','Open <strong>Your businesses → Join a partnership</strong>, enter the partnership code and follow the Pro access flow if needed.'],
      ['How do I invite my partner?','From the relevant partnership business, use Partner Sync to share the partnership code through the available share or copy option.'],
      ['What happens if I leave?','Your membership is removed. Shared records remain for other authorised members. If the last member leaves, the approved deletion lifecycle applies.']]],
    ['Troubleshooting',[
      ["I can't sign in",'Use Google Sign-In in a normal supported browser. Check that popups are allowed and your connection is working. If the problem continues, contact support.'],
      ['My data is not syncing','Confirm you are signed into the expected Google account and online. If local records are important, create a backup before troubleshooting further.'],
      ['My receipt will not upload','Check that you are online, signed in and have Plus or Pro access. Use an image file within the supported size limit.'],
      ['Checkout does not open','Try again once. If the payment service is temporarily unavailable, no plan should change. Contact support if it persists.'],
      ['I changed phone','Sign in with the same Google account to retrieve supported synced records. Keep a full ZIP backup as additional protection.'],
      ['How do I install TaxMate?',"Use the app's install guidance for your device and browser. On iPhone, use Safari's Add to Home Screen flow."]]]
  ];
  const PRIVACY_SECTIONS=[
    ["What information does TaxMate use?","TaxMate can process business and Limited Company names and types; Companies House identity checks and public-record snapshots; incorporation, trading, accounting-period and Corporation Tax facts; director, shareholder and effective-dated ownership records; income, expense, salary, dividend, loan, share-funding, evidence, mileage, category, date and note records; tax-year adjustments; receipt images; backup files; partnership membership and shared records; and app preferences. Google sign-in supplies an account identifier and may supply your name, email and profile image. Billing records can include a Stripe customer identifier, subscription status, plan, renewal or cancellation status and promotion redemption. Support messages and limited technical diagnostics are also processed. Do not enter another person’s information unless it is genuinely needed for company records and you are entitled to use it. Billing support also records payment/refund identifiers, amounts, customer requests, replies, staff decisions and calculation references, status history, plan-change quotes and versioned purchase confirmations. Access to private casework is restricted to authorised staff; bookkeeping backups do not include it."],
    ['Why does TaxMate use it?','TaxMate uses account, bookkeeping, receipt, backup, sync, partnership and entitlement information to provide the service or take steps you request before a contract. Payment and accounting records are used to perform paid services and meet legal obligations. Necessary security, abuse-prevention, promotion-integrity and strictly minimised error diagnostics support the legitimate interests of protecting and operating TaxMate. Optional usage measurement is based on consent and is off unless you enable it. TaxMate does not sell personal information or use bookkeeping records for advertising.'],
    ['Where is my data stored?','The app can work locally without an account; local records remain in your browser until you clear, reset or delete them. Signed-in personal records use Firebase Authentication, Cloud Firestore and Cloud Storage. The production Firestore database and server functions use the London region. Receipt Storage uses its configured United States location.'],
    ['Who receives my data?','Google and Firebase process sign-in, app security checks, cloud records, receipts and server functions. Stripe processes checkout, payment methods, invoices and subscriptions; TaxMate does not receive complete card details. Sentry processes minimised error reports. If you opt in, Google Analytics 4 processes a small approved set of value-free usage events. Namecheap forwards messages sent to the support address and Microsoft Outlook is the destination mailbox service. Browsers also connect to Google Fonts and software content-delivery networks for app assets. Professional advisers, regulators, courts or law-enforcement bodies may receive information where necessary and lawful.'],
    ['How long is it kept?','Effective Plus or Pro retains historical bookkeeping data across the whole account. If paid access ends and you remain Free, that history is kept through the following 5 April and deleted from 6 April. This covers ordinary and self-employed records, your partnership history, LTD records and associated receipts. New-year Free records, authentication and billing data, and shared records needed by other members are protected. Connected devices remove expired local history, rollback copies and stale queued writes when they receive the server deletion control; an offline device cannot receive that control until it reconnects. A device-only account without a verified paid-end date is not assigned an invented expiry. This service retention period does not replace your statutory record-keeping duties. Provider backups, logs, fraud-prevention records and legally required transaction records may remain for limited provider-defined or legally required periods.'],
    ['How do I delete my data?','Use <strong>Delete all my data</strong> for the authenticated deletion workflow. This removes the personal Firestore tree, receipt objects, promotion-redemption records, TaxMate’s Stripe customer object and Firebase Auth identity. If a partnership has another member, shared records remain for them and your membership is removed; if you are the last member, the partnership is deleted. A deletion request is complete only when the app reports server-side success.'],
    ['What are my privacy rights?','You can use TaxMate locally, correct records, export JSON, export a full ZIP containing available receipt binaries, withdraw analytics consent and request deletion. Depending on the lawful basis and circumstances, you may have rights of access, correction, erasure, restriction, objection and portability. You may object to processing based on legitimate interests by contacting TaxMate. Withdrawing consent does not affect earlier processing.'],
    ['Who runs TaxMate & how do I contact them?',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader and the controller for this service. ICO registration: <strong>ZC174150</strong>. Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>. Public correspondence and contact address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. TaxMate has not appointed a data protection officer.`],
    ['International transfers','Google, Stripe, Sentry and their subprocessors may process information in the UK, EEA, United States and elsewhere. Provider terms describe applicable adequacy arrangements, the UK Extension to the Data Privacy Framework and contractual safeguards such as the UK Addendum to standard contractual clauses. Contact TaxMate for further information about applicable safeguards.'],
    ['Analytics & error reporting','Optional analytics is off by default and limited to approved value-free events. Error reports are minimised to remove account identity, bookkeeping values, business names, notes, receipt content and unnecessary request details. You can change analytics consent in Settings.'],
    ['Complaints','Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a> about privacy or to exercise a right. You may complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner’s Office</a>. Material policy changes will be dated and communicated appropriately.']
  ];
  const TERMS_SHORT=['TaxMate helps you keep records, estimate tax and prepare figures for official filing routes.','Paid subscriptions renew until cancelled.','Paid PDF exports lock when paid access ends.','If you remain Free after paid access ends, whole-account historical data is deleted from 6 April after that UK tax year; download and retain the records you need.'];
  const TERMS_SECTIONS=[
    ['Using TaxMate','You must be at least 18 and able to enter a contract. By using TaxMate you agree to these terms. TaxMate helps UK self-employed users and directors keep bookkeeping records, estimate selected Self Assessment and Corporation Tax amounts and create summaries or working-paper exports. TaxMate does not file statutory accounts, CT600 returns or Companies House accounts. You are responsible for lawful and accurate input, protecting your account and devices, keeping suitable backups, reviewing calculations and meeting deadlines. Do not upload unlawful content, malware or information you lack authority to use.'],
    ['Free, Plus & Pro','Free costs £0 and provides the core functions shown in the Free plan. Plus costs £3.99 per month or £29.99 per year and adds multiple businesses, receipt photos, Receipt Pack PDF, mileage comparison and the PDF tax report. Pro includes Plus, Partner Sync, the SA104 partnership working paper, MTD quarterly record preparation and one active Limited Company. Limited Company creation, editing, posting, calculation, restore and outbound cloud writes require effective Pro access. The approved Pro prices are the launch price of £9.99 per month, the standard monthly price of £11.99 per month and £99.99 per year. Paid or Founder-promotion Pro resolves to the same effective Limited Company access.'],
    ['Prices and renewal','Before payment, Checkout shows the selected final price, renewal interval, included plan and payment method. Stripe Tax is off and no VAT amount is added to the listed price. Paid subscriptions renew until cancelled. A future price change applies only as disclosed for a future billing period. During the launch promotion, the monthly Pro plan displays the standard price of £11.99 struck through beside the £9.99 launch price; this comparison identifies the approved standard and launch prices and does not claim that a customer was previously charged £11.99.'],
    ["Cancellation and refunds","Cancel through <strong>Manage subscription</strong> or contact support. Stopping renewal is separate from requesting a refund; the already paid period remains available. Download paid PDF reports before their features end and keep a Full Backup ZIP. Other valid Plus or Pro grants retain whole-account history. If you remain Free, historical records are kept through 5 April at the end of the UK tax year in which paid access ended, then deleted from 6 April; new-year Free records and shared data needed by other members remain protected. Later payment does not recover deleted history. For an applicable distance service contract, consumers normally have 14 days after the day of contract formation to cancel; missing required information can extend this. An express early-start request is recorded separately: mere use does not waive cancellation rights. Lawful proportionate charges for services supplied before cancellation apply only where the statutory request and information conditions were met. Applicable cancellation refunds are made without undue delay, within the legal deadline, normally by the original payment method without a refund fee. Service-quality remedies and other mandatory rights are separate and unaffected. Contact support with any clear cancellation statement. We record receipt, review, provider submission and provider confirmation separately. Outside legal and contractual obligations, additional full, partial or declined refunds are decided individually, with no automatic extra refund promise. A successful full refund removes its corresponding funded entitlement, not unrelated valid plans or later paid periods. A partial refund does not automatically change access. Your payment provider or issuer controls when confirmed funds appear."],
    ["Plan changes and unsuccessful payments","Plus to Pro: before you confirm, we show the actual difference, credit for paid unused time, effective time and next payment. Pro applies only after successful difference payment. Unpaid or previously credited time is not credited again. Pro to Plus: the paid Pro period continues to its end, then the same subscription renews as Plus. No overlapping subscription is opened for that change. Your existing billing interval is retained; complex subscriptions require individual support review. If payment fails, unexpired funded access and other valid grants remain. No extra free grace period is added; the unpaid expired tier ends without early deletion of your records."],
    ['Cancellation form — supplier-address verification pending',`<p>This candidate is not cleared for new consumer sales. The supplier establishment address and completed statutory model form require verification before checkout is enabled. The existing PO Box is a correspondence address, not a verified establishment address.</p><p>You can send any clear cancellation statement to <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>; no special wording or form is required. A working service-cancellation template is below. The <a href="https://www.legislation.gov.uk/uksi/2013/3134/schedule/3">official model form is in Schedule 3, Part B</a>.</p><blockquote>Recipient: Hau Ying Ou-Yang, trading as TaxMate UK; support@taxmate.uk.<br>Geographical establishment address: awaiting verification.<br>I am cancelling my TaxMate service contract.<br>Service or plan: __________<br>Contract or order date: __________<br>Customer name and postal address: __________<br>Date of this notice: __________<br>Signature if sent on paper: __________</blockquote>`],
    ['Promotion codes','A valid TaxMate promotion grants fixed-period or permanent Plus or Pro access. It requires no card, creates no Stripe subscription and never starts an automatic charge by itself. A fixed campaign ends at its stated expiry even if redeemed later. Disabling a code stops future redemptions but does not cancel grants already redeemed. A specific revocation is separate. TaxMate applies the highest active paid or promotional tier. When a fixed promotion ends, the same paid-feature and tax-year retention rules apply; download paid reports and make a backup before access ends.'],
    ['Tax estimates, HMRC and Companies House','TaxMate provides planning estimates and working aids, not tax, accounting or legal advice. It does not file Self Assessment returns, MTD updates, statutory accounts, CT600 Corporation Tax returns or Companies House accounts, is not HMRC submission software and is not affiliated with HMRC or Companies House. Exports are not official filings or proof that an authority will accept a treatment. Verify important figures with current guidance or a qualified adviser.'],
    ['Accounts and partnerships','Google is the only sign-in provider. A partnership code grants access to shared records, so share it only with an intended partner. Members can see shared records; new collaboration and write actions require Pro. If Pro ends, authorised historical access remains but new Pro-only collaboration stops. Account deletion removes your membership; records remain for other members and are deleted when the last member leaves.'],
    ['Data and backups','You retain rights in your records and permit TaxMate to process them only to provide the service as you direct. Free basic JSON backup and Full Backup ZIP restore remain available for eligible records; unavailable LTD records do not block ordinary records. A Full Backup ZIP includes receipt binaries; JSON is data-only, and a PDF is a reference report, not a restore file. Free restore keeps receipt binaries on the restoring device; include them in your next ZIP. Paid reports stop at actual effective entitlement expiry. Plus or Pro retains whole-account history; if you remain Free it is deleted from 6 April after that tax year ends. Restore of your own backup after deletion is explicit and does not grant paid features. You are responsible for keeping legally required records, normally for six years where the applicable rule requires it. The separate account deletion control remains available.'],
    ['Availability and liability','TaxMate uses reasonable care and skill but cannot promise uninterrupted availability or compatibility with every device. TaxMate is responsible for foreseeable loss resulting from breach or failure to use reasonable care and skill, but not loss caused by inaccurate input, ignoring a clear warning, failing to keep a backup or treating an estimate as professional advice. Nothing limits liability where the law does not allow it, including fraud or death or personal injury caused by negligence.'],
    ['Who provides TaxMate & contact',`TaxMate UK (“TaxMate”) is a trading name used by Hau Ying Ou-Yang, a UK sole trader. Public correspondence, contact and complaints address: <strong>${PUBLIC_CORRESPONDENCE_ADDRESS}</strong>. These terms are governed by the law of England and Wales; mandatory consumer protections where you live continue to apply. Questions, complaints, cancellation requests and requests for the model cancellation form: <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.`]
  ];
  function accordion(sections){return sections.map(([title,body])=>`<details class="content-accordion"><summary>${title}</summary><div class="content-body">${body}</div></details>`).join('');}
  function helpGroups(){return HELP_GROUPS.map(([group,items])=>`<section class="content-group"><h2>${group}</h2>${accordion(items)}</section>`).join('');}
  const helpHtml=`<div class="stitle">Help &amp; support</div><div class="s content-lede">Practical help for using TaxMate.</div>${helpGroups()}<div class="notice green"><strong>Still need help?</strong><br>Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.</div>`;
  const privacyHtml=`<div class="stitle">Privacy</div><div class="s content-lede">How TaxMate uses your information.</div><div class="s content-date">Last updated: ${LAST_UPDATED}</div>${accordion(PRIVACY_SECTIONS)}`;
  const termsHtml=`<div class="stitle">Terms of use</div><div class="s content-date">Last updated: ${LAST_UPDATED}</div><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>${accordion(TERMS_SECTIONS)}`;
  function publicPage(kind){
    const config={help:{title:'Help & Support | TaxMate UK',description:'Practical help for TaxMate bookkeeping, tax estimates, receipts, plans, backups and partnerships.',robots:'index,follow,max-image-preview:large',heading:'Help & support',lede:'Practical help for using TaxMate.',body:helpGroups()+`<div class="public-contact"><strong>Still need help?</strong><br>Email <a href="mailto:support@taxmate.uk">support@taxmate.uk</a>.</div>`},privacy:{title:'Privacy | TaxMate UK',description:'How TaxMate uses account, bookkeeping, receipt, billing, analytics and error-reporting information.',robots:'noindex,follow',heading:'Privacy',lede:'How TaxMate uses your information.',body:`<p class="public-date">Last updated: ${LAST_UPDATED}</p>`+accordion(PRIVACY_SECTIONS)},terms:{title:'Terms of use | TaxMate UK',description:'Terms for TaxMate Free, Plus, Pro and promotion access.',robots:'noindex,follow',heading:'Terms of use',lede:'The terms for using TaxMate.',body:`<p class="public-date">Last updated: ${LAST_UPDATED}</p><section class="content-group"><h2>The short version</h2><ul>${TERMS_SHORT.map(item=>`<li>${item}</li>`).join('')}</ul></section>`+accordion(TERMS_SECTIONS)}}[kind];
    if(!config)throw new Error('Unknown public page');
    return`<!doctype html>\n<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>${config.title}</title><meta name="description" content="${config.description}"><meta name="robots" content="${config.robots}"><link rel="canonical" href="https://www.taxmate.uk/${kind}.html"><style>html{background:#f3f6f4}@media(prefers-color-scheme:dark){html{background:#101714}}html[data-theme=dark]{background:#101714}html[data-theme=light]{background:#f3f6f4}</style><script src="/src/app/public-theme.js"></script><link rel="stylesheet" href="/src/app/public-pages.css"></head>\n<body><main class="public-shell"><a class="brand" href="/">TaxMate</a><header><h1>${config.heading}</h1><p>${config.lede}</p></header>${config.body}<nav class="public-nav"><a href="/">TaxMate</a><a href="/help.html">Help</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></nav></main></body></html>\n`;
  }
  return Object.freeze({POLICY_VERSION,LAST_UPDATED,PUBLIC_CORRESPONDENCE_ADDRESS,HELP_GROUPS,PRIVACY_SECTIONS,TERMS_SHORT,TERMS_SECTIONS,helpHtml,privacyHtml,termsHtml,publicPage});
});
