'use strict';
// Real Firestore emulator transactions and Rules. Authentication is synthetic;
// these are not live Functions, provider or real-account acceptance tests.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,writeBatch,setDoc,deleteDoc}=require('firebase/firestore');
const functionsRequire=require('node:module').createRequire(require('node:path').resolve(__dirname,'../../functions/package.json'));
const {initializeApp,deleteApp}=functionsRequire('firebase-admin/app');
const {getFirestore,FieldValue}=functionsRequire('firebase-admin/firestore');
const {HttpsError}=functionsRequire('firebase-functions/v2/https');
const Setup=require('../../functions/ltd-setup'),ReceiptAdmission=require('../../functions/receipt-admission'),Sync=require('../../src/core/ltd-sync'),Profile=require('../../src/core/company-profile');
assert.equal(process.env.FIRESTORE_EMULATOR_HOST,'127.0.0.1:48388','This suite must only run against its isolated emulator');
const projectId='demo-taxmate-setup',app=initializeApp({projectId}),db=getFirestore(app);let env,sequence=0;
const handlers=Setup.createHandlers({db,FieldValue,HttpsError,authenticate:req=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in required');return req.auth;},requireTier:async uid=>{const entitlement=(await db.doc(`users/${uid}/entitlements/current`).get()).data();if(entitlement?.paidTier!=='pro'||entitlement.currentPeriodEnd<=Date.now())throw new HttpsError('permission-denied','Pro required',{reason:'tier-required'});}});
test.before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{host:'127.0.0.1',port:48388,rules:fs.readFileSync('firestore.rules','utf8')}});await env.clearFirestore();});
test.after(async()=>{if(env)await env.cleanup();await deleteApp(app);});
const anchor=uid=>db.doc(`users/${uid}/ltdControl/activeCompany`),outcome=(uid,id)=>db.doc(`users/${uid}/ltdSetupOutcomes/${Sync.docId(id)}`),recordRef=(uid,row)=>db.doc(Sync.documentPath(uid,row.collection,row.recordId));
function seeds(id){const stamp=Date.now();return[Sync.envelope('companyProfiles',Profile.createDraft({entityId:id,now:stamp,deviceId:'emulator-test'}),id),Sync.envelope('entities',{id,name:'Synthetic Setup Ltd',type:'limited_company',currency:'GBP',createdAt:stamp,updatedAt:stamp,deletedAt:null,deviceId:'emulator-test'},id)];}
async function fixture({legacy=false}={}){const uid='setup-test-'+(++sequence),companyId='company:'+uid;await db.doc(`users/${uid}/entitlements/current`).set({paidTier:'pro',subscriptionStatus:'active',currentPeriodEnd:Date.now()+86400000});const request={auth:{uid},data:{companyId,...(legacy?{}:{setupProtocol:Setup.PROTOCOL,setupRecords:seeds(companyId)})}};await handlers.claim(request);return{uid,companyId,request,manage:data=>handlers.manage({auth:{uid},data:{companyId,...data}})};}
async function snapshot(uid){const result={};for(const name of Setup.COLLECTIONS){const rows=await db.collection(`users/${uid}/ltd/v1/${name}`).get();for(const row of rows.docs)result[row.ref.path]={data:row.data(),version:row.updateTime.toMillis()};}return result;}
async function admitted(uid,row,clientUid=uid){const target=recordRef(uid,row).path,client=env.authenticatedContext(clientUid).firestore();await ReceiptAdmission.prepareBatch({db,uid,records:[{target,payload:row}]});const batch=writeBatch(client);batch.set(doc(client,target),row);batch.delete(doc(client,`users/${uid}/receiptLtdAdmissions/current`));return batch.commit();}
const rejected=(promise,reason)=>assert.rejects(promise,error=>error.details?.reason===reason);

test('modern claim creates pending stage and canonical seeds; completed stage is one-way and cannot release the slot',async()=>{
 const f=await fixture();assert.equal((await anchor(f.uid).get()).data().setupState,'setup_pending');const initial=await f.manage({action:'inspect'});assert.equal(initial.canDiscard,true);assert.ok(initial.versionToken);assert.equal((await f.manage({action:'complete',expectedVersion:initial.versionToken})).status,'completed');assert.equal((await f.manage({action:'complete',expectedVersion:'old'})).idempotent,true);assert.equal((await f.manage({action:'inspect'})).canDiscard,false);await rejected(f.manage({action:'discard',operationId:'no-release-1',expectedVersion:initial.versionToken}),'setup_already_completed');assert.equal((await anchor(f.uid).get()).data().setupState,'setup_completed');
});
test('discard changes only two setup tombstones and its slot; repeat after a lost response and a new claim preserves all old data',async()=>{
 const f=await fixture(),old=Sync.envelope('economicEvents',{id:'historic-income',deletedAt:123,receiptPath:'receipts/'+f.uid+'/historic.jpg',sourceTransaction:{beneficiaryEntityId:'company:historic'},updatedAt:123},'company:historic');await recordRef(f.uid,old).set(old);const oldVersion=(await recordRef(f.uid,old).get()).updateTime.toMillis(),before=await snapshot(f.uid),checked=await f.manage({action:'inspect'}),input={action:'discard',operationId:'discard-once-1',expectedVersion:checked.versionToken},result=await f.manage(input);assert.equal(result.records.length,2);result.records.forEach(row=>{Sync.validateEnvelope(row);assert.ok(row.deletedAt);assert.equal(row.companyId,f.companyId);});assert.equal((await anchor(f.uid).get()).exists,false);assert.deepEqual((await recordRef(f.uid,old).get()).data(),old);assert.equal((await recordRef(f.uid,old).get()).updateTime.toMillis(),oldVersion);assert.equal(Object.keys(await snapshot(f.uid)).length,Object.keys(before).length);
 const next='company:new-'+f.uid;await handlers.claim({auth:{uid:f.uid},data:{companyId:next,setupProtocol:Setup.PROTOCOL,setupRecords:seeds(next)}});assert.equal((await f.manage(input)).idempotent,true);assert.equal((await anchor(f.uid).get()).data().activeCompanyId,next);await rejected(f.manage({...input,operationId:'different-request'}),'setup_already_completed');await anchor(f.uid).delete();await rejected(handlers.claim(f.request),'company_identity_retired');
});
test('changed version, financial-bearing draft, receipt-bearing draft and retention/reset work block discard without mutation',async()=>{
 const f=await fixture(),v=await f.manage({action:'inspect'}),profile=recordRef(f.uid,f.request.data.setupRecords[0]);await profile.update({'payload.legalName':'Changed on another device'});const before=await snapshot(f.uid);await rejected(f.manage({action:'discard',operationId:'stale-version',expectedVersion:v.versionToken}),'setup_changed_review_again');assert.deepEqual(await snapshot(f.uid),before);
 const financial=Sync.envelope('paymentAccounts',{id:'account-company-bank:'+f.companyId,ownerType:'entity',ownerId:f.companyId},f.companyId);await recordRef(f.uid,financial).set(financial);assert.equal((await f.manage({action:'inspect'})).reason,'setup_has_bookkeeping');await rejected(f.manage({action:'discard',operationId:'has-records',expectedVersion:'x'}),'setup_has_bookkeeping');await recordRef(f.uid,financial).delete();await profile.update({'payload.receiptPath':`receipts/${f.uid}/must-keep.jpg`});assert.equal((await f.manage({action:'inspect'})).reason,'setup_has_bookkeeping');await profile.update({'payload.receiptPath':FieldValue.delete()});await db.doc(`users/${f.uid}/retention/current`).set({status:'processing',epoch:2});await rejected(f.manage({action:'inspect'}),'retention_processing');await db.doc(`users/${f.uid}/retention/current`).set({status:'complete',epoch:2});await db.doc(`accountResets/${f.uid}`).set({status:'deleting'});await rejected(f.manage({action:'inspect'}),'account_reset_processing');assert.equal((await anchor(f.uid).get()).exists,true);
});
test('legacy slots retain their release policy and owner/Pro checks remain enforced',async()=>{
 const f=await fixture({legacy:true}),before=(await anchor(f.uid).get()).data();assert.equal((await f.manage({action:'inspect'})).reason,'setup_legacy_slot');assert.equal((await f.manage({action:'complete'})).status,'legacy');await rejected(f.manage({action:'discard',operationId:'legacy-removal',expectedVersion:'x'}),'setup_legacy_slot');assert.deepEqual((await anchor(f.uid).get()).data(),before);await assert.rejects(handlers.manage({data:{companyId:f.companyId,action:'inspect'}}),e=>e.code==='unauthenticated');await anchor(f.uid).update({accountOwnerUid:'another-owner'});await rejected(f.manage({action:'inspect'}),'setup_owner_mismatch');await anchor(f.uid).update({accountOwnerUid:f.uid});await db.doc(`users/${f.uid}/entitlements/current`).update({paidTier:'free'});await rejected(f.manage({action:'inspect'}),'tier-required');assert.equal((await anchor(f.uid).get()).data().activeCompanyId,f.companyId);
});
test('uncertain claim retirement fences later claims and never releases another company slot',async()=>{
 const f=await fixture(),unused='company:unused-'+f.uid,inspect=await f.manage({action:'inspect',companyId:unused});assert.equal(inspect.status,'unclaimed');const input={action:'discard',companyId:unused,operationId:'retire-unused-1',expectedVersion:inspect.versionToken};assert.deepEqual((await f.manage(input)).records,[]);assert.equal((await f.manage(input)).idempotent,true);assert.equal((await anchor(f.uid).get()).data().activeCompanyId,f.companyId);await anchor(f.uid).delete();await rejected(handlers.claim({auth:{uid:f.uid},data:{companyId:unused,setupProtocol:Setup.PROTOCOL,setupRecords:seeds(unused)}}),'company_identity_retired');
});
test('malformed or receipt-bearing modern claim seeds are rejected without creating a slot',async()=>{
 const f=await fixture();await anchor(f.uid).delete();for(const mutate of [rows=>{rows[0]=null;},rows=>{rows[0].companyId='other';},rows=>{rows[0].payload.lifecycleStatus='confirmed';rows[0].checksum=Setup.fingerprint(rows[0].payload);},rows=>{rows[0].payload.receiptPath=`receipts/${f.uid}/receipt.jpg`;rows[0].checksum=Setup.fingerprint(rows[0].payload);},rows=>{rows[0].updatedAt='wrong';}]){const companyId='company:invalid-'+(++sequence),setupRecords=seeds(companyId);mutate(setupRecords);await rejected(handlers.claim({auth:{uid:f.uid},data:{companyId,setupProtocol:Setup.PROTOCOL,setupRecords}}),'setup_seed_invalid');assert.equal((await anchor(f.uid).get()).exists,false);}
});
test('Rules require the pending stage, correct company and receipt admission, then permit only confirmed profiles after completion',async()=>{
 const f=await fixture(),client=env.authenticatedContext(f.uid).firestore(),base=f.request.data.setupRecords[0],draft={...base,payload:{...base.payload,legalName:'Updated draft'},retentionEpoch:0};draft.checksum=Sync.envelope('companyProfiles',draft.payload,f.companyId).checksum;await assertSucceeds(admitted(f.uid,draft));await assertFails(setDoc(doc(client,recordRef(f.uid,draft).path),draft));await assertFails(admitted(f.uid,draft,'other-owner'));
 const confirmed=Sync.envelope('companyProfiles',{...draft.payload,lifecycleStatus:'confirmed'},f.companyId),deleted=Sync.envelope('companyProfiles',{...draft.payload,deletedAt:Date.now()},f.companyId),finance=Sync.envelope('economicEvents',{id:'new-income',sourceTransaction:{beneficiaryEntityId:f.companyId}},f.companyId),foreign=Sync.envelope('companyProfiles',{...draft.payload,entityId:'company:other'},f.companyId);for(const row of [confirmed,deleted,finance,foreign])await assertFails(admitted(f.uid,row));
 const checked=await f.manage({action:'inspect'});await f.manage({action:'complete',expectedVersion:checked.versionToken});await assertSucceeds(admitted(f.uid,confirmed));await assertFails(admitted(f.uid,draft));await assertSucceeds(admitted(f.uid,finance));await assertFails(deleteDoc(doc(client,recordRef(f.uid,finance).path)));await assertFails(setDoc(doc(client,anchor(f.uid).path),{setupState:'setup_pending'}));await assertFails(deleteDoc(doc(client,anchor(f.uid).path)));await assertFails(setDoc(doc(client,outcome(f.uid,f.companyId).path),{status:'discarded'}));await assertFails(getDoc(doc(env.authenticatedContext('other-owner').firestore(),outcome(f.uid,f.companyId).path)));
});
test('Rules preserve legacy confirmed-company writes and Pro/retention restrictions',async()=>{
 const f=await fixture({legacy:true}),row=Sync.envelope('companyProfiles',{id:'company-profile:'+f.companyId,entityId:f.companyId,lifecycleStatus:'confirmed'},f.companyId);await assertSucceeds(admitted(f.uid,row));const tombstone=Sync.envelope('companyProfiles',{...row.payload,deletedAt:Date.now()},f.companyId);await assertSucceeds(admitted(f.uid,tombstone));await db.doc(`users/${f.uid}/entitlements/current`).update({paidTier:'free'});await assertFails(admitted(f.uid,row));
});
test('real five-step driver records sync through admitted client batches, complete once and retain history when another unfinished setup is discarded',async()=>{
 const {make,PRO_ENTITLEMENT}=require('../test-fixture'),{CanonicalCompanyDriver}=require('../../src/integration/ltd/CanonicalCompanyDriver');
 async function drive({discard=false}={}){
  const uid='driver-'+(++sequence);await db.doc(`users/${uid}/entitlements/current`).set({paidTier:'pro',subscriptionStatus:'active',currentPeriodEnd:Date.now()+86400000});
  const driver=new CanonicalCompanyDriver({state:make('fresh').driver.state,now:Date.now,entitlementSnapshot:PRO_ENTITLEMENT,activeCompanyClaim:data=>handlers.claim({auth:{uid},data}),manageCompanySetup:data=>handlers.manage({auth:{uid},data})});
  async function push(){const remote=Object.values(await snapshot(uid)).map(row=>row.data),result=Sync.reconcile(driver.state,remote,uid);assert.deepEqual(result.conflicts,[]);if(!result.uploads.length)return;const rows=result.uploads.map(op=>({target:op.path,payload:op.record}));await ReceiptAdmission.prepareBatch({db,uid,records:rows});const client=env.authenticatedContext(uid).firestore(),batch=writeBatch(client);for(const row of rows)batch.set(doc(client,row.target),row.payload);batch.delete(doc(client,`users/${uid}/receiptLtdAdmissions/current`));await assertSucceeds(batch.commit());}
  await driver.chooseBusinessCategory({category:'limited_company'});const companyId=driver.activeProfile().entityId;
  for(const [step,values]of [[1,{companyNumberStatus:'provided',companyNumber:'12345678',legalName:'Five Steps Ltd',incorporationDate:'2026-04-06'}],[2,{tradingStatus:'trading',tradingStartDate:'2026-05-06',corporationTaxStatus:'registered'}],[3,{founderName:'Synthetic Founder',founderShares:100,directorAnswer:'yes'}],[4,{ordinaryServiceDigital:true,riskAnswers:Object.fromEntries(Profile.SETUP_RISK_FIELDS.map(field=>[field,false]))}]]){const result=await driver.continueStep({step,values});assert.ok(['ok','review_required'].includes(result.status),JSON.stringify(result.fieldErrors));await push();}
  if(discard){const before=await snapshot(uid),check=await driver.inspectSetupExit();assert.equal(check.canDiscard,true);await driver.discardCompanySetup({companyId,expectedVersion:check.versionToken,operationId:'driver-discard-once'});assert.equal(driver.activeProfile(),null);const after=await snapshot(uid);for(const [path,row]of Object.entries(before))if(!/\/(entities|companyProfiles)\//.test(path))assert.deepEqual(after[path],row);const reconcile=Sync.reconcile(driver.state,Object.values(after).map(row=>row.data),uid);assert.deepEqual(reconcile.conflicts,[]);assert.deepEqual(Sync.partitionDiscardedSetupOperations(reconcile.uploads,[companyId],uid).kept,[]);}
  else{const result=await driver.continueStep({step:5,values:{confirmed:true}});assert.ok(['ok','review_required'].includes(result.status),JSON.stringify(result.fieldErrors));await push();assert.equal((await anchor(uid).get()).data().setupState,'setup_completed');assert.equal((await driver.inspectSetupExit()).canDiscard,false);assert.equal(driver.activeProfile().lifecycleStatus,'confirmed');}
 }
 await drive();await drive({discard:true});
});
