const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const root=path.join(__dirname,'../..'); const fire=fs.readFileSync(path.join(root,'firestore.rules'),'utf8'); const storage=fs.readFileSync(path.join(root,'storage.rules'),'utf8');
test('normal clients cannot write appConfig, billing, or entitlement truth',()=>{ assert.match(fire,/appConfig[\s\S]*allow write: if false/); assert.match(fire,/entitlements[\s\S]*allow write: if false/); assert.match(fire,/billing[\s\S]*allow read, write: if false/); });
test('normal clients cannot enumerate or modify Founder promo truth or redemptions',()=>{assert.match(fire,/founderPromotions[\s\S]*allow read, write: if false/);assert.match(fire,/promotionRedemptions[\s\S]*allow read, write: if false/);});
test('server reset epochs and legacy safety claims are owner-readable but never client-writable',()=>{assert.match(fire,/accountResets\/\{uid\}[\s\S]*allow read: if owner\(uid\); allow write: if false/);assert.match(fire,/accountClaims\/\{uid\}[\s\S]*allow read: if owner\(uid\); allow write: if false/);assert.doesNotMatch(fire,/accountQuarantines/);});
test('personal records are UID isolated and physical deletes are denied',()=>{ assert.match(fire,/request\.auth\.uid == uid/); assert.match(fire,/entries\/\{entryId\}[\s\S]*allow delete: if false/); });
test('Ltd sync retains owner reads but requires Pro plus the server-owned active-company anchor for writes',()=>{assert.match(fire,/match \/ltd\/v1\/\{collection\}\/\{recordId\}/);assert.match(fire,/allow read: if owner\(uid\)/);assert.match(fire,/allow create, update: if owner\(uid\) && pro\(uid\) && activeLtdMatches\(uid\) && validLtdRecord/);assert.match(fire,/match \/ltdControl\/\{document=\*\*\}[\s\S]*allow write: if false/);assert.match(fire,/activeCompanyId == request\.resource\.data\.companyId/);assert.match(fire,/companyProfileRevisions/);assert.match(fire,/companyOwnershipVersions/);assert.match(fire,/request\.resource\.data\.documentId == recordId/);assert.match(fire,/allow delete: if false/);});
test('partnership access preserves member reads but gates server-created collaboration writes to Pro',()=>{ assert.match(fire,/members\/\$\(request\.auth\.uid\)/); assert.match(fire,/promotionAccess/); assert.match(fire,/allow create: if false/); assert.match(fire,/allow read: if member\(partnershipId\)/); assert.match(fire,/allow create, update: if member\(partnershipId\) && pro\(request\.auth\.uid\)/); });
test('receipt storage is owner-only, image-only, size limited and entitlement-gated on upload',()=>{ assert.match(storage,/request\.auth\.uid == uid/); assert.match(storage,/firestore\.get/); assert.match(storage,/paidTier in \['plus', 'pro'\]/); assert.match(storage,/promotionAccess\.plusExpiresAt/); assert.match(storage,/allow create, update:[\s\S]*receiptAccess\(uid\)/); assert.match(storage,/allow read:[\s\S]*request\.auth\.uid == uid/); assert.match(storage,/allow delete:[\s\S]*request\.auth\.uid == uid/); assert.match(storage,/contentType\.matches\('image\/\.\*'\)/); assert.match(storage,/10 \* 1024 \* 1024/); });
