'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const State=require('../../src/integration/ltd/company-state');
// Generated by the released 2.1.20 code at 724657dcdcf20c61754833b28f9432088fbc610b:
// initial migration, add business and income, ordinary second save. Synthetic data.
const saved=require('../fixtures/upgrade-2.1.20-saved-state.json');
test('valid 2.1.20 save upgrades without losing records or reconciliation history',()=>{
  const bytes=JSON.stringify(saved),next=State.migrate(saved,1788900000000,'upgrade');
  State.validateState(next);assert.equal(JSON.stringify(saved),bytes);
  assert.deepEqual(next.businesses,saved.businesses);assert.deepEqual(next.entries,saved.entries);
  assert.deepEqual(next.companyStateMigration.previousReconciliation,saved.companyStateReconciliation);
  assert.deepEqual(State.migrate(next,1788900000001,'upgrade'),next);
});
test('unrecognised reconciliation and future state remain blocked',()=>{
  const invalid=JSON.parse(JSON.stringify(saved));invalid.companyStateReconciliation.toDomainSchemaVersion=99;
  assert.throws(()=>State.validateState(State.migrate(invalid,1788900000000,'upgrade')),/reconciliation provenance/);
  assert.throws(()=>State.migrate({...saved,companyStateSchemaVersion:99}),/Future company state/);
});
test('recovery offers the signed-in account an exit and sign-out preserves its stored bytes',async()=>{
  const source=fs.readFileSync('src/app/app.js','utf8'),stored=new Map([['account:canonical','original-account-bytes']]);
  let signedOut=false,activated=false;
  const context=vm.createContext({cloudUser:()=>({uid:'recovery-account'}),fbConfigured:()=>true,t:key=>key,esc:String,TaxMateCore:{VERSIONS:{APP_VERSION:'test',BUILD_ID:'test'}},stopUserSync(){},closeOnboardingSurface(){},freshState:()=>({}),render(){},firebase:{auth:()=>({signOut:async()=>{signedOut=true;}})},TaxMateAccountStorage:{localScope:()=>({kind:'local'})},activateAccountScope(){activated=true;},localStorage:{removeItem:key=>stored.delete(key),setItem:(key,value)=>stored.set(key,value)}});
  vm.runInContext(source.slice(source.indexOf('function pageStateRecovery(){'),source.indexOf('\nfunction render()'))+source.slice(source.indexOf('async function doSignOut(){'),source.indexOf('function userRoot(')),context);
  const html=vm.runInContext('pageStateRecovery()',context);assert.match(html,/data-tm-click="doSignOut\(\)"/);assert.match(html,/href="help.html"/);assert.match(html,/mailto:support@taxmate.uk/);
  assert.equal(await vm.runInContext('doSignOut()',context),true);assert.ok(signedOut&&activated);assert.equal(stored.get('account:canonical'),'original-account-bytes');
});
