const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const flow=require('../../src/core/auth-flow'),app=fs.readFileSync('src/app/app.js','utf8');
const take=(start,end)=>app.slice(app.indexOf(start),app.indexOf(end,app.indexOf(start)));
const fastFlow={create(options={}){const attempt=flow.create({...options,timeoutMs:150});const wait=attempt.wait;attempt.wait=(task,stage)=>wait(task,stage,30);return attempt;}};
test('unsettled initialization is bounded and identifies the stage',async()=>{const a=flow.create({timeoutMs:200});await assert.rejects(a.wait(()=>new Promise(()=>{}),'initialization',15),e=>e.code==='auth/flow-timeout'&&e.stage==='initialization');assert.equal(a.signal.aborted,true);a.close();});
test('cancel prevents a delayed task from progressing to the next stage',async()=>{const a=flow.create();let resolve,commits=0;const p=a.wait(()=>new Promise(r=>resolve=r),'google').then(()=>commits++);await Promise.resolve();a.cancel();await assert.rejects(p);resolve('late credential');await Promise.resolve();assert.equal(commits,0);a.close();});
test('synchronous launch errors and external cancellation settle without unhandled rejection',async()=>{const abort=new AbortController(),a=flow.create({signal:abort.signal});await assert.rejects(a.wait(()=>{throw Error('missing plugin');},'launch'),/missing plugin/);const pending=a.wait(()=>new Promise(()=>{}),'google');abort.abort(Error('back'));await assert.rejects(pending,/back/);a.close();});
function harness(source){const c={TaxMateAuthFlow:fastFlow,OB:{screen:'login',pendingIntent:source?{source,returnScreen:'entry'}:null,_authReturnScreen:source?'entry':null,billingCadence:'yearly',promoCode:'SAVE_PRO'},S:{settings:{lang:'en'}},cloudUser:()=>null,fbConfigured:()=>true,t:k=>k,obIntentCopy:x=>JSON.parse(JSON.stringify(x)),obPersistDraft:()=>{},obRender:()=>{},obGo:screen=>c.OB.screen=screen,TaxMateOnboardingRoot:{open:()=>{}},ACTIVE_SIGN_IN_OPERATION:null,AUTH_PENDING_INTENT:null,AUTH_PENDING_FORM:null,AUTH_PENDING_INTENT_INTERACTION:null,ACCOUNT_UI_READY:{state:'local'},document:{},setTimeout,clearTimeout,AbortController};vm.createContext(c);vm.runInContext(take('function flowText(key)','function obChoosePlan'),c);vm.runInContext(take('let OB_AUTH_GENERATION=0','/* ENTRY */'),c);return c;}
for(const source of [null,'ltd','partner_sync']){
  test(`${source||'general'} sign-in timeout restores Retry and preserves intent`,async()=>{const c=harness(source);c.signIn=()=>new Promise(()=>{});await c.obSignIn();assert.equal(c.OB._signingInFlow,false);assert.equal(c.OB.screen,'login');assert.match(c.OB._signInError,/too long/);assert.equal(c.OB.pendingIntent?.source,source||undefined);assert.equal(c.OB.promoCode,'SAVE_PRO');assert.equal(c.OB.billingCadence,'yearly');});
  test(`${source||'general'} Back ignores a late successful sign-in result`,async()=>{const c=harness(source);let resolve;c.signIn=()=>new Promise(r=>resolve=r);const p=c.obSignIn();await Promise.resolve();c.obCancelRequiredSignIn();resolve({uid:'late'});await p;assert.equal(c.OB.screen,'entry');assert.equal(c.OB._signingInFlow,false);assert.equal(c.OB.pendingIntent?.source,source||undefined);});
}
test('retry uses a fresh operation and follows the existing new-user route',async()=>{const c=harness();c.signIn=()=>new Promise(()=>{});await c.obSignIn();c.signIn=async()=>({uid:'new'});c.cloudUser=()=>({uid:'new'});c.waitForAuthenticatedAccountScope=async()=>{};c.startUserSync=async()=>({state:'converged',existingCloudAccount:false});await c.obSignIn();assert.equal(c.OB.screen,'entry');assert.equal(c.OB.loggedIn,true);});
test('both feature explanations explicitly say Pro and explain the post-login gate',()=>{const c=harness();for(const k of ['signInLtdPro','signInPartnerPro'])assert.match(c.flowText(k),/Pro.*Sign in first.*choose a plan after signing in/);});

