'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Transfer=require('../../src/core/backup-transfer'),Policy=require('../../src/core/retention-policy'),Portable=require('../../src/core/portable-backup'),Evidence=require('../../src/core/company-evidence'),Books=require('../../src/core/company-books'),{CanonicalCompanyDriver}=require('../../src/integration/ltd/CanonicalCompanyDriver'),{make}=require('../test-fixture');
test('Free mixed-account basic backup does not block ordinary records when LTD retention is unknown',()=>{const {driver}=make(),result=Transfer.project(driver.state,{snapshot:{paidTier:'free'},now:driver.now()});assert.equal(result.omittedLtd,true);assert.equal(result.state.entries.length,driver.state.entries.length);assert.equal(result.state.domain.companyProfiles.length,0);assert.match(result.notice,/eligible/);assert.equal(driver.state.domain.companyProfiles.length,1);});
test('expired mixed restore preserves new-year ordinary data without importing unavailable LTD or granting paid operations',()=>{const {driver}=make(),state=driver.state;state.entries.push({...state.entries[0],id:'new',date:'2027-04-06'});const snapshot={paidTier:'free',subscriptionStatus:'canceled',lastPaidTier:'pro',currentPeriodEnd:Date.UTC(2026,5,1)},control={schemaVersion:2,status:'complete',epoch:2,cutoffDate:'2027-04-06',deleteOnDate:'2027-04-06'};state.retention={epoch:999};const result=Transfer.project(state,{snapshot,control,now:Date.UTC(2027,5,1),restoring:true});assert.deepEqual(result.state.entries.map(e=>e.id),['new']);assert.equal(result.state.domain.companyProfiles.length,0);assert.equal(result.state.retention.epoch,2);});
test('an actual ZIP relocates receipt bytes and keeps only a previously current filing review current',async()=>{
 const {driver,facade}=make(),original='receipts/previous-user/book-evidence.jpg';driver.eventsFor()[0].sourceTransaction.evidenceRefs=[original];const checklist=driver.statutorySnapshot().checklist;
 assert.equal((await facade.onSaveStatutoryReview({sourceFingerprint:checklist.sourceFingerprint,expectedRevision:0,facts:{recordsBackedUp:{value:true,evidenceRefs:[original]},microEntityEligibilityConfirmed:{value:true,evidenceRefs:[original]}}})).status,'ok');
 const bytes=Uint8Array.from([255,216,255,217]),groups=new Map();for(const a of [...Evidence.requiredReceiptAssociations(driver.state),...driver.state.entries.filter(e=>e.receiptPath||e.receiptUrl).map(e=>({recordType:'legacy_entry',recordId:e.id,originalPath:e.receiptPath||e.receiptUrl}))]){if(!groups.has(a.originalPath))groups.set(a.originalPath,[]);groups.get(a.originalPath).push(a);}
 const zip=await Portable.createArchive({state:driver.state,receipts:[...groups].map(([originalPath,associations])=>({originalPath,associations,bytes,mimeType:'image/jpeg'})),nodeBuffer:true,identity:{appVersion:'2.1.23',buildId:'retention-test'}}),inspected=await Portable.inspectArchive(zip.archive);assert.deepEqual([...inspected.receipts[0].bytes],[...bytes]);
 const relocated=Transfer.relocate(inspected.state,{[original]:{path:'receipts/new-user/restored.jpg',url:'http://localhost/_taxmate_receipt/restored'}}),next=new CanonicalCompanyDriver({state:relocated,now:driver.now,enforceEntitlement:false});
 assert.equal(relocated.domain.companyProfiles[0].statutoryReview.sourceFingerprint,Books.statutoryFingerprint(next.statutoryInput()));assert.equal(next.statutorySnapshot().checklist.reviewStatus,'current');
 const stale=JSON.parse(JSON.stringify(inspected.state));stale.domain.economicEvents.find(e=>e.origin==='company_v1_5').updatedAt++;
 const unchanged=stale.domain.companyProfiles[0].statutoryReview.sourceFingerprint,restoredStale=Transfer.relocate(stale,{[original]:{path:'receipts/new-user/old.jpg',url:'http://localhost/old'}});assert.equal(restoredStale.domain.companyProfiles[0].statutoryReview.sourceFingerprint,unchanged);
});
test('retention history gaps reach the real VAT/pack input and unknown company-year figures are not zero',()=>{
 const {driver}=make(),next=Policy.apply(driver.state,{policy:{cutoffDate:'2027-04-06',deleteOnDate:'2027-04-06'},epoch:1,warnings:[]},Date.UTC(2027,5,1)),read=new CanonicalCompanyDriver({state:next,now:()=>Date.UTC(2027,5,1),enforceEntitlement:false});
 assert.equal(read.statutoryInput().vatHistoryIncomplete,true);const figures=read.companyYearFigures();assert.equal(figures.profitAndLoss.turnoverMinor,null);const pack=Books.buildSelfFilingPack(read.statutoryInput());assert.equal(pack.readiness.figuresReady,false);assert.ok(pack.accountsFiling.profitAndLossLines.every(l=>l.figureMinor===null));
});
