'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {make,PRO_ENTITLEMENT}=require('../test-fixture');
const Sync=require('../../src/core/ltd-sync'),Profile=require('../../src/core/company-profile');
const {CanonicalCompanyDriver,DEFAULT_NOW}=require('../../src/integration/ltd/CanonicalCompanyDriver');
const {TaxMateLtdUIFacade}=require('../../src/integration/ltd/TaxMateLtdUIFacade');
const Structural=require('../../src/integration/ltd/company-structural-state');
const clone=value=>JSON.parse(JSON.stringify(value));
function fixture(options={}){const state=options.state||make('fresh').driver.state,driver=new CanonicalCompanyDriver({state,now:()=>DEFAULT_NOW,entitlementSnapshot:PRO_ENTITLEMENT,...options}),storage=options.storage||Structural.memoryStorage(),facade=new TaxMateLtdUIFacade({driver,storage,draftKey:'setup-test'});return{driver,facade,storage};}
const step1={companyNumberStatus:'provided',companyNumber:'12345678',legalName:'Synthetic Setup Ltd',incorporationDate:'2026-04-06'};
async function start(f){await f.facade.onAddBusinessCategoryChosen({category:'limited_company'});return f.driver.activeProfile().entityId;}
async function field(f,id,value,screenId='ltd.onboarding.step1'){await f.facade.onDraftChanged({screenId,field:{id,type:'text',value}});}

test('unclaimed keep survives a new facade, merges only this draft into latest account data, and resumes the same answers',async()=>{
 const f=fixture(),id=await start(f),canonicalBefore=clone(f.driver.repository.load());await field(f,'legalName','My unfinished company');
 await f.facade.onDismissRequested();assert.equal(f.facade.setupExit.status,'local');assert.equal((await f.facade.onSaveCompanyDraft()).status,'ok');assert.equal(f.facade.workflow.snapshot().pendingDiscard,null);assert.deepEqual(f.driver.repository.load(),canonicalBefore);
 const latest=clone(canonicalBefore);latest.settings.language='zh-HK';const reopened=fixture({state:latest,storage:f.storage});assert.equal(reopened.driver.activeProfile().entityId,id);assert.equal(reopened.driver.state.settings.language,'zh-HK');assert.deepEqual(reopened.driver.repository.load(),latest);assert.equal((await reopened.facade.onResumeCompanyDraft()).nextRoute,'ltd.onboarding.step1');assert.equal(reopened.facade.drafts.get('ltd.onboarding.step1').fields[0].value,'My unfinished company');
});
test('removing only an unclaimed draft keeps account records and the next identity is new',async()=>{
 const f=fixture(),before=clone(f.driver.repository.load()),id=await start(f);await field(f,'legalName','Discard me');await f.facade.onDismissRequested();assert.equal((await f.facade.onDiscardCompanySetup()).status,'ok');assert.equal(f.facade.drafts.getSetup(),null);assert.equal(f.facade.drafts.get('ltd.onboarding.step1'),null);assert.deepEqual(f.driver.repository.load(),before);assert.notEqual(await start(f),id);
});
test('close continues editing; Back within setup navigates; first-step Back and Home both request an exit choice',async()=>{
 const f=fixture();await start(f);await f.facade.onBack();assert.equal(f.facade.setupExit.status,'local');await f.facade.onDiscardCancelled();assert.equal(f.facade.workflow.currentRoute().screenId,'ltd.onboarding.step1');f.facade.route('ltd.onboarding.step2');await f.facade.onBack();assert.equal(f.facade.workflow.currentRoute().screenId,'ltd.onboarding.step1');assert.equal(f.facade.setupExit,null);assert.equal((await f.facade.onOpenHome()).status,'review_required');assert.equal(f.facade.workflow.currentRoute().screenId,'ltd.onboarding.step1');
});
test('claim seeds use canonical sync envelopes and a legacy slot has no narrow discard permission',async()=>{
 let seed;const f=fixture({activeCompanyClaim:async data=>{seed=data;return{status:'claimed',activeCompanyId:data.companyId};}});await start(f);const result=await f.facade.onContinueStep({step:1,values:step1});assert.equal(result.status,'ok');assert.equal(seed.setupProtocol,'ltd-setup.1');seed.setupRecords.forEach(Sync.validateEnvelope);const record=Sync.recordsForSync(f.driver.state).companyProfiles[0];assert.equal(seed.setupRecords[0].checksum,Sync.envelope('companyProfiles',record,record.entityId).checksum);await f.facade.onDismissRequested();assert.equal(f.facade.setupExit.status,'legacy');assert.equal(f.facade.setupExit.canDiscard,false);assert.equal((await f.facade.onSaveCompanyDraft()).status,'ok');
});
test('a lost claim response persists attempted identity and must use the trusted discard path after reload',async()=>{
 const f=fixture({activeCompanyClaim:async()=>{throw Error('lost response');}});const id=await start(f);await field(f,'legalName',step1.legalName);assert.equal((await f.facade.onContinueStep({step:1,values:step1})).status,'field_error');assert.equal(f.facade.drafts.getSetup().pending.claimAttempted,true);
 const calls=[],reopened=fixture({state:f.driver.repository.load(),storage:f.storage,manageCompanySetup:async input=>{calls.push(input);return input.action==='inspect'?{status:'unclaimed',canDiscard:true,companyId:id,versionToken:'v1'}:{status:'discarded',companyId:id,operationId:input.operationId,records:[]};}});await reopened.facade.onResumeCompanyDraft();await reopened.facade.onDismissRequested();assert.equal(reopened.facade.setupExit.status,'unclaimed');assert.equal((await reopened.facade.onDiscardCompanySetup()).status,'ok');assert.deepEqual(calls.map(x=>x.action),['inspect','discard']);assert.equal(reopened.driver.activeProfile(),null);
});
test('uncertain discard preserves answers and retries the same operation and version; explicit conflict asks for a fresh review',async()=>{
 let attempts=0,first;const f=fixture({manageCompanySetup:async input=>{if(input.action==='inspect')return{status:'pending',canDiscard:true,companyId:f.driver.activeProfile().entityId,versionToken:'v1'};first=first||input;assert.equal(input.operationId,first.operationId);assert.equal(input.expectedVersion,first.expectedVersion);attempts++;throw Object.assign(Error('request failed'),{code:attempts===1?'unavailable':'setup_changed_review_again'});}});await start(f);await f.facade.onContinueStep({step:1,values:step1});await field(f,'tradingStartDate','2026-05-06','ltd.onboarding.step2');await f.facade.onDismissRequested();await f.facade.onDiscardCompanySetup();assert.equal(f.facade.setupExit.reason,'setup_discard_uncertain');assert.ok(f.facade.drafts.get('ltd.onboarding.step2'));assert.ok(f.facade.drafts.getSetup().discardOperationId);assert.equal((await f.facade.onSaveCompanyDraft()).status,'failure');await f.facade.onDiscardCancelled();await f.facade.onDismissRequested();assert.equal(attempts,2);assert.equal(f.facade.setupExit.reason,'setup_changed_review_again');assert.equal(f.facade.drafts.getSetup().discardOperationId,undefined);
});
test('local pending restoration rejects reused tombstoned identities and other active companies',async()=>{
 const f=fixture(),id=await start(f),saved=f.driver.pendingSetup(),latest=f.driver.repository.load();latest.domain.companyProfiles.push({...saved.profile,deletedAt:DEFAULT_NOW});latest.domain.entities.push({...saved.entity,deletedAt:DEFAULT_NOW});const reopened=fixture({state:latest});assert.equal(reopened.driver.restorePendingSetup(saved),false);assert.equal(reopened.driver.activeProfile(),null);assert.equal(reopened.driver.state.domain.companyProfiles[0].entityId,id);
});
test('confirmed company cannot use local draft discard and saving drafts still requires Pro',async()=>{
 const existing=make('existing').driver;assert.equal((await existing.inspectSetupExit()).canDiscard,false);await assert.rejects(existing.discardCompanySetup({companyId:existing.activeProfile().entityId}),/setup_not_unfinished/);const f=fixture();await start(f);f.driver.setEntitlementSnapshot({paidTier:'free',subscriptionStatus:'inactive',serverVerifiedAt:DEFAULT_NOW});assert.equal((await f.facade.onSaveCompanyDraft()).status,'failure');
});
test('server outcome queue retirement is limited to this owner and setup records, keeping financial and foreign operations',()=>{
 const ops=[{kind:'ltd-record',uid:'owner',companyId:'old',collection:'companyProfiles'},{kind:'ltd-record',uid:'owner',companyId:'old',collection:'economicEvents'},{kind:'ltd-record',uid:'other',companyId:'old',collection:'entities'},{kind:'ltd-record',uid:'owner',companyId:'new',collection:'entities'},{kind:'ltd-record',uid:'owner',ownerUid:'other',companyId:'old',collection:'entities'}],before=clone(ops),result=Sync.partitionDiscardedSetupOperations(ops,['old'],'owner');assert.deepEqual(result.retired,[ops[0]]);assert.deepEqual(result.kept,ops.slice(1));assert.deepEqual(ops,before);
});
test('anchor checks accept retained historical tombstones with no slot or a new slot but reject unrelated active identities',()=>{
 const old=Profile.createDraft({entityId:'old',now:DEFAULT_NOW,deviceId:'test'}),state={domain:{entities:[{id:'old',type:'limited_company',deletedAt:DEFAULT_NOW}],companyProfiles:[{...old,deletedAt:DEFAULT_NOW}]}};assert.equal(Sync.validateAnchorState(null,state,[]),true);assert.equal(Sync.validateAnchorState({activeCompanyId:'new'},state,[Sync.envelope('entities',{id:'new',type:'limited_company'},'new')]),true);assert.throws(()=>Sync.validateAnchorState({activeCompanyId:'other'},state,[Sync.envelope('entities',{id:'new',type:'limited_company'},'new')]),/mismatch/);
});
test('repeated setup discards leave the shared account holder local when no active binding exists, without inventing a historical upload',()=>{
 const state={domain:{entities:[{id:'old-a',type:'limited_company',deletedAt:1},{id:'old-b',type:'limited_company',deletedAt:2}],persons:[{id:'person:account-holder',name:'Existing account holder'}]}},result=Sync.reconcile(state,[],'owner');assert.equal(result.uploads.some(row=>row.collection==='persons'),false);assert.equal(state.domain.persons.length,1);const remote=Sync.envelope('persons',state.domain.persons[0],'old-a');assert.equal(Sync.reconcile(state,[remote],'owner').conflicts.length,0);
});
test('Back after resuming Step 2 still opens Step 1 before offering exit',async()=>{const f=fixture();await start(f);f.facade.workflow.enter('home');f.facade.workflow.enter('ltd.onboarding.step2');assert.equal((await f.facade.onBack()).nextRoute,'ltd.onboarding.step1');assert.equal(f.facade.setupExit,null);assert.equal((await f.facade.onBack()).status,'review_required');});
test('a cloud tombstone received after a lost discard response still permits idempotent UI cleanup',async()=>{
 let receipt;const f=fixture({manageCompanySetup:async input=>{if(input.action==='inspect')return receipt?{status:'discarded',companyId:receipt.companyId,canDiscard:false}:{status:'pending',companyId:input.companyId,canDiscard:true,versionToken:'v1'};if(receipt)return receipt;const p=f.driver.activeProfile(),entity=f.driver.entityFor(p),records=[Sync.envelope('companyProfiles',{...p,deletedAt:DEFAULT_NOW+1000},p.entityId),Sync.envelope('entities',{...entity,deletedAt:DEFAULT_NOW+1000},p.entityId)];receipt={status:'discarded',companyId:p.entityId,operationId:input.operationId,records};f.driver.repository.replace(Sync.applyDownloads(f.driver.repository.load(),records));f.driver.reload();throw Object.assign(Error('Lost response'),{code:'unavailable'});}});
 await start(f);await f.facade.onContinueStep({step:1,values:step1});await field(f,'tradingStartDate','2026-05-06','ltd.onboarding.step2');await f.facade.onDismissRequested();await f.facade.onDiscardCompanySetup();assert.equal(f.driver.activeProfile(),null);assert.equal(f.facade.setupExit.reason,'setup_discard_uncertain');await f.facade.onDiscardCancelled();assert.equal((await f.facade.onDismissRequested()).status,'ok');assert.equal(f.facade.drafts.getSetup(),null);assert.equal(f.facade.workflow.currentRoute().screenId,'home');
});
