'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('src/app/app.js','utf8'),billing=fs.readFileSync('src/app/billing-ui.js','utf8');
function take(source,start,end){return source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));}
function harness(tier='free',signedIn=true){
 const c={OB:{screen:'entry',monthsAll:[],data:{},billingCadence:'yearly'},cloudUser:()=>signedIn?{uid:'fixture'}:null,CLOUD:{hydrationState:'converged'},ENTITLEMENT:{loaded:true},currentTier:()=>tier,obRender:()=>{},obPersistDraft:()=>{},t:x=>x,esc:x=>x,S:{settings:{lang:'en'}},document:{},window:{},TaxMateOnboardingRoot:{progress:(state,screen,render)=>{state.screen=screen;render();},open:()=>{}},partnerCodeValid:x=>/^[A-Z0-9]{8}$/.test(x)};
 vm.createContext(c);vm.runInContext(take(app,'function obGo(s)','function obProgress'),c);vm.runInContext(take(app,'function obScrEntry()','function obScrLtdChoice'),c);vm.runInContext(take(app,'function obStartPartnerSync()','function obSetConnectCode'),c);vm.runInContext(take(app,'async function obContinuePendingIntent()','async function obExecutePendingIntent()'),c);vm.runInContext(take(app,'function obReturnFromProGate()','function obProUpgrade()'),c);c.launches=0;c.obExecutePendingIntent=()=>c.launches++;return c;
}
test('all tiers see both paid choices with Pro badges and a logo before signing in',()=>{for(const signed of [false,true]){const c=harness('free',signed);c.obShell=(_,body)=>c.taxmateFlowBrand()+body;c.obProgress=()=>'';const html=c.obScrEntry();assert.ok(html.includes('obStartLtd()'));assert.ok(html.includes('obStartPartnerSync()'));assert.equal(html.match(/ob-entry-pro/g).length,2);assert.ok(html.includes('brand-logo-light'));}});
test('guest feature selection saves intent before presenting Google sign-in',async()=>{for(const source of ['ltd','partner_sync']){const c=harness('free',false);if(source==='ltd')c.obStartLtd();else c.obStartPartnerSync();assert.equal(c.OB.screen,'login');assert.equal(c.OB.pendingIntent.source,source);assert.equal(c.OB._authReturnScreen,'entry');assert.equal(c.launches,0);}});
test('Free and Plus reach plans; Pro resumes directly after authoritative hydration',async()=>{for(const tier of ['free','plus','pro']){const c=harness(tier);c.obSetPendingIntent('ltd',{returnScreen:'entry'});await c.obContinuePendingIntent();assert.equal(c.launches,tier==='pro'?1:0);if(tier!=='pro')assert.equal(c.OB.screen,'pro-gate');}});
test('Back while entitlement lookup is pending prevents its delayed response from navigating',async()=>{const c=harness('pro');let resolve;c.CLOUD.hydrationState='loading';c.startUserSync=()=>new Promise(r=>resolve=r);c.obSetPendingIntent('ltd',{returnScreen:'entry'});const pending=c.obContinuePendingIntent();c.obReturnFromProGate();resolve({state:'converged'});await pending;assert.equal(c.OB.screen,'entry');assert.equal(c.launches,0);assert.equal(c.OB.billingCadence,'yearly');});
test('payment cancellation keeps plans without refreshing and executing its feature',async()=>{const c={window:{TAXMATE_BILLING_RETURN:{status:'cancelled',uid:'fixture',interaction:1,intent:true}},cloudUser:()=>({uid:'fixture'}),TaxMateForegroundUI:{interactionVersion:()=>1},OB:{pendingIntent:{source:'ltd'}},obRefreshPaidAccess:()=>{throw Error('must not resume cancelled checkout');}};vm.createContext(c);vm.runInContext(take(billing,'async function billingHandleReturn()','async function billingBeginPurchase'),c);await c.billingHandleReturn();assert.equal(c.window.TAXMATE_BILLING_RETURN,null);});
test('pending intent has priority over existing account routing and transfers only UI form state',()=>{const c=harness('free');c.AUTH_PENDING_INTENT={source:'partner_sync',returnScreen:'entry',formState:{partnerCode:'CONNECT8'}};c.AUTH_PENDING_FORM={screen:'login',promoCode:'PROMO_9',billingCadence:'yearly'};c.AUTH_PENDING_INTENT_INTERACTION=1;c.TaxMateForegroundUI={interactionVersion:()=>1};c.firstSyncSurfaceOpen=()=>false;c.OB=null;c.obDefaultState=()=>({});c.normalisePartnerCode=x=>x;vm.runInContext(take(app,'function pendingIntentForHydration()','function beginAccountTransition'),c);assert.equal(c.pendingIntentForHydration().source,'partner_sync');assert.equal(c.OB.connectCode,'CONNECT8');assert.equal(c.OB.promoCode,'PROMO_9');assert.equal(c.BILLING_CADENCE,'yearly');assert.equal(c.AUTH_PENDING_FORM,null);});
test('standalone Redeem returns to its original app tab after account transition',()=>{const c=harness();c.OB._redeemReturn='app';c.OB._returnAppTab='more';c.S.tab='home';c.obClose=()=>{c.OB=null;};c.render=()=>{};c.obBackFromRedeem();assert.equal(c.S.tab,'more');assert.equal(c.OB,null);});
