const test=require('node:test');const assert=require('node:assert/strict');const JSZip=require('jszip');const P=require('../../src/core/portable-backup');
const state=(entries=[])=>({v:5,businesses:[{id:'b1',name:'Trade',structure:'sole'}],entries,folders:[],tombstones:[],yearData:{},customCats:{},activeCats:{},catRenames:{},settings:{lang:'en'}});
const entry=(id,receipt=false)=>({id,bizId:'b1',kind:'expense',date:'2026-05-01',amount:10,cat:'other',receiptPath:receipt?`receipts/u/${id}.jpg`:null,receiptUrl:receipt?'https://example.test/r.jpg':null});
const identity={appVersion:'2.0.0',buildId:'test',deviceId:'dev-test'};const img=n=>new Uint8Array(Array.from({length:n},(_,i)=>(i*17)%256));
async function build(s,receipts=[]){return(await P.createArchive({state:s,identity,receipts,nodeBuffer:true,exportedAt:'2026-08-17T00:00:00.000Z'})).archive;}
test('portable backup round trip with no receipts',async()=>{const out=await P.inspectArchive(await build(state([entry('e1')])));assert.equal(out.preview.receipts,0);assert.equal(out.state.entries[0].amount,10);assert.equal(out.metadata.receiptCount,0);});
test('one linked receipt round trips with association and verified bytes',async()=>{const archive=await build(state([entry('e1',true)]),[{entryId:'e1',bytes:img(128),mimeType:'image/jpeg',originalPath:'receipts/u/e1.jpg'}]);const out=await P.inspectArchive(archive);assert.equal(out.preview.receipts,1);assert.deepEqual(out.receipts[0].bytes,img(128));assert.equal(out.receipts[0].entryId,'e1');});
test('multiple linked receipts and declared orphan files are preserved',async()=>{const archive=await build(state([entry('e1',true),entry('e2',true)]),[{entryId:'e1',bytes:img(32),mimeType:'image/png'},{entryId:'e2',bytes:img(33),mimeType:'image/webp'},{entryId:null,bytes:img(34),mimeType:'image/jpeg',originalPath:'receipts/u/unlinked.jpg'}]);const out=await P.inspectArchive(archive);assert.deepEqual(out.preview,{businesses:1,entries:2,receipts:2,orphans:1,totalReceiptBytes:99});});
test('missing referenced receipt and duplicate association fail export',async()=>{await assert.rejects(()=>build(state([entry('e1',true)]),[]),/missing/);await assert.rejects(()=>build(state([entry('e1',true)]),[{entryId:'e1',bytes:img(1)},{entryId:'e1',bytes:img(2)}]),/Duplicate receipt association/);});
test('one storage object cannot be silently associated with two entries',async()=>{await assert.rejects(()=>build(state([entry('e1',true),entry('e2',true)]),[{entryId:'e1',bytes:img(2),originalPath:'receipts/u/same.jpg'},{entryId:'e2',bytes:img(2),originalPath:'receipts/u/same.jpg'}]),/Duplicate receipt input/);});
test('duplicate entry IDs fail before archive creation',async()=>{await assert.rejects(()=>build(state([entry('e1'),entry('e1')]),[]),/Duplicate entry id/);});
test('corrupt ZIP and corrupt embedded JSON fail safely',async()=>{await assert.rejects(()=>P.inspectArchive(Buffer.from('not a zip')),/Corrupt/);const zip=await JSZip.loadAsync(await build(state([entry('e1')])));zip.file('taxmate-backup.json','{bad');const corrupt=await zip.generateAsync({type:'nodebuffer'});await assert.rejects(()=>P.inspectArchive(corrupt),/JSON is corrupt/);});
test('unsupported future backup schema is rejected',async()=>{const zip=await JSZip.loadAsync(await build(state([entry('e1')])));const data=JSON.parse(await zip.file('taxmate-backup.json').async('string'));data.metadata.backupSchemaVersion=99;zip.file('taxmate-backup.json',JSON.stringify(data));const future=await zip.generateAsync({type:'nodebuffer'});await assert.rejects(()=>P.inspectArchive(future),/future schema/);});
test('undeclared orphan file and missing manifest file are rejected',async()=>{let zip=await JSZip.loadAsync(await build(state([entry('e1')])));zip.file('receipts/orphans/dW5saW5rZWQ.jpg',img(3));let invalid=await zip.generateAsync({type:'nodebuffer'});await assert.rejects(()=>P.inspectArchive(invalid),/not declared/);zip=await JSZip.loadAsync(await build(state([entry('e1',true)]),[{entryId:'e1',bytes:img(4),mimeType:'image/jpeg'}]));const manifest=JSON.parse(await zip.file('receipt-manifest.json').async('string'));zip.remove(manifest.receipts[0].archivePath);invalid=await zip.generateAsync({type:'nodebuffer'});await assert.rejects(()=>P.inspectArchive(invalid),/missing file/);});
test('realistic larger receipt set stays deterministic and within limits',async()=>{const entries=[],receipts=[];for(let i=0;i<120;i++){const id='e'+i;entries.push(entry(id,true));receipts.push({entryId:id,bytes:img(4096+i),mimeType:i%2?'image/jpeg':'image/png'});}const out=await P.inspectArchive(await build(state(entries),receipts));assert.equal(out.preview.receipts,120);assert.equal(out.preview.entries,120);assert.ok(out.preview.totalReceiptBytes>490000);});
