(function attachTaxMateLtdUIFacadeClient(root){
  'use strict';
  const CALLBACKS=['onOpenHome','onAddBusiness','onAddBusinessCategoryChosen','onSelfEmployedStructureChosen','onOpenLegacyBusiness','onEditLegacyBusiness','onOpenExistingCompany','onResumeCompanyDraft','onSaveCompanyDraft','onContinueStep','onLookupCompaniesHouse','onRecheckCompaniesHouse','onPlanCompanyPeriods','onFixCompanyFact','onDraftChanged','onOpenInfo','onCloseInfo','onBack','onDismissRequested','onDiscardConfirmed','onDiscardCancelled','onSetWorkspaceArea','onOpenMetric','onAddIncome','onAddExpense','onAddSharedExpense','onAddPersonallyPaidExpense','onAddDirectorLoanFunding','onRecordDirectorLoanRepayment','onRecordShareFunding','onOpenRecord','onEditDraft','onSaveDraftEdit','onDeleteDraft','onCorrectRecord','onRunCtEstimate','onRunScenario','onRecordSalary','onDeclareDividend','onRecordDividendPayment','onOpenCompanyEdit','onEditCompany','onOpenOwnershipChange','onChangeOwnership','onDownloadWorkingPack','onRemoveCompany','onResetPreview'];
  class TaxMateLtdUIFacadeClient{
    constructor(mode,tier){this.mode=mode==='fresh'?'fresh':'existing';this.tier=['free','plus'].includes(tier)?tier:'pro';this.snapshot=null;this.listeners=new Set();this.busy={active:false,action:null};for(const name of CALLBACKS)this[name]=input=>this.invoke(name,input||{});}
    subscribe(listener){this.listeners.add(listener);if(this.snapshot)listener(this.snapshot);return()=>this.listeners.delete(listener);}
    emit(){for(const listener of this.listeners)listener(this.getSnapshot());}
    getSnapshot(){return this.snapshot?JSON.parse(JSON.stringify({...this.snapshot,busy:this.busy.active?this.busy:this.snapshot.busy})):null;}
    endpoint(path){return `${path}?mode=${encodeURIComponent(this.mode)}&tier=${encodeURIComponent(this.tier)}`;}
    async refresh(){const response=await fetch(this.endpoint('/api/snapshot'),{credentials:'omit',cache:'no-store'});if(!response.ok)throw new Error(`Snapshot failed: ${response.status}`);this.snapshot=await response.json();this.emit();return this.getSnapshot();}
    async invoke(callback,input){const quietStart=callback==='onDraftChanged'||callback==='onPlanCompanyPeriods';if(this.busy.active&&!quietStart)return{status:'busy',error:{reasonCode:'action_in_progress',copyKey:'error.fix_issue',params:{action:this.busy.action}},snapshot:this.getSnapshot()};if(!quietStart){this.busy={active:true,action:callback};this.emit();}try{const response=await fetch(this.endpoint('/api/action'),{method:'POST',credentials:'omit',cache:'no-store',headers:{'content-type':'application/json'},body:JSON.stringify({callback,input})});const result=await response.json();if(!response.ok&&result.status!=='failure')throw new Error(`Action failed: ${response.status}`);this.snapshot=result.snapshot||this.snapshot;if(!quietStart)this.busy={active:false,action:null};if(callback!=='onDraftChanged')this.emit();return result;}catch(_){if(!quietStart)this.busy={active:false,action:null};if(callback!=='onDraftChanged')this.emit();return{status:'failure',error:{reasonCode:'localhost_transport_failure',copyKey:'error.fix_issue',params:{}},snapshot:this.getSnapshot()};}}
  }
  root.TaxMateLtdUIFacadeClient=TaxMateLtdUIFacadeClient;
  root.TaxMateLtdUICallbacks=Object.freeze(CALLBACKS.slice());
})(typeof globalThis!=='undefined'?globalThis:this);
